### PR TITLE
[INLONG-6058][DataProxy] Add parameter checking and optimize client creation logic

### LINKED ISSUE #6058: [Bug][DataProxy] Add parameter checking and optimize client creation logic
### What happened

In the return result of getConfig, if the configuration item is null, the comparison will fail; at the same time, in the Pulsar client creation structure, the deletion and addition are optimized to avoid the creation failure.

### What you expected to happen

If the value is null, it is considered consistent when compared with the string "null"

### How to reproduce

return null value in getConfig result

### Environment

Linux

### InLong version

master

### InLong Component

InLong DataProxy

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by gosonzhang**
- Fixes #6058

### CODE REVIEW

**Review by baomingyu — APPROVED** [review]
+1

File: inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/config/ConfigManager.java [hunk 1]
```diff
@@ -157,8 +159,14 @@ private boolean updatePropertiesHolder(Map<String, String> result,
...
         for (Map.Entry<String, String> entry : result.entrySet()) {
             String oldValue = tmpHolder.put(entry.getKey(), entry.getValue());
-            if (!ObjectUtils.equals(oldValue, entry.getValue())) {
-                changed = true;
+            if (entry.getValue() == null) {
+                if (!Objects.equals(oldValue, "null")) {
+                    changed = true;
+                }
+            } else {
+                if (!ObjectUtils.equals(oldValue, entry.getValue())) {
```
Comment (healchow) [inline inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/config/ConfigManager.java:167]:
```suggestion
                if (!Objects.equals(oldValue, entry.getValue())) {
```

**Review by healchow — APPROVED** [review]
