### PR TITLE
[INLONG-7543][Sort] Fix PostgreSQL connector output two data with the same UPDATE operation

### LINKED ISSUE #7543: [Bug][Sort] PostgreSQL connector output two data with the same UPDATE operation
### What happened

Refer issue #7397 , postgres cdc connector also sends two data with the same UPDATE operation.

### What you expected to happen

Refer issue https://github.com/apache/inlong/issues/7397 , postgres cdc connector also should fix the type in canal-json or debezium-json when UPDATE operation.

### How to reproduce

Just run the `AllMigratePostgreSQLTest` JUnit test class, it will reproduce this problem.

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Sort

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by liaorui**
### Prepare a Pull Request
*(Change the title refer to the following example)*

- Title Example: [INLONG-XYZ][Component] Title of the pull request

*(The following *XYZ* should be replaced by the actual [GitHub Issue](https://github.com/apache/inlong/issues) number)*

- Fixes #7543

### Motivation

*Explain here the context, and why you're making that change. What is the problem you're trying to solve?*

Refer issue https://github.com/apache/inlong/issues/7397 , postgres cdc connector also sends two data with the same UPDATE operation.

Postgres cdc connector also should fix the type in canal-json or debezium-json when UPDATE operation.

### Modifications

*Describe the modifications you've done.*

For UPDATE_BEFORE output DELETE
For UPDATE_AFTER output INSERT

### Verifying this change

*(Please pick either of the following options)*

- [ ] This change is a trivial rework/code cleanup without any test coverage.

- [ ] This change is already covered by existing tests, such as:
  *(please describe tests)*

- [ ] This change added tests and can be verified as follows:

  *(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a follow-up issue for adding the documentation

### CODE REVIEW

File: inlong-sort/sort-connectors/postgres-cdc/src/main/java/org/apache/inlong/sort/cdc/postgres/table/PostgreSQLReadableMetaData.java [hunk 1]
```diff
@@ -473,21 +482,50 @@ public static Map<String, Integer> getSqlType(@Nullable TableChange tableSchema)
         return postgresType;
     }
 
+    /**
+     * convert canal operation to canal-json operation type
+     *
+     * @param record
```
Comment (healchow) [inline inlong-sort/sort-connectors/postgres-cdc/src/main/java/org/apache/inlong/sort/cdc/postgres/table/PostgreSQLReadableMetaData.java:488]: Please add more desc for `@param` and `@return` tags, otherwise, there are some warnings in the IDE.

File: inlong-sort/sort-connectors/postgres-cdc/src/main/java/org/apache/inlong/sort/cdc/postgres/table/PostgreSQLReadableMetaData.java [hunk 2]
```diff
@@ -473,21 +482,50 @@ public static Map<String, Integer> getSqlType(@Nullable TableChange tableSchema)
...
+                throw new IllegalStateException("the record only have states in DELETE, "
+                        + "UPDATE_BEFORE, INSERT and UPDATE_AFTER");
+        }
+        return opType;
+    }
+
     /**
      * convert debezium operation to debezium-json operation type
      *
      * @param record
```
Comment (healchow) [inline inlong-sort/sort-connectors/postgres-cdc/src/main/java/org/apache/inlong/sort/cdc/postgres/table/PostgreSQLReadableMetaData.java:512]: Add more comments for Javadoc tags, thank you.

**Review by yunqingmoswu — APPROVED** [review]

**Review by dockerzhang — APPROVED** [review]

**Review by dockerzhang — APPROVED** [review]

File: inlong-sort/sort-connectors/postgres-cdc/src/main/java/org/apache/inlong/sort/cdc/postgres/table/PostgreSQLReadableMetaData.java [hunk 3]
```diff
@@ -426,8 +435,8 @@ private static StringData getCanalData(SourceRecord record, TableChange tableSch
     /**
      * convert debezium operation to canal-json operation type
      *
-     * @param record
-     * @return
+     * @param record: source record
```
Comment (healchow) [inline inlong-sort/sort-connectors/postgres-cdc/src/main/java/org/apache/inlong/sort/cdc/postgres/table/PostgreSQLReadableMetaData.java:438]: Hi, there are not need add `:` after `@param` and `@return`:

image

After javadoc compiles, it looks like:

image

**Review by gong — APPROVED** [review]

**Review by healchow — APPROVED** [review]
