### PR TITLE
[INLONG-9936][Manager] Support for parallel acquisition of data preview data from multiple Pulsar clusters

### LINKED ISSUE #9936: [Improve][Manager] Support for parallel acquisition of data preview data from multiple Pulsar clusters
### Description

When clusterTag have multiple Pulsar clusters and the amount of data is little, reading the data preview data from only one Pulsar cluster may result in no data being found. If polling all Pulsar clusters, it may cause query timeouts. In this case, it is necessary to query all Pulsar clusters in parallel to avoid timeout exceptions.

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by luchunliang**
### Prepare a Pull Request

- Fixes #9936 

### Motivation

When clusterTag have multiple Pulsar clusters and the amount of data is little, reading the data preview data from only one Pulsar cluster may result in no data being found. If polling all Pulsar clusters, it may cause query timeouts. In this case, it is necessary to query all Pulsar clusters in parallel to avoid timeout exceptions.

### Modifications

*Describe the modifications you've done.*

### Verifying this change

*(Please pick either of the following options)*

- [ ] This change is a trivial rework/code cleanup without any test coverage.

- [ ] This change is already covered by existing tests, such as:
  *(please describe tests)*

- [ ] This change added tests and can be verified as follows:

  *(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a follow-up issue for adding the documentation

### CODE REVIEW

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/pulsar/QueryLatestMessagesRunnable.java [hunk 1]
```diff
@@ -0,0 +1,84 @@
...
+        String namespace = inlongPulsarInfo.getMqResource();
+        String topicName = streamInfo.getMqResource();
+        String fullTopicName = tenant + "/" + namespace + "/" + topicName;
+        String clusterTag = inlongPulsarInfo.getInlongClusterTag();
+        String subs = String.format(PULSAR_SUBSCRIPTION_REALTIME_REVIEW, clusterTag, topicName);
+        boolean serial = InlongConstants.PULSAR_QUEUE_TYPE_SERIAL.equals(inlongPulsarInfo.getQueueModule());
+        List<BriefMQMessage> messages = pulsarOperator.queryLatestMessage(clusterInfo, fullTopicName, subs,
+                messageCount, streamInfo, serial);
+        if (messages != null) {
+            briefMQMessages.addAll(messages);
```
Comment (fuweng11) [inline inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/pulsar/QueryLatestMessagesRunnable.java:80]:
```suggestion
       if(CollectionUtils.isNotEmpty(messages)) {
            briefMQMessages.addAll(messages);
```

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/pulsar/QueryLatestMessagesRunnable.java [hunk 2]
```diff
@@ -0,0 +1,84 @@
...
+
+import java.util.List;
+import java.util.concurrent.CountDownLatch;
+
+/**
+ * QueryLatestMessagesRunnable
+ */
+public class QueryLatestMessagesRunnable implements Runnable {
+
+    public static final String PULSAR_SUBSCRIPTION = "%s_%s_%s_consumer_group";
```
Comment (vernedeng) [inline inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/pulsar/QueryLatestMessagesRunnable.java:36]: It seems a useless definition

Comment (luchunliang) [reply inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/pulsar/QueryLatestMessagesRunnable.java]: fixed

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/pulsar/QueryLatestMessagesRunnable.java (hunk 1 above)
Comment (luchunliang) [reply inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/pulsar/QueryLatestMessagesRunnable.java]: fixed

**Comment by aloyszhang** [comment]
The messages from all clusters are mixed, is it ok?

**Comment by luchunliang** [comment]
> The messages from all clusters are mixed, is it ok?
It is ok, the messages come from a InLong stream of a cluster tag, they have same protocol.

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/pulsar/QueryLatestMessagesRunnable.java [hunk 3]
```diff
@@ -0,0 +1,83 @@
...
+        String namespace = inlongPulsarInfo.getMqResource();
+        String topicName = streamInfo.getMqResource();
+        String fullTopicName = tenant + "/" + namespace + "/" + topicName;
+        String clusterTag = inlongPulsarInfo.getInlongClusterTag();
+        String subs = String.format(PULSAR_SUBSCRIPTION_REALTIME_REVIEW, clusterTag, topicName);
+        boolean serial = InlongConstants.PULSAR_QUEUE_TYPE_SERIAL.equals(inlongPulsarInfo.getQueueModule());
+        List<BriefMQMessage> messages = pulsarOperator.queryLatestMessage(clusterInfo, fullTopicName, subs,
+                messageCount, streamInfo, serial);
+        if (CollectionUtils.isNotEmpty(messages)) {
+            briefMQMessages.addAll(messages);
```
Comment (aloyszhang) [inline inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/pulsar/QueryLatestMessagesRunnable.java:79]: briefMQMessages may have more messages than `messageCount`

Comment (luchunliang) [reply inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/pulsar/QueryLatestMessagesRunnable.java:78]: fixed

**Review by aloyszhang — DISMISSED** [review]

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/pulsar/PulsarQueueResourceOperator.java [hunk 4]
```diff
@@ -303,35 +309,34 @@ private void deletePulsarTopic(InlongPulsarInfo pulsarInfo, PulsarClusterInfo pu
...
                 id, subs, groupId, topicName);
-        return briefMQMessages;
+
+        // cut
+        int finalMsgCount = Math.min(messageCount, briefMQMessages.size());
+        if (finalMsgCount > 0) {
+            return briefMQMessages.subList(0, finalMsgCount);
+        } else {
+            return new ArrayList<>();
+        }
```
Comment (fuweng11) [inline inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/pulsar/PulsarQueueResourceOperator.java:339]:
```suggestion
        int finalMsgCount = Math.max(Math.min(messageCount, briefMQMessages.size()), 0);
        return briefMQMessages.subList(0, finalMsgCount);
```

Comment (luchunliang) [reply inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/pulsar/PulsarQueueResourceOperator.java:339]: This is not necessary. If the size is 0, there is no need to create an ArrayList object + SynchronizedList object.

**Review by fuweng11 — APPROVED** [review]

**Review by vernedeng — APPROVED** [review]
LGTM
