### PR TITLE
[INLONG-5201][Manager] Find entities in the database before updating inlong group

### LINKED ISSUE #5201: [Bug][Manager] The inlong group cannot be updated normally after the approval is successful
### What happened

WeChatWorkScreenshot_28ced6ba-f7ea-4600-b912-9d371e66af2a
After the approval is successful, the cluster tag cannot be inserted into the inlong group normally.

### What you expected to happen

After successful approval, the inlong group and inlong stream can be updated normally.

### How to reproduce

1、New access
2、Approved

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by fuweng11**
### Prepare a Pull Request

- Fixes #5201 

### Motivation

After successful approval, the inlong group and inlong stream can be updated normally.

### Modifications

1、Find entities in the database before updating inlong group.
2、Ensure that each update operation is verified for the success of the update.

### Verifying this change

- [ ] This change is a trivial rework/code cleanup without any test coverage.

- [X] This change is already covered by existing tests, such as:
  *(please describe tests)*

- [ ] This change added tests and can be verified as follows:

### Documentation

  - Does this pull request introduce a new feature? (no)

### CODE REVIEW

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/workflow/group/listener/apply/AfterApprovedTaskListener.java [hunk 1]
```diff
@@ -74,7 +74,7 @@ public ListenerResult listen(WorkflowContext context) throws WorkflowListenerExc
         }
 
         // save the inlong group and other info after approval
-        groupService.updateAfterApprove(approveInfo, context.getOperator());
+        groupService.updateAfterApprove(approveInfo, context.getOperator(), entity);
```
Comment (healchow) [inline inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/workflow/group/listener/apply/AfterApprovedTaskListener.java:77]: Suggest moving the check and entity into the `updateAfterApprove ` method.

**Review by healchow — APPROVED** [review]

**Review by dockerzhang — APPROVED** [review]

**Review by haifxu — APPROVED** [review]
