### PR TITLE
[INLONG-5163][DataProxy] Fixing Pulsar clients initialization error

### LINKED ISSUE #5163: [Bug][DataProxy] Dataproxy can not send data to pulsar as topic NotFoundException
### What happened

Dataproxy can not send data to pulsar:
error info:
send_pulsar_error

### What you expected to happen

Send data to pulsar gracefully, and can decide if using batch type or not by configuration.

### How to reproduce

Using binlog source to collect data

### Environment

_No response_

### InLong version

master

### InLong Component

InLong DataProxy

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by woofyzhao**
- Fixes #5163

The predicate should be after getting the url2token config.

### CODE REVIEW

File: inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/pulsar/PulsarClientService.java [hunk 1]
```diff
@@ -283,9 +284,9 @@ private void sendResponse(OrderEvent orderEvent, String inlongGroupId, String in
      */
     private void createConnection(CreatePulsarClientCallBack callBack) throws FlumeException {
         if (!pulsarClients.isEmpty()) {
+            logger.info("pulsar clients may already be initialized by config updating thread");
```
Comment (dockerzhang) [inline inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/pulsar/PulsarClientService.java:287]: this line may be needless, and I think we should remove it to avoid too logs if `pulsarClients` is not empty.

File: inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/pulsar/PulsarClientService.java [hunk 2]
```diff
@@ -132,8 +132,9 @@ public void setConfigLogMetric(StreamConfigLogMetric streamConfigLogMetric) {
     }
 
     public void initCreateConnection(CreatePulsarClientCallBack callBack) {
+        pulsarUrl2token = ConfigManager.getInstance().getMqClusterUrl2Token();
         if (pulsarUrl2token == null || pulsarUrl2token.isEmpty()) {
-            logger.warn("failed to get Pulsar Cluster, make sure register pulsar to manager successfully.");
+            logger.warn("no pulsar cluster urls on startup, new deployment or cluster not registered properly");
```
Comment (dockerzhang) [inline inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/pulsar/PulsarClientService.java:137]: the translation is not very accurate

**Review by healchow — APPROVED** [review]

**Review by dockerzhang — APPROVED** [review]
