### PR TITLE
[INLONG-5788][DataProxy] Fix the incorrect readFailSize metric value

### LINKED ISSUE #5788: [Bug][DataProxy] Incorrect readFailSize metric value
### What happened

In the case that the sent messages are all successful, the readFailSize value is not 0:
image

From the implementation point of view, it should be caused by an implementation bug:
image

So, we need to adjust it.

### What you expected to happen

Should return to zero when all are successful

### How to reproduce

Send success messages and check the readFailSize value

### Environment

Linux 

### InLong version

master

### InLong Component

InLong DataProxy

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by gosonzhang**
- Fixes #5788 
-

### CODE REVIEW

**Review by luchunliang — APPROVED** [review]
OK

**Review by dockerzhang — APPROVED** [review]

File: inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/TubeSink.java [hunk 1]
```diff
@@ -285,7 +285,7 @@ public Status process() throws EventDeliveryException {
                     cachedMsgCnt.incrementAndGet();
                     DataProxyMetricItem metricItem = this.metricItemSet.findMetricItem(dimensions);
                     metricItem.readSuccessCount.incrementAndGet();
-                    metricItem.readFailSize.addAndGet(event.getBody().length);
+                    metricItem.readSuccessSize.addAndGet(event.getBody().length);
                 } else {
                     tx.rollback();
                     //logger.info("[{}] Channel --> Queue(has no enough space,current code point) "
```
Comment (healchow) [inline inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/TubeSink.java:291]: Could you please remove those unused log codes at the same time?

Comment (gosonzhang) [reply inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/TubeSink.java:291]: I see a lot of such useless comments and codes. It is better to submit a separate issue to solve it.
@healchow

**Review by healchow — APPROVED** [review]
