### PR TITLE
[INLONG-7646][Audit] Fix NPE when mq configuration is not registered

### LINKED ISSUE #7646: [Bug][Audit] NPE when mq configuration is not registered
### What happened

When the MQ configuration has not been registered in the manager, `Audit` obtains the MQ configuration and causes NPE.

企业微信截图_16792136908776

### What you expected to happen

Accurately get the MQ configuration.

### How to reproduce

Run `store-start.sh`

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Audit

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by haifxu**
### Prepare a Pull Request

- Fixes #7646 

### Motivation

When the MQ configuration has not been registered in the manager, Audit obtains the MQ configuration and causes NPE.

image

### Modifications

If the MQ configuration is not obtained, wait for 5 seconds and retry.

### CODE REVIEW

**Review by yunqingmoswu — APPROVED** [review]

File: inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/service/AuditMsgConsumerServer.java [hunk 1]
```diff
@@ -133,19 +135,23 @@ private List<InsertData> getInsertServiceList() {
...
             properties.load(inputStream);
             String managerHosts = properties.getProperty("manager.hosts");
             String clusterTag = properties.getProperty("proxy.cluster.tag");
             String[] hostList = StringUtils.split(managerHosts, ",");
             for (String host : hostList) {
-                List<MQInfo> mqConfig = getMQConfig(host, clusterTag);
-                if (ObjectUtils.isNotEmpty(mqConfig)) {
-                    LOG.info("return mqConfig");
-                    return mqConfig;
+                while (true) {
```
Comment (healchow) [inline inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/service/AuditMsgConsumerServer.java:145]: Do we need to set a maximum number of retries? If it exceeds, it will fail, otherwise, the program will loop infinitely.

File: inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/service/AuditMsgConsumerServer.java [hunk 2]
```diff
@@ -133,19 +135,23 @@ private List<InsertData> getInsertServiceList() {
...
+                    mqConfig = getMQConfig(host, clusterTag);
+                    if (ObjectUtils.isNotEmpty(mqConfig)) {
+                        return mqConfig;
+                    }
+                    LOG.info("MQ config may not be registered yet, wait for 5s and try again");
+                    Thread.sleep(INTERVAL_MS);
```
[the remark this answers is not in the document]
Comment (dockerzhang) [reply inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/service/AuditMsgConsumerServer.java:151]: it's not a common configuration, I think there is no need to add to configuration files.

File: inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/service/AuditMsgConsumerServer.java (hunk 1 above)
Comment (dockerzhang) [reply inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/service/AuditMsgConsumerServer.java:145]: there is no need to set a maximum number of retries, because MQ is a necessary service for audit and other InLong components, we don't know when the users would configure the MQ cluster, it's better to keep waiting.

**Review by dockerzhang — APPROVED** [review]

File: inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/service/AuditMsgConsumerServer.java (hunk 1 above)
Comment (healchow) [reply inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/service/AuditMsgConsumerServer.java:145]: Ok, let's change it like this and keep watching.

**Review by healchow — APPROVED** [review]
