### PR TITLE
[INLONG-6022][Agent] Fix lost read and send count

### LINKED ISSUE #6022: [Bug][Agent] Lost metrics values with send and read
### What happened

Lost metrics values with send and read

### What you expected to happen

Metrics values with send and read are correct

### How to reproduce

Normally run

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Agent

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by lucaspeng12138**
### Prepare a Pull Request

Fix lost read and send count
- Fixes #6022 

### Motivation

Fix lost read and send count

### Modifications

Fix lost read and send count

### Verifying this change

Fix lost read and send count

### CODE REVIEW

File: inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/SenderManager.java [hunk 1]
```diff
@@ -264,11 +265,13 @@ public void sendBatchSync(String groupId, String streamId,
             if (result == SendResult.OK) {
```
Comment (pocozh) [inline inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/SenderManager.java:265]: If `pluginSendCount` includes success and fail, is it better to add it just after doing send operation?

**Review by pocozh — APPROVED** [review]

**Review by healchow — APPROVED** [review]

**Review by dockerzhang — APPROVED** [review]
