### PR TITLE
[INLONG-6507][Sort] Convert date to timestamp in oracle connector

### LINKED ISSUE #6507: [Bug][Sort] Should convert date type to timestamp type in Oracle connector
### What happened

In debezium, the oracle date type will be read as the int64 type, but the oracle date type mapping is the debezium timestamp type, and the debezium timestamp type is the string format of date-time.

For example:

In oracle, if there is a field called `STAET_ DATE`, which is a date type and has a value of `2001-01-13 00:00:00`, but the debezium reads `979315200000`, which is an error.

### What you expected to happen

The date type read by oracle and debezium are consistent.

### How to reproduce

Add a date type field to any table in oracle.

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Sort

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by e-mhui**
### Prepare a Pull Request

[INLONG-6507][Sort] Convert date to timestamp in oracle connector

- Fixes #6507

### Motivation

In debezium, the oracle date type will be read as the int64 type, but the oracle date type mapping is the debezium timestamp type, and the debezium timestamp type is the string format of date-time. So, we need to convert the int64 to the string format of date-time.

### Modifications

When parsing field value, if the field schema is date or timestamp type, we need to convert the filed value from the number of milliseconds to the string format of date-time. The main logic is as follows:

```java
    /**
     * extract the data with the format provided by debezium
     *
     * @param fieldValue
     * @param schemaName
     * @return the extracted data with schema
     */
    private Object getValueWithSchema(Object fieldValue, String schemaName) {
        if (MicroTime.SCHEMA_NAME.equals(schemaName)) {
            Instant instant = Instant.ofEpochMilli((Long) fieldValue / 1000);
            fieldValue = timeFormatter.format(LocalDateTime.ofInstant(instant, serverTimeZone));
        } else if (Date.SCHEMA_NAME.equals(schemaName)) {
            fieldValue = dateFormatter.format(LocalDate.ofEpochDay((Integer) fieldValue));
        } else if (ZonedTimestamp.SCHEMA_NAME.equals(schemaName)) {
            ZonedDateTime zonedDateTime = ZonedDateTime.parse((CharSequence) fieldValue);
            fieldValue = zonedDateTime.withZoneSameInstant(serverTimeZone).toLocalDateTime()
                    .atZone(ZONE_UTC).format(DateTimeFormatter.ISO_INSTANT);
        } else if (Timestamp.SCHEMA_NAME.equals(schemaName)) {
            Instant instantTime = Instant.ofEpochMilli((Long) fieldValue);
            fieldValue = LocalDateTime.ofInstant(instantTime, ZONE_UTC).toString();
        }
        return fieldValue;
    }
```

### CODE REVIEW

**Review by yunqingmoswu — APPROVED** [review]

**Review by healchow — APPROVED** [review]

**Comment by gong** [comment]
Maybe, PR description is not consistent with modification of code

**Review by EMsnap — COMMENTED** [review]
Please check the mysql connector for the date and timestamp data.

**Comment by e-mhui** [comment]
> Please check the mysql connector for the date and timestamp data.

Yes, the oracle connector handles date and timestamp data like the mysql connector.

**Comment by e-mhui** [comment]
> Maybe, PR description is not consistent with modification of code

More details have been added to the PR description.

File: inlong-sort/sort-connectors/oracle-cdc/src/main/java/org/apache/inlong/sort/cdc/oracle/debezium/table/RowDataDebeziumDeserializeSchema.java [hunk 1]
```diff
@@ -760,33 +760,18 @@ public Object convert(Object dbzObj, Schema schema, TableChange tableSchema) thr
      * @return the extracted data with schema
      */
     private Object getValueWithSchema(Object fieldValue, String schemaName) {
-        if (fieldValue == null) {
-            return null;
-        }
-        // Remove shaded pattern prefix of package name
-        schemaName = schemaName.replace(shadedPatternPrefix, "");
```
Comment (gong) [inline inlong-sort/sort-connectors/oracle-cdc/src/main/java/org/apache/inlong/sort/cdc/oracle/debezium/table/RowDataDebeziumDeserializeSchema.java]:
```java
private static final String shadedPatternPrefix = "org.apache.inlong.sort.cdc.oracle.shaded.";
```
It is not used.

**Comment by gong** [comment]
> > Maybe, PR description is not consistent with modification of code
> 
> More details have been added to the PR description.

@e-mhui good.

File: inlong-sort/sort-connectors/oracle-cdc/src/main/java/org/apache/inlong/sort/cdc/oracle/debezium/table/RowDataDebeziumDeserializeSchema.java (hunk 1 above)
Comment (e-mhui) [reply inlong-sort/sort-connectors/oracle-cdc/src/main/java/org/apache/inlong/sort/cdc/oracle/debezium/table/RowDataDebeziumDeserializeSchema.java]: done.

**Review by gong — APPROVED** [review]

**Review by EMsnap — APPROVED** [review]
