### PR TITLE
[INLONG-5818][Sort] Fix metric computing for Pulsar connector

### LINKED ISSUE #5818: [Bug][Sort] Wrong metric computing for Pulsar connector
### What happened

use pulsar connctor

### What you expected to happen

right

### How to reproduce

just use pulsar

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Sort

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by gong**
### Prepare a Pull Request

- [INLONG-5818][Sort] Fix pulsar connector metric computing

- Fixes #5818 

### Motivation

Fix pulsar connector metric computing

### Modifications

* Modify log to slf4j
* Change metric computing

### CODE REVIEW

**Review by thesumery — APPROVED** [review]

**Review by EMsnap — APPROVED** [review]

**Review by yunqingmoswu — APPROVED** [review]

File: inlong-sort/sort-formats/format-inlongmsg-base/src/main/java/org/apache/inlong/sort/formats/inlongmsg/InLongMsgDeserializationSchema.java [hunk 1]
```diff
@@ -38,6 +39,8 @@
 
 public class InLongMsgDeserializationSchema implements DeserializationSchema<RowData> {
 
+    private static final Logger log = LoggerFactory.getLogger(InLongMsgDeserializationSchema.class);
```
Comment (healchow) [inline inlong-sort/sort-formats/format-inlongmsg-base/src/main/java/org/apache/inlong/sort/formats/inlongmsg/InLongMsgDeserializationSchema.java:42]: For static final variable, suggest using UPPER case.

**Review by healchow — APPROVED** [review]
