### PR TITLE
[INLONG-11282][SDK] Transform enhance Array-related Collection Functions

### LINKED ISSUE #11282: [Feature][SDK] Transform enhance Collection Functions
### Description

* parent issue: #10796 
* from flinksql: https://nightlies.apache.org/flink/flink-docs-master/docs/dev/table/functions/systemfunctions/#collection-functions
* this issue will enhance pr #11274 
* enhance Collection Functions of Array() function such as below:

1. `CARDINALITY(array)`--Returns the number of elements in array.
2. `ELEMENT(array)`--Returns the sole element of array (whose cardinality should be one); returns NULL if array is empty. Throws an exception if array has more than one element.
3. `ARRAY_APPEND(array, element)`--Appends an element to the end of the array and returns the result. If the array itself is null, the function will return null. If an element to add is null, the null element will be added to the end of the array.
4. `ARRAY_CONTAINS(haystack, needle)`--Returns whether the given element exists in an array. Checking for null elements in the array is supported. If the array itself is null, the function will return null. The given element is cast implicitly to the array’s element type if necessary.
5. `ARRAY_DISTINCT(haystack)`--Returns an array with unique elements. If the array itself is null, the function will return null. Keeps ordering of elements.
6. `ARRAY_POSITION(haystack, needle)`--Returns the position of the first occurrence of element in the given array as int. Returns 0 if the given value could not be found in the array. Returns null if either of the arguments are null. And this is not zero based, but 1-based index. The first element in the array has index 1.
7. `ARRAY_PREPEND(array, element)`--Appends an element to the beginning of the array and returns the result. If the array itself is null, the function will return null. If an element to add is null, the null element will be added to the beginning of the array.
8. `ARRAY_REMOVE(haystack, needle)`--Removes all elements that equal to element from array. If the array itself is null, the function will return null. Keeps ordering of elements.
9. `ARRAY_REVERSE(haystack)`--Returns an array in reverse order. If the array itself is null, the function will return null.
10. `ARRAY_SLICE(array, start_offset[, end_offset])`--Returns a subarray of the input array between ‘start_offset’ and ’end_offset’ inclusive. The offsets are 1-based however 0 is also treated as the beginning of the array. Positive values are counted from the beginning of the array while negative from the end. If ’end_offset’ is omitted then this offset is treated as the length of the array. If ‘start_offset’ is after ’end_offset’ or both are out of array bounds an empty array will be returned. Returns null if any input is null.
11. `ARRAY_SORT(array[, ascending_order[, null_first]])`--Returns the array in sorted order.The function sorts an array, defaulting to ascending order with NULLs at the start when only the array is input. Specifying ascending_order as true orders the array in ascending with NULLs first, and setting it to false orders it in descending with NULLs last. Independently, null_first as true moves NULLs to the beginning, and as false to the end, irrespective of the sorting order. The function returns null if any input is null.
12. `ARRAY_UNION(array1, array2)`--Returns an array of the elements in the union of array1 and array2, without duplicates. If any of the array is null, the function will return null.
13. `ARRAY_CONCAT(array1, …)`--Returns an array that is the result of concatenating at least one array. This array contains all the elements in the first array, followed by all the elements in the second array, and so forth, up to the Nth array. If any input array is NULL, the function returns NULL.
14. `ARRAY_EXCEPT(array1, array2)`--Returns an ARRAY that contains the elements from array1 that are not in array2, without duplicates. If no elements remain after excluding the elements in array2 from array1, the function returns an empty ARRAY. If one or both arguments are NULL, the function returns NULL. The order of the elements from array1 is kept.
15. `ARRAY_INTERSECT(array1, array2)`--Returns an ARRAY that contains the elements from array1 that are also in array2, without duplicates. If no elements that are both in array1 and array2, the function returns an empty ARRAY. If any of the array is null, the function will return null. The order of the elements from array1 is kept.
16. `ARRAY_MAX(array)`--Returns the maximum value from the array, if array itself is null, the function returns null.
17. `ARRAY_JOIN(array, delimiter[, nullReplacement])`--Returns a string that represents the concatenation of the elements in the given array and the elements’ data type in the given array is string. The delimiter is a string that separates each pair of consecutive elements of the array. The optional nullReplacement is a string that replaces null elements in the array. If nullReplacement is not specified, null elements in the array will be omitted from the resulting string. Returns null if input array or delimiter or nullReplacement are null.
18. `ARRAY_MIN(array)`--Returns the minimum value from the array, if array itself is null, the function returns null.

### Use case

_No response_

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by emptyOVO**
Fixes #11282 

### Motivation
add function classes referenced in issue, provide unit tests for each class

### Verifying this change

*(Please pick either of the following options)*

- [ ] This change is a trivial rework/code cleanup without any test coverage.

- [x] This change is already covered by existing tests, such as:
  *(please describe tests)*

- [ ] This change added tests and can be verified as follows:

  *(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a follow-up issue for adding the documentation

### CODE REVIEW

File: inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/string/TestArrayAppendFunction.java [hunk 1]
```diff
@@ -0,0 +1,88 @@
...
+        config = new TransformConfig(transformSql);
+        processor = TransformProcessor
+                .create(config, SourceDecoderFactory.createCsvDecoder(csvSource),
+                        SinkEncoderFactory.createKvEncoder(kvSink));
+
+        // case1: array_append(array('he',7,'xxd'), 'cloud')
+        data = "he|xxd|cloud|7|3|3";
+        output = processor.transform(data, new HashMap<>());
+        Assert.assertEquals(1, output.size());
+        Assert.assertEquals("result=[he, 7, xxd, cloud]", output.get(0));
```
Comment (luchunliang) [inline inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/string/TestArrayAppendFunction.java:50]: These array operation functions lack application scenarios. Currently, JSON array functions such as json_array_contains are used.
The SQL is "select json_array_contains(string1,'he') from source".
Source data is "['he',7,'xxd']|cloud|aa";
Sink data is "result=true".

Comment (emptyOVO) [reply inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/string/TestArrayAppendFunction.java:50]: i think of application scenarios here is to be able to operate on arrays after the ARRAY() function is used，we can still customize what we want to do with the array

**Review by luchunliang — APPROVED** [review]

**Review by aloyszhang — APPROVED** [review]

**Review by luchunliang — APPROVED** [review]
