### PR TITLE
[INLONG-7011][Manager] Check Pulsar non-partition table if exist

### LINKED ISSUE #7011: [Bug][Manager] Check Pulsar non-partitioned table if exist
### What happened

For pulsar non-partitioned tables, when the list is obtained through 'topics', the topic name returned by default has a suffix.
Therefore, when judging whether it exists, special processing is required

### What you expected to happen

For pulsar non-partitioned tables, remove the suffix of topic name.

### How to reproduce

Step 1. pulsar non-partitioned
Step 2. create pulsar table
Step 3. check if exist

### Environment

_No response_

### InLong version

1.4.0

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by featzhang**
### Prepare a Pull Request
*[INLONG-7011][Manager] Check Pulsar non-partition table if exist*
 
- Fixes #7011 

### Motivation

*Explain here the context, and why you're making that change. What is the problem you're trying to solve?*

### Modifications

*Describe the modifications you've done.*

### Verifying this change

*(Please pick either of the following options)*

- [x] This change is a trivial rework/code cleanup without any test coverage.

- [x] This change is already covered by existing tests, such as:
  *(please describe tests)*

- [ ] This change added tests and can be verified as follows:

  *(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a follow-up issue for adding the documentation

### CODE REVIEW

**Review by healchow — APPROVED** [review]

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/pulsar/PulsarOperator.java [hunk 1]
```diff
@@ -292,6 +292,9 @@ public boolean topicExists(PulsarAdmin pulsarAdmin, String tenant, String namesp
             }
             for (String t : topicList) {
                 t = t.substring(t.lastIndexOf("/") + 1); // not contains /
+                if (!isPartitioned) {
+                    t = t.substring(0, t.lastIndexOf("-partition-"));
```
Comment (healchow) [inline inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/pulsar/PulsarOperator.java:296]: @aloyszhang  @lordcheng10 PTAL

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/pulsar/PulsarOperator.java [hunk 2]
```diff
@@ -292,6 +292,9 @@ public boolean topicExists(PulsarAdmin pulsarAdmin, String tenant, String namesp
             }
             for (String t : topicList) {
                 t = t.substring(t.lastIndexOf("/") + 1); // not contains /
+                if (!isPartitioned) {
```
Comment (aloyszhang) [inline inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/pulsar/PulsarOperator.java:295]: Exception cound be thrown if the topic(non-partitioned topic) is not suffixed with `-partition-`

**Review by aloyszhang — APPROVED** [review]
LGTM

**Review by healchow — APPROVED** [review]

**Review by dockerzhang — APPROVED** [review]
