### PR TITLE
[INLONG-9791][Sort] Return null instead of throwing an exception when deserialization by type fails

### LINKED ISSUE #9791: [Feature][Sort] Return null instead of throwing an exception when deserialization by type fails
### Description

_No response_

### Use case

_No response_

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by baomingyu**
- Fixes #9791

### CODE REVIEW

File: inlong-sort/sort-formats/format-rowdata/format-rowdata-base/src/main/java/org/apache/inlong/sort/formats/base/DefaultDeserializationSchema.java [hunk 1]
```diff
@@ -110,7 +125,7 @@ public boolean skipCurrentRecord(T element) {
         return ignoreErrors && errorOccurred;
     }
 
-    protected abstract T deserializeInternal(byte[] bytes) throws IOException;
+    protected abstract T deserializeInternal(byte[] bytes) throws Exception;
```
Comment (aloyszhang) [inline inlong-sort/sort-formats/format-rowdata/format-rowdata-base/src/main/java/org/apache/inlong/sort/formats/base/DefaultDeserializationSchema.java:128]: Why expand IOException to Exception？

File: inlong-sort/sort-formats/format-common/src/main/java/org/apache/inlong/sort/formats/inlongmsg/IgnoreFailureHandler.java [hunk 2]
```diff
@@ -27,6 +27,11 @@ public class IgnoreFailureHandler implements FailureHandler {
 
     private static final Logger LOG = LoggerFactory.getLogger(IgnoreFailureHandler.class);
 
+    @Override
+    public void onParsingMsgFailure(Object msg, Exception exception) {
+        LOG.error("Could not properly serialize msg=[%s].", msg, exception);
```
Comment (aloyszhang) [inline inlong-sort/sort-formats/format-common/src/main/java/org/apache/inlong/sort/formats/inlongmsg/IgnoreFailureHandler.java:32]: LOG may not recognize the %s here

File: inlong-sort/sort-formats/format-common/src/main/java/org/apache/inlong/sort/formats/inlongmsg/NoOpFailureHandler.java [hunk 3]
```diff
@@ -27,6 +27,12 @@ public class NoOpFailureHandler implements FailureHandler {
 
     private static final Logger LOG = LoggerFactory.getLogger(NoOpFailureHandler.class);
 
+    @Override
+    public void onParsingMsgFailure(Object msg, Exception t) throws Exception {
+        LOG.error("Could not properly serialize msg=[%s].", msg, t);
```
Comment (aloyszhang) [inline inlong-sort/sort-formats/format-common/src/main/java/org/apache/inlong/sort/formats/inlongmsg/NoOpFailureHandler.java:32]: ditto

File: inlong-sort/sort-formats/format-rowdata/format-rowdata-json/src/main/java/org/apache/inlong/sort/formats/json/JsonRowDataDeserializationSchema.java [hunk 4]
```diff
@@ -104,13 +103,20 @@ public static Builder builder(RowType rowType, TypeInformation<RowData> resultTy
...
             return null;
         }
 
         String jsonStr = new String(message, charset);
-        return (RowData) runtimeConverter.convert(jsonStr);
+        RowData rowData = null;
+        try {
+            rowData = (RowData) runtimeConverter.convert(jsonStr);
+        } catch (Throwable t) {
+            failureHandler.onParsingMsgFailure(message, new RuntimeException(
```
Comment (aloyszhang) [inline inlong-sort/sort-formats/format-rowdata/format-rowdata-json/src/main/java/org/apache/inlong/sort/formats/json/JsonRowDataDeserializationSchema.java:116]: For readability, `jsonStr` is better than `message`

File: inlong-sort/sort-formats/format-rowdata/format-rowdata-csv/src/main/java/org/apache/inlong/sort/formats/csv/CsvRowDataDeserializationSchema.java [hunk 5]
```diff
@@ -241,12 +241,12 @@ public RowData deserializeInternal(@Nullable byte[] message) {
                     rowData.setField(i, converters[i].convert(field));
                 }
             }
-
             return rowData;
         } catch (Throwable t) {
-            throw new RuntimeException(
-                    String.format("Could not properly deserialize csv. Text=[%s].", text), t);
+            failureHandler.onParsingMsgFailure(message, new RuntimeException(
```
Comment (aloyszhang) [inline inlong-sort/sort-formats/format-rowdata/format-rowdata-csv/src/main/java/org/apache/inlong/sort/formats/csv/CsvRowDataDeserializationSchema.java:246]: `text` is more readable than `message`

File: inlong-sort/sort-formats/format-rowdata/format-rowdata-kv/src/main/java/org/apache/inlong/sort/formats/kv/KvRowDataDeserializationSchema.java [hunk 6]
```diff
@@ -170,9 +171,10 @@ public RowData deserializeInternal(byte[] bytes) throws IOException {
             }
             return rowData;
         } catch (Throwable t) {
-            throw new IOException(
-                    String.format("Could not properly deserialize kv. Text=[%s].", text), t);
+            failureHandler.onParsingMsgFailure(bytes, new RuntimeException(
```
Comment (aloyszhang) [inline inlong-sort/sort-formats/format-rowdata/format-rowdata-kv/src/main/java/org/apache/inlong/sort/formats/kv/KvRowDataDeserializationSchema.java:174]: ditto

File: inlong-sort/sort-formats/format-rowdata/format-rowdata-json/src/main/java/org/apache/inlong/sort/formats/json/JsonRowDataDeserializationSchema.java (hunk 4 above)
Comment (baomingyu) [reply inlong-sort/sort-formats/format-rowdata/format-rowdata-json/src/main/java/org/apache/inlong/sort/formats/json/JsonRowDataDeserializationSchema.java:116]: onParsingMsgFailure's parameter is byte type. josnStr is string

File: inlong-sort/sort-formats/format-rowdata/format-rowdata-base/src/main/java/org/apache/inlong/sort/formats/base/DefaultDeserializationSchema.java (hunk 1 above)
Comment (baomingyu) [reply inlong-sort/sort-formats/format-rowdata/format-rowdata-base/src/main/java/org/apache/inlong/sort/formats/base/DefaultDeserializationSchema.java:128]: failed handler throw Exception, not IOException

File: inlong-sort/sort-formats/format-rowdata/format-rowdata-csv/src/main/java/org/apache/inlong/sort/formats/csv/CsvRowDataDeserializationSchema.java (hunk 5 above)
Comment (baomingyu) [reply inlong-sort/sort-formats/format-rowdata/format-rowdata-csv/src/main/java/org/apache/inlong/sort/formats/csv/CsvRowDataDeserializationSchema.java]: done

File: inlong-sort/sort-formats/format-rowdata/format-rowdata-kv/src/main/java/org/apache/inlong/sort/formats/kv/KvRowDataDeserializationSchema.java (hunk 6 above)
Comment (baomingyu) [reply inlong-sort/sort-formats/format-rowdata/format-rowdata-kv/src/main/java/org/apache/inlong/sort/formats/kv/KvRowDataDeserializationSchema.java]: done

**Comment by EMsnap** [comment]
please update the description 
image

File: inlong-sort/sort-formats/format-common/src/main/java/org/apache/inlong/sort/formats/inlongmsg/IgnoreFailureHandler.java [hunk 7]
```diff
@@ -27,6 +27,11 @@ public class IgnoreFailureHandler implements FailureHandler {
 
     private static final Logger LOG = LoggerFactory.getLogger(IgnoreFailureHandler.class);
 
+    @Override
+    public void onParsingMsgFailure(Object msg, Exception exception) {
+        LOG.error("Could not properly serialize msg=[{}].", msg, exception);
```
Comment (EMsnap) [inline inlong-sort/sort-formats/format-common/src/main/java/org/apache/inlong/sort/formats/inlongmsg/IgnoreFailureHandler.java:32]: I believe parse is equal to deserialize rather than serialize

File: inlong-sort/sort-formats/format-common/src/main/java/org/apache/inlong/sort/formats/inlongmsg/FailureHandler.java [hunk 8]
```diff
@@ -24,6 +24,16 @@
  */
 public interface FailureHandler extends Serializable {
 
+    /**
+     * This method is called when there is a failure occurred while parsing not InLongMsg.
```
Comment (EMsnap) [inline inlong-sort/sort-formats/format-common/src/main/java/org/apache/inlong/sort/formats/inlongmsg/FailureHandler.java:28]: parsing non-inlong message

**Review by aloyszhang — DISMISSED** [review]

File: inlong-sort/sort-formats/format-rowdata/format-rowdata-base/src/main/java/org/apache/inlong/sort/formats/base/DefaultDeserializationSchema.java [hunk 9]
```diff
@@ -49,13 +52,25 @@ public abstract class DefaultDeserializationSchema<T> implements Deserialization
...
+        if (ignoreErrors) {
+            failureHandler = new IgnoreFailureHandler();
+        } else {
+            failureHandler = new NoOpFailureHandler();
+        }
+    }
+
+    public DefaultDeserializationSchema(FailureHandler failureHandler) {
+        this.failureHandler = failureHandler;
+        this.ignoreErrors = false;
```
Comment (EMsnap) [inline inlong-sort/sort-formats/format-rowdata/format-rowdata-base/src/main/java/org/apache/inlong/sort/formats/base/DefaultDeserializationSchema.java:73]: why         this.ignoreErrors = false is alway false? maybe user will pass IgnoreFailureHandler here

File: inlong-sort/sort-formats/format-common/src/main/java/org/apache/inlong/sort/formats/inlongmsg/NoOpFailureHandler.java (hunk 3 above)
Comment (baomingyu) [reply inlong-sort/sort-formats/format-common/src/main/java/org/apache/inlong/sort/formats/inlongmsg/NoOpFailureHandler.java]: done

File: inlong-sort/sort-formats/format-rowdata/format-rowdata-base/src/main/java/org/apache/inlong/sort/formats/base/DefaultDeserializationSchema.java (hunk 9 above)
Comment (baomingyu) [reply inlong-sort/sort-formats/format-rowdata/format-rowdata-base/src/main/java/org/apache/inlong/sort/formats/base/DefaultDeserializationSchema.java]: done

File: inlong-sort/sort-formats/format-common/src/main/java/org/apache/inlong/sort/formats/inlongmsg/FailureHandler.java (hunk 8 above)
Comment (baomingyu) [reply inlong-sort/sort-formats/format-common/src/main/java/org/apache/inlong/sort/formats/inlongmsg/FailureHandler.java]: done

File: inlong-sort/sort-formats/format-common/src/main/java/org/apache/inlong/sort/formats/inlongmsg/IgnoreFailureHandler.java (hunk 7 above)
Comment (baomingyu) [reply inlong-sort/sort-formats/format-common/src/main/java/org/apache/inlong/sort/formats/inlongmsg/IgnoreFailureHandler.java]: done

**Review by aloyszhang — DISMISSED** [review]

**Comment by dockerzhang** [comment]
@baomingyu please fix the failed UT, thanks.

**Review by aloyszhang — DISMISSED** [review]

**Review by dockerzhang — DISMISSED** [review]

**Review by dockerzhang — APPROVED** [review]

**Review by aloyszhang — APPROVED** [review]

**Review by vernedeng — APPROVED** [review]
