### PR TITLE
[INLONG-9285][Manager] When creating KafkaSource, the autoOffsetReset param cannot be empty

### LINKED ISSUE #9285: [Bug][Manager] When creating KafkaSource, the autoOffsetReset param cannot be empty
### What happened

When I used the client to create a data synchronization task for Kafka2Hive I found that the Kafka source must be set to 'autoOffsetReset' when submitting it, and an exception occurred at this time

### What you expected to happen

If I have not set 'autoOffsetReset', there should be a default value so that no errors will be reported

### How to reproduce

Executing the ‘org.apache.inlong.manager.client.ut.Kafka2HiveTest#testCreateGroupForHive’ method will result in an exception

image

### Environment

_No response_

### InLong version

1.9.0

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by LiJie20190102**
When creating 'KafkaSource', 'autoOffsetReset' cannot be empty

### Prepare a Pull Request
*(Change the title refer to the following example)*

- [INLONG-9285][Manager]When creating 'KafkaSource', 'autoOffsetReset' cannot be empty

*(The following *XYZ* should be replaced by the actual [GitHub Issue](https://github.com/apache/inlong/issues) number)*

- Fixes #9285 

### Motivation

      When I used the client to create a data synchronization task for Kafka2Hive I found that the Kafka source must be set to 'autoOffsetReset' when submitting it, and an exception occurred at this time.
      I found from the error log that 'fieldList' will be supplemented, but 'autoOffsetReset' will not be assigned a value：
    
image
      Of course, 'org.apache.inlong.manager.service.source.kafka.KafkaSourceOperator#getSourcesMap' will assign a value to 'autoOffsetReset'
image

### Modifications

Provide the initial value 'latest' for 'autoOffsetReset'

### Verifying this change

*(Please pick either of the following options)*

- [ ] This change is a trivial rework/code cleanup without any test coverage.

- [√ ] This change is already covered by existing tests, such as:
- Add ‘org.apache.inlong.manager.client.ut.Kafka2HiveTest#testCreateGroupForHive’ testing information, then create a new task, and observe the manager logs.

- [ ] This change added tests and can be verified as follows:

  *(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a follow-up issue for adding the documentation

### CODE REVIEW

File: inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/kafka/KafkaSource.java [hunk 1]
```diff
@@ -67,7 +67,7 @@ public class KafkaSource extends StreamSource {
     private String timestampMillis;
 
     @ApiModelProperty(value = "The strategy of auto offset reset", notes = "including earliest, specific, latest (the default), none")
-    private String autoOffsetReset;
+    private String autoOffsetReset = "latest";
```
Comment (dockerzhang) [inline inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/kafka/KafkaSource.java:70]: it's better to use an enum value?

Comment (LiJie20190102) [reply inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/kafka/KafkaSource.java]: ok

**Review by dockerzhang — APPROVED** [review]

File: inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/kafka/KafkaSource.java [hunk 2]
```diff
@@ -67,7 +68,7 @@ public class KafkaSource extends StreamSource {
     private String timestampMillis;
 
     @ApiModelProperty(value = "The strategy of auto offset reset", notes = "including earliest, specific, latest (the default), none")
-    private String autoOffsetReset;
+    private KafkaOffset autoOffsetReset = KafkaOffset.LATEST;
```
Comment (fuweng11) [inline inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/kafka/KafkaSource.java:71]: `AutoOffsetReset` also exists in `KafkaSourceRequest` and `KafkaSourceDTO`. If kafka is used as the source during data synchronization, it will become unavailable.

**Review by vernedeng — DISMISSED** [review]

File: inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/kafka/KafkaSource.java (hunk 2 above)
Comment (fuweng11) [reply inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/kafka/KafkaSource.java:71]: Just set the default value of source to private `String autoOffsetReset=KafkaOffset. LATEST. getName()`;

File: inlong-manager/manager-client/src/test/java/org/apache/inlong/manager/client/api/inner/ClientFactoryTest.java [hunk 3]
```diff
@@ -37,6 +37,7 @@
 import org.apache.inlong.manager.common.consts.SinkType;
 import org.apache.inlong.manager.common.consts.SourceType;
 import org.apache.inlong.manager.common.enums.ClusterType;
+import org.apache.inlong.manager.common.enums.KafkaOffset;
```
Comment (healchow) [inline inlong-manager/manager-client/src/test/java/org/apache/inlong/manager/client/api/inner/ClientFactoryTest.java:40]: The KafkaOffset class is only used by Kafka and is not intended for public use. Therefore, I don't think it's appropriate to place it in the common package.

Comment (LiJie20190102) [reply inlong-manager/manager-client/src/test/java/org/apache/inlong/manager/client/api/inner/ClientFactoryTest.java]: OK

File: inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/kafka/KafkaSourceRequest.java [hunk 4]
```diff
@@ -62,7 +62,7 @@ public class KafkaSourceRequest extends SourceRequest {
     private String timestampMillis;
 
     @ApiModelProperty(value = "The strategy of auto offset reset", notes = "including earliest, latest (the default), none")
-    private String autoOffsetReset;
+    private KafkaOffset autoOffsetReset = KafkaOffset.LATEST;
```
Comment (fuweng11) [inline inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/kafka/KafkaSourceRequest.java:65]: This will result in the following error if `autoOffsetReset: "latest"` is set when saving `kafkaSourceRequest`.
企业微信截图_f9bd448c-dd87-47bd-929d-87cb7ae41358

Comment (fuweng11) [reply inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/kafka/KafkaSourceRequest.java:65]: And it is best not to set the default value in the request, as this will cause the default value to be overwritten if you do not want to modify the `kakfaSource` and pass `autoOffsetReset: null`.

File: inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/kafka/KafkaSource.java (hunk 2 above)
Comment (LiJie20190102) [reply inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/kafka/KafkaSource.java]: OK

File: inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/kafka/KafkaSourceRequest.java (hunk 4 above)
Comment (LiJie20190102) [reply inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/kafka/KafkaSourceRequest.java]: Okay, thank you. I see

**Review by fuweng11 — APPROVED** [review]

**Review by dockerzhang — APPROVED** [review]

**Review by vernedeng — APPROVED** [review]

**Review by healchow — APPROVED** [review]
