### PR TITLE
[INLONG-8013][Sort] Fix UT failed caused by OOM

### LINKED ISSUE #8013: [Bug][Sort] Cause lots of OOM UT failed
### What happened

Cause logs of OOM UT failed.

image

### What you expected to happen

All UTs passed

### How to reproduce

see the latest workflow.

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Sort

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by e-mhui**
### Prepare a Pull Request

[INLONG-8013][Sort] Fix UT failed

*(The following *XYZ* should be replaced by the actual [GitHub Issue](https://github.com/apache/inlong/issues) number)*

- Fixes #8013 

### Motivation

There are two ways to solve it:

1. All test classes need to inherit from `AbstractTestBase`, because `AbstractTestBase` can reuse the same Flink cluster, which can reduce resource usage.

image

2. Add the `taskmanager.memory.network.min` parameter to limit the memory consumption of the network (the default memory for the network is 64 MB). More details see: https://nightlies.apache.org/flink/flink-docs-release-1.17/docs/deployment/memory/mem_setup_tm/

```java
        EnvironmentSettings settings = EnvironmentSettings
                .newInstance()
                .useBlinkPlanner()
                .inStreamingMode()
                .build();
        Configuration configuration = new Configuration();
        // Set `taskmanager.memory.network.min` to avoid NetworkBufferPool OOM during run workflow.
        configuration.setString("taskmanager.memory.network.min", "1 mb");
        env = StreamExecutionEnvironment.getExecutionEnvironment(configuration);
        env.setParallelism(1);
        env.enableCheckpointing(10000);
        this.tableEnv = StreamTableEnvironment.create(env, settings);
```

### CODE REVIEW

File: inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/AllMigrateMongoDBTest.java [hunk 1]
```diff
@@ -40,6 +40,7 @@
 import org.apache.inlong.sort.protocol.node.load.KafkaLoadNode;
 import org.apache.inlong.sort.protocol.transformation.FieldRelation;
 import org.apache.inlong.sort.protocol.transformation.relation.NodeRelation;
+import org.junit.Assert;
```
Comment (healchow) [inline inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/AllMigrateMongoDBTest.java:43]: Why import this class here?

**Comment by EMsnap** [comment]
maybe this is not the reason for the failure of UT case and we should find out the root cause of the OOM. Maybe we can login to the compile machine to analyse  ?

**Review by yunqingmoswu — APPROVED** [review]

File: inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/AllMigrateMongoDBTest.java (hunk 1 above)
Comment (e-mhui) [reply inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/AllMigrateMongoDBTest.java:44]: This PR  https://github.com/apache/inlong/pull/7998 caused OOM when running the workflow. Adding this is to test whether there is any impact.

**Review by dockerzhang — APPROVED** [review]

**Review by healchow — APPROVED** [review]
