### PR TITLE
[INLONG-6003][Manager] Change the transform source node name to be MQ node in standard mode

### LINKED ISSUE #6003: [Bug][Manager] The transform source node relation is incorrect under standard mode
### What happened

The transform input node is wrong

### What you expected to happen

Should be mq node instead of upstream source in sort configuration

### How to reproduce

Use transform under standard mode

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by woofyzhao**
- Fixes #6003

### Motivation

In the beginning only **lightweight mode** supports the ETL transform nodes. Clients configure their extract/transform/load nodes  at will and what they submit is what they see so everyone is happy.

This ceases to be the case when **standard sort mode** tries to support transform nodes as well. In standard mode multiple upstream sources are collected to MQ first and are not the real extract nodes anymore. Instead the MQ cache node becomes **the real extract node**.  

This is achieved by manager through replacing the original upstream source nodes (file、binlog...) with the MQ cache node when constructing the extract node in standard mode.

However the clients are ignorant of any of this.  From their point of view nothing is changed and the MQ node is invisible to them. So in their submitted **node relation configuration** the extract node is still some upstream source node (file、binlog...) rather than the MQ cache node. This results in the incorrect DataFlow configuration:

image

### Changes
- change the transform fields's original node id to be MQ cache node
-  update the user submitted node relation to use MQ cache node as the real extract node

### CODE REVIEW

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sort/DefaultSortConfigOperator.java [hunk 1]
```diff
@@ -137,6 +148,58 @@ private GroupInfo getGroupInfo(InlongGroupInfo groupInfo, List<InlongStreamInfo>
...
+        }
+
+        // set relations' input node to mq node when necessary
+        String mqNodeName = sources.get(0).getSourceName();
+        Set<String> validNameSet = getValidInputNodeNamesInStandardMode(sources, transforms);
+        for (NodeRelation relation : relations) {
+            List<String> inputs = relation.getInputs();
+            for (int index = 0; index < inputs.size(); ++index) {
+                String inputName = inputs.get(index);
+                if (!(validNameSet.contains(inputName))) {
```
Comment (yunqingmoswu) [inline inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sort/DefaultSortConfigOperator.java:196]: !(validNameSet.contains(inputName)) -> !validNameSet.contains(inputName)

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sort/DefaultSortConfigOperator.java [hunk 2]
```diff
@@ -137,6 +148,58 @@ private GroupInfo getGroupInfo(InlongGroupInfo groupInfo, List<InlongStreamInfo>
...
+    }
+
+    private void adjustNodeRelations(List<NodeRelation> relations, InlongGroupInfo groupInfo,
+            List<StreamSource> sources, List<TransformResponse> transforms) {
+        if (InlongConstants.LIGHTWEIGHT_MODE.equals(groupInfo.getLightweight())) {
+            return;
+        }
+
+        // set relations' input node to mq node when necessary
+        String mqNodeName = sources.get(0).getSourceName();
```
Comment (yunqingmoswu) [inline inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sort/DefaultSortConfigOperator.java:190]: Why is it get(0)?

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sort/DefaultSortConfigOperator.java [hunk 3]
```diff
@@ -137,6 +148,58 @@ private GroupInfo getGroupInfo(InlongGroupInfo groupInfo, List<InlongStreamInfo>
...
+    }
+
+    private void preprocessTransformList(InlongGroupInfo groupInfo, List<StreamSource> sources,
+            List<TransformResponse> transforms) {
+        if (InlongConstants.LIGHTWEIGHT_MODE.equals(groupInfo.getLightweight())) {
+            return;
+        }
+
+        // set transform fields' origin node to mq node when necessary
+        String mqNodeName = sources.get(0).getSourceName();
```
Comment (yunqingmoswu) [inline inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sort/DefaultSortConfigOperator.java:169]: Why is it get(0)?

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sort/DefaultSortConfigOperator.java [hunk 4]
```diff
@@ -137,6 +148,58 @@ private GroupInfo getGroupInfo(InlongGroupInfo groupInfo, List<InlongStreamInfo>
...
+        Set<String> validNameSet = getValidInputNodeNamesInStandardMode(sources, transforms);
+        for (TransformResponse transform : transforms) {
+            for (StreamField field : transform.getFieldList()) {
+                String originNodeName = field.getOriginNodeName();
+                if (!(validNameSet.contains(originNodeName))) {
```
Comment (yunqingmoswu) [inline inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sort/DefaultSortConfigOperator.java:174]: !(validNameSet.contains(originNodeName)) -> !validNameSet.contains(originNodeName)

**Review by yunqingmoswu — COMMENTED** [review]
Should the relation between Agent source and MQ source be found instead of MQSources.get(0)

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sort/DefaultSortConfigOperator.java (hunk 2 above)
Comment (woofyzhao) [reply inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sort/DefaultSortConfigOperator.java:190]: In standard mode there is exactly one mq source for each stream at the moment. 
Its source name is the corresponding stream id.

**Comment by woofyzhao** [comment]
> Should the relation between Agent source and MQ source be found instead of MQSources.get(0)

The source object here, when understand mode, is already the MQ source found. Currently there is exactly one mq source for each stream.

**Review by yunqingmoswu — APPROVED** [review]

**Review by healchow — APPROVED** [review]
