### PR TITLE
[INLONG-11455][Sort] Only one OpenTelemetryAppender should be registered

### LINKED ISSUE #11455: [Bug][Sort] Only one OpenTelemetryAppender should be registered
### What happened

The current `OpenTelemetryLogger` may generate multiple OpenTelemetryAppenders, which may cause duplicate log reporting.

### What you expected to happen

Only one OpenTelemetryAppender should be registered

### How to reproduce

Some connectors need to instantiate multiple sourceReaders, which will cause multiple identical OpenTelemetryAppenders to be registered in the LoggerContext.

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Sort

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by qy-liuhuo**
Fixes #11455 

### Motivation

Only one OpenTelemetryAppender should be registered

### Modifications

Added duplicate registration judgment to the install and uninstall functions, and use synchronized locks to ensure concurrency safety.

Furthermore, since users may set different logging levels, force log messages to be appended on successful installs and uninstalls to ensure successful reporting at any logging level. This also makes it easier to write unit tests to check that the logging reports are working.

```java
before:
LOG.info("OpenTelemetryLogger installed");

now:
otelAppender.append(
                    new Log4jLogEvent.Builder()
                        .setLevel(Level.INFO)
                        .setMessage(new SimpleMessage("OpenTelemetryLogger installed"))
                        .build());
```

### Verifying this change

*(Please pick either of the following options)*

- [ ] This change is a trivial rework/code cleanup without any test coverage.

- [ ] This change is already covered by existing tests, such as:
  *(please describe tests)*

- [ ] This change added tests and can be verified as follows:

  *(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a follow-up issue for adding the documentation

### CODE REVIEW

File: inlong-sort/sort-flink/base/src/main/java/org/apache/inlong/sort/base/util/OpenTelemetryLogger.java [hunk 1]
```diff
@@ -172,64 +175,80 @@ private void createOpenTelemetrySdk() {
...
-    public void install() {
-        addOpenTelemetryAppender();
-        createOpenTelemetrySdk();
-        OpenTelemetryAppender.install(SDK);
-        LOG.info("OpenTelemetryLogger installed");
+    public boolean install() {
+        synchronized (OpenTelemetryLogger.class) {
+            org.apache.logging.log4j.spi.LoggerContext loggerContextSpi = LogManager.getContext(false);
+            if (!(loggerContextSpi instanceof LoggerContext)) {
+                LOG.warn("LoggerContext is not instance of LoggerContext");
```
Comment (vernedeng) [inline inlong-sort/sort-flink/base/src/main/java/org/apache/inlong/sort/base/util/OpenTelemetryLogger.java:185]: please log the loaded whole class name and the target whole class name.

**Comment by qy-liuhuo** [comment]
It seems that this failed unit test was not caused by this pr，can you restart it for me

**Review by vernedeng — APPROVED** [review]

**Review by dockerzhang — APPROVED** [review]

**Review by EMsnap — APPROVED** [review]

**Review by XiaoYou201 — APPROVED** [review]
LGTM~
