### PR TITLE
[INLONG-6343][Manager] Fix the problem that the cluster tag is empty when saving cluster information

### LINKED ISSUE #6343: [Bug][Manager] Get NullPointerException when bind cluster
### What happened

企业微信截图_16672147574022

企业微信截图_16672147803272

### What you expected to happen

bind successfully.

### How to reproduce

build master branch and deploy.

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by fuweng11**
### Prepare a Pull Request
- Fixes #6343 

### Motivation
Ensure that the key information is not empty when saving the cluster information
### Modifications
When saving cluster information, determine whether the cluster tag, type, name is empty

When saving cluster information, determine whether the cluster tag, type, name is empty

### Verifying this change

- [X] This change is a trivial rework/code cleanup without any test coverage.

- [ ] This change is already covered by existing tests, such as:
  *(please describe tests)*

- [ ] This change added tests and can be verified as follows:

  *(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Documentation

  - Does this pull request introduce a new feature? (no)

### CODE REVIEW

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/heartbeat/HeartbeatManager.java [hunk 1]
```diff
@@ -215,6 +216,9 @@ private ClusterInfo fetchCluster(ComponentHeartbeat componentHeartbeat) {
         final String clusterName = componentHeartbeat.getClusterName();
         final String type = componentHeartbeat.getComponentType();
         final String clusterTag = componentHeartbeat.getClusterTag();
+        Preconditions.checkNotNull(clusterTag, "cluster tag cannot be null");
+        Preconditions.checkNotNull(type, "cluster type cannot be null");
+        Preconditions.checkNotNull(clusterTag, "cluster name cannot be null");
```
Comment (healchow) [inline inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/heartbeat/HeartbeatManager.java:221]: `clasterName`

**Review by dockerzhang — APPROVED** [review]

**Review by healchow — APPROVED** [review]

**Review by ciscozhou — APPROVED** [review]

**Review by GanfengTan — APPROVED** [review]

**Review by LvJiancheng — APPROVED** [review]
