### PR TITLE
[INLONG-5830][DataProxy] Fix required parameter topic exception

### LINKED ISSUE #5830: [Bug][DataProxy] Required parameter topic exception
### What happened

be990f1903b7af615e29f3c8a0d949e

### What you expected to happen

In the HTTP configuration file of dataproxy, if pulsar topic is not configured, an exception will be thrown, but this topic will not be used.

### How to reproduce

Start dataproxy with http config file.

### Environment

_No response_

### InLong version

master

### InLong Component

InLong DataProxy

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by xuesongxs**
- Fixes #5830

### CODE REVIEW

File: inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/http/HttpBaseSource.java [hunk 1]
```diff
@@ -117,10 +117,7 @@ public void configure(Context context) {
 
         topic = context.getString(ConfigConstants.TOPIC);
         attr = context.getString(ConfigConstants.ATTR);
-        Configurables.ensureRequiredNonNull(context, ConfigConstants.TOPIC, ConfigConstants.ATTR);
```
Comment (gosonzhang) [inline inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/http/HttpBaseSource.java:120]: How to handle the message if the topic is empty and not checked?

**Comment by xuesongxs** [comment]
Use the topic in the topics.properties file to handle the message, instead of using the topic field in the dataproxy-mulit-pulsar-http-example.conf file.

From: Goson Zhang
Date: 2022-09-08 15:26
To: apache/inlong
CC: xuesongxs; Author
Subject: Re: [apache/inlong] [INLONG-5830][DataProxy] Fix required parameter topic exception (PR #5831)
@gosonzhang commented on this pull request.


In inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/http/HttpBaseSource.java:
> @@ -117,10 +117,7 @@ public void configure(Context context) {
 
         topic = context.getString(ConfigConstants.TOPIC);
         attr = context.getString(ConfigConstants.ATTR);
-        Configurables.ensureRequiredNonNull(context, ConfigConstants.TOPIC, ConfigConstants.ATTR);

How to handle the message if the topic is empty and not checked?

File: inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/http/HttpBaseSource.java (hunk 1 above)
Comment (xuesongxs) [reply inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/http/HttpBaseSource.java:120]: > How to handle the message if the topic is empty and not checked?

Use the topic in the topics.properties file to handle the message, instead of using the topic field in the dataproxy-mulit-pulsar-http-example.conf file.

Comment (xuesongxs) [reply inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/http/HttpBaseSource.java:120]: image

**Review by gosonzhang — APPROVED** [review]

**Review by healchow — APPROVED** [review]

File: inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/http/HttpBaseSource.java (hunk 1 above)
Comment (gosonzhang) [reply inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/http/HttpBaseSource.java:120]: @xuesongxs, you're right, and from your reply, you've figured out how it works, thanks!

Looking forward to your more contributions!!

**Review by luchunliang — APPROVED** [review]
LGTM

**Review by dockerzhang — APPROVED** [review]
