### PR TITLE
[INLONG-11751][Manager] Modify doDeleteCheck method verify

### LINKED ISSUE #11751: [Bug][Manager] Failed to delete inlong group for groupId
## What happened

CC #11737

### Description

1. Unable to delete groups under the synchronization menu normally. 

error message:  `groupId=test_pulsar_group1 have [1] inlong streams, deleted failed`

Here is the table data of Inlong Stream that I retrieved from the local Docker MySQL container.

### Detailed Reproduction Steps
1. **[Data Synchronization] Create a data flow group**
   - Insert data into the `inlong_group` and `inlong_stream` tables, with a delete flag of 0 and status as pending submission.
2. **[Configure Data Flow] Create new data source and data target**
   - The data source will be inserted into the `stream_source` table, with a delete flag of 0.
3. **Manually modify the `status` field value to 120 in the three tables**
   - This aims to simulate a configuration failure scenario.
4. **[Data Synchronization/Data Group/Configure Data Flow] Delete the data source from the page**
   - At this point, the delete flag in `stream_source` changes to the current primary key id, indicating it has been deleted.
5. **[Data Synchronization] Delete the data flow group**
   - Error message: `groupId=test_pulsar_group4 have [1] inlong streams, deleted failed`

**Inlong Group Table**

| id  | inlong_group_id    | name | description | mq_type | mq_resource        | daily_records | daily_storage | peak_records | max_length | enable_zookeeper | enable_create_resource | inlong_group_mode | data_report_type | inlong_cluster_tag | ext_params                                | tenant | in_charges | followers | status | previous_status | is_deleted | creator | modifier | create_time         | modify_time         | version |
|-----|---------------------|------|-------------|---------|--------------------|---------------|---------------|--------------|------------|------------------|------------------------|-------------------|------------------|--------------------|-------------------------------------------|--------|------------|-----------|--------|-----------------|------------|---------|----------|---------------------|---------------------|---------|
|  2  | test_pulsar_group1  |      |             | NONE    | test_pulsar_group1 |            10 |            10 |         1000 |      10240 |                0 |                      1 |                 1 |                0 | NULL               | NULL                                      | public | admin      | NULL      |    120 |             110 |          0 | admin   | admin    | 2025-01-22 09:53:27 | 2025-02-11 07:45:53 |       2 |

**Inlong Stream Table**

| id | inlong_group_id    | inlong_stream_id   | name  | description | mq_resource        | data_type | wrap_type     | data_encoding | data_separator | data_escape_char | sync_send | daily_records | daily_storage | peak_records | max_length | storage_period | ext_params                                                                                                                                                          | status | previous_status | is_deleted | creator | modifier | create_time         | modify_time         | version |
|----|--------------------|--------------------|-------|-------------|--------------------|-----------|---------------|---------------|----------------|------------------|-----------|---------------|---------------|--------------|------------|----------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------|-----------------|------------|---------|----------|---------------------|---------------------|---------|
|  3 | test_pulsar_group1 | test_pulsar_group1 | NULL  |             | test_pulsar_group1 | NULL      | INLONG_MSG_V0 | UTF-8         | 124            | NULL             |         0 |            10 |            10 |         1000 |      10240 |              1 | {"ignoreParseError":null,"kvSeparator":null,"lineSeparator":null,"useExtendedFields":false,"predefinedFields":null,"sinkMultipleEnable":true,"extendedFieldSize":0} |    120 |             100 |          0 | admin   | admin    | 2025-01-22 09:53:27 | 2025-02-11 07:45:53 |       3 |

### What you expected to happen

Can delete data stream groups normally.

### How to reproduce

Create a data flow group, note: there was a configuration error during creation

### Environment

CentOS

### InLong version

master

### InLong Component

InLong Dashboard, InLong Manager

### Are you willing to submit PR?

- [x] Yes, I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Jzow**
Fixes #11751

### Motivation

Resolve the issue of not being able to delete the data stream group under the data synchronization menu properly

### Modifications

> [!NOTE]
> 2. Added `Inlong Group Mode` validation in the `doDeleteCheck` method

### Verifying this change

*(Please pick either of the following options)*

- [x] This change is a trivial rework/code cleanup without any test coverage.

- [ ] This change is already covered by existing tests, such as:
  *(please describe tests)*

- [ ] This change added tests and can be verified as follows:

  *(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a follow-up issue for adding the documentation

### CODE REVIEW

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupServiceImpl.java [hunk 1]
```diff
@@ -648,9 +649,10 @@ public InlongGroupInfo doDeleteCheck(String groupId, String operator) {
                     String.format("current group status=%s was not allowed to delete", curState));
         }
 
-        // If the status not allowed deleting directly, you need to delete the related "inlong_stream" first,
+        // If the status not allowed deleting directly, and the group mode is STANDARD,
+        // you need to delete the related "inlong_stream" first.
         // otherwise, all associated info will be logically deleted.
-        if (GroupStatus.deleteStreamFirst(curState)) {
+        if (GroupStatus.deleteStreamFirst(curState) && groupInfo.getInlongGroupMode() == GroupMode.STANDARD.getCode()) {
```
Comment (fuweng11) [inline inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupServiceImpl.java:655]:
```suggestion
        if (GroupStatus.deleteStreamFirst(curState) && InlongConstants.STANDARD_MODE.equals(groupInfo.getInlongGroupMode())) {
```

**Comment by dockerzhang** [comment]
Run 'mvn spotless:apply' to fix these violations.

**Comment by Jzow** [comment]
> Run 'mvn spotless:apply' to fix these violations.

Thanks, `CI` is normal.

File: inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/GroupMode.java [hunk 2]
```diff
@@ -60,4 +63,12 @@ public static GroupMode forMode(String mode) {
         throw new IllegalArgumentException(String.format("Unsupported group mode for %s", mode));
     }
 
+    public static GroupMode forCode(int code) {
```
Comment (fuweng11) [inline inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/GroupMode.java:66]: This class is not used and does not require modification.

**Review by fuweng11 — DISMISSED** [review]

**Review by vernedeng — DISMISSED** [review]

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupServiceImpl.java [hunk 3]
```diff
@@ -648,9 +648,11 @@ public InlongGroupInfo doDeleteCheck(String groupId, String operator) {
                     String.format("current group status=%s was not allowed to delete", curState));
         }
 
-        // If the status not allowed deleting directly, you need to delete the related "inlong_stream" first,
+        // If the status not allowed deleting directly, and the group mode is STANDARD,
```
Comment (dockerzhang) [inline inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupServiceImpl.java:651]:
```suggestion
        // If the status does not allow deleting directly, and the group mode is STANDARD,
```

**Review by dockerzhang — APPROVED** [review]

**Review by vernedeng — CHANGES_REQUESTED** [review]
Please submit the test result

**Comment by Jzow** [comment]
local testing, it has been verified.

`manager-all.log:`
```java
[ ] 2025-02-19 00:22:23.021 - INFO [http-nio-8083-exec-7] .g.UpdateGroupCompleteListener:68 - begin to execute UpdateGroupCompleteListener for groupId=test_off_group, operateType=DELETE 
[ ] 2025-02-19 00:22:23.033 -DEBUG [http-nio-8083-exec-7] .m.s.s.InlongStreamServiceImpl:481 - begin to update inlong stream without check, request=InlongStreamRequest(id=19, inlongGroupId=test_off_group, inlongStreamId=test_off_group, name=null, description=, mqResource=test_off_group, dataType=null, dataEncoding=UTF-8, dataSeparator=124, dataEscapeChar=null, syncSend=0, dailyRecords=10, dailyStorage=10, peakRecords=1000, maxLength=10240, storagePeriod=1, extParams={"ignoreParseError":null,"kvSeparator":null,"lineSeparator":null,"useExtendedFields":false,"predefinedFields":null,"sinkMultipleEnable":false,"extendedFieldSize":0}, fieldList=null, extList=null, version=1, ignoreParseError=null, useExtendedFields=false, extendedFieldSize=0, sinkMultipleEnable=false, syncField=false, wrapType=INLONG_MSG_V0) 
[ ] 2025-02-19 00:22:23.036 -DEBUG [http-nio-8083-exec-7] o.a.i.l.j.BaseJdbcLogger      :137 - ==>  Preparing: select id, inlong_group_id, inlong_stream_id, name, description, mq_resource, data_type, wrap_type, data_encoding, data_separator, data_escape_char, sync_send, daily_records, daily_storage, peak_records, max_length, storage_period, ext_params, status, previous_status, is_deleted, creator, modifier, create_time, modify_time, version from inlong_stream WHERE is_deleted = 0 and inlong_group_id = ? and inlong_stream_id = ? 
[ ] 2025-02-19 00:22:23.038 -DEBUG [http-nio-8083-exec-7] o.a.i.l.j.BaseJdbcLogger      :137 - ==> Parameters: test_off_group(String), test_off_group(String) 
[ ] 2025-02-19 00:22:23.038 -DEBUG [http-nio-8083-exec-7] o.a.i.l.j.BaseJdbcLogger      :137 - <==      Total: 1 
[ ] 2025-02-19 00:22:23.042 -DEBUG [http-nio-8083-exec-7] o.a.i.l.j.BaseJdbcLogger      :137 - ==>  Preparing: update inlong_stream SET inlong_group_id = ?, inlong_stream_id = ?, description = ?, mq_resource = ?, wrap_type = ?, data_encoding = ?, data_separator = ?, sync_send = ?, daily_records= ?, daily_storage= ?, peak_records= ?, max_length= ?, storage_period = ?, ext_params = ?, status = ?, previous_status = ?, is_deleted = ?, creator = ?, modifier = ?, version = ? + 1 where inlong_group_id = ? and inlong_stream_id = ? and is_deleted = 0 and version = ? 
[ ] 2025-02-19 00:22:23.044 -DEBUG [http-nio-8083-exec-7] o.a.i.l.j.BaseJdbcLogger      :137 - ==> Parameters: test_off_group(String), test_off_group(String), (String), test_off_group(String), INLONG_MSG_V0(String), UTF-8(String), 124(String), 0(Integer), 10(Integer), 10(Integer), 1000(Integer), 10240(Integer), 1(Integer), {"ignoreParseError":null,"kvSeparator":null,"lineSeparator":null,"useExtendedFields":false,"predefinedFields":null,"sinkMultipleEnable":false,"extendedFieldSize":0}(String), 100(Integer), 100(Integer), 0(Integer), admin(String), admin(String), 1(Integer), test_off_group(String), test_off_group(String), 1(Integer) 
[ ] 2025-02-19 00:22:23.048 -DEBUG [http-nio-8083-exec-7] o.a.i.l.j.BaseJdbcLogger      :137 - <==    Updates: 1 
[ ] 2025-02-19 00:22:23.048 -DEBUG [http-nio-8083-exec-7] .m.s.s.InlongStreamServiceImpl:907 - begin to update inlong stream field, groupId=test_off_group, streamId=test_off_group, field=null 
[ ] 2025-02-19 00:22:23.049 -DEBUG [http-nio-8083-exec-7] o.a.i.l.j.BaseJdbcLogger      :137 - ==>  Preparing: delete from inlong_stream_field where inlong_group_id = ? and inlong_stream_id = ? and is_deleted = 0 
[ ] 2025-02-19 00:22:23.052 -DEBUG [http-nio-8083-exec-7] o.a.i.l.j.BaseJdbcLogger      :137 - ==> Parameters: test_off_group(String), test_off_group(String) 
[ ] 2025-02-19 00:22:23.054 -DEBUG [http-nio-8083-exec-7] o.a.i.l.j.BaseJdbcLogger      :137 - <==    Updates: 0 
[ ] 2025-02-19 00:22:23.055 - INFO [http-nio-8083-exec-7] .m.s.s.InlongStreamServiceImpl:912 - success to update inlong stream field for groupId=test_off_group 
[ ] 2025-02-19 00:22:23.056 - INFO [http-nio-8083-exec-7] .m.s.s.InlongStreamServiceImpl:937 - begin to save or update inlong stream ext info, groupId=test_off_group, streamId=test_off_group, ext=null 
[ ] 2025-02-19 00:22:23.056 - INFO [http-nio-8083-exec-7] .m.s.s.InlongStreamServiceImpl:519 - success to update inlong stream without check for groupId=test_off_group streamId=test_off_group 
[ ] 2025-02-19 00:22:23.058 - INFO [http-nio-8083-exec-7] i.m.s.g.InlongGroupServiceImpl:668 - begin to delete inlong group for groupId=test_off_group by user=admin 
[ ] 2025-02-19 00:22:23.059 -DEBUG [http-nio-8083-exec-7] o.a.i.l.j.BaseJdbcLogger      :137 - ==>  Preparing: select id, inlong_group_id, name, description, tenant, mq_type, mq_resource, daily_records, daily_storage, peak_records, max_length, enable_zookeeper, enable_create_resource, inlong_group_mode, data_report_type, inlong_cluster_tag, ext_params, in_charges, followers, status, previous_status, is_deleted, creator, modifier, create_time, modify_time, version from inlong_group WHERE inlong_group_id = ? and is_deleted = 0 and tenant = ? 
[ ] 2025-02-19 00:22:23.062 -DEBUG [http-nio-8083-exec-7] o.a.i.l.j.BaseJdbcLogger      :137 - ==> Parameters: test_off_group(String), public(String) 
[ ] 2025-02-19 00:22:23.063 -DEBUG [http-nio-8083-exec-7] o.a.i.l.j.BaseJdbcLogger      :137 - <==      Total: 1 
[ ] 2025-02-19 00:22:23.065 -DEBUG [http-nio-8083-exec-7] o.a.i.l.j.BaseJdbcLogger      :137 - ==>  Preparing: update inlong_group SET name = ?, description = ?, mq_type = ?, mq_resource = ?, daily_records = ?, daily_storage = ?, peak_records = ?, max_length = ?, enable_zookeeper = ?, enable_create_resource = ?, inlong_group_mode = ?, data_report_type = ?, in_charges = ?, previous_status = status, status = ?, is_deleted = ?, modifier = ?, version = ? + 1 WHERE inlong_group_id = ? and tenant = ? and is_deleted = 0 and version = ? 
[ ] 2025-02-19 00:22:23.067 -DEBUG [http-nio-8083-exec-7] o.a.i.l.j.BaseJdbcLogger      :137 - ==> Parameters: (String), 1231313(String), NONE(String), test_off_group(String), 10(Integer), 10(Integer), 1000(Integer), 10240(Integer), 0(Integer), 1(Integer), 2(Integer), 0(Integer), admin(String), 40(Integer), 19(Integer), admin(String), 1(Integer), test_off_group(String), public(String), 1(Integer) 
[ ] 2025-02-19 00:22:23.068 -DEBUG [http-nio-8083-exec-7] o.a.i.l.j.BaseJdbcLogger      :137 - <==    Updates: 1 
[ ] 2025-02-19 00:22:23.071 -DEBUG [http-nio-8083-exec-7] o.a.i.l.j.BaseJdbcLogger      :137 - ==>  Preparing: update inlong_group_ext set is_deleted = id where inlong_group_id = ? and is_deleted = 0 
[ ] 2025-02-19 00:22:23.072 -DEBUG [http-nio-8083-exec-7] o.a.i.l.j.BaseJdbcLogger      :137 - ==> Parameters: test_off_group(String) 
[ ] 2025-02-19 00:22:23.074 -DEBUG [http-nio-8083-exec-7] o.a.i.l.j.BaseJdbcLogger      :137 - <==    Updates: 0 
[ ] 2025-02-19 00:22:23.074 -DEBUG [http-nio-8083-exec-7] .a.i.m.s.s.ScheduleServiceImpl:154 - begin to delete schedule info for groupId=test_off_group 
[ ] 2025-02-19 00:22:23.075 -DEBUG [http-nio-8083-exec-7] o.a.i.l.j.BaseJdbcLogger      :137 - ==>  Preparing: select id, inlong_group_id, name, description, tenant, mq_type, mq_resource, daily_records, daily_storage, peak_records, max_length, enable_zookeeper, enable_create_resource, inlong_group_mode, data_report_type, inlong_cluster_tag, ext_params, in_charges, followers, status, previous_status, is_deleted, creator, modifier, create_time, modify_time, version from inlong_group WHERE inlong_group_id = ? and is_deleted = 0 and tenant = ? 
[ ] 2025-02-19 00:22:23.076 -DEBUG [http-nio-8083-exec-7] o.a.i.l.j.BaseJdbcLogger      :137 - ==> Parameters: test_off_group(String), public(String) 
[ ] 2025-02-19 00:22:23.077 -DEBUG [http-nio-8083-exec-7] o.a.i.l.j.BaseJdbcLogger      :137 - <==      Total: 0 
[ ] 2025-02-19 00:22:23.077 -ERROR [http-nio-8083-exec-7] .a.i.m.s.s.ScheduleServiceImpl:179 - inlong group not found by groupId=test_off_group 
[ ] 2025-02-19 00:22:23.079 - WARN [http-nio-8083-exec-7] i.m.s.g.InlongGroupServiceImpl:694 - failed to delete schedule info for groupId=test_off_group, error msg: Inlong group does not exist/no operation authority 
[ ] 2025-02-19 00:22:23.079 - INFO [http-nio-8083-exec-7] i.m.s.g.InlongGroupServiceImpl:698 - success to delete group and group ext property for groupId=test_off_group by user=admin 
[ ] 2025-02-19 00:22:23.081 - INFO [http-nio-8083-exec-7] .m.s.s.StreamSourceServiceImpl:442 - begin to logic delete all source info by groupId=test_off_group, streamId=null 
[ ] 2025-02-19 00:22:23.083 -DEBUG [http-nio-8083-exec-7] o.a.i.l.j.BaseJdbcLogger      :137 - ==>  Preparing: select id, inlong_group_id, inlong_stream_id, source_type, source_name, task_map_id, agent_ip, uuid, data_node_name, inlong_cluster_name, inlong_cluster_node_group, serialization_type, snapshot, report_time, data_time_zone, ext_params, version, status, previous_status, is_deleted, creator, modifier, create_time, modify_time from stream_source WHERE is_deleted = 0 and inlong_group_id = ? 
[ ] 2025-02-19 00:22:23.085 -DEBUG [http-nio-8083-exec-7] o.a.i.l.j.BaseJdbcLogger      :137 - ==> Parameters: test_off_group(String) 
[ ] 2025-02-19 00:22:23.086 -DEBUG [http-nio-8083-exec-7] o.a.i.l.j.BaseJdbcLogger      :137 - <==      Total: 0 
[ ] 2025-02-19 00:22:23.086 - INFO [http-nio-8083-exec-7] .m.s.s.StreamSourceServiceImpl:465 - success to logic delete all source by groupId=test_off_group, streamId=null 
[ ] 2025-02-19 00:22:23.087 - INFO [http-nio-8083-exec-7] .g.UpdateGroupCompleteListener:104 - success to execute UpdateGroupCompleteListener for groupId=test_off_group, operateType=DELETE 
[ ] 2025-02-19 00:22:23.089 -DEBUG [http-nio-8083-exec-7] o.a.i.l.j.BaseJdbcLogger      :137 - ==>  Preparing: insert into workflow_event_log (id, process_id, process_name, process_display_name, inlong_group_id, task_id, element_name, element_display_name, event_type, event, listener, status, async, ip, start_time, end_time, remark, exception) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) 
[ ] 2025-02-19 00:22:23.090 -DEBUG [http-nio-8083-exec-7] o.a.i.l.j.BaseJdbcLogger      :137 - ==> Parameters: null, 11(Integer), DELETE_GROUP_PROCESS(String), Delete Group(String), test_off_group(String), null, EndEvent(String), EndEvent(String), ProcessEvent(String), COMPLETE(String), UpdateGroupCompleteListener(String), 1(Integer), 0(Integer), 192.168.157.1(String), 2025-02-19 00:22:23.021(Timestamp), 2025-02-19 00:22:23.087(Timestamp), null, null 
[ ] 2025-02-19 00:22:23.092 -DEBUG [http-nio-8083-exec-7] o.a.i.l.j.BaseJdbcLogger      :137 - <==    Updates: 1 
[ ] 2025-02-19 00:22:23.098 - INFO [http-nio-8083-exec-7] .s.g.InlongGroupProcessService:267 - success to delete group for groupId=test_off_group by user=admin 
```


Image

Image

**Review by vernedeng — APPROVED** [review]
