### PR TITLE
[INLONG-7035][SDK] Fix the id generator not globally unique for DataProxy

### LINKED ISSUE #7035: [Bug][SDK] The message id in DataProxy is not globally unique
### What happened

Some messages are given the same message id under multi-threading

### What you expected to happen

Unique id

### How to reproduce

multi-threading

### Environment

_No response_

### InLong version

master

### InLong Component

InLong SDK

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by woofyzhao**
- Fixes #7035

### Motivation

The message sender generate repeated msg id when in concurrency.

### Modifications

Make it globally unique by static sharing

### CODE REVIEW

**Review by dockerzhang — APPROVED** [review]

**Review by gosonzhang — APPROVED** [review]

File: inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/DefaultMessageSender.java [hunk 1]
```diff
@@ -48,8 +48,8 @@ public class DefaultMessageSender implements MessageSender {
             new ConcurrentHashMap<>();
     private static final AtomicBoolean MANAGER_FETCHER_THREAD_STARTED = new AtomicBoolean(false);
     private static ManagerFetcherThread managerFetcherThread;
+    private static final SequentialID idGenerator;
```
Comment (healchow) [inline inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/DefaultMessageSender.java:51]:
```suggestion
    private static final SequentialID idGenerator = new SequentialID(Utils.getLocalIp());
```

Comment (healchow) [reply inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/DefaultMessageSender.java:51]: The not need a static block.

**Review by baomingyu — APPROVED** [review]

**Review by healchow — APPROVED** [review]
