### PR TITLE
[INLONG-11670][SDK] Rename the ProxysdkException class name to ProxySdkException

### LINKED ISSUE #11670: [Improve][SDK] Rename the ProxysdkException class name to ProxySdkException
### Description

The ProxysdkException class name is not standardized, and the file placement is unreasonable, so adjust it:

1. https://github.com/apache/inlong/blob/master/inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/network/ProxysdkException.java

### InLong Component

InLong SDK

### Are you willing to submit PR?

- [x] Yes, I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by gosonzhang**
Fixes #11670

1. Modify the ProxysdkException class name and location;

2. Add SDK version information acquisition method

3. Add reporting attribute Key "msgUUID" and "sdkVersion"

### CODE REVIEW

**Review by luchunliang — DISMISSED** [review]

**Review by justinwwhuang — DISMISSED** [review]

**Review by fuweng11 — APPROVED** [review]

**Review by justinwwhuang — APPROVED** [review]

**Review by vernedeng — APPROVED** [review]

File: inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/exception/ProxySdkException.java [hunk 1]
```diff
@@ -15,22 +15,34 @@
...
+ * Used for unacceptable situations when reporting messages, such as empty input parameters,
+ * illegal parameters, abnormal execution status, and exceptions encountered during execution that
+ * were not considered during design, etc.
+ *
+ * If this exception is thrown during the debugging phase, the caller needs to check and
+ * adjust the corresponding implementation according to the exception content; if the exception
+ * is encountered during operation; the caller can try a limited number of times,
+ * and discard this report if it fails after trying again.
+ */
+public class ProxySdkException extends Exception {
```
Comment (aloyszhang) [inline inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/exception/ProxySdkException.java:32]:
```suggestion
public class ProxySDKException extends Exception {
```

Comment (gosonzhang) [reply inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/exception/ProxySdkException.java:32]: Camel case naming is mainly used here. “SDK” if used, will be connected with the later "E" to form "SDKE", which makes people mistakenly think it is another special definition. At the same time, I checked and found that "SDK" and "Sdk" are both ok.
