### PR TITLE
[INLONG-10094][agent] Fix the bug: the task record for data supplementation has not expired

### LINKED ISSUE #10094: [Improve][Agent] The task record for data supplementation has not expired
### Description

The task record for data supplementation has not expired and has been deleted

### InLong Component

InLong Agent

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by justinwwhuang**
Fixes #10094

### Motivation

Fix the bug: the task record for data supplementation has not expired
### Modifications

Put the logic of deleting expired records into OffsetManager for unified management

### Verifying this change

*(Please pick either of the following options)*

- [x] This change is a trivial rework/code cleanup without any test coverage.

- [ ] This change is already covered by existing tests, such as:
  *(please describe tests)*

- [ ] This change added tests and can be verified as follows:

  *(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Documentation

No doc needed

### CODE REVIEW

File: inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/task/OffsetManager.java [hunk 1]
```diff
@@ -115,6 +117,63 @@ public OffsetProfile getOffset(String taskId, String instanceId) {
...
+        Iterator<InstanceProfile> iterator = instanceDb.listAllInstances().listIterator();
+        while (iterator.hasNext()) {
+            if (cleanCount.get() > CLEAN_INSTANCE_ONCE_LIMIT) {
+                return;
+            }
+            InstanceProfile instanceFromDb = iterator.next();
+            String taskId = instanceFromDb.getTaskId();
+            String instanceId = instanceFromDb.getInstanceId();
+            if (instanceFromDb.getState() != InstanceStateEnum.FINISHED) {
+                return;
```
Comment (aloyszhang) [inline inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/task/OffsetManager.java:146]: Should we also check the state of following instances?

Comment (justinwwhuang) [reply inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/task/OffsetManager.java]: yes

**Review by aloyszhang — APPROVED** [review]
LGTM

**Review by doleyzi — APPROVED** [review]
