### PR TITLE
[INLONG-11819][Sort] Sort kv/csv format support keep escape, using line delimiter and call back when parse field has exception

### LINKED ISSUE #11819: [Feature][Sort] Sort kv/csv format must support keep escape, using line delimiter and call back when parse field has exception.
### Use case

such as , 
CSV string: aaa|bbbb|dd\\cc , 
when using keep escape configuration
result is  "aaa  bbbb dd\\cc"
but default parse result is "aaa  bbbb ddcc"

other format kv
kv string:  a=b&c=\\=d
when using keep escape configuration
result values are  "b   \\=d"
but default parse result values are "b =d"

### Are you willing to submit PR?

- [x] Yes, I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by baomingyu**
fix #11819
CSV and KC format case 

first support keep escape such as:
CSV : aaa|bbbb|dd\cc ,
when using keep escape configuration
result is "aaa bbbb dd\cc"
but default parse result is "aaa bbbb ddcc"

kv : a=b&c=\=d
when using keep escape configuration
result values are "b \=d"
but default parse result values are "b =d"

second using line delimiter such as:
CSV : aaa|bbbb|dd\n aaa|cc ,
when using line delimiter '\n' configuration
result is 
"aaa bbbb dd"
"aaa cc"
but default parse result is "aaa bbbb dd aaa cc"

kv : a=b&c=\nc=d
when using line delimiter '\n' configuration
result values are 
"b  "
"d"
but default parse result values are "b  d"

### CODE REVIEW

**Review by vernedeng — APPROVED** [review]

**Review by aloyszhang — DISMISSED** [review]

File: inlong-sort/sort-formats/format-common/src/main/java/org/apache/inlong/sort/formats/inlongmsg/NoOpFailureHandler.java [hunk 1]
```diff
@@ -51,6 +53,13 @@ public void onConvertingRowFailure(InLongMsgHead head, InLongMsgBody body, Excep
         throw exception;
     }
 
+    @Override
+    public void onConvertingFieldFailure(String fieldName, String fieldText, FormatInfo formatInfo,
+            Exception exception) throws Exception {
+        LOG.warn("Cannot convert the InLongMsg Filed (fieldName = {}, formatInfo = {}, fieldText = {}),"
+                + " exception = {}", fieldName, formatInfo, fieldText, exception);
+    }
```
Comment (luchunliang) [inline inlong-sort/sort-formats/format-common/src/main/java/org/apache/inlong/sort/formats/inlongmsg/NoOpFailureHandler.java:61]: ditto

File: inlong-sort/sort-formats/format-common/src/main/java/org/apache/inlong/sort/formats/inlongmsg/IgnoreFailureHandler.java [hunk 2]
```diff
@@ -47,6 +49,13 @@ public void onConvertingRowFailure(InLongMsgHead head, InLongMsgBody body, Excep
         LOG.warn("Cannot properly convert the InLongMsg ({}, {})", head, body, exception);
     }
 
+    @Override
+    public void onConvertingFieldFailure(String fieldName, String fieldText, FormatInfo formatInfo,
+            Exception exception) throws Exception {
+        LOG.warn("Cannot convert the InLongMsg Filed (fieldName = {}, formatInfo = {}, fieldText = {}),"
+                + " exception = {}", fieldName, formatInfo, fieldText, exception);
```
[the remark this answers is not in the document]
Comment (baomingyu) [reply inlong-sort/sort-formats/format-common/src/main/java/org/apache/inlong/sort/formats/inlongmsg/IgnoreFailureHandler.java]: done

File: inlong-sort/sort-formats/format-common/src/main/java/org/apache/inlong/sort/formats/inlongmsg/NoOpFailureHandler.java (hunk 1 above)
Comment (baomingyu) [reply inlong-sort/sort-formats/format-common/src/main/java/org/apache/inlong/sort/formats/inlongmsg/NoOpFailureHandler.java:61]: done

**Review by aloyszhang — APPROVED** [review]

**Review by luchunliang — APPROVED** [review]

**Review by dockerzhang — APPROVED** [review]
