### PR TITLE
[INLONG-5009][Docker] Fix dataproxy-docker script judgement

### LINKED ISSUE #5009: [Bug][Docker] Dataproxy proc cannot startup
### What happened

Dataproxy proc cannot startup

### What you expected to happen

Dataproxy proc startup normally

### How to reproduce

Fix dataproxy-docker script

### Environment

_No response_

### InLong version

master

### InLong Component

InLong DataProxy, Other for not specified component

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by lucaspeng12138**
### Prepare a Pull Request
Fix dataproxy-docker script judgement

- Fixes #5009 

### Motivation

Fix dataproxy-docker script judgement

### Modifications

Fix dataproxy-docker script judgement

### Verifying this change
Bash cannot recognize symbol "==". Change it into "="

### CODE REVIEW

**Review by healchow — APPROVED** [review]

File: inlong-dataproxy/dataproxy-docker/dataproxy-docker.sh [hunk 1]
```diff
@@ -24,10 +24,10 @@ sed -i "s/manager.hosts=.*$/manager.hosts=${MANAGER_OPENAPI_IP}:${MANAGER_OPENAP
 sed -i "s/audit.proxys=.*$/audit.proxys=${AUDIT_PROXY_URL}/g" "${common_conf_file}"
 
 # start
-if [ $MQ_TYPE == "pulsar" ]; then
+if [ "${MQ_TYPE}" = "pulsar" ]; then
```
Comment (healchow) [inline inlong-dataproxy/dataproxy-docker/dataproxy-docker.sh:27]: Is it ok to change `==` to `=`?

Comment (lucaspeng12138) [reply inlong-dataproxy/dataproxy-docker/dataproxy-docker.sh:27]: yes, I tested
WeChatWorkScreenshot_a9d6ee64-89a3-45ad-a388-4dc450b93baa

**Review by dockerzhang — APPROVED** [review]
