### PR TITLE
[INLONG-7121][Sort] Fix the parsing error of Flink SQL for MongoDB

### LINKED ISSUE #7121: [Bug][Sort] Parsing Flink SQL error for MongoDB
### What happened

Repair bug for MongoDb parse Flink Sql

### What you expected to happen

parse flink sql err for MongoDb

### How to reproduce

repair bug

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Sort

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by kuansix**
### Prepare a Pull Request
- Title Example: [INLONG-7121][Sort] Repair bug for MongoDb parse flink sql
- Fixes #7121 

### Motivation

*Explain here the context, and why you're making that change. What is the problem you're trying to solve?*

### Modifications

*Describe the modifications you've done.*

### Verifying this change

*(Please pick either of the following options)*

- [ ] This change is a trivial rework/code cleanup without any test coverage.

- [ ] This change is already covered by existing tests, such as:
  *(please describe tests)*

- [ ] This change added tests and can be verified as follows:

  *(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a follow-up issue for adding the documentation

### CODE REVIEW

File: inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/parser/impl/FlinkSqlParser.java [hunk 1]
```diff
@@ -890,10 +910,13 @@ private String parseFields(List<FieldInfo> fields, Node node) {
...
      * @param primaryKey The primary key of table
+     * @param filterPrimaryKey filter PrimaryKey, use for mongo
      * @return Primary key format in sql
      */
-    private String genPrimaryKey(String primaryKey) {
-        if (StringUtils.isNotBlank(primaryKey)) {
+    private String genPrimaryKey(String primaryKey, String filterPrimaryKey) {
+        boolean checkPrimaryKeyFlag = StringUtils.isNotBlank(primaryKey)
+                && (filterPrimaryKey.isEmpty() || !primaryKey.contains(filterPrimaryKey));
+        if (checkPrimaryKeyFlag) {
```
Comment (gong) [inline inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/parser/impl/FlinkSqlParser.java:919]: NPE when filterPrimaryKey is null

**Review by yunqingmoswu — APPROVED** [review]

File: inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/parser/impl/FlinkSqlParser.java [hunk 2]
```diff
@@ -890,10 +910,13 @@ private String parseFields(List<FieldInfo> fields, Node node) {
...
      *
      * @param primaryKey The primary key of table
+     * @param filterPrimaryKey filter PrimaryKey, use for mongo
      * @return Primary key format in sql
      */
-    private String genPrimaryKey(String primaryKey) {
-        if (StringUtils.isNotBlank(primaryKey)) {
+    private String genPrimaryKey(String primaryKey, String filterPrimaryKey) {
+        boolean checkPrimaryKeyFlag = StringUtils.isNotBlank(primaryKey)
+                && (StringUtils.isBlank(filterPrimaryKey) || !primaryKey.contains(filterPrimaryKey));
```
Comment (healchow) [inline inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/parser/impl/FlinkSqlParser.java:918]: Will there is problem using the `contains` method? For example, when primaryKey="global_id" and filterPrimaryKey="id".

Comment (gong) [reply inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/parser/impl/FlinkSqlParser.java:918]: @kuansix you need modify to use `equals`

**Review by gong — APPROVED** [review]

**Review by dockerzhang — APPROVED** [review]
