### PR TITLE
[INLONG-5582][Manager][Dashboard] Fix error in client API

### LINKED ISSUE #5585: [Bug][Manager] Some errors of inlong stream API and user API
### What happened

1. This url does not need the leading `/`
image

2. `GET` requests do not support objects as parameters
image

### What you expected to happen

1.Remove `/`.

2.Use `MAP` instead of object.

### How to reproduce

1. org.apache.inlong.manager.client.api.service.InlongStreamApi

2. org.apache.inlong.manager.client.api.service.UserApi

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by haifxu**
- Fixes #5585 

### Motivation

1.This url does not need the leading `/`.
image

2.`GET` requests do not support objects as parameters.
image

### Modifications

1.Remove `/`.

2.Modify request method to POST.

### Verifying this change

- [x] This change is a trivial rework/code cleanup without any test coverage.

### CODE REVIEW

File: inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/service/UserApi.java [hunk 1]
```diff
@@ -41,7 +43,7 @@ public interface UserApi {
     Call<Response<UserInfo>> getById(@Path("id") Integer id);
 
     @GET("user/listAll")
-    Call<Response<PageInfo<UserInfo>>> list(UserRequest request);
+    Call<Response<PageInfo<UserInfo>>> list(@Query("request") Map<String, Object> request);
```
Comment (healchow) [inline inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/service/UserApi.java:46]: Suggested changing to POST method.

Comment (haifxu) [reply inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/service/UserApi.java]: Done.

**Review by healchow — APPROVED** [review]
LGTM

**Review by leezng — APPROVED** [review]

**Review by gong — APPROVED** [review]
