### PR TITLE
[INLONG-7401][Manager] Fix that cannot create Pulsar partitions based on numPartitions param

### LINKED ISSUE #7401: [Bug][Manager] Cannot create Pulsar partitions based on numPartitions
### What happened

Cannot create partitions based numPartitions in inlong group.

### What you expected to happen

Create partitions based numPartitions in inlong group

### How to reproduce

Create the pulsar topic through the manager.

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by fuweng11**
### Prepare a Pull Request
- Fixes #7401 

### Motivation

Fix the problem of partitions could not be created based on numPartitions in the inlong group
### Modifications

Fix the problem of partitions could not be created based on numPartitions in the inlong group

### CODE REVIEW

**Review by vernedeng — APPROVED** [review]
LGTM

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/pulsar/PulsarOperator.java [hunk 1]
```diff
@@ -49,7 +49,7 @@
 public class PulsarOperator {
 
     private static final Logger LOGGER = LoggerFactory.getLogger(InlongClusterServiceImpl.class);
-    private static final int MAX_PARTITION = 100;
+    private static final int MAX_PARTITION = 1000;
```
Comment (healchow) [inline inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/pulsar/PulsarOperator.java:52]: Please add some comment for the value, such as:
```suggestion
    /**
     *The maximum number of partitions, which is an empirical value,
     * generally does not exceed 1000 in large clusters.
     */
    private static final int MAX_PARTITION = 1000;
```

**Review by healchow — APPROVED** [review]

**Review by gong — APPROVED** [review]
