### PR TITLE
[INLONG-6533][Manager] Fix the problem of manager did not distribute the task according to the clusterName

### LINKED ISSUE #6533: [Bug][Manager] The manager did not distribute the task according to the clusterName
### What happened

The manager did not distribute the task according to the clusterName.

### What you expected to happen

Manager issues tasks according to clusterName

### How to reproduce

Set tasks with different cluster names under the same agent, the source of the same agentIp will issue tasks with different cluster names.

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by fuweng11**
### Prepare a Pull Request
- Fixes #6533 

### Motivation

Fix the problem of manager did not distribute the task according to the clusterName

### Modifications

Query the tasks to be delivered based on the clustername.

### CODE REVIEW

**Review by vernedeng — APPROVED** [review]
lgtm

**Review by gong — APPROVED** [review]

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java [hunk 1]
```diff
@@ -283,12 +283,14 @@ private DataConfig getFileTaskFromEntity(TaskRequest taskRequest, StreamSourceEn
 
     private List<DataConfig> fetchIssuedTasks(TaskRequest taskRequest) {
         final String agentIp = taskRequest.getAgentIp();
+        final String agentClusterName = taskRequest.getAgentIp();
```
Comment (healchow) [inline inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java:286]: Is the Agent IP also used as Agent cluster name?

Comment (fuweng11) [reply inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java]: I fixed it.

**Review by dockerzhang — APPROVED** [review]

**Review by healchow — APPROVED** [review]
