### PR TITLE
[INLONG-11803][Sort] Solve the NPE problem when parsing InLongMsg

### LINKED ISSUE #11803: [Bug][Sort] When there is an issue with the format of the InLongmsg body, the parsing process will throw a Null Pointer Exception (NPE).
### What happened

Image

### What you expected to happen
When there are messages with dirty format, it will not throw a Null Pointer Exception (NPE).
### How to reproduce

This issue occurs sporadically，it may occur when there is network jitter or when the upstream sends a part of the binary package serialized by InLongmsg.

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Sort

### Are you willing to submit PR?

- [x] Yes, I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by baomingyu**
Fixes #11803

### CODE REVIEW

File: inlong-sort/sort-formats/format-rowdata/format-inlongmsg-rowdata-base/src/main/java/org/apache/inlong/sort/formats/inlongmsg/AbstractInLongMsgFormatDeserializer.java [hunk 1]
```diff
@@ -81,6 +88,21 @@ public List<InLongMsgWrap> preParse(byte[] bytes) throws Exception {
         final List<InLongMsgWrap> result = new ArrayList<>();
 
         InLongMsg inLongMsg = InLongMsg.parseFrom(bytes);
+        if (inLongMsg == null) {
+            failureHandler.onParsingMsgFailure(bytes, new IOException(
+                    String.format("Could not parse InLongMsg from bytes. bytes={}.",
+                            StringUtils.join(bytes))));
```
Comment (aloyszhang) [inline inlong-sort/sort-formats/format-rowdata/format-inlongmsg-rowdata-base/src/main/java/org/apache/inlong/sort/formats/inlongmsg/AbstractInLongMsgFormatDeserializer.java:94]: Is it to much content to print the bytes?

File: inlong-sort/sort-formats/format-rowdata/format-inlongmsg-rowdata-base/src/main/java/org/apache/inlong/sort/formats/inlongmsg/AbstractInLongMsgFormatDeserializer.java [hunk 2]
```diff
@@ -81,6 +88,21 @@ public List<InLongMsgWrap> preParse(byte[] bytes) throws Exception {
...
+            return result;
+        }
+        try {
+            Set<String> set = inLongMsg.getAttrs();
+        } catch (Exception e) {
+            failureHandler.onParsingMsgFailure(bytes, new IOException(
+                    String.format("Parse InLongMsg from bytes has exception. bytes={}.",
+                            StringUtils.join(bytes)),
```
Comment (aloyszhang) [inline inlong-sort/sort-formats/format-rowdata/format-inlongmsg-rowdata-base/src/main/java/org/apache/inlong/sort/formats/inlongmsg/AbstractInLongMsgFormatDeserializer.java:102]: ditto

File: inlong-sort/sort-formats/format-rowdata/format-inlongmsg-rowdata-base/src/main/java/org/apache/inlong/sort/formats/inlongmsg/AbstractInLongMsgFormatDeserializer.java (hunk 1 above)
Comment (baomingyu) [reply inlong-sort/sort-formats/format-rowdata/format-inlongmsg-rowdata-base/src/main/java/org/apache/inlong/sort/formats/inlongmsg/AbstractInLongMsgFormatDeserializer.java:94]: This is the callback processing, no printing

File: inlong-sort/sort-formats/format-rowdata/format-inlongmsg-rowdata-base/src/main/java/org/apache/inlong/sort/formats/inlongmsg/AbstractInLongMsgFormatDeserializer.java (hunk 2 above)
Comment (baomingyu) [reply inlong-sort/sort-formats/format-rowdata/format-inlongmsg-rowdata-base/src/main/java/org/apache/inlong/sort/formats/inlongmsg/AbstractInLongMsgFormatDeserializer.java:102]: This is the callback processing, no printing

**Review by vernedeng — APPROVED** [review]

File: inlong-sort/sort-formats/format-rowdata/format-inlongmsg-rowdata-base/src/main/java/org/apache/inlong/sort/formats/inlongmsg/AbstractInLongMsgFormatDeserializer.java (hunk 1 above)
Comment (luchunliang) [reply inlong-sort/sort-formats/format-rowdata/format-inlongmsg-rowdata-base/src/main/java/org/apache/inlong/sort/formats/inlongmsg/AbstractInLongMsgFormatDeserializer.java:94]: image
It is bad operation.

**Review by dockerzhang — APPROVED** [review]
