### PR TITLE
[INLONG-10189][Agent] Handling SDK initialization exceptions

### LINKED ISSUE #10189: [Improve][Agent] There is a risk of agent getting stuck after SDK initialization exception
### Description

There is a risk of agent getting stuck after SDK initialization exception

### InLong Component

InLong Agent

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by justinwwhuang**
Fixes #10189

### Motivation

Handling data proxy SDK initialization exceptions

### Modifications

1 Add instance heartbeat timeout detection
2 Clean up timeout instances and wait for retry
3 Move the source startup operation from the initialization function to the main Instance thread

### Verifying this change

*(Please pick either of the following options)*

- [x] This change is a trivial rework/code cleanup without any test coverage.

- [ ] This change is already covered by existing tests, such as:
  *(please describe tests)*

- [ ] This change added tests and can be verified as follows:

  *(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Documentation

No doc needed

### CODE REVIEW

File: inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/instance/InstanceManager.java [hunk 1]
```diff
@@ -240,6 +241,10 @@ private void traverseMemoryTasksToDb() {
             if (stateFromDb != InstanceStateEnum.DEFAULT) {
                 deleteFromMemory(instance.getInstanceId());
             }
+            if (AgentUtils.getCurrentTime() - instance.getLastHeartbeatTime() > INSTANCE_MAX_HEARTBEAT_GAP_MS) {
+                LOGGER.error("instance heartbeat timeout {} will delete from memory", instance.getInstanceId());
```
Comment (aloyszhang) [inline inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/instance/InstanceManager.java:245]:
```suggestion
                LOGGER.error("instance {} heartbeat timeout, will delete from memory", instance.getInstanceId());
```

**Review by aloyszhang — APPROVED** [review]

**Review by dockerzhang — APPROVED** [review]
