### PR TITLE
[INLONG-5419][Manager][Dashboard] Fix the Pulsar creates model of queue error

### LINKED ISSUE #5419: [Bug][Manager] Pulsar creates model of queue error
### What happened

Selection and creation are inconsistent.
image

### What you expected to happen

Selection and creation are consistent.

### How to reproduce

Create data stream group.

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by GanfengTan**
Fix  selection and creation are inconsistent.
- Fixes #5419 

### Motivation

No message

### Modifications
No message

### Verifying this change

*(Please pick either of the following options)*

- [x] This change is a trivial rework/code cleanup without any test coverage.

- [ ] This change is already covered by existing tests, such as:
  *(please describe tests)*

- [ ] This change added tests and can be verified as follows:

### CODE REVIEW

**Review by gong — APPROVED** [review]

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/pulsar/PulsarOperator.java [hunk 1]
```diff
@@ -152,7 +152,7 @@ public void createTopic(PulsarAdmin pulsarAdmin, PulsarTopicBean topicBean) thro
         }
 
         try {
-            if (PULSAR_QUEUE_TYPE_SERIAL.equals(topicBean.getQueueModule())) {
+            if (PULSAR_QUEUE_TYPE_SERIAL.equalsIgnoreCase(topicBean.getQueueModule())) {
```
Comment (healchow) [inline inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/pulsar/PulsarOperator.java:155]: It is recommended to standardize the parameters passed externally instead of making different types of case compatibility on the server side.

**Review by healchow — CHANGES_REQUESTED** [review]

**Review by dockerzhang — APPROVED** [review]

**Review by woofyzhao — APPROVED** [review]

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/pulsar/PulsarOperator.java (hunk 1 above)
Comment (GanfengTan) [reply inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/pulsar/PulsarOperator.java]: done

**Review by healchow — APPROVED** [review]
