### PR TITLE
[INLONG-4715][Manager] Fix exception when no sink info is configured

### LINKED ISSUE #4715: [Bug][Manager] Should not start the Init-Sort process when there is no sink info
### What happened

1. No configuration sink
企业微信截图_2852a6f6-ae2f-4a85-a1cb-d6f0d9e9ada8
2. Start Sort
企业微信截图_ac7bff4a-e1d8-4100-82e5-3bfc60de1bcb

### What you expected to happen

Only the collection process is required.

### How to reproduce

agent-->dataproxy-->tube

### Environment

_No response_

### InLong version

1.2.0

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by woofyzhao**
- Fixes #4715

### CODE REVIEW

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sort/CreateSortConfigListenerV2.java [hunk 1]
```diff
@@ -91,6 +92,11 @@ public ListenerResult listen(WorkflowContext context) throws Exception {
         InlongGroupInfo groupInfo = form.getGroupInfo();
         List<InlongStreamInfo> streamInfos = form.getStreamInfos();
         final String groupId = groupInfo.getInlongGroupId();
+        List<StreamSink> streamSinks = sinkService.listSink(groupId, null);
+        if (CollectionUtils.isEmpty(streamSinks)) {
+            log.info("No sinks configured, assuming direct consumption from MQ");
```
Comment (healchow) [inline inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sort/CreateSortConfigListenerV2.java:97]: Suggest changing the log level to warn, and changing the log info to `not any sinks found for groupId={}, skip to create sort config`.

**Review by dockerzhang — APPROVED** [review]

**Comment by healchow** [comment]
In this scenario, it is should not start the `Group-InitSort` and related process.

**Comment by woofyzhao** [comment]
1. Remove skip resolver to simply workflow processing.
2. Annihilate unnecessary work when no sink is configured.

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sort/CreateSortConfigListenerV2.java [hunk 2]
```diff
@@ -194,7 +204,7 @@ private List<NodeRelation> createNodeRelationsForStream(List<StreamSource> sourc
     }
 
     private void upsertDataFlow(InlongGroupInfo groupInfo, InlongGroupExtInfo extInfo) {
```
Comment (gong) [inline inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sort/CreateSortConfigListenerV2.java:206]: Maybe function name `upsertDataFlow` need to change. Because it has been expanded to upsert other field.

File: inlong-manager/manager-plugins/src/main/java/org/apache/inlong/manager/plugin/listener/StartupSortListener.java [hunk 3]
```diff
@@ -81,6 +81,12 @@ public ListenerResult listen(WorkflowContext context) throws Exception {
             kvConf.putAll(result);
         }
 
+        String sinkCount = kvConf.get(InlongConstants.SINK_COUNT);
```
Comment (healchow) [inline inlong-manager/manager-plugins/src/main/java/org/apache/inlong/manager/plugin/listener/StartupSortListener.java:84]: I think maintaining this config is complex.
Can we use `GroupResourceProcessForm#streamInfos` to determine whether the `sinkList` of `InlongStreamInfo` is empty?

**Review by kipshi — APPROVED** [review]

**Review by healchow — APPROVED** [review]
