### PR TITLE
[INLONG-10811][SDK] Fix callback function calls lead to coredump in python sdk

### LINKED ISSUE #10811: [Bug][SDK] Python dataproxy sdk callback function call leads to coredump
### What happened

When using python sdk, when a callback function is defined and triggered, it causes coredump to exit the process abnormally.

### What you expected to happen

The defined callback function should be able to be triggered normally and not cause a coredump to exit the process.

### How to reproduce

Define the callback function in the project, use it when calling the send function, and set inlong_group_id and inlong_stream_id to a set of non-existing ids to trigger the callback function.

### Environment

_No response_

### InLong version

master

### InLong Component

InLong SDK

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by yfsn666**
Fixes #10811

### Motivation

Fix callback function calls lead to coredump in python sdk

### Modifications

Modify the pybind wrapper code and CMakeLists.
### Verifying this change

*(Please pick either of the following options)*

- [x] This change is a trivial rework/code cleanup without any test coverage.

- [ ] This change is already covered by existing tests, such as:
  *(please describe tests)*

- [ ] This change added tests and can be verified as follows:

  *(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Documentation

  - Does this pull request introduce a new feature? no

### CODE REVIEW

File: inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-python/inlong_dataproxy.cpp [hunk 1]
```diff
@@ -18,44 +18,62 @@
...
+                auto now = std::chrono::high_resolution_clock::now();
+                auto elapsed_ms = std::chrono::duration_cast<std::chrono::milliseconds>(now - start);
+                if (elapsed_ms.count() >= max_waitms) {
+                    std::cout << "Maximum wait time reached" << std::endl;
+                    break;
+                }
+                std::this_thread::sleep_for(std::chrono::milliseconds(100));
+            }
+            py::gil_scoped_release release;
+            return self.CloseApi(10000);
```
Comment (doleyzi) [inline inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-python/inlong_dataproxy.cpp:77]: Why is 10000 fixed here?

Comment (yfsn666) [reply inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-python/inlong_dataproxy.cpp]: fixed

**Review by doleyzi — APPROVED** [review]

**Review by luchunliang — APPROVED** [review]
