### PR TITLE
[INLONG-5555][Manager] Fix missing heartbeat fields and the file task split error

### LINKED ISSUE #5555: [Bug][Manager] Fix missing heartbeat fields and stream source subtask creation
### What happened

1. The heartbeat misses some critical fields.
2. The file task dispatching by cluster name is broken.

### What you expected to happen

no error

### How to reproduce

deploy master 

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Manager, InLong Agent, InLong DataProxy

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by woofyzhao**
- Fixes #5555

### Change list
1. add cluster name and ip fields for agent and dataproxy heartbeat report.
2. remove some redundant fields in file source model.
3. fix the file task split by cluster implementation bug.
4. remove the deletion logic from client

### CODE REVIEW

File: inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/file/FileSource.java [hunk 1]
```diff
@@ -48,9 +48,6 @@ public class FileSource extends StreamSource {
     @ApiModelProperty("Agent Cluster tag")
     private String clusterTag;
```
Comment (healchow) [inline inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/file/FileSource.java:49]: Do we need this field?

File: inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/file/FileSourceDTO.java [hunk 2]
```diff
@@ -42,9 +42,6 @@ public class FileSourceDTO {
 
     private static final ObjectMapper OBJECT_MAPPER = new ObjectMapper();
 
-    @ApiModelProperty("Agent Cluster tag")
-    private String clusterTag;
-
     @ApiModelProperty("Agent IP address")
     private String ip;
```
Comment (healchow) [inline inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/file/FileSourceDTO.java:46]: This field seems can be replaced by `agentIp` in the parent class.

File: inlong-manager/manager-web/sql/apache_inlong_manager.sql [hunk 3]
```diff
@@ -397,27 +397,27 @@ CREATE TABLE IF NOT EXISTS `source_file_detail`
...
-    `modify_time`        timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Modify time',
+    `id`                  int(11)      NOT NULL AUTO_INCREMENT COMMENT 'ID',
+    `inlong_group_id`     varchar(256) NOT NULL COMMENT 'Inlong group id',
+    `inlong_stream_id`    varchar(256) NOT NULL COMMENT 'Inlong stream id',
+    `source_name`         varchar(128) NOT NULL DEFAULT '' COMMENT 'source_name',
+    `source_type`         varchar(20)           DEFAULT '0' COMMENT 'Source type, including: FILE, DB, etc',
+    `agent_ip`            varchar(40)           DEFAULT NULL COMMENT 'Ip of the agent running the task',
+    `uuid`                varchar(30)           DEFAULT NULL COMMENT 'Mac uuid of the agent running the task',
+    `data_node_name`      varchar(128)          DEFAULT NULL COMMENT 'Node name, which links to data_node table',
+    `inlong_cluster_name` varchar(128)          DEFAULT NULL COMMENT 'Cluster name of the agent running the task',
```
Comment (healchow) [inline inlong-manager/manager-web/sql/apache_inlong_manager.sql:408]: Please change the param in the `manager-test` module at the same time.

File: inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/entity/StreamSourceEntity.java [hunk 4]
```diff
@@ -36,9 +36,10 @@ public class StreamSourceEntity implements Serializable {
     private String sourceName;
     private String agentIp;
     private String uuid;
+    private String subTaskAgentIps;
```
Comment (healchow) [inline inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/entity/StreamSourceEntity.java:39]: Excuse me, what is the usage of this field?

File: inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/file/FileSource.java (hunk 1 above)
Comment (woofyzhao) [reply inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/file/FileSource.java:49]: Might not be used for now but the agent cluster do have a cluster name AND  cluster tag, right?

File: inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/file/FileSourceDTO.java (hunk 2 above)
Comment (woofyzhao) [reply inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/file/FileSourceDTO.java:46]: This DTO class does not have a parent class. It might be used alone and carry the ip data by whoever needs it.

File: inlong-manager/manager-web/sql/apache_inlong_manager.sql (hunk 3 above)
Comment (woofyzhao) [reply inlong-manager/manager-web/sql/apache_inlong_manager.sql:408]: ok

File: inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/entity/StreamSourceEntity.java (hunk 4 above)
Comment (woofyzhao) [reply inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/entity/StreamSourceEntity.java:39]: This field records all the sub task agent ip from the same cluster name task.

Comment (woofyzhao) [reply inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/entity/StreamSourceEntity.java:39]: Redudant, should be  deleted.

File: inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/file/FileSource.java (hunk 1 above)
Comment (woofyzhao) [reply inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/file/FileSource.java:49]: On second though this is indeed redundant, the group has already specified the clusterTag. Sources belonging to some group need not specify cluster tags again.

File: inlong-dataproxy/conf/common.properties [hunk 5]
```diff
@@ -23,8 +23,10 @@ manager.hosts=127.0.0.1:8083
 manager.auth.secretId=
 manager.auth.secretKey=
 proxy.local.ip=127.0.0.1
+proxy.local.port=46801
```
Comment (dockerzhang) [inline inlong-dataproxy/conf/common.properties:26]: may conflict with `agent1.sources.tcp-source.port ` in `dataproxy-tube/pulsar.conf`.

File: inlong-manager/manager-dao/src/main/resources/mappers/StreamSourceEntityMapper.xml [hunk 6]
```diff
@@ -187,6 +187,24 @@
...
         </where>
     </select>
+    <select id="selectByAgentIpOrCluster" resultType="org.apache.inlong.manager.dao.entity.StreamSourceEntity">
+        select
+        <include refid="Base_Column_List"/>
+        from stream_source
+        <where>
+            is_deleted = 0
+            and status in
+            <foreach item="item" index="index" collection="statusList" open="(" close=")" separator=",">
```
Comment (healchow) [inline inlong-manager/manager-dao/src/main/resources/mappers/StreamSourceEntityMapper.xml:197]: Before the foreach, suggest checking whether the list is null or not.

**Review by healchow — APPROVED** [review]

**Review by chestnut-c — APPROVED** [review]

**Review by aloyszhang — APPROVED** [review]
