### PR TITLE
[INLONG-5799][Manager] Fix the source delete/stop/restart bug

### LINKED ISSUE #5799: [Bug][Manager] The stream source task is unable to be stopped/deleted/restarted
### What happened

The stream source task is unable to be stopped/deleted/restarted when stopping/deleting/restarting its group.

### What you expected to happen

correctly stopped/deleted/restarted

### How to reproduce

try stop a running group

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by woofyzhao**
- Fixes #5799

### Motivation

1. the template task should not be operated
2.  fix the incorrect status predicator

### CODE REVIEW

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/listener/source/AbstractSourceOperateListener.java [hunk 1]
```diff
@@ -99,6 +99,10 @@ protected void operateStreamSources(String groupId, String streamId, String oper
      */
     @SneakyThrows
     public boolean checkIfOp(StreamSource streamSource, List<StreamSource> unOperatedSources) {
+        // template source task need not be operated
```
Comment (healchow) [inline inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/listener/source/AbstractSourceOperateListener.java:102]: Where are the sub-sources operated?

Comment (woofyzhao) [reply inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/listener/source/AbstractSourceOperateListener.java]: Also here.  The template task is filtered.
Comments added.

**Review by GanfengTan — APPROVED** [review]

**Review by healchow — APPROVED** [review]

**Review by dockerzhang — APPROVED** [review]
