### PR TITLE
[INLONG-6720][Manager] Implement InlongClusterEntityMapper.selectByClusterTag

### LINKED ISSUE #6720: [Bug][Manager] InlongClusterEntityMapper.selectByClusterTag lacks specific implementation
### What happened

InlongClusterEntityMapper.selectByClusterTag lacks specific implementation

### What you expected to happen

Implement InlongClusterEntityMapper.selectByClusterTag.

### How to reproduce

Use InlongClusterEntityMapper.selectByClusterTag.

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by fuweng11**
### Prepare a Pull Request

- Fixes #6720 

### Motivation

Implement InlongClusterEntityMapper.selectByClusterTag
### Modifications

Implement InlongClusterEntityMapper.selectByClusterTag

### CODE REVIEW

File: inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/InlongClusterEntityMapper.java [hunk 1]
```diff
@@ -47,15 +47,15 @@ List<InlongClusterEntity> selectByKey(@Param("clusterTag") String clusterTag, @P
 
     List<InlongClusterEntity> selectByCondition(ClusterPageRequest request);
 
-    /**
+    /**a
```
Comment (gosonzhang) [inline inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/InlongClusterEntityMapper.java:50]: useless symbols

**Review by vernedeng — APPROVED** [review]
lgtm

**Review by gosonzhang — APPROVED** [review]

**Review by dockerzhang — APPROVED** [review]
