### PR TITLE
[INLONG-7202][Sort] Fix unit tests ( including PostgreSql \ Hbase \ Elasticsearch ) in sort-core

### LINKED ISSUE #7202: [Bug] Fix Unit Tests ( including PostgreSql \ Hbase \ Elasticsearch ) in sort-core
### What happened

1\
企业微信截图_9a7a1a04-d75b-4380-b33e-8ab1605fbdbd

2 + 3\
企业微信截图_f3fecfcd-9692-4419-aa8f-4aca9595ddb5

### What you expected to happen

fix ut

### How to reproduce

mvn clean package -Dmaven.javadoc.skip=true

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Sort

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by EMsnap**
### Prepare a Pull Request
- Fixes #7202 

### Motivation

Fix Unit Tests ( including PostgreSql \ Hbase \ Elasticsearch ) in sort-core

### Modifications

Relocate classes that has conflict 

### Verifying this change

mvn clean package -Dmaven.javadoc.skip=true

### Documentation

  - Does this pull request introduce a new feature? (no)

### CODE REVIEW

File: inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/HbaseLoadFlinkSqlParseTest.java [hunk 1]
```diff
@@ -74,7 +74,7 @@ private HbaseLoadNode buildHbaseLoadNode() {
         Map<String, String> properties = new LinkedHashMap<>();
         properties.put("dirty.side-output.connector", "log");
         properties.put("dirty.ignore", "true");
-        properties.put("dirty.side-output.enable", "true");
+        properties.put("dirty.side-output.enable", "false");
```
Comment (yunqingmoswu) [inline inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/HbaseLoadFlinkSqlParseTest.java:77]: This skips the ut of dirty data sink?

File: inlong-sort/sort-connectors/elasticsearch-7/pom.xml [hunk 2]
```diff
@@ -248,6 +248,10 @@
                                     <pattern>com.github.mustachejava</pattern>
                                     <shadedPattern>org.apache.flink.elasticsearch7.shaded.com.github.mustachejava</shadedPattern>
                                 </relocation>
+                                <relocation>
+                                    <pattern>org.apache.inlong.sort.elasticsearch</pattern>
+                                    <shadedPattern>org.apache.inlong.sort.elasticsearch7</shadedPattern>
```
Comment (gong) [inline inlong-sort/sort-connectors/elasticsearch-7/pom.xml:253]: Dose the es6 also need to change pom?

Comment (EMsnap) [reply inlong-sort/sort-connectors/elasticsearch-7/pom.xml:253]: es6 conflict with es7, since es7 has relocated , es6 doesn't need  to do so

File: inlong-sort/sort-connectors/postgres-cdc/pom.xml [hunk 3]
```diff
@@ -138,6 +138,10 @@
                                     <pattern>org.apache.inlong.sort.base</pattern>
                                     <shadedPattern>org.apache.inlong.sort.cdc.postgres.shaded.org.apache.inlong.sort.base</shadedPattern>
                                 </relocation>
+                                <relocation>
+                                    <pattern>org.apache.inlong.sort.cdc.base</pattern>
+                                    <shadedPattern>org.apache.inlong.sort.cdc.postgres.shaded.org.apache.inlong.sort.cdc.base</shadedPattern>
```
Comment (gong) [inline inlong-sort/sort-connectors/postgres-cdc/pom.xml:143]: maybe other connector that use this cdc-base alse need to shade

Comment (EMsnap) [reply inlong-sort/sort-connectors/postgres-cdc/pom.xml:143]: yes indeed, but ut only fails for postgres, I will add the relocation for other connectors

**Review by dockerzhang — APPROVED** [review]

**Review by yunqingmoswu — APPROVED** [review]

File: inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/HbaseLoadFlinkSqlParseTest.java (hunk 1 above)
Comment (EMsnap) [reply inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/HbaseLoadFlinkSqlParseTest.java]: done

**Review by gong — APPROVED** [review]
