### PR TITLE
[INLONG-4951][Manager] Fix cluster tag property update error

### LINKED ISSUE #4951: [Bug][Manger] Unable to save the change when updating the chargers of cluster tag
### What happened

Unable to save the change when updating the chargers of cluster tag
update tag

### What you expected to happen

save rightly

### How to reproduce

update chargers of cluster tag

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by woofyzhao**
- Fixes #4951 

The problem is manager only deals with the situation where tag name is changed. Other tag property changes like in-charges should also be properly dealt with.

### CODE REVIEW

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/UserServiceImpl.java [hunk 1]
```diff
@@ -78,18 +78,20 @@ public UserInfo getById(Integer userId) {
...
-            Integer version = entity.getEncryptVersion();
-            byte[] secretKeyBytes = AESUtils.decryptAsString(entity.getSecretKey(), version);
-            byte[] publicKeyBytes = AESUtils.decryptAsString(entity.getPublicKey(), version);
-            result.setSecretKey(new String(secretKeyBytes, StandardCharsets.UTF_8));
-            result.setPublicKey(new String(publicKeyBytes, StandardCharsets.UTF_8));
-        } catch (Exception e) {
-            String errMsg = String.format("decryption error: %s", e.getMessage());
-            log.error(errMsg, e);
-            throw new BusinessException(errMsg);
+        if (entity.getSecretKey() != null && entity.getPublicKey() != null) {
```
Comment (healchow) [inline inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/UserServiceImpl.java:81]: Please use `StringUtils.isNotBlank()` to check.

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/InlongClusterServiceImpl.java [hunk 2]
```diff
@@ -169,42 +169,41 @@ public Boolean updateTag(ClusterTagRequest request, String operator) {
...
-            throw new BusinessException(errMsg);
-        }
 
-        // check if there are some InlongGroups that uses this tag
         String oldClusterTag = exist.getClusterTag();
-        this.assertNoInlongGroupExists(oldClusterTag);
+        if (!newClusterTag.equals(oldClusterTag)) {
+            InlongClusterTagEntity tagConflict = clusterTagMapper.selectByTag(newClusterTag);
+            if (tagConflict != null) {
+                String errMsg = String.format("inlong cluster tag [%s] already exist by id [%d]", newClusterTag,
```
Comment (healchow) [inline inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/InlongClusterServiceImpl.java:177]: The cluster tag is enough, no need to record the id because the id was passed from outsides.

Comment (woofyzhao) [reply inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/InlongClusterServiceImpl.java:177]: The id is the other name-conflicting tag entity id, not the one passed from client.

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/UserServiceImpl.java (hunk 1 above)
Comment (woofyzhao) [reply inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/UserServiceImpl.java]: Moved to a new pr.

**Review by dockerzhang — APPROVED** [review]

**Review by healchow — APPROVED** [review]
