### PR TITLE
[INLONG-7752][Agent] PulsarSink threadPool throw reject exception

### LINKED ISSUE #7752: [Bug][Agent] PulsarSink threadPool throw reject exception
### What happened

When remove the file data source on databoard. Then add one file data source in new inlong group on databoard. Agent occur the following exception:
```java
023-03-31 22:06:50.408 -ERROR  [               task-job_11_2-6] o.a.i.a.c.t.TaskWrapper       :211 error while running wrapper
java.util.concurrent.RejectedExecutionException: Task org.apache.inlong.agent.plugin.sinks.PulsarSink$$Lambda$208/701747533@5f91f266 rejected from java.util.concurrent.ThreadPoolExecutor@43d6a181[Shutting down, pool size = 6, active threads = 6, queued tasks = 0, completed tasks = 2]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063) ~[?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830) ~[?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379) ~[?:1.8.0_151]
	at org.apache.inlong.agent.plugin.sinks.PulsarSink.init(PulsarSink.java:153) ~[agent-plugins-1.7.0-SNAPSHOT.jar:1.7.0-SNAPSHOT]
	at org.apache.inlong.agent.core.task.Task.init(Task.java:76) ~[agent-core-1.7.0-SNAPSHOT.jar:1.7.0-SNAPSHOT]
	at org.apache.inlong.agent.core.task.TaskWrapper.run(TaskWrapper.java:203) ~[agent-core-1.7.0-SNAPSHOT.jar:1.7.0-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_151]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_151]
``` 

### What you expected to happen

Agent `PulsarSink` thread pool is global, like this:
```java
public class PulsarSink extends AbstractSink {

    private static final Logger LOGGER = LoggerFactory.getLogger(LoggerFactory.class);
    private static final AtomicInteger CLIENT_INDEX = new AtomicInteger(0);
    private static final ExecutorService EXECUTOR_SERVICE = new ThreadPoolExecutor(0, Integer.MAX_VALUE,
            60L, TimeUnit.SECONDS, new SynchronousQueue<>(), new AgentThreadFactory("PulsarSink"));
```

When `PulsarSink#destroy`, the thread pool will be shut down.
```java
public void destroy() {
  ...
  EXECUTOR_SERVICE.shutdown();
  ...
}
```

Then `PulsarSink#init`  submit thread to the `shutdown thread pool`  may cause the problem.   
```java
public void init(JobProfile jobConf) {
  ...
  EXECUTOR_SERVICE.execute(sendDataThread());
  ...
}
```

### How to reproduce

Remove the file data source on databoard. Then add one file data source in new inlong group on databoard. Agent occur the exception.

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Agent

### Are you willing to submit PR?

- [x] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by wangpeix**
### Prepare a Pull Request
- Title: [INLONG-7752][Agent] PulsarSink threadPool throw reject exception
- Fixes #7752 

### Motivation

Fix `PulsarSink` threadPool throw reject exception when  delete file data source on dashboard and then add  file data source.

### Modifications

Do not shut down the global thread pool when destroy the `PulsarSink` of one task.

### CODE REVIEW

**Review by healchow — APPROVED** [review]

File: inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/PulsarSink.java [hunk 1]
```diff
@@ -196,7 +196,6 @@ public void destroy() {
             AgentUtils.silenceSleepInMs(batchFlushInterval);
         }
         shutdown = true;
-        EXECUTOR_SERVICE.shutdown();
```
Comment (healchow) [inline inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/PulsarSink.java:199]: Then, when we shutdown this global thread pool?

**Review by doleyzi — APPROVED** [review]

File: inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/PulsarSink.java (hunk 1 above)
Comment (wangpeix) [reply inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/PulsarSink.java:199]: The `PulsarSink` thread pool is global and, based on the current design, will always exist throughout the agent's lifecycle. When closed, new tasks cannot be submitted to the thread pool; think it's okay not to shutdown it.

Comment (healchow) [reply inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/PulsarSink.java:199]: Ok

**Review by healchow — APPROVED** [review]

**Review by dockerzhang — APPROVED** [review]
