### PR TITLE
[INLONG-6345][Sort] Add metrics for Doris connector

### LINKED ISSUE #6345: [Bug][Sort] Add metrics for Doris connector
### What happened

no metric

### What you expected to happen

has metric

### How to reproduce

add metric

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Sort

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by kuansix**
### Prepare a Pull Request

- Title Example: [INLONG-6345] add metrics for Doris connector

- Fixes #6345 

### Motivation

add metrics

### Modifications

add metrics

### Verifying this change

*(Please pick either of the following options)*

- [ ] This change is a trivial rework/code cleanup without any test coverage.

- [ ] This change is already covered by existing tests, such as:
  *(please describe tests)*

- [ ] This change added tests and can be verified as follows:

  *(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a follow-up issue for adding the documentation

### CODE REVIEW

File: inlong-sort/sort-connectors/doris/src/main/java/org/apache/inlong/sort/doris/table/DorisStreamLoad.java [hunk 1]
```diff
@@ -80,7 +81,7 @@ protected boolean isRedirectable(String method) {
         this.httpClient = httpClientBuilder.build();
     }
 
-    public void load(String db, String tbl, String value) throws StreamLoadException {
+    public void load(String db, String tbl, String value, SinkMetricData metricData) throws StreamLoadException {
```
Comment (yunqingmoswu) [inline inlong-sort/sort-connectors/doris/src/main/java/org/apache/inlong/sort/doris/table/DorisStreamLoad.java:84]: It is recommended to modify the method return instead of modifying the input parameters to support metric collection.

**Comment by yunqingmoswu** [comment]
Lack of single-table sync metric collect.

File: inlong-sort/sort-connectors/doris/src/main/java/org/apache/inlong/sort/doris/table/DorisStreamLoad.java (hunk 1 above)
Comment (kuansix) [reply inlong-sort/sort-connectors/doris/src/main/java/org/apache/inlong/sort/doris/table/DorisStreamLoad.java]: accept

**Comment by kuansix** [comment]
> Lack of single-table sync metric collect.

single-table sync not supported by inLong product. 
metric follow product.

**Review by gong — APPROVED** [review]

File: inlong-sort/sort-connectors/doris/src/main/java/org/apache/inlong/sort/doris/model/RespContent.java [hunk 2]
```diff
@@ -0,0 +1,95 @@
...
+
+    @JsonProperty(value = "CommitAndPublishTimeMs")
+    private int commitAndPublishTimeMs;
+
+    @JsonProperty(value = "ErrorURL")
+    private String errorURL;
+
+    @Override
+    public String toString() {
+        ObjectMapper mapper = new ObjectMapper();
```
Comment (healchow) [inline inlong-sort/sort-connectors/doris/src/main/java/org/apache/inlong/sort/doris/model/RespContent.java:87]: Suggest using a global instance of `ObjectMapper`.

Comment (kuansix) [reply inlong-sort/sort-connectors/doris/src/main/java/org/apache/inlong/sort/doris/model/RespContent.java]: accept and repair

**Review by healchow — APPROVED** [review]

**Review by yunqingmoswu — APPROVED** [review]

**Review by EMsnap — APPROVED** [review]
