### PR TITLE
[INLONG-9200][Agent] Fix bug: duplicate file collect instance

### LINKED ISSUE #9200: [Bug][Agent] Duplicate file collect instance
### What happened

Duplicate file collect instance

### What you expected to happen

File collect instance should not be duplicate

### How to reproduce

Fix the bug

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Agent

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by justinwwhuang**
### Prepare a Pull Request
[INLONG-9200][Agent] Fix bug: duplicate file collect instance
- Fixes #9200 

### Motivation

 Fix bug: duplicate file collect instance

### Modifications

 Fix bug: duplicate file collect instance

### Verifying this change

*(Please pick either of the following options)*

- [ ] This change is a trivial rework/code cleanup without any test coverage.

- [ ] This change is already covered by existing tests, such as:
  *(please describe tests)*

- [ ] This change added tests and can be verified as follows:

  *(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a follow-up issue for adding the documentation

### CODE REVIEW

File: inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/task/filecollect/LogFileCollectTask.java [hunk 1]
```diff
@@ -305,14 +316,17 @@ private void dealWithEvenMap() {
         removeTimeoutEven(eventMap, retry);
         for (Map.Entry<String, Map<String, InstanceProfile>> entry : eventMap.entrySet()) {
             Map<String, InstanceProfile> sameDataTimeEvents = entry.getValue();
+            if (sameDataTimeEvents.isEmpty()) {
+                return;
+            }
             // 根据event的数据时间、业务的周期、偏移量计算出该event是否需要在当前时间处理
```
Comment (doleyzi) [inline inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/task/filecollect/LogFileCollectTask.java:322]: chinese

Comment (justinwwhuang) [reply inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/task/filecollect/LogFileCollectTask.java:322]: get

**Review by EMsnap — APPROVED** [review]

**Review by doleyzi — APPROVED** [review]

**Review by luchunliang — APPROVED** [review]
