### PR TITLE
[INLONG-6570][Manager] Ignore the length of the field when building sort config

### LINKED ISSUE #6570: [Bug][Manager] Cannot parse the field type with length when building the Sort config
### What happened

Cannot parse the field type with length when building sort config.

image

### What you expected to happen

Build sort config successfully.

### How to reproduce

Use a data source field with the length.

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by haifxu**
### Prepare a Pull Request

- Fixes #6570 

### Motivation

image

### Modifications

Gets the string before the first occurrence of a `(`.

### Verifying this change

- [x] This change is a trivial rework/code cleanup without any test coverage.

### CODE REVIEW

**Review by woofyzhao — APPROVED** [review]

**Review by dockerzhang — APPROVED** [review]

**Review by fuweng11 — APPROVED** [review]

**Review by gosonzhang — APPROVED** [review]

**Review by ciscozhou — APPROVED** [review]

File: inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/util/FieldInfoUtils.java [hunk 1]
```diff
@@ -172,7 +174,7 @@ public static FormatInfo convertFieldFormat(String type) {
      */
     public static FormatInfo convertFieldFormat(String type, String format) {
         FormatInfo formatInfo;
-        FieldType fieldType = FieldType.forName(type);
+        FieldType fieldType = FieldType.forName(StringUtils.substringBefore(type, LEFT_BRACKET));
```
Comment (healchow) [inline inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/util/FieldInfoUtils.java:177]: How to deal with `int(4)`, `int(11)` and other types?

Comment (haifxu) [reply inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/util/FieldInfoUtils.java:177]: At this point, we have created the target table, so there is no need to pay attention to the length.

Comment (haifxu) [reply inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/util/FieldInfoUtils.java:177]: The sink table was created before this, and the field type here is only used for `sort` and does not require length. 
企业微信截图_16689978292227

Comment (healchow) [reply inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/util/FieldInfoUtils.java:177]: Okay.

**Review by healchow — APPROVED** [review]
LGTM
