### PR TITLE
[INLONG-5836][Manager] Fix the source status related behavior problems

### LINKED ISSUE #5836: [Bug][Manager] Stream source status related behavior problem fix
### What happened

1. The AUTO_PUSH source type should always be normal.
2. The template source should also be deleted when group is deleted.

### What you expected to happen

correct behavior

### How to reproduce

Delete the group

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by woofyzhao**
- Fixes #5836

- AUTO_PUSH source type should always be normal.
- Template sources should also be deleted when their groups are deleted.
- Other bugs.

### CODE REVIEW

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/AbstractSourceOperator.java [hunk 1]
```diff
@@ -155,22 +153,25 @@ public void updateOpt(SourceRequest request, Integer groupStatus, String operato
...
-                case SOURCE_NORMAL:
-                    entity.setStatus(SourceStatus.TO_BE_ISSUED_ADD.getCode());
-                    break;
-                case SOURCE_FAILED:
-                    entity.setStatus(SourceStatus.SOURCE_NEW.getCode());
-                    break;
-                default:
-                    // others leave it be
-                    break;
+        if (!entity.getSourceType().equals(SourceType.AUTO_PUSH)) {
```
Comment (healchow) [inline inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/AbstractSourceOperator.java:156]: Suggest moving this check to the beginning of this method, if it is `AUTO_PUSH` source, just print a log and then return.

**Review by GanfengTan — APPROVED** [review]

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java [hunk 2]
```diff
@@ -215,15 +216,15 @@ private List<DataConfig> fetchFileTasks(TaskRequest taskRequest) {
         Preconditions.checkTrue(StringUtils.isNotBlank(agentIp) || StringUtils.isNotBlank(agentClusterName),
                 "both agent ip and cluster name are blank when fetching file task");
         List<StreamSourceEntity> sourceEntities = sourceMapper.selectByAgentIpOrCluster(needAddStatusList,
-                Lists.newArrayList(SourceType.FILE), agentIp, agentClusterName,TASK_FETCH_SIZE * 10);
+                Lists.newArrayList(SourceType.FILE), agentIp, agentClusterName,UNLIMITED_FETCH_SIZE);
```
Comment (healchow) [inline inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java:219]: Suggested removing the limit in SQL.

**Review by healchow — CHANGES_REQUESTED** [review]

**Review by dockerzhang — APPROVED** [review]

**Review by healchow — APPROVED** [review]
