### PR TITLE
[INLONG-10041][Sort] Thread unsafety of time format serialization

### LINKED ISSUE #10041: [Bug][Sort] Thread unsafety of time format serialization
### What happened

The serialization and deserialization of the Timestamp, Time, and Date format of Sort will produce unexcepted results because SimpleDateFormatter is thread-unsafe.

### What you expected to happen

Thread safe sort format.

### How to reproduce

Use Timestamp, Time, and Date format and call the serialization and deserialization method

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Sort

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by vernedeng**
### Prepare a Pull Request
*(Change the title refer to the following example)*

- Title Example: [INLONG-XYZ][Component] Title of the pull request

*(The following *XYZ* should be replaced by the actual [GitHub Issue](https://github.com/apache/inlong/issues) number)*

- Fixes #10041 

### Motivation

The serialization and deserialization of the Timestamp, Time, and Date format of Sort will produce unexcepted results because SimpleDateFormatter is thread-unsafe.

### Modifications

*Describe the modifications you've done.*

### Verifying this change

*(Please pick either of the following options)*

- [ ] This change is a trivial rework/code cleanup without any test coverage.

- [ ] This change is already covered by existing tests, such as:
  *(please describe tests)*

- [ ] This change added tests and can be verified as follows:

  *(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a follow-up issue for adding the documentation

### CODE REVIEW

**Review by luchunliang — DISMISSED** [review]

File: inlong-common/src/main/java/org/apache/inlong/common/pojo/sort/dataflow/field/format/DateFormatInfo.java [hunk 1]
```diff
@@ -98,11 +99,10 @@ public String serialize(Date date) {
                 return Long.toString(seconds);
             }
             default: {
-                if (simpleDateFormat == null) {
+                if (formatter == null) {
                     throw new IllegalStateException();
                 }
-
-                return simpleDateFormat.format(date);
+                return date.toLocalDate().format(formatter);
```
Comment (luchunliang) [inline inlong-common/src/main/java/org/apache/inlong/common/pojo/sort/dataflow/field/format/DateFormatInfo.java:105]: Date.toLocalDate is deprecated.
It is SortFlink job timezone, it is not business data timezone.

Comment (vernedeng) [reply inlong-common/src/main/java/org/apache/inlong/common/pojo/sort/dataflow/field/format/DateFormatInfo.java]: Fixed, use thread local to ensure the thread safety.

File: inlong-common/src/main/java/org/apache/inlong/common/pojo/sort/dataflow/field/format/DateFormatInfo.java [hunk 2]
```diff
@@ -126,11 +137,7 @@ public Date deserialize(String text) throws ParseException {
                 return new Date(millis);
             }
             default: {
-                if (simpleDateFormat == null) {
-                    throw new IllegalStateException();
-                }
-
-                java.util.Date jDate = simpleDateFormat.parse(text.trim());
+                java.util.Date jDate = get().parse(text.trim());
```
Comment (luchunliang) [inline inlong-common/src/main/java/org/apache/inlong/common/pojo/sort/dataflow/field/format/DateFormatInfo.java:140]: If it is invalid date string, this will throw exception, it is better to return null or default value.

File: inlong-common/src/main/java/org/apache/inlong/common/pojo/sort/dataflow/field/format/DateFormatInfo.java [hunk 3]
```diff
@@ -50,11 +50,15 @@ public class DateFormatInfo implements BasicFormatInfo<Date> {
     @Nullable
     private final SimpleDateFormat simpleDateFormat;
 
+    @JsonIgnore
+    @Nullable
+    private final ThreadLocal<SimpleDateFormat> threadLocal;
```
Comment (luchunliang) [inline inlong-common/src/main/java/org/apache/inlong/common/pojo/sort/dataflow/field/format/DateFormatInfo.java:55]: There is a SimpleDateFormat in every field object. 
It is better to use DateFormat tool class.

File: inlong-common/src/main/java/org/apache/inlong/common/pojo/sort/dataflow/field/format/DateFormatInfo.java (hunk 2 above)
Comment (vernedeng) [reply inlong-common/src/main/java/org/apache/inlong/common/pojo/sort/dataflow/field/format/DateFormatInfo.java:140]: It should throw ParseException when the input is an invalid string, the invoker should handle this exception.

File: inlong-common/src/main/java/org/apache/inlong/common/pojo/sort/dataflow/field/format/DateFormatInfo.java (hunk 3 above)
Comment (vernedeng) [reply inlong-common/src/main/java/org/apache/inlong/common/pojo/sort/dataflow/field/format/DateFormatInfo.java]: Use FastDateFormat

**Review by luchunliang — APPROVED** [review]

**Review by dockerzhang — APPROVED** [review]
