### PR TITLE
[INLONG-7790][Sort] Capture newly added tables when setting "scan.newly-added-table.enabled=true" and "scan.startup.mode=latest-offset"

### LINKED ISSUE #7790: [Bug][Sort] Setting "scanNewlyAddedTableEnabled=true" and "scan.startup.mode=latest-offset" in MySQL CDC failed to capture newly added tables
### What happened

Setting "scanNewlyAddedTableEnabled=true" and "scan.startup.mode=latest-offset" in MySQL CDC failed to capture newly added tables.

### What you expected to happen

Setting "scanNewlyAddedTableEnabled=true" and "scan.startup.mode=latest-offset" in MySQL CDC success to capture newly added tables.

### How to reproduce

Setting "scanNewlyAddedTableEnabled=true" and "scan.startup.mode=latest-offset" in MySQL CDC, then add newly table.

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Sort

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by e-mhui**
### Prepare a Pull Request

[INLONG-7790][Sort] Capture newly added tables when setting "scan.newly-added-table.enabled=true" and "scan.startup.mode=latest-offset"

- Fixes #7790 

### Motivation

Capture newly added tables when setting "scan.newly-added-table.enabled=true" and "scan.startup.mode=latest-offset"

### Modifications

When executing the `discoverTableSchemasForBinlogSplit()` method, determine whether to query the schema of newly added tables based on `sourceConfig.isScanNewlyAddedTableEnabled()`.

### CODE REVIEW

**Review by healchow — APPROVED** [review]

File: inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/reader/MySqlSourceReader.java [hunk 1]
```diff
@@ -235,12 +235,22 @@ public void addSplits(List<MySqlSplit> splits) {
 
     private MySqlBinlogSplit discoverTableSchemasForBinlogSplit(MySqlBinlogSplit split) {
         final String splitId = split.splitId();
-        if (split.getTableSchemas().isEmpty()) {
+        if (split.getTableSchemas().isEmpty() || sourceConfig.isScanNewlyAddedTableEnabled()) {
```
Comment (supermefz) [inline inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/reader/MySqlSourceReader.java:238]: 1

**Review by dockerzhang — APPROVED** [review]

**Review by yunqingmoswu — APPROVED** [review]

**Review by EMsnap — APPROVED** [review]
