### PR TITLE
[INLONG-7028][Manager] Fix query task status list failed

### LINKED ISSUE #7028: [Bug][Manager] Failed to query the task status
### What happened

Failed to query the task status when one of them have deleted.

### What you expected to happen

Skip this task, guaranteed to return normal information.

### How to reproduce

List sort job status.

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by haifxu**
### Prepare a Pull Request

- Fixes #7028 

### Motivation

Failed to query the task status when one of them have deleted.

### Modifications

Skip this task, guaranteed to return normal information.

### Verifying this change

- [x] This change is a trivial rework/code cleanup without any test coverage.

### CODE REVIEW

**Review by woofyzhao — APPROVED** [review]

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/SortServiceImpl.java [hunk 1]
```diff
@@ -80,7 +81,15 @@ public List<SortStatusInfo> listSortStatus(SortStatusRequest request) {
 
         try {
             List<InlongGroupInfo> groupInfoList = request.getInlongGroupIds().stream()
-                    .map(groupId -> groupService.get(groupId))
+                    .map(groupId -> {
+                        try {
+                            return groupService.get(groupId);
+                        } catch (Exception e) {
+                            log.debug("{} may have already been deleted, skip it", groupId);
```
Comment (vernedeng) [inline inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/SortServiceImpl.java:88]: Why not print the exception

**Review by gosonzhang — APPROVED** [review]

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/SortServiceImpl.java (hunk 1 above)
Comment (haifxu) [reply inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/SortServiceImpl.java:88]: The exception has been printed in `groupService.get()`.

**Review by dockerzhang — APPROVED** [review]

**Review by fuweng11 — APPROVED** [review]

**Review by vernedeng — APPROVED** [review]
lgtm

**Review by healchow — APPROVED** [review]
