### PR TITLE
[INLONG-4766][Manager] Fix workflow NP problem when the COMPLETE request is fired directly from client

### LINKED ISSUE #4766: [Bug][Manager] The task retry error information is not detailed and NPE
### What happened

Invalid task retry and NPE.
image

image

### What you expected to happen

Tasks can be retried with detailed error messages.

### How to reproduce

For example: the configuration task cannot submit the task.

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by woofyzhao**
- Fixes #4766

When the complete request is fired directly from client the action context is already built.

### CODE REVIEW

File: inlong-manager/manager-workflow/src/main/java/org/apache/inlong/manager/workflow/processor/ServiceTaskProcessor.java [hunk 1]
```diff
@@ -120,6 +121,10 @@ public boolean complete(WorkflowContext context) {
     }
 
     private void resetActionContext(WorkflowContext context) {
+        if (CollectionUtils.isEmpty(context.getNewTaskList())) {
+            // direct complete request where the action context is already present
```
Comment (ciscozhou) [inline inlong-manager/manager-workflow/src/main/java/org/apache/inlong/manager/workflow/processor/ServiceTaskProcessor.java:125]: where -> when?

**Review by kipshi — APPROVED** [review]

**Review by healchow — APPROVED** [review]
