### PR TITLE
[INLONG-7325][Manager] Format the topic name and data separator for Kafka

### LINKED ISSUE #7325: [Bug][Manager] The topic name format error of Kafka
### What happened

The kafka topic naming rules are updated to: `inlongGroupId.inlongStreamId`, but the flink task submitted by sort is still `inlongstreamId`.

### What you expected to happen

Fix topic name.

### How to reproduce

Use kafka MQ

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by haifxu**
### Prepare a Pull Request

- Fixes #7325 

### Motivation

The Kafka topic naming rules are updated to: `inlongGroupId.inlongStreamId`, but the Flink task submitted by sort is still `inlongstreamId`.

### Modifications

`inlongstreamId` -> `inlongGroupId.inlongStreamId`

### Verifying this change

- [x] This change is a trivial rework/code cleanup without any test coverage.

- [ ] This change is already covered by existing tests, such as:

- [ ] This change added tests and can be verified as follows:

### CODE REVIEW

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/kafka/KafkaResourceOperators.java [hunk 1]
```diff
@@ -134,7 +134,13 @@ public void deleteQueueForStream(InlongGroupInfo groupInfo, InlongStreamInfo str
         log.info("begin to delete kafka resource for groupId={} streamId={}", groupId, streamId);
 
         try {
-            this.deleteKafkaTopic(groupInfo, streamInfo.getMqResource());
+            String topicName = streamInfo.getMqResource();
+            if (topicName.equals(streamId)) {
```
Comment (fuweng11) [inline inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/kafka/KafkaResourceOperators.java:138]: `Objects.equals(topicName, streamId)`

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/kafka/KafkaSourceOperator.java [hunk 2]
```diff
@@ -113,6 +114,13 @@ public Map<String, List<StreamSource>> getSourcesMap(InlongGroupInfo groupInfo,
             kafkaSource.setBootstrapServers(bootstrapServers);
             kafkaSource.setTopic(streamInfo.getMqResource());
             String serializationType = DataTypeEnum.forType(streamInfo.getDataType()).getType();
+            String topicName = streamInfo.getMqResource();
+            if (topicName.equals(streamId)) {
```
Comment (fuweng11) [inline inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/kafka/KafkaSourceOperator.java:118]: `Objects.equals(topicName, streamId)`

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/kafka/KafkaSourceOperator.java [hunk 3]
```diff
@@ -126,6 +134,17 @@ public Map<String, List<StreamSource>> getSourcesMap(InlongGroupInfo groupInfo,
                 }
             }
 
+            // if the SerializationType is still null, set it to the CSV
+            if (StringUtils.isEmpty(kafkaSource.getSerializationType())) {
+                kafkaSource.setSerializationType(DataTypeEnum.CSV.getType());
+            }
+            if (DataTypeEnum.CSV.getType().equalsIgnoreCase(kafkaSource.getSerializationType())) {
+                kafkaSource.setDataSeparator(streamInfo.getDataSeparator());
+                if (StringUtils.isEmpty(kafkaSource.getDataSeparator())) {
```
Comment (fuweng11) [inline inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/kafka/KafkaSourceOperator.java:143]: `StringUtils.isBlank()`

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/kafka/KafkaSourceOperator.java [hunk 4]
```diff
@@ -126,6 +134,17 @@ public Map<String, List<StreamSource>> getSourcesMap(InlongGroupInfo groupInfo,
                 }
             }
 
+            // if the SerializationType is still null, set it to the CSV
+            if (StringUtils.isEmpty(kafkaSource.getSerializationType())) {
```
Comment (fuweng11) [inline inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/kafka/KafkaSourceOperator.java:138]: `StringUtils.isBlank()`

**Review by dockerzhang — APPROVED** [review]

**Review by healchow — APPROVED** [review]

**Review by fuweng11 — APPROVED** [review]

**Review by woofyzhao — APPROVED** [review]
