### PR TITLE
[INLONG-5476][Manager] Fix heartbeat status and node list query problem

### LINKED ISSUE #5476: [Bug][Manager] Heartbeat is not functioning properly under sparse report
### What happened

1. The removal cause is not filtered correctly.
2. Scheduler is missing to perform eager eviction.

### What you expected to happen

Heartbeat status is correct.

### How to reproduce

Deploy manager and watch node status.

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by woofyzhao**
- Fixes #5476

1. the cache remove cause should be filtered
2. should use cleanup to do eager eviction in time 
https://github.com/ben-manes/caffeine/wiki/Cleanup

image
This is exactly the case of heartbeat scenario

3. Query by clusterTag is broken, fix it

### CODE REVIEW

**Review by healchow — APPROVED** [review]
LGTM

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/heartbeat/HeartbeatManager.java [hunk 1]
```diff
@@ -66,16 +68,18 @@ public class HeartbeatManager implements AbstractHeartbeatManager {
...
                 .removalListener((ComponentHeartbeat k, HeartbeatMsg msg, RemovalCause c) -> {
-                    if (msg != null) {
+                    if ((c.wasEvicted() || c == RemovalCause.EXPLICIT) && msg != null) {
                         evictClusterNode(msg);
                     }
                 }).build();
 
         clusterInfoCache = Caffeine.newBuilder()
-                .expireAfterAccess(expireTime, TimeUnit.SECONDS)
+                .expireAfterAccess(expireTime * 2L, TimeUnit.SECONDS)
```
Comment (woofyzhao) [inline inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/heartbeat/HeartbeatManager.java:82]: Why double again, needs explanation.

**Review by dockerzhang — APPROVED** [review]

**Review by dockerzhang — APPROVED** [review]

**Review by gong — APPROVED** [review]
