### PR TITLE
[INLONG-5762][Sort] Fix the computing for the Pulsar source metric

### LINKED ISSUE #5762: [Bug][Sort] The computing of Pulsar source metric was wrong
### What happened

Now, pulsar metric computing is just pulsar record, but record can be unpacked. We should compute unpacked data.
And, pulsar metric name is not right. We expect metric name is `flink_taskmanager_job_task_operator_groupId_streamId_nodeId_numRecordsIn`, but metric name is `flink_taskmanager_job_task_operator_user_groupId_streamId_nodeId_numRecordsIn`

### What you expected to happen

metric result is right and metric name is right

### How to reproduce

just test inlongmsg format

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Sort

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by gong**
### Prepare a Pull Request

- [INLONG-5762][Sort] Fix pulsar source metric computing

- Fixes #5762 

### Motivation

Fix pulsar source metric computing

### Modifications

* Add CallbackCollector for computing
* modify metric name

### CODE REVIEW

File: inlong-sort/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/table/DynamicPulsarDeserializationSchema.java [hunk 1]
```diff
@@ -132,6 +140,39 @@ public void open(DeserializationSchema.InitializationContext context) throws Exc
 
     }
 
+    /**
+     * reflect get metricGroup
+     *
+     * @param context
+     * @return
+     */
+    private MetricGroup getMetricGroup(DeserializationSchema.InitializationContext context)
```
Comment (thesumery) [inline inlong-sort/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/table/DynamicPulsarDeserializationSchema.java:149]: Why not modify FlinkPulsarSource#open directly?

Comment (gong) [reply inlong-sort/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/table/DynamicPulsarDeserializationSchema.java:149]: @thesumery Because pulsar self metric will be affected if I modify FlinkPulsarSource#open directly. And `org.apache.flink.streaming.connectors.pulsar.FlinkPulsarSource` will need be modified if I use adminUrl pulsar.

File: inlong-sort/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/table/DynamicPulsarDeserializationSchema.java [hunk 2]
```diff
@@ -132,6 +140,39 @@ public void open(DeserializationSchema.InitializationContext context) throws Exc
 
     }
 
+    /**
+     * reflect get metricGroup
+     *
+     * @param context
```
Comment (healchow) [inline inlong-sort/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/table/DynamicPulsarDeserializationSchema.java:146]: Suggested adding description for `@param` and `@return`.

Comment (gong) [reply inlong-sort/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/table/DynamicPulsarDeserializationSchema.java]: done

**Review by healchow — APPROVED** [review]

File: inlong-sort/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/table/DynamicPulsarDeserializationSchema.java [hunk 3]
```diff
@@ -132,6 +140,40 @@ public void open(DeserializationSchema.InitializationContext context) throws Exc
...
+     * reflect get metricGroup
+     *
+     * @param context Contextual information that can be used during initialization.
+     * @return metric group that can be used to register new metrics with Flink and to create a nested hierarchy based
+     *         on the group names.
+     */
+    private MetricGroup getMetricGroup(DeserializationSchema.InitializationContext context)
+            throws NoSuchFieldException, IllegalAccessException {
+        MetricGroup metricGroup;
+        String className = "RuntimeContextDeserializationInitializationContextAdapter";
```
Comment (EMsnap) [inline inlong-sort/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/table/DynamicPulsarDeserializationSchema.java:153]: pls extract constant for class name

File: inlong-sort/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/table/DynamicPulsarDeserializationSchema.java [hunk 4]
```diff
@@ -132,6 +140,40 @@ public void open(DeserializationSchema.InitializationContext context) throws Exc
...
+        String fieldName = "runtimeContext";
+        Class runtimeContextDeserializationInitializationContextAdapter = null;
+        Class[] innerClazz = RuntimeContextInitializationContextAdapters.class.getDeclaredClasses();
+        for (Class clazz : innerClazz) {
+            int mod = clazz.getModifiers();
```
Comment (EMsnap) [inline inlong-sort/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/table/DynamicPulsarDeserializationSchema.java:158]: mod -> modifier since mod is a term in math

File: inlong-sort/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/table/DynamicPulsarDeserializationSchema.java (hunk 1 above)
Comment (EMsnap) [reply inlong-sort/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/table/DynamicPulsarDeserializationSchema.java:150]: > Why not modify FlinkPulsarSource#open directly?

same with me, no need to reflect the metric group. It's ok if we modify the user metrics group since we build the source by ourselves

File: inlong-sort/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/table/DynamicPulsarDeserializationSchema.java (hunk 3 above)
Comment (gong) [reply inlong-sort/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/table/DynamicPulsarDeserializationSchema.java:153]: I don't think that it need constant for class name.

**Review by dockerzhang — APPROVED** [review]
