### PR TITLE
[INLONG-5082][Dashboard] Fix Elasticsearch fields cannot be saved

### LINKED ISSUE #5082: [Bug][Dashboard] Elasticsearch fields cannot be saved
### What happened

Elasticsearch fields cannot be saved.

### What you expected to happen

Save fields successfully.

### How to reproduce

Add ES fields in the dashboard, but query null.

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Dashboard

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by ciscozhou**
### Prepare a Pull Request

- Fixes #5082

### Motivation

Fix Elasticsearch fields cannot be saved.

### CODE REVIEW

File: inlong-dashboard/src/components/MetaData/StorageEs.tsx [hunk 1]
```diff
@@ -162,7 +162,7 @@ const getForm: GetStorageFormFieldsType = (
       suffix: i18n.t('components.AccessHelper.StorageMetaData.Es.RetryTimesUnit'),
     },
     {
-      name: 'fieldList',
+      name: 'sinkFieldList',
```
Comment (healchow) [inline inlong-dashboard/src/components/MetaData/StorageEs.tsx:165]: @leezng PTAL.

**Review by healchow — APPROVED** [review]

**Review by leezng — APPROVED** [review]
