### PR TITLE
[INLONG-7987][Manager] Add heartbeat timeout status to the source

### LINKED ISSUE #7987: [Improve][Manager] Add a heartBeatTimeout status to the source
### Description

Add a heartBeatTimeout status to the source.

Currently streamSource has the following problems：
1.StreamSource information that is in the status to be delivered or modified cannot be deleted.
2.If the agent does not report data for a long time due to the abnormal status of the streamSource, streamSource information cannot be deleted or remains in the status `to be issued` for a long time.

Solution：
Currently, the Agent supports heartbeat reporting and automatic registration. After receiving the heartbeat information from the Agent, the Manager registers the corresponding cluster and node information and sets the node status to `NORMAL`.

To solve the above two problems, the agent `HEARTBEAT_TIMEOUT` state is added to the streamSource. The streamSource in this state can be deleted but cannot be modified.

In this case, if the Agent cluster corresponding to the data source to be delivered fails to report the heartbeat information due to various problems, the Manager does not receive the heartbeat information of the Agent for a long time and changes the node status to `HEARTBEAT_TIMEOUT` and change the status of the streamSource corresponding to the node to agent heartbeat Timeout. 

In this case, you can choose to delete the data source or wait for the recovery of the agent node to continue the task. If you choose to delete the data source, after the Agent node recovers,

The Manager determines if the previous task needs to continue based on the is_deleted property of the current data source, if` is_delted! =0`, the current data source needs to be deleted. Therefore, the data source status is changed to to be deleted.

To solve the above two problems.

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by fuweng11**
### Prepare a Pull Request

- Fixes #7987 

### Motivation

Add a heartBeatTimeout status to the source.

### Modifications

Add a heartBeatTimeout status to the source.

### CODE REVIEW

**Review by vernedeng — APPROVED** [review]
LGTM

**Review by kipshi — APPROVED** [review]
good job

**Review by kipshi — APPROVED** [review]
good job

**Review by kipshi — APPROVED** [review]
good job

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/heartbeat/HeartbeatManager.java [hunk 1]
```diff
@@ -162,6 +177,23 @@ public void reportHeartbeat(HeartbeatMsg heartbeat) {
...
+                        for (StreamSourceEntity sourceEntity : sourceEntities) {
+                            // restore state for all source by ip and type
+                            if (sourceEntity.getIsDeleted() != 0) {
+                                sourceEntity.setPreviousStatus(sourceEntity.getStatus());
+                                sourceEntity.setStatus(SourceStatus.TO_BE_ISSUED_DELETE.getCode());
+                            } else {
+                                sourceEntity.setStatus(sourceEntity.getPreviousStatus());
+                                sourceEntity.setPreviousStatus(SourceStatus.HEARTBEAT_TIMEOUT.getCode());
+                            }
+                            sourceMapper.updateByPrimaryKeySelective(sourceEntity);
```
Comment (healchow) [inline inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/heartbeat/HeartbeatManager.java:194]: It is a bad practice to read and write DB in a loop.
Can you change to update records in batches?

Comment (healchow) [inline inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/heartbeat/HeartbeatManager.java:194]: It is a bad practice to read and write DB in a loop.
Can you change to update records in batches?

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java [hunk 2]
```diff
@@ -416,6 +418,24 @@ private void preProcessLabelFileTasks(TaskRequest taskRequest) {
...
+        for (StreamSourceEntity sourceEntity : sourceEntities) {
+            // restore state for all source by ip and type
+            if (sourceEntity.getIsDeleted() != 0) {
+                sourceEntity.setPreviousStatus(sourceEntity.getStatus());
+                sourceEntity.setStatus(SourceStatus.TO_BE_ISSUED_DELETE.getCode());
+            } else {
+                sourceEntity.setStatus(sourceEntity.getPreviousStatus());
+                sourceEntity.setPreviousStatus(SourceStatus.HEARTBEAT_TIMEOUT.getCode());
+            }
+            sourceMapper.updateByPrimaryKeySelective(sourceEntity);
```
Comment (healchow) [inline inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java:435]: ditto

**Review by healchow — CHANGES_REQUESTED** [review]

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java [hunk 3]
```diff
@@ -129,6 +129,8 @@ public void report(TaskRequest request) {
             throw new BusinessException("agent request or agent ip was empty, just return");
         }
 
+        preTimeoutTasks(request);
```
Comment (healchow) [inline inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java:132]: Can this method be made asynchronous, or can StreamSources be added to the queue, and other threads can be scheduled to rotate for processing to prevent this operation from taking too long or other problems, causing the report interface to respond to timeout or failure?

这个方法能否做成异步的，或者将配置加入队列，由其他的线程定时去轮训处理，以防止这个操作耗时太久或出现其他问题，导致 report 接口响应超时或失败。

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java (hunk 2 above)
Comment (fuweng11) [reply inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java]: done

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/heartbeat/HeartbeatManager.java (hunk 1 above)
Comment (fuweng11) [reply inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/heartbeat/HeartbeatManager.java]: done

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java (hunk 3 above)
Comment (fuweng11) [reply inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java:158]: done

**Review by dockerzhang — APPROVED** [review]

**Review by dockerzhang — APPROVED** [review]

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/AbstractSourceOperator.java [hunk 4]
```diff
@@ -172,21 +172,30 @@ public void updateOpt(SourceRequest request, Integer groupStatus, Integer groupM
...
+                        nextStatus = SourceStatus.SOURCE_NEW.getCode();
                         break;
                     default:
                         // others leave it be
                         break;
                 }
             }
+            entity.setStatus(nextStatus);
+            // When the source is in a heartbeat timeout state, set nextStatus to preStatus
+            if (Objects.equals(SourceStatus.HEARTBEAT_TIMEOUT.getCode(), sourceStatus.getCode())) {
```
Comment (healchow) [inline inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/AbstractSourceOperator.java:195]: I think that after the user modifies the configuration, the status should change to "modification pending delivery" instead of keeping the heartbeat timeout.

The heartbeat timeout should be determined by other processes that are specifically responsible for processing heartbeats.

Comment (fuweng11) [reply inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/AbstractSourceOperator.java]: done

File: inlong-manager/manager-dao/src/main/resources/mappers/StreamSourceEntityMapper.xml [hunk 5]
```diff
@@ -498,6 +523,38 @@
...
+                <foreach item="item" index="index" collection="idList" open="(" close=")" separator=",">
+                    #{item}
+                </foreach>
+            </if>
+        </where>
+    </update>
+    <update id="updateStatusToTimeout">
+        update stream_source
+        <set>
+            status = 105
```
Comment (healchow) [inline inlong-manager/manager-dao/src/main/resources/mappers/StreamSourceEntityMapper.xml:550]: Please set the previous_status before.

File: inlong-manager/manager-dao/src/main/resources/mappers/StreamSourceEntityMapper.xml [hunk 6]
```diff
@@ -342,6 +342,29 @@
             </if>
         </where>
     </select>
+    <select id="selectNeedUpdateByAgentIpAndCluster" resultType="java.lang.Integer">
```
Comment (healchow) [inline inlong-manager/manager-dao/src/main/resources/mappers/StreamSourceEntityMapper.xml:345]: Change the name to `selectHeartbeatTimeoutIds`, and no need transfer the `statusList` param.

File: inlong-manager/manager-dao/src/main/resources/mappers/StreamSourceEntityMapper.xml [hunk 7]
```diff
@@ -498,6 +523,38 @@
             </if>
         </where>
     </update>
+    <update id="restoreStatusFromHeartbeatByIds">
```
Comment (healchow) [inline inlong-manager/manager-dao/src/main/resources/mappers/StreamSourceEntityMapper.xml:526]: Maybe call `rollbackTimeoutStatusByIds`, and no need transfer the `status` param is better.

Comment (fuweng11) [reply inlong-manager/manager-dao/src/main/resources/mappers/StreamSourceEntityMapper.xml]: done

File: inlong-manager/manager-dao/src/main/resources/mappers/StreamSourceEntityMapper.xml (hunk 6 above)
Comment (fuweng11) [reply inlong-manager/manager-dao/src/main/resources/mappers/StreamSourceEntityMapper.xml]: done

File: inlong-manager/manager-dao/src/main/resources/mappers/StreamSourceEntityMapper.xml (hunk 5 above)
Comment (fuweng11) [reply inlong-manager/manager-dao/src/main/resources/mappers/StreamSourceEntityMapper.xml:551]: done

File: inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/StreamSourceEntityMapper.java [hunk 8]
```diff
@@ -164,6 +171,21 @@ int updateIpAndUuid(@Param("id") Integer id, @Param("agentIp") String agentIp, @
...
+     *
+     * @param idList source id list
+     * @param operator operator name
+     */
+    void rollbackTimeoutStatusByIds(@Param("idList") List<Integer> idList, @Param("operator") String operator);
+
+    /**
+     * Update the source status when it has been deleted
+     *
+     * @param timeBefore the latest modify time before which to select
```
Comment (healchow) [inline inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/StreamSourceEntityMapper.java:185]:
```suggestion
     * @param beforeSeconds the modified time was beforeSeconds seconds ago
```

**Review by healchow — APPROVED** [review]
LGTM
