### PR TITLE
[INLONG-12073][Manager] Optimize Pulsar message query with thread pool and proper error handling

### LINKED ISSUE #12073: [Bug][Manager] No proper error handling when MQ message query thread pool is exhausted
### What happened

Currently, when querying MQ messages from multiple Pulsar clusters, there are several issues:

1. **No thread pool management**: Message queries are executed without proper thread pool management, which may lead to resource exhaustion under high concurrency.

2. **No graceful handling for task rejection**: When too many concurrent requests come in, the system doesn't properly handle the `RejectedExecutionException` and doesn't provide a user-friendly error response.

3. **No task cancellation mechanism**: When task submission fails, previously submitted tasks continue to run unnecessarily.

4. **No interruption support**: Long-running IO operations cannot be cancelled when the request is aborted.

### What you expected to happen

1. **Add a dedicated thread pool**: Use `ThreadPoolTaskExecutor` with configurable core/max pool size and queue capacity for message query tasks.

2. **Add proper error handling**: 
   - Add a new error code `PULSAR_QUERY_REJECTED(2610)` for task rejection scenarios
   - Return proper error code and message to the caller: `{"success": false, "errCode": 2610, "errMsg": "Query task rejected: too many concurrent requests, please try again later"}`

3. **Implement task cancellation**: When `RejectedExecutionException` occurs, cancel all previously submitted tasks to free up resources.

4. **Add interruption checks**: Check `Thread.currentThread().isInterrupted()` before and after IO operations to support task cancellation.

### How to reproduce

If you frequently submit tasks to a multi-cluster Pulsar setup, you will find that later-submitted tasks time out during submission. However, these tasks remain queued and processed in the code, even though they are useless and should be discarded.

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [x] Yes, I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by healchow**
[INLONG-12073][Manager] Optimize Pulsar message query with thread pool and proper error handling

Fixes #12073

### Motivation

Currently, when querying MQ messages from multiple Pulsar clusters, there are several issues:

1. **No thread pool management**: Message queries are executed without proper thread pool management, which may lead to resource exhaustion under high concurrency.

2. **No graceful handling for task rejection**: When too many concurrent requests come in, the system doesn't properly handle the `RejectedExecutionException` and doesn't provide a user-friendly error response.

3. **No task cancellation mechanism**: When task submission fails, previously submitted tasks continue to run unnecessarily.

4. **No interruption support**: Long-running IO operations cannot be cancelled when the request is aborted.

### Modifications

1. **Add a dedicated thread pool**: Use `ThreadPoolTaskExecutor` with configurable core/max pool size and queue capacity for message query tasks.

2. **Implement task cancellation**: When `RejectedExecutionException` occurs, cancel all previously submitted tasks to free up resources.

3. **Add interruption checks**: Check `Thread.currentThread().isInterrupted()` before and after IO operations to support task cancellation.

### Verifying this change

- [ ] This change is a trivial rework/code cleanup without any test coverage.

- [ ] This change is already covered by existing tests, such as:
  *(please describe tests)*

- [x] This change added tests and can be verified as follows:

  - *Added unit tests QueryLatestMessagesRunnableTest to verified this change*

### Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a follow-up issue for adding the documentation

### CODE REVIEW

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/pulsar/PulsarQueueResourceOperator.java [hunk 1]
```diff
@@ -307,34 +372,150 @@ private void deletePulsarTopic(InlongPulsarInfo pulsarInfo, PulsarClusterInfo pu
...
+        String clusterTag = groupInfo.getInlongClusterTag();
+        List<ClusterInfo> clusterInfos = clusterService.listByTagAndType(clusterTag, ClusterType.PULSAR);
+        if (CollectionUtils.isEmpty(clusterInfos)) {
+            log.warn("No pulsar cluster found for clusterTag={} for groupId={}", clusterTag, groupId);
+            return Collections.emptyList();
+        }
+
+        // Select clusters and calculate per-cluster query count
+        Integer requestCount = request.getMessageCount();
+        List<ClusterInfo> selectedClusters = randomSelectQueryClusters(clusterInfos, requestCount);
```
Comment (fuweng11) [inline inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/pulsar/PulsarQueueResourceOperator.java]: Data may be concentrated on a specific pulsar, making it impossible for other pulsar clusters to retrieve the data. Therefore, it is not feasible to randomly select a cluster for querying. Instead, all pulsar clusters need to be queried.

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/pulsar/PulsarQueueResourceOperator.java [hunk 2]
```diff
@@ -307,34 +370,127 @@ private void deletePulsarTopic(InlongPulsarInfo pulsarInfo, PulsarClusterInfo pu
...
+        List<ClusterInfo> clusterInfos = clusterService.listByTagAndType(clusterTag, ClusterType.PULSAR);
+        if (CollectionUtils.isEmpty(clusterInfos)) {
+            log.warn("No pulsar cluster found for clusterTag={} for groupId={}", clusterTag, groupId);
+            return Collections.emptyList();
+        }
+
+        // Select clusters and calculate per-cluster query count
+        Integer requestCount = request.getMessageCount();
+        int clusterSize = clusterInfos.size();
+        int perClusterCount = calculatePerClusterCount(requestCount, clusterSize);
```
Comment (fuweng11) [inline inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/pulsar/PulsarQueueResourceOperator.java]: Since data may be concentrated on a certain cluster, the average should not be calculated based on the number of clusters and queries during querying.

**Review by fuweng11 — DISMISSED** [review]

**Review by luchunliang — DISMISSED** [review]

**Review by vernedeng — DISMISSED** [review]

**Review by vernedeng — APPROVED** [review]
