### PR TITLE
[INLONG-7577][Manager] Fix high CPU usage when the number of StreamSource is too large

### LINKED ISSUE #7577: [Bug][Manager] The number of StreamSource is too large, resulting in high CPU usage
### What happened

When too many agents are deployed, a large number of StreamSource instances are generated when the agent pulls tasks from the manager, leading to a large number of GC.The result is CPU100%.

### What you expected to happen

The manager does not generate too many streamSource instances when pulling tasks.

企业微信截图_d978311a-ebb5-4773-a814-ce0bff687feb

### How to reproduce

More than 100 agents are deployed.

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by fuweng11**
### Prepare a Pull Request

- Fixes #7577 

### Motivation

Fix the manager generate too many streamSource instances when pulling tasks.
### Modifications
The previous query was to pull out all Streamsources in the templateId and filter them.
If there were 200 agents, this method would generate 500 + streamSource instances each time, leading to a large amount of gc.
Filtering is now done directly in the mysql layer to avoid generating too many instances and causing gc.

### CODE REVIEW

File: inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/StreamSourceEntityMapper.java [hunk 1]
```diff
@@ -41,6 +41,9 @@ public interface StreamSourceEntityMapper {
      */
     StreamSourceEntity selectForAgentTask(Integer id);
 
+    StreamSourceEntity selectExistsByTemplateIdAndIp(@Param("templateId") Integer templateId,
```
Comment (healchow) [inline inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/StreamSourceEntityMapper.java:44]: 1. Please add Javadoc for the method.
2. Maybe `selectOneByTemplatedIdAndAgentIp` is more readable.

Comment (fuweng11) [reply inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/StreamSourceEntityMapper.java]: done.

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java [hunk 2]
```diff
@@ -338,31 +334,25 @@ private void preProcessTemplateFileTask(TaskRequest taskRequest) {
...
-                    fileEntity.setTemplateId(sourceEntity.getId());
-                    fileEntity.setAgentIp(agentIp);
-                    fileEntity.setStatus(SourceStatus.TO_BE_ISSUED_ADD.getCode());
-                    // create new sub source task
-                    sourceMapper.insert(fileEntity);
-                    LOGGER.info("Transform new template task({}) for agent({}) in cluster({}).",
-                            fileEntity.getId(), taskRequest.getAgentIp(), taskRequest.getClusterName());
-                });
+        sourceEntities.forEach(sourceEntity -> {
+            StreamSourceEntity subSource = sourceMapper.selectOneByTemplatedIdAndAgentIp(sourceEntity.getId(),
```
Comment (healchow) [inline inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java:338]: Are you sure it's the code here that is causing the high CPU usage?

Only one query is made here, and the amount of data is too large, which should lead to excessive memory usage, and then trigger the GC process of the JVM.

After changing to query one by one, you can solve the problem of too many query results, but it will cause the method to cycle too many times, frequently query the DB, put too much pressure on the DB, and take too long time.

**Comment by gong** [comment]
@fuweng11 Maybe add some description that why it can solve this fix high CPU usage.

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java (hunk 2 above)
Comment (fuweng11) [reply inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java:338]: The previous query was to pull out all Streamsources in the templateId and filter them.
If there were 200 agents, this method would generate 500 + streamSource instances each time, leading to a large amount of gc.
Filtering is now done directly in the mysql layer to avoid generating too many instances and causing gc.

**Comment by fuweng11** [comment]
> @fuweng11 Maybe add some description that why it can solve this fix high CPU usage.

done.

**Review by thexiay — APPROVED** [review]

**Comment by thexiay** [comment]
LTGM

**Review by yunqingmoswu — APPROVED** [review]

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java [hunk 3]
```diff
@@ -338,30 +336,24 @@ private void preProcessTemplateFileTask(TaskRequest taskRequest) {
...
-                    fileEntity.setTemplateId(sourceEntity.getId());
-                    fileEntity.setAgentIp(agentIp);
-                    fileEntity.setStatus(SourceStatus.TO_BE_ISSUED_ADD.getCode());
-                    // create new sub source task
-                    sourceMapper.insert(fileEntity);
-                    LOGGER.info("Transform new template task({}) for agent({}) in cluster({}).",
-                            fileEntity.getId(), taskRequest.getAgentIp(), taskRequest.getClusterName());
+        sourceEntities.forEach(sourceEntity -> {
+                    StreamSourceEntity subSource = sourceMapper.selectExistsByTemplateIdAndIp(sourceEntity.getId(),
+                            agentIp);
```
[the remark this answers is not in the document]
Comment (fuweng11) [reply inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java]: It won't.

**Review by dockerzhang — APPROVED** [review]

**Comment by thexiay** [comment]
please apply `mvn spotless:apply`

**Review by healchow — APPROVED** [review]

**Review by gong — APPROVED** [review]
