### PR TITLE
[INLONG-11583][TubeMQ] Go SDK load balance logic not perfect, causing consumption to stop suddenly

### LINKED ISSUE #11583: [Bug][TubeMQ] Go SDK load balance logic not perfect, causing consumption to stop suddenly
### What happened

consumption suddenly stop
image

### What you expected to happen

1. If the old code fails to register to Master again, there will be no further actions. It needs to be changed to continue retrying indefinitely upon failure.
企业微信截图_17334052584263

2. OfferEventAndNotify is responsible for receiving rebalance events, while OfferEventResult handles the results of those events. Therefore, the former should definitely not operate on rebalanceResults, nor should it reprocess the header of rebalanceResults as if it were a newly received event. Otherwise, if the result of the previous event has not been reported yet when the second event arrives, the subsequent processRebalanceEvent will end up processing the first event again, causing the second received event to be discarded.
企业微信截图_1733405369322

3. ip_selector directly returns the domain name, while the connection pool maintains one connection per address, and it will not reconnect as long as the packet sending and receiving are normal. If there is a cluster switch, as long as the old master is sending and receiving packets normally, even if the registration fails, the TCP connection will not reconnect. Therefore, it is necessary to resolve the domain name into an IP address before returning it. During a cluster switch, a new IP can be returned by re-selecting. 
企业微信截图_17334056241261

4. Here, there is no check to see if rsp's success is true. If a cluster change causes the master to no longer recognize the client, it will continue to send heartbeats without re-registering.
企业微信截图_17334061728723

### How to reproduce

when master changes

### Environment

_No response_

### InLong version

master

### InLong Component

InLong TubeMQ

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by yuexihan**
Fixes #11583

### Verifying this change

*(Please pick either of the following options)*

- [ ] This change is a trivial rework/code cleanup without any test coverage.

- [ ] This change is already covered by existing tests, such as:
  *(please describe tests)*

- [ ] This change added tests and can be verified as follows:

  *(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a follow-up issue for adding the documentation

### CODE REVIEW

**Comment by aloyszhang** [comment]
please create an issue to describe what this pull request is for.

File: inlong-tubemq/tubemq-client-twins/tubemq-client-go/client/consumer_impl.go [hunk 1]
```diff
@@ -105,72 +106,92 @@ func NewConsumer(config *config.Config) (Consumer, error) {
...
+func (c *consumer) routine(ctx context.Context) {
+	defer close(c.routineClosed)
+
+	for {
+		select {
+		case <-ctx.Done():
+			return
+		default:
+		}
+		// 选主
```
Comment (gosonzhang) [inline inlong-tubemq/tubemq-client-twins/tubemq-client-go/client/consumer_impl.go:135]: To make it easier for more people to understand, please use English annotations

**Review by gosonzhang — APPROVED** [review]

**Review by justinwwhuang — APPROVED** [review]
