### PR TITLE
[INLONG-5164][Agent] BinlogReader adds audit and metrics

### LINKED ISSUE #5164: [Bug][Agent] The agent receive count is zero but the send count not.
### What happened

The agent receive count is zero but the send count not.
receive_count_0

### What you expected to happen

The receive count should be equal of send count.

### How to reproduce

Collect data by binlog source.

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Agent

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by pocozh**
### Prepare a Pull Request
*(Change the title refer to the following example)*

- [INLONG-5164][Agent] BinlogReader adds audit and metrics

*(The following *XYZ* should be replaced by the actual [GitHub Issue](https://github.com/apache/inlong/issues) number)*

- Fixes #5164 

### Motivation

*Explain here the context, and why you're making that change. What is the problem you're trying to solve?*

### Modifications

*Describe the modifications you've done.*

### Verifying this change

*(Please pick either of the following options)*

- [ ] This change is a trivial rework/code cleanup without any test coverage.

- [ ] This change is already covered by existing tests, such as:
  *(please describe tests)*

- [ ] This change added tests and can be verified as follows:

  *(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a follow-up issue for adding the documentation

### CODE REVIEW

File: inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/metrics/audit/AuditUtils.java [hunk 1]
```diff
@@ -69,6 +69,12 @@ public static void initAudit() {
         }
     }
 
+    public static void add(int auditID, String inlongGroupId, String inlongStreamId, long logTime, int count) {
```
Comment (GanfengTan) [inline inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/metrics/audit/AuditUtils.java:72]: Please, add doc

**Review by healchow — APPROVED** [review]

File: inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/metrics/audit/AuditUtils.java (hunk 1 above)
Comment (pocozh) [reply inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/metrics/audit/AuditUtils.java:75]: > Please, add doc

done

**Review by EMsnap — APPROVED** [review]

**Review by dockerzhang — APPROVED** [review]

**Review by GanfengTan — APPROVED** [review]
