### PR TITLE
[INLONG-6382][Sort] Iceberg data is messed up when the source table has no primary key in multiple sink scenes

### LINKED ISSUE #6382: [Bug][Sort] Iceberg data is messed up when the source table has no primary key in multiple sink scenes
### What happened

Iceberg miss data when source table do not have primary key in multiple sink scences

### What you expected to happen

Iceberg miss data when source table do not have primary key in multiple sink scences

### How to reproduce

Submit a Iceberg multiple sink task , and prepare a table without primary key in source table.

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Sort

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by thesumery**
[INLONG-6382][Sort] Bugfix:Iceberg miss data when source table do not have primary key in multiple sink scences

### Prepare a Pull Request
- [INLONG-6382][Sort] Bugfix:Iceberg miss data when source table do not have primary key in multiple sink scences
- Fixes #6382 

### Motivation

*Bugfix:Iceberg miss data when source table do not have primary key in multiple sink scences*

### Modifications

*Bugfix:Iceberg miss data when source table do not have primary key in multiple sink scences*

### CODE REVIEW

**Review by gong — APPROVED** [review]

File: inlong-sort/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/multiple/IcebergMultipleStreamWriter.java [hunk 1]
```diff
@@ -130,12 +129,6 @@ public void processElement(RecordWithSchema recordWithSchema) throws Exception {
             List<Integer> equalityFieldIds = recordWithSchema.getPrimaryKeys().stream()
                     .map(pk -> recordWithSchema.getSchema().findField(pk).fieldId())
                     .collect(Collectors.toList());
-            // if physical primary key not exist, put all field to logical primary key
-            if (equalityFieldIds.isEmpty()) {
```
Comment (yunqingmoswu) [inline inlong-sort/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/multiple/IcebergMultipleStreamWriter.java:134]: It is recommend to add a option 'sink.multiple.handle-strategy-without-pk'(The value maybe ['append'|'all-columns']) to decide what to do, if it is 'append',  all the records will be write use append mode, else use upsert mode by all columns.

**Comment by EMsnap** [comment]
I think the Pr title doesn't match with the code

File: inlong-sort/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/multiple/IcebergMultipleStreamWriter.java (hunk 1 above)
Comment (thesumery) [reply inlong-sort/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/multiple/IcebergMultipleStreamWriter.java:134]: good proposal

**Review by yunqingmoswu — APPROVED** [review]

**Review by dockerzhang — APPROVED** [review]

**Review by EMsnap — APPROVED** [review]
