### PR TITLE
[INLONG-8409][SDK] Data sending fails but dataproxy-sdk-cpp returns success

### LINKED ISSUE #8409: [Bug][dataproxy-sdk-cpp] Data sending fails but dataproxy-sdk-cpp returns success
### What happened

When reporting data to DataProxy through dataproxy-sdk-cpp, after DataProxy returns an error, dataproxy-sdk-cpp still counts successfully

### What you expected to happen

counts failure

### How to reproduce

sdk send a message,  dataproxy  force return a error, check result

### Environment

Linux

### InLong version

master

### InLong Component

InLong SDK

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by doleyzi**
### Prepare a Pull Request
- Fixes #8409

### Motivation

*When reporting data to DataProxy through dataproxy-sdk-cpp, after DataProxy returns an error, dataproxy-sdk-cpp still counts successfully*

### Modifications

*According to the latest dp return packet protocol, the errorcode is analyzed and judged.*

### CODE REVIEW

File: inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/net/socket_connection.cc [hunk 1]
```diff
@@ -367,6 +373,10 @@ namespace dataproxy_sdk
     {
         uint32_t uniq = recv_buf_->ReadUint32();
         uint16_t attr_len = recv_buf_->ReadUint16();
+        char attr[attr_len + 1];
```
Comment (justinwwhuang) [inline inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/net/socket_connection.cc:376]: attr_len maybe invalid，cause stackoverflow？

**Review by luchunliang — APPROVED** [review]

**Review by justinwwhuang — APPROVED** [review]
LGTM

File: inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/net/socket_connection.cc (hunk 1 above)
Comment (doleyzi) [reply inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/net/socket_connection.cc:384]: resolved

**Review by gosonzhang — APPROVED** [review]

**Review by dockerzhang — APPROVED** [review]
