### PR TITLE
[INLONG-5409][Manager] Fix json serialization for class BaseSortConf

### LINKED ISSUE #5409: [Bug][Manager] Fix json serialization for class BaseSortConf
### What happened

It will reproduce the problem when request inlong/manager/api/group/get/{groupId}.
It will generate tow same field and one is null. It will lead deserialization exception.

### What you expected to happen

no exception.

### How to reproduce

You can modify UT to reproduce the problem in inlong-manager/manager-client/src/test/java/org/apache/inlong/manager/client/api/inner/ClientFactoryTest.java
image

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by gong**
### Prepare a Pull Request

- [INLONG-5409][Manager] Fix json serialization for class BaseSortConf

- Fixes #5409 

### Motivation

 Fix json serialization for class BaseSortConf

### Modifications

* Remove `sortType` field for BaseSortConf
* Add `getType` method for FlinkSortConf and UserDefinedSortConf
* Remove `type` field for FlinkSortConf and UserDefinedSortConf
* Add UT for BaseSortConf

### CODE REVIEW

**Review by woofyzhao — APPROVED** [review]

File: inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/BaseSortConf.java [hunk 1]
```diff
@@ -29,8 +29,6 @@
 @JsonTypeInfo(use = JsonTypeInfo.Id.NAME, visible = true, property = "sortType")
 public abstract class BaseSortConf {
 
-    public String sortType;
```
Comment (healchow) [inline inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/BaseSortConf.java:32]: This field should not be removed, because it was used by `JsonTypeInfo`.
Suggests set its value in each subclass's constructor.

**Review by healchow — CHANGES_REQUESTED** [review]

**Review by leosanqing — APPROVED** [review]

File: inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/BaseSortConf.java (hunk 1 above)
Comment (gong) [reply inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/BaseSortConf.java:32]: It don't need declare `sortType` field. Annotation will generate sortType data when serialization

**Review by dockerzhang — APPROVED** [review]

**Review by healchow — APPROVED** [review]
