### PR TITLE
[INLONG-6076][Audit] Bugs in the ClickHouseService.processOutput()

### LINKED ISSUE #6076: [Bug][Audit] Bugs in the ClickHouseService.processOutput()
### What happened

In the ClickHouseService.processOutput() function[a], there are several places that need to be optimized:
1. data needs to read batchQueue data inside the while loop;
2. After exiting the while loop, you need to judge whether there is still unwritten data, and then do the commit operation

a. https://github.com/apache/inlong/blob/master/inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/service/ClickHouseService.java#L106
企业微信截图_16645225199676

### What you expected to happen

fix bugs

### How to reproduce

see code

### Environment

Linux

### InLong version

master

### InLong Component

InLong Audit

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by gosonzhang**
- Fixes #6076

### CODE REVIEW

File: inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/service/ClickHouseService.java [hunk 1]
```diff
@@ -99,10 +99,13 @@ private void processOutput() {
             return;
         }
         // output
-        try (PreparedStatement pstat = this.conn.prepareStatement(INSERT_SQL)) {
```
Comment (healchow) [inline inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/service/ClickHouseService.java:102]: Suggested using the `try-with-resource`, because the `PreparedStatement` implements the `AutoCloseable` interface, it will be closed automatically, we don't need to write additional `finally` block to close it.

Comment (gosonzhang) [reply inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/service/ClickHouseService.java:102]: Ok, you are right

**Review by healchow — APPROVED** [review]

**Review by doleyzi — APPROVED** [review]

**Review by dockerzhang — APPROVED** [review]
