### PR TITLE
[INLONG-5353][Sort] Fix HBase connector packaging problem and inlong metrics delimiter problem

### LINKED ISSUE #5353: [Bug][Sort] Fix HBase connector packaging problem and inlong metrics delimiter problem
### What happened

maven packaging lost class file of connector-base.
inlong metric use `-` delimiter.

### What you expected to happen

maven packaging include class file of connector-base.
inlong metric should use `&` delimiter.

### How to reproduce

just package

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Sort

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by gong**
### Prepare a Pull Request

- [INLONG-5353][Sort] Fix HBase connector packaging problem and inlong metrics delimiter problem

- Fixes #5353 

### Motivation
Fix HBase connector packaging problem and inlong metrics delimiter problem

### Modifications

* modify HBase connector pom file
* modify HBase connector inlong metric delimiter

### CODE REVIEW

**Review by Oneal65 — COMMENTED** [review]
LGTM

**Review by Oneal65 — APPROVED** [review]

File: inlong-sort/sort-connectors/hbase/src/main/java/org/apache/inlong/sort/hbase/sink/HBaseSinkFunction.java [hunk 1]
```diff
@@ -128,18 +129,18 @@ public void open(Configuration parameters) throws Exception {
             this.runtimeContext = getRuntimeContext();
             sinkMetricData = new SinkMetricData(runtimeContext.getMetricGroup());
```
Comment (EMsnap) [inline inlong-sort/sort-connectors/hbase/src/main/java/org/apache/inlong/sort/hbase/sink/HBaseSinkFunction.java:130]: here if sinkMetricData would throw npe if inlongMetrics is null. So the initialization should be after the check of inlongMetrics.
if (inLongMetric != null && !inLongMetric.isEmpty()) { new sinkMetricData  ... }

**Review by yunqingmoswu — APPROVED** [review]
LGTM

**Review by dockerzhang — APPROVED** [review]

**Review by EMsnap — APPROVED** [review]
