### PR TITLE
[INLONG-11861][CI] Compile dataproxy-sdk fail when there is no .git dictionary in the base path

### LINKED ISSUE #11861: [Bug][CI] Compile dataproxy-sdk fail when there is no .git dictionary in the base path
### What happened

Image

### What you expected to happen

Fix it.

### How to reproduce

Compile dataproxy-sdk from source code

### Environment

_No response_

### InLong version

master

### InLong Component

InLong SDK

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by gosonzhang**
Fixes #11861

Adjust the SDK version acquisition method

### CODE REVIEW

**Review by vernedeng — APPROVED** [review]

**Review by fuweng11 — APPROVED** [review]

File: inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/utils/ProxyUtils.java [hunk 1]
```diff
@@ -104,11 +104,19 @@ public static String getJarVersion() {
         if (sdkVersion != null) {
             return sdkVersion;
         }
-        Properties properties = new Properties();
-        try (InputStream is = ProxyUtils.class.getResourceAsStream("/git.properties")) {
-            properties.load(is);
-            sdkVersion = properties.getProperty("git.build.version");
+        try (InputStream is = ProxyUtils.class.getClassLoader().getResourceAsStream("sdk.version")) {
```
Comment (featzhang) [inline inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/utils/ProxyUtils.java:107]: <resources>
			<resource>
				<directory>src/main/resources</directory>
				<filtering>false</filtering>
			</resource>
			<resource>
				<directory>src/main/resources-filtered</directory>
				<filtering>true</filtering>
			</resource>
		</resources>
		
		
https://maven.apache.org/plugins/maven-resources-plugin/examples/filter.html

Using Maven resource filtering seems to be a good solution, which does not rely on git.
