### PR TITLE
[INLONG-6356][Sort] Oracle connector supports precision and binary type

### LINKED ISSUE #6356: [Bug][Sort] Verify all field types for Oracle connector
### What happened

Verify all field types of oracle connector

### What you expected to happen

Verify all field types of oracle connector

### How to reproduce

null

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Sort

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by e-mhui**
### Prepare a Pull Request

[INLONG-6356][Sort] Oracle connector supports precision and binary type

- Fixes #6356

### Motivation

Oracle connector supports precision and binary type

### CODE REVIEW

**Review by gong — APPROVED** [review]

File: inlong-sort/sort-connectors/oracle-cdc/src/main/java/org/apache/inlong/sort/cdc/oracle/table/OracleReadableMetaData.java [hunk 1]
```diff
@@ -447,16 +448,22 @@ public static Map<String, String> getOracleType(@Nullable TableChanges.TableChan
...
-                        column -> {
-                            oracleType.put(
-                                    column.name(),
-                                    String.format(
-                                            "%s(%d)",
-                                            column.typeName(),
-                                            column.length()));
-                        });
+        for (Column column : table.columns()) {
+            if (column.typeName().matches("\\w.+\\([\\d ,]+\\)")) {
```
Comment (EMsnap) [inline inlong-sort/sort-connectors/oracle-cdc/src/main/java/org/apache/inlong/sort/cdc/oracle/table/OracleReadableMetaData.java:452]: suggested extracted as a constant

Comment (yunqingmoswu) [inline inlong-sort/sort-connectors/oracle-cdc/src/main/java/org/apache/inlong/sort/cdc/oracle/table/OracleReadableMetaData.java:452]: It is recomment to give a reason for the handle?

Comment (e-mhui) [reply inlong-sort/sort-connectors/oracle-cdc/src/main/java/org/apache/inlong/sort/cdc/oracle/table/OracleReadableMetaData.java:453]: done.

**Review by EMsnap — APPROVED** [review]

**Review by yunqingmoswu — APPROVED** [review]
