### PR TITLE
[INLONG-7855][Sort] Fix Sort hang up reader in snapshot phase when reducing parallelism

### LINKED ISSUE #7855: [Bug][Sort] Hang up reader in snapshot phase when reducing paralleism
### What happened

This bug happends when:
1、sort task runs in multi paralleism
2、sort task running in snapshot phase running mysql cdc
3、stop job and reduce paralleism and restart 

the task will read one chunk and then read another one 
the log tells that a binlog client starts twice 
and then the second chunk won't be processed anymore 

image

### What you expected to happen

no hang up reader in snapshot phase when reducing paralleism

### How to reproduce

This bug happends when:
1、sort task runs in multi paralleism
2、sort task running in snapshot phase running mysql cdc
3、stop job and reduce paralleism and restart 

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Sort

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by EMsnap**
### Prepare a Pull Request
- Fixes #7855 

### Motivation

 Fix Sort hang up reader in snapshot phase when reducing parallelism

1、When a subtask receives two chunk splits to read;
2、The first chunk reads perfectly, and then it will start a BinlogClient to read the binlogs from lw to hw in chunk1. 
3、When the second chunk arrives the BinlogClient will be reused
4、So when reading chunk2 and start to read from lw to hw in chunk2, the binlog reader will be reused and the event listener in chunk1 will be reused also. So that the BINLOG_END event in chunk2 will never be received  

### Modifications

remove the eventListener in the formal chunk 

### Documentation

  - Does this pull request introduce a new feature? (no)

### CODE REVIEW

**Review by yunqingmoswu — APPROVED** [review]

**Review by healchow — APPROVED** [review]

File: inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/debezium/task/MySqlBinlogSplitReadTask.java [hunk 1]
```diff
@@ -88,6 +94,29 @@ public MySqlBinlogSplitReadTask(
     @Override
     public void execute(ChangeEventSourceContext context) throws InterruptedException {
         this.context = context;
+
+        /**
```
Comment (healchow) [inline inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/debezium/task/MySqlBinlogSplitReadTask.java:98]: Unsupported javadoc in the method.

**Review by dockerzhang — APPROVED** [review]

**Comment by dockerzhang** [comment]
Please run `spotless:apply` to fix the check style error.

**Review by yunqingmoswu — APPROVED** [review]

**Review by e-mhui — APPROVED** [review]

**Comment by EMsnap** [comment]
> Please run `spotless:apply` to fix the check style error.

done
