### PR TITLE
[INLONG-6353][Sort] Fix delete event handle error for doris connector

### LINKED ISSUE #6353: [Bug][Sort] Fix delete event handle error for doris connector
### What happened

Doris connector handle the delete event error with multiple sink scenario, it is that the data of source is a delete event, but it can not be delete in doris.

### What you expected to happen

Doris connector handle the delete event all right.

### How to reproduce

Write data of multiple database and tables with the doris connector can be reproduced.

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Sort

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by yunqingmoswu**
### Prepare a Pull Request
*(Change the title refer to the following example)*

Title: [INLONG-6353][Sort] Fix delete event handle error for doris connector

*(The following *XYZ* should be replaced by the actual [GitHub Issue](https://github.com/apache/inlong/issues) number)*

Fixes #6353

### Motivation

Fix delete event handle error for doris connector

### Modifications

1. Add delete event support in DorisDynamicSchemaOutputFormat. 

### Verifying this change

*(Please pick either of the following options)*

- [ ] This change is a trivial rework/code cleanup without any test coverage.

- [x] This change is already covered by existing tests, such as:
  *(please describe tests)*

- [ ] This change added tests and can be verified as follows:

  *(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a follow-up issue for adding the documentation

### CODE REVIEW

**Review by gong — APPROVED** [review]

File: inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/format/CanalJsonDynamicSchemaFormat.java [hunk 1]
```diff
@@ -113,6 +113,9 @@ public boolean extractDDLFlag(JsonNode data) {
     @Override
     public RowType extractSchema(JsonNode data, List<String> pkNames) {
         JsonNode schema = data.get(SCHEMA);
+        if (schema == null) {
+            throw new IllegalArgumentException(String.format("Error schema: %s.", data));
```
Comment (healchow) [inline inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/format/CanalJsonDynamicSchemaFormat.java:117]:
```suggestion
            throw new IllegalArgumentException(String.format("Not found schema from: %s", data));
```

File: inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/format/DebeziumJsonDynamicSchemaFormat.java [hunk 2]
```diff
@@ -224,6 +224,9 @@ public RowType extractSchema(JsonNode data, List<String> pkNames) {
             return extractSchemaFromExtractInfo(data, pkNames);
         } catch (IllegalArgumentException e) {
             JsonNode schema = data.get(SCHEMA);
+            if (schema == null) {
+                throw new IllegalArgumentException(String.format("Error schema: %s.", data));
```
Comment (healchow) [inline inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/format/DebeziumJsonDynamicSchemaFormat.java:228]:
```suggestion
                throw new IllegalArgumentException(String.format("Not found schema from: %s", data));
```

**Review by healchow — APPROVED** [review]

**Review by EMsnap — APPROVED** [review]

File: inlong-sort/sort-connectors/doris/src/main/java/org/apache/inlong/sort/doris/table/DorisDynamicSchemaOutputFormat.java [hunk 3]
```diff
@@ -277,6 +284,53 @@ private void addBatch(T row) throws IOException {
...
+            }
+        } catch (IllegalArgumentException e) {
+            LOG.warn("extract schema failed", e);
+            // Extract schema from physicalData
+            JsonNode first = physicalData.isArray() ? physicalData.get(0) : physicalData;
+            // Add column key when fieldNames is not empty
+            fieldNames = first.fieldNames();
+        }
+        if (fieldNames != null && fieldNames.hasNext()) {
+            StringBuilder sb = new StringBuilder();
```
Comment (EMsnap) [inline inlong-sort/sort-connectors/doris/src/main/java/org/apache/inlong/sort/doris/table/DorisDynamicSchemaOutputFormat.java:318]: a method for this logic to construct doris columns would be better
