### PR TITLE
[INLONG-4803][DataProxy] Add warn log when there is no mq info when start for the first time

### LINKED ISSUE #4803: [Bug][DataProxy] caught IllegalStateException: No pulsar server url specified
### What happened

image

### What you expected to happen

no exception

### How to reproduce

start dataproxy and see the log

### Environment

_No response_

### InLong version

1.2.0

### InLong Component

InLong DataProxy

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by dockerzhang**
### Prepare a Pull Request
*(Change the title refer to the following example)*

- Title Example: [INLONG-XYZ][Component] Title of the pull request

*(The following *XYZ* should be replaced by the actual [GitHub Issue](https://github.com/apache/inlong/issues) number)*

- Fixes #4803

### Motivation

*Explain here the context, and why you're making that change. What is the problem you're trying to solve?*

### Modifications

*Describe the modifications you've done.*

### Verifying this change

*(Please pick either of the following options)*

- [ ] This change is a trivial rework/code cleanup without any test coverage.

- [ ] This change is already covered by existing tests, such as:
  *(please describe tests)*

- [ ] This change added tests and can be verified as follows:

  *(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a follow-up issue for adding the documentation

### CODE REVIEW

File: inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/DataProxyController.java [hunk 1]
```diff
@@ -65,7 +65,7 @@ public Response<DataProxyConfig> getConfig(
             @RequestParam(required = true) String clusterName) {
         DataProxyConfig config = clusterService.getDataProxyConfig(clusterTag, clusterName);
         if (CollectionUtils.isEmpty(config.getMqClusterList()) || CollectionUtils.isEmpty(config.getTopicList())) {
-            return Response.fail("failed to get mq clusters or topics");
+            return Response.fail("Failed to get mq clusters or topics, make sure register mq to manager successfully");
```
Comment (healchow) [inline inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/DataProxyController.java:68]: It seems not necessary to change this, because the topic list also may be empty.
So, check whether the MQ clusters are empty in the DataProxy is enough.

Comment (dockerzhang) [reply inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/DataProxyController.java]: make the message more meaningful.

**Review by healchow — APPROVED** [review]

**Review by EMsnap — APPROVED** [review]
