### PR TITLE
[INLONG-6919][Audit] Fix bug that no exceptions are printed in the log

### LINKED ISSUE #6919: [Bug][Audit] No exceptions are printed in the log
### What happened

No exceptions are printed in the log. I don't know how to locate the specific cause of this error

image

### What you expected to happen

image

### How to reproduce

For example, when creating a task, the port occupies

### Environment

MacOS 12.6 

### InLong version

master

### InLong Component

InLong Audit

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by leosanqing**
### Prepare a Pull Request
*(Change the title refer to the following example)*

- Fixes #6919 

### Motivation
Fix bug that no exceptions are printed in the log
### Modifications
Log add exception info

### Verifying this change

*(Please pick either of the following options)*

- [x] This change is a trivial rework/code cleanup without any test coverage.

### Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a follow-up issue for adding the documentation

### CODE REVIEW

**Review by dockerzhang — APPROVED** [review]

**Review by doleyzi — APPROVED** [review]

File: inlong-audit/audit-proxy/src/main/java/org/apache/inlong/audit/source/SimpleTcpSource.java [hunk 1]
```diff
@@ -181,7 +181,7 @@ public synchronized void start() {
             }
         } catch (Exception e) {
             logger.error("Simple TCP Source error bind host {} port {},program will exit!", host,
```
Comment (healchow) [inline inlong-audit/audit-proxy/src/main/java/org/apache/inlong/audit/source/SimpleTcpSource.java:183]: There is something wrong with the log description, could you please modify it to:
```suggestion
            logger.error("Simple TCP Source bind {}:{} error, the program will exit!", host, port, e);
```

**Review by gosonzhang — APPROVED** [review]
+1

**Review by healchow — APPROVED** [review]
