### PR TITLE
[INLONG-6409][Sort] Unspported Time and Timestamp iceberg auto create table in spark session query

### LINKED ISSUE #6409: [Bug][Sort] Unspported `Time` and `Timestamp` iceberg auto create table in spark session query
### What happened

Unspported `Time` and `Timestamp` iceberg auto create table in spark session query

### What you expected to happen

`Time` and `Timestamp` data type in iceberg can be supported read by  spark 

### How to reproduce

none

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Sort

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by thesumery**
[INLONG-6409][Sort] Bugfix:unspported Time and Timestamp iceberg auto create table in spark session query

### Prepare a Pull Request
*(Change the title refer to the following example)*

- [INLONG-6409][Sort] Bugfix:unspported Time and Timestamp iceberg auto create table in spark session query
- Fixes #6409 

### Motivation

*Spported Time and Timestamp iceberg auto create table in spark session query*

### Modifications

*convert time to string and timestamp to timestamp with local zone.*

### CODE REVIEW

File: inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/Constants.java [hunk 1]
```diff
@@ -163,4 +163,11 @@ public final class Constants {
                     .booleanType()
                     .defaultValue(true)
                     .withDescription("Whether ignore the single table erros when multiple sink writing scenario.");
+
+    public static final ConfigOption<Boolean> SINK_MULTIPLE_TYPE_MAP_SPARK_ENGINE_ENABLE =
+            ConfigOptions.key("sink.multiple.typemap.spark.engine.enable")
```
Comment (yunqingmoswu) [inline inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/Constants.java:168]: Maybe it is better to call 'sink.multiple.typemap-compatible-with-spark'?

File: inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/format/DebeziumJsonDynamicSchemaFormat.java [hunk 2]
```diff
@@ -289,16 +281,6 @@ public List<RowData> extractRowData(JsonNode data, RowType rowType) {
         return extractRowData(payload, rowType);
     }
 
-    /**
-     * Get the identifier of this dynamic schema format
-     *
-     * @return The identifier of this dynamic schema format
-     */
-    @Override
-    public String identifier() {
```
Comment (yunqingmoswu) [inline inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/format/DebeziumJsonDynamicSchemaFormat.java:298]: Maybe it is better to keep the  'identifier()'?

File: inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/format/DebeziumJsonDynamicSchemaFormat.java [hunk 3]
```diff
@@ -44,7 +44,6 @@
  */
 public class DebeziumJsonDynamicSchemaFormat extends JsonDynamicSchemaFormat {
 
-    private static final String IDENTIFIER = "debezium-json";
```
Comment (yunqingmoswu) [inline inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/format/DebeziumJsonDynamicSchemaFormat.java:47]: Maybe it is better to keep the 'IDENTIFIER'?

Comment (thesumery) [reply inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/format/DebeziumJsonDynamicSchemaFormat.java:47]: 'IDENTIFIER' is used for distinguish different DynamicSchemaFormat，but 'map<String, ?>'  keys can achieve the same goal. Here if want to keep 'IDENTIFIER', must modify getIdentifier to static function because it is private.

**Review by yunqingmoswu — APPROVED** [review]
LGTM

File: inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/Constants.java [hunk 4]
```diff
@@ -163,4 +163,11 @@ public final class Constants {
                     .booleanType()
                     .defaultValue(true)
                     .withDescription("Whether ignore the single table erros when multiple sink writing scenario.");
+
+    public static final ConfigOption<Boolean> SINK_MULTIPLE_TYPE_MAP_COMPATIBLE_WITH_SPARK =
+            ConfigOptions.key("sink.multiple.typemap-compatible-with-spark")
+                    .booleanType()
+                    .defaultValue(false)
+                    .withDescription("Because spark do not support iceberg data type: `timestamp without time zone` and"
+                            + "`time`, so type conversions must be mapped to types supported by spark.");
```
Comment (EMsnap) [inline inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/Constants.java:172]: maped to string ?

**Review by EMsnap — APPROVED** [review]

File: inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/Constants.java (hunk 4 above)
Comment (EMsnap) [reply inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/Constants.java:172]: I guess it's nessasary to mention the conversion explicitly like datetime to varchar

**Comment by thesumery** [comment]
Wait to merge

**Review by dockerzhang — APPROVED** [review]
