### PR TITLE
[INLONG-11897][Dashboard] Clicking the audit page query will call this interface multiple times

### LINKED ISSUE #11897: [Bug][Dashboard] Click on the audit page to query multiple calls to the interface
### What happened

Click on the audit page to query multiple calls to the interface

### What you expected to happen

Clicking the query button will only call once

### How to reproduce

Remove manual call

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Dashboard

### Are you willing to submit PR?

- [x] Yes, I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by wohainilaodou**
…alls to the interface

Fixes #11897 

### Motivation

Clicking the audit page query will call this interface multiple times

### Modifications

Clicking the audit page query will call this interface multiple times

### Verifying this change

before: Click on the audit page to query multiple calls to the interface
image
after: Click on the audit page to query once calls to the interface
image

### CODE REVIEW

File: inlong-dashboard/src/ui/pages/GroupDetail/Audit/config.tsx [hunk 1]
```diff
@@ -405,7 +386,7 @@ export const getFormContent = (
       },
       {
         type: 'select',
-        label: i18n.t('pages.GroupDetail.SinkType'),
+        label: 'sink类型',
```
Comment (dockerzhang) [inline inlong-dashboard/src/ui/pages/GroupDetail/Audit/config.tsx:389]:
```suggestion
        label: 'Sink 类型',
```
