### PR TITLE
[INLONG-5963][Audit] Solve the sdk memory leak problem

### LINKED ISSUE #5963: [Bug][Audit] Solve the sdk memory leak problem
### What happened

The audit-sdk  cause a memory leak problem

### What you expected to happen

This problem can cause a memory leak

### How to reproduce

企业微信截图_e7a56cc5-65e7-45f5-b705-2a6e616033f2

### Environment

_No response_

### InLong version

1.3.0

### InLong Component

InLong Audit

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by doleyzi**
### Prepare a Pull Request

- Fixes #5963

### Motivation

*release the allocated memory*

### Modifications

*Solve the sdk memory leak problem.*

### Verifying this change

*(Please pick either of the following options)*

- [ ] This change is a trivial rework/code cleanup without any test coverage.

- [ ] This change is already covered by existing tests, such as:
  *(please describe tests)*

- [ ] This change added tests and can be verified as follows:

  *(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a follow-up issue for adding the documentation

### CODE REVIEW

File: inlong-audit/audit-sdk/src/main/java/org/apache/inlong/audit/send/SenderGroup.java [hunk 1]
```diff
@@ -110,6 +110,7 @@ public SenderResult send(ByteBuf dataBuf) {
             }
             if (channel == null) {
                 logger.error("can not get a channel");
+                dataBuf.release();
```
Comment (baomingyu) [inline inlong-audit/audit-sdk/src/main/java/org/apache/inlong/audit/send/SenderGroup.java:113]: here need release too
if (channels.size() <= 0) {
                logger.error("channels is empty");
                return new SenderResult("channels is empty", 0, false);
            }

**Review by baomingyu — CHANGES_REQUESTED** [review]

**Review by dockerzhang — APPROVED** [review]

**Review by baomingyu — APPROVED** [review]
+1

**Review by pocozh — APPROVED** [review]
