### PR TITLE
[INLONG-7473][Manager] Fix StreamSource in the TO_BE_ISSUED_DELETE state cannot be issued properly

### LINKED ISSUE #7473: [Bug][Manager] StreamSource in the TO_BE_ISSUED_DELETE state cannot be issued properly
### What happened

StreamSource in the TO_BE_ISSUED_DELETE state cannot be issued properly.
企业微信截图_fcc3e2e3-2a00-4e74-be92-3b148f86a4ad

### What you expected to happen

StreamSource in the TO_BE_ISSUED_DELETE state cannot be issued properly.

### How to reproduce

Delete the InlongGroup when you delete the streamSource.

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by fuweng11**
### Prepare a Pull Request

- Fixes #7473 

### Motivation

Fix StreamSource in the TO_BE_ISSUED_DELETE state cannot be issued properly.

### Modifications

Fix StreamSource in the TO_BE_ISSUED_DELETE state cannot be issued properly.

### CODE REVIEW

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java [hunk 1]
```diff
@@ -471,70 +471,68 @@ private DataConfig getDataConfig(StreamSourceEntity entity, int op) {
...
+                    topicConfig.setTopic(topic);
+                    dataConfig.setTopicInfo(topicConfig);
+                } else if (MQType.TUBEMQ.equals(mqType)) {
+                    DataProxyTopicInfo topicConfig = new DataProxyTopicInfo();
+                    topicConfig.setInlongGroupId(groupId);
+                    topicConfig.setTopic(mqResource);
+                    dataConfig.setTopicInfo(topicConfig);
+                }
+            } else {
+                dataConfig.setSyncSend(0);
```
Comment (healchow) [inline inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java:534]: Why set the syncSend=0 when inlong_group or inlong_stream was null?

Comment (fuweng11) [reply inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java]: This set to 0 was unnecessary, I remove it.

**Review by healchow — APPROVED** [review]

**Review by dockerzhang — APPROVED** [review]
