### PR TITLE
[INLONG-7981][Manager] Failed to stop source correctly when suspend a group

### LINKED ISSUE #7981: [Bug][Manager] Failed to stop source correctly when suspend a group
### What happened

Failed to stop source correctly when suspend a group.
A task was generated when an agent was added to a `SUSPENDED` group.

### What you expected to happen

Success to stop source correctly when suspend a group.
No task was generated when an agent was added to a `SUSPENDED` group.

### How to reproduce

Suspend group.

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by fuweng11**
### Prepare a Pull Request
- Fixes #7981 

### Motivation
Fix the following issues:

1.Failed to stop source correctly when suspend a group.
2.A task was generated when an agent was added to a SUSPENDED group.

### CODE REVIEW

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java [hunk 1]
```diff
@@ -337,6 +337,11 @@ private void preProcessTemplateFileTask(TaskRequest taskRequest) {
         List<StreamSourceEntity> sourceEntities = sourceMapper.selectTemplateSourceByCluster(needCopiedStatusList,
                 Lists.newArrayList(SourceType.FILE), agentClusterName);
         sourceEntities.forEach(sourceEntity -> {
+            InlongGroupEntity groupEntity = groupMapper.selectByGroupId(sourceEntity.getInlongGroupId());
+            Set<GroupStatus> noNeedAddTask = Sets.newHashSet(GroupStatus.SUSPENDED, GroupStatus.SUSPENDING);
```
Comment (vernedeng) [inline inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java:341]: Why no put **_noNeedAddTask_** outside the loop?

**Review by vernedeng — CHANGES_REQUESTED** [review]

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java (hunk 1 above)
Comment (fuweng11) [reply inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java:341]: Because `inlongGroupId` may be different in `sourceEntities`.

**Review by vernedeng — APPROVED** [review]
LGTM

**Review by dockerzhang — APPROVED** [review]
