### PR TITLE
[INLONG-5698][Manager] Fixed the DataProxy cluster tag was restored after the manager was restarted

### LINKED ISSUE #5698: [Bug][Manager] The DataProxy cluster tag was restored after restarting the manager
### What happened

Dataproxy cluster name (default)_ Dataproxy, the default tag is default_ Cluster, change its tag to test and restart the inlong manager. At this time, the dataproxy cluster tag is restored to default_ cluster

### What you expected to happen

After restart, the cluster information in Manger will not be modified by the reported information.

### How to reproduce

Modify the cluster label of the default dataproxy, and then restart the manager

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by fuweng11**
### Prepare a Pull Request
- Fixes #5698 

### Motivation

Make sure the dataproxy cluster tag was not restored to the default after the manager was restarted.

### Modifications

After receiving the cluster heartbeat information, if there is a cluster with the same name, the information will not be modified.

### Verifying this change

- [X] This change is a trivial rework/code cleanup without any test coverage.

- [ ] This change is already covered by existing tests, such as:
  *(please describe tests)*

- [ ] This change added tests and can be verified as follows:

### Documentation

  - Does this pull request introduce a new feature? (no)

### CODE REVIEW

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/heartbeat/HeartbeatManager.java [hunk 1]
```diff
@@ -158,12 +157,11 @@ private ClusterInfo fetchCluster(ComponentHeartbeat componentHeartbeat) {
         final String clusterName = componentHeartbeat.getClusterName();
         final String type = componentHeartbeat.getComponentType();
         final String clusterTag = componentHeartbeat.getClusterTag();
-        List<InlongClusterEntity> entities = clusterMapper.selectByKey(clusterTag, clusterName, type);
-        if (CollectionUtils.isNotEmpty(entities)) {
+        InlongClusterEntity entity = clusterMapper.selectByNameAndType(clusterName, type);
+        if (!Objects.isNull(entity)) {
```
Comment (healchow) [inline inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/heartbeat/HeartbeatManager.java:161]: Just call `if (null != entity)`.

**Review by healchow — APPROVED** [review]

**Comment by woofyzhao** [comment]
suggest searching for similar code snippets  in case there are more like this

**Review by woofyzhao — APPROVED** [review]

**Review by dockerzhang — APPROVED** [review]
