### PR TITLE
[INLONG-6517][Manager] Support delete stream sink when the inlong group was config_failed

### LINKED ISSUE #6517: [Bug][Manager] Failed to delete stream sink when the inlong group was config_failed
### What happened

Delete a stream sink failed:

### What you expected to happen

Should support delete stream sinks when inlong group status was in config_failed.

### How to reproduce

-

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by healchow**
### Prepare a Pull Request

- Fixes #6517

### Motivation

Support delete stream sink when the inlong group was config_failed.

### Verifying this change

- [x] This change is a trivial rework/code cleanup without any test coverage.

### CODE REVIEW

**Review by woofyzhao — APPROVED** [review]

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupServiceImpl.java [hunk 1]
```diff
@@ -465,7 +465,7 @@ public Boolean delete(String groupId, String operator) {
         // logically delete the associated extension info
         groupExtMapper.logicDeleteAllByGroupId(groupId);
 
-        if (GroupStatus.allowedLogicDelete(GroupStatus.forCode(entity.getStatus()))) {
+        if (GroupStatus.notAllowedDelete(GroupStatus.forCode(entity.getStatus()))) {
             streamService.logicDeleteAll(groupId, operator);
```
Comment (gong) [inline inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupServiceImpl.java:469]: Maybe, `GroupStatus.notAllowedDelete(GroupStatus.forCode(entity.getStatus()))`  modify to `!GroupStatus.notAllowedDelete(GroupStatus.forCode(entity.getStatus()))`

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupServiceImpl.java [hunk 2]
```diff
@@ -435,7 +435,7 @@ public InlongGroupInfo doDeleteCheck(String groupId, String operator) {
 
         // If the status allowed logic delete, all associated info will be logically deleted.
         // In other status, you need to delete the related "inlong_stream" first.
-        if (!GroupStatus.allowedLogicDelete(curState)) {
+        if (!GroupStatus.notAllowedDelete(curState)) {
             int count = streamService.selectCountByGroupId(groupId);
```
Comment (gong) [inline inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupServiceImpl.java:439]: Maybe, `!GroupStatus.notAllowedDelete(curState)` modify to `GroupStatus.notAllowedDelete(curState)`

Comment (healchow) [reply inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupServiceImpl.java:439]: When the inlong group supports the delete operate, we should check whether there are undeleted streams.

**Review by fuweng11 — APPROVED** [review]

File: inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/GroupStatus.java [hunk 3]
```diff
@@ -117,40 +115,55 @@ public static boolean notAllowedUpdate(GroupStatus status) {
...
     }
 
     /**
      * Temporary group status, adding, deleting and modifying operations are not allowed
      */
     public static boolean isTempStatus(GroupStatus status) {
-        return status == TO_BE_APPROVAL || status == CONFIG_ING;
+        return status == TO_BE_APPROVAL || status == CONFIG_ING
+                || status == SUSPENDING || status == RESTARTING
+                ;
```
Comment (fuweng11) [inline inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/GroupStatus.java:166]: Comma does not need to start on a new line.

Comment (fuweng11) [reply inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/GroupStatus.java:166]: Whether the temporary status needs to be added `DELETING`.

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupServiceImpl.java (hunk 1 above)
Comment (healchow) [reply inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupServiceImpl.java]: Fixed.

File: inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/GroupStatus.java (hunk 3 above)
Comment (healchow) [reply inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/GroupStatus.java:166]: Done, thanks.

**Review by vernedeng — APPROVED** [review]

File: inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/SimpleGroupStatus.java [hunk 4]
```diff
@@ -36,7 +36,6 @@ public enum SimpleGroupStatus {
     public static SimpleGroupStatus parseStatusByCode(int code) {
         GroupStatus groupStatus = GroupStatus.forCode(code);
         switch (groupStatus) {
-            case DRAFT:
```
Comment (gong) [inline inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/SimpleGroupStatus.java:39]: why to delete it?

Comment (healchow) [reply inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/SimpleGroupStatus.java:39]: Because this status is not used anywhere.

**Review by gong — APPROVED** [review]
