### PR TITLE
[INLONG-9222][Manager] SortStandalone configuration support multiple tags

### LINKED ISSUE #9222: [Bug][Manager] When cluster have multiple cluster tag,manager return wrong metadata info
### What happened

If the pulsar or tube  cluster has multiple cluster tags, sort standalone can get wrong metadata info.
image

### What you expected to happen

1、manager return correct metadata info

### How to reproduce

1、create a pulsar cluster
2、 assigned two cluster tag for the pulsar cluster
3、run a sort standalone  task

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by vernedeng**
### Prepare a Pull Request
*(Change the title refer to the following example)*

- Title Example: [INLONG-XYZ][Component] Title of the pull request

*(The following *XYZ* should be replaced by the actual [GitHub Issue](https://github.com/apache/inlong/issues) number)*

- Fixes #9222 

### Motivation

*Explain here the context, and why you're making that change. What is the problem you're trying to solve?*

### Modifications

*Describe the modifications you've done.*

### Verifying this change

*(Please pick either of the following options)*

- [ ] This change is a trivial rework/code cleanup without any test coverage.

- [ ] This change is already covered by existing tests, such as:
  *(please describe tests)*

- [ ] This change added tests and can be verified as follows:

  *(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a follow-up issue for adding the documentation

### CODE REVIEW

File: inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/standalone/SortSourceClusterInfo.java [hunk 1]
```diff
@@ -46,9 +50,17 @@ public class SortSourceClusterInfo {
     String clusterTags;
     String extTag;
     String extParams;
+    Set<String> clusterTagsSet;
     Map<String, String> extTagMap = new ConcurrentHashMap<>();
     Map<String, String> extParamsMap = new ConcurrentHashMap<>();
 
+    public Set<String> getClusterTagsSet() {
+        if (CollectionUtils.isEmpty(clusterTagsSet)) {
+            clusterTagsSet = ImmutableSet.copyOf(clusterTags.split(","));
```
Comment (fuweng11) [inline inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/standalone/SortSourceClusterInfo.java:59]: `InlongConstants.COMMA`

Comment (vernedeng) [reply inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/standalone/SortSourceClusterInfo.java]: fixed, thx

**Review by fuweng11 — APPROVED** [review]

**Review by dockerzhang — APPROVED** [review]
