### PR TITLE
[INLONG-5712][Sort] Fix class not found in Elasticsearch 6 connector for producting

### LINKED ISSUE #5712: [Bug][Sort] Fix class not found in Elasticsearch 6 connector for producting
### Description

Fix class not found in Elasticsearch 6 connector for producting

### InLong Component

InLong Sort

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Oneal65**
- Fixes #5712 

### Motivation

Fix class not found in Elasticsearch 6 connector for producting

### Modifications

modify some poms and add test

### CODE REVIEW

**Review by gong — APPROVED** [review]

File: inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/ElasticsearchSqlParseTest.java [hunk 1]
```diff
@@ -59,7 +58,7 @@ private MySqlExtractNode buildMysqlExtractNode() {
             true, null);
     }
 
-    private ElasticsearchLoadNode buildElasticsearchLoadNode() {
+    ElasticsearchLoadNode buildElasticsearchLoadNode(int i) {
```
Comment (healchow) [inline inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/ElasticsearchSqlParseTest.java:61]: The parameter `i` is not understood easily.

Comment (Oneal65) [reply inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/ElasticsearchSqlParseTest.java:61]: OK, I will modify it. it means version number

**Review by yunqingmoswu — APPROVED** [review]

**Review by dockerzhang — APPROVED** [review]

**Review by healchow — APPROVED** [review]
