### PR TITLE
[INLONG-5675][Agent] Support custom fixed ip for Agent

### LINKED ISSUE #5675: [Improve][Agent] Support custom fixed ip for Agent
### Description

_No response_

### InLong Component

InLong Agent

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by GanfengTan**
Support custom fixed ip for Agent.
For example:
Ip has to fixed in the k8s.

- Fixes #5675 

### Motivation

Add config information.

### Modifications
No message.

### Verifying this change

*(Please pick either of the following options)*

- [x] This change is a trivial rework/code cleanup without any test coverage.

- [ ] This change is already covered by existing tests, such as:
  *(please describe tests)*

- [ ] This change added tests and can be verified as follows:

### CODE REVIEW

**Review by EMsnap — APPROVED** [review]

File: inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/utils/AgentUtils.java [hunk 1]
```diff
@@ -348,6 +349,10 @@ public static String getmValue(String addictiveAttr) {
      * Check agent ip from manager
      */
     public static String fetchLocalIp() {
+        if (AgentConfiguration.getAgentConf().hasKey(CUSTOM_FIXED_IP) && StringUtils
```
Comment (healchow) [inline inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/utils/AgentUtils.java:352]: Suggested changing to:
```
if (AgentConfiguration.getAgentConf().hasKey(CUSTOM_FIXED_IP) 
        && StringUtils.isNoneBlank(AgentConfiguration.getAgentConf().get(CUSTOM_FIXED_IP))) {

```

Comment (GanfengTan) [reply inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/utils/AgentUtils.java]: done

**Review by dockerzhang — APPROVED** [review]
