### PR TITLE
[INLONG-8244][Agent] Fix the thread leaks after job finished

### LINKED ISSUE #8244: [Bug][Agent]thread leaks after job finished
### What happened

thread leaks after job finished

### What you expected to happen

thread shut down after job finished

### How to reproduce

fix the bug

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Agent

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by justinwwhuang**
### Prepare a Pull Request
*fix the bug that thread leaks after job finished*
- Fixes #8244 

### Motivation

*fix the bug that thread leaks after job finished*

### Modifications

*fix the bug that thread leaks from direction trigger after job finished*

### Verifying this change

*(Please pick either of the following options)*

- [ ] This change is a trivial rework/code cleanup without any test coverage.

- [ ] This change is already covered by existing tests, such as:
  *(please describe tests)*

- [ ] This change added tests and can be verified as follows:

  *(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a follow-up issue for adding the documentation

### CODE REVIEW

**Review by doleyzi — APPROVED** [review]

**Review by dockerzhang — APPROVED** [review]

File: inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/file/TriggerFileReader.java [hunk 1]
```diff
@@ -31,6 +31,8 @@ public class TriggerFileReader implements Reader {
     @NotNull
     private String triggerId;
 
+    public volatile boolean finished = false;
```
Comment (healchow) [inline inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/file/TriggerFileReader.java:34]: Does this varible need `public` scope?

**Review by healchow — CHANGES_REQUESTED** [review]

**Review by aloyszhang — APPROVED** [review]

File: inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/file/TriggerFileReader.java (hunk 1 above)
Comment (justinwwhuang) [reply inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/file/TriggerFileReader.java]: no need, fix it

**Review by healchow — APPROVED** [review]

**Review by pocozh — APPROVED** [review]
