### PR TITLE
[INLONG-6047][Agent] Fix file could not be matched in the k8s

### LINKED ISSUE #6047: [Bug][Agent] File could not be matched in the k8s
### What happened

The standard output file could not match.

### What you expected to happen

The standard output file matches and gets the metadata.

### How to reproduce

No 

### Environment

_No response_

### InLong version

1.3.0

### InLong Component

InLong Agent

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by GanfengTan**
Fix file could not be matched in the k8s.
 Add a Regular Expression.
- Fixes #6047 

### Motivation
The file name in the soft link path must be matched with the regular.

### Modifications

Add a util

### Verifying this change

*(Please pick either of the following options)*

- [x] This change is a trivial rework/code cleanup without any test coverage.

- [ ] This change is already covered by existing tests, such as:
  *(please describe tests)*

- [ ] This change added tests and can be verified as follows:

### CODE REVIEW

File: inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/utils/MetaDataUtils.java [hunk 1]
```diff
@@ -47,16 +49,17 @@ public class MetaDataUtils {
...
-    private static final String STANDARD_OUT = "/var/log/containers";
+    private static final String FILE_NAME_PATTERN = "(^[-a-zA-Z0-9]+)_([a-zA-Z0-9-]+)_([a-zA-Z0-9-]+)(.log)";
 
     /**
      * standard log for k8s
      *
      * get pod_name,namespace,container_name,container_id
      */
     public static Map<String, String> getLogInfo(String fileName) {
+        Matcher matcher = Pattern.compile(FILE_NAME_PATTERN).matcher(fileName);
```
Comment (healchow) [inline inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/utils/MetaDataUtils.java:60]: Suggested extracting the `Pattern.compile` to a static final field, it is more efficient.

File: inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/file/KubernetesFileReader.java [hunk 2]
```diff
@@ -115,7 +115,7 @@ public Map<String, String> getK8sMetadata(JobProfile jobConf) {
             return null;
         }
         Map<String, String> k8sInfo = MetaDataUtils.getLogInfo(fileReaderOperator.file.getName());
-        log.info("k8s information size:{}", k8sInfo.size());
+        log.info("file name is:{},k8s information size:{}", fileReaderOperator.file.getName(), k8sInfo.size());
```
Comment (healchow) [inline inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/file/KubernetesFileReader.java:118]:
```suggestion
        log.info("file name is: {}, k8s information size: {}", fileReaderOperator.file.getName(), k8sInfo.size());
```

File: inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/utils/MetaDataUtils.java (hunk 1 above)
Comment (GanfengTan) [reply inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/utils/MetaDataUtils.java]: done

File: inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/file/KubernetesFileReader.java (hunk 2 above)
Comment (GanfengTan) [reply inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/file/KubernetesFileReader.java]: done

**Review by healchow — APPROVED** [review]
+1

**Review by EMsnap — APPROVED** [review]
