### PR TITLE
[INLONG-7557][Sort] Fix class incompatible error between elasticsearch6 with elasticsearch7

### LINKED ISSUE #7557: [Bug][Sort] Fix class incompatible error between elasticsearch6 with elasticsearch7
### What happened

it encounters a class incompatible error when dirty data archiving is enabled.
image

### What you expected to happen

it's exactly right when dirty data archiving is enabled.

### How to reproduce

It can reproduce by the follow code:
```
CREATE TABLE `table_input`(
    PRIMARY KEY (`a`) NOT ENFORCED,
    `database_wedata_di` STRING METADATA FROM 'meta.database_name' VIRTUAL,
    `table_wedata_di` STRING METADATA FROM 'meta.table_name' VIRTUAL,
    `type_wedata_di` STRING METADATA FROM 'meta.op_type' VIRTUAL,
    `ts_wedata_di` TIMESTAMP_LTZ(3) METADATA FROM 'meta.op_ts' VIRTUAL,
    `processing_time_wedata_di` AS PROCTIME(),
    `a` INT,
    `b` STRING,
    `c` STRING,
    `PROCESS_TIME` AS PROCTIME())
    WITH (
    'debezium.snapshot.locking.mode' = 'none',
    'scan.startup.mode' = 'initial',
    'debezium.binary.handling.mode' = 'base64',
    'inlong.metric.labels' = 'groupId=1&streamId=1&nodeId=1',
    'connector' = 'mysql-cdc-inlong',
    'hostname' = 'localhost',
    'database-name' = 'test_db',
    'port' = '3306',
    'scan.incremental.snapshot.enabled' = 'true',
    'server-time-zone' = 'Asia/Shanghai',
    'username' = 'root',
    'password' = 'password',
    'table-name' = 'test_db.mysql_dirtydata_source'
);
CREATE TABLE `table_output`(
    `a` INT,
    `b` STRING,
    `c` STRING)
    WITH (
    'dirty.side-output.field-delimiter' = ',',
    'dirty.side-output.s3.region' = 'ap-beijing',
    'dirty.side-output.log-tag' = 'DirtyData',
    'dirty.side-output.log.enable' = 'true',
    'dirty.ignore' = 'true',
    'dirty.side-output.s3.secret-key-id' = 'secretkeyid',
    'dirty.side-output.s3.endpoint' = 's3.endpoint',
    'dirty.side-output.s3.access-key-id' = 'secretaccesskeyid',
    'dirty.side-output.format' = 'csv',
    'dirty.identifier' = 'DirtyData',
    'failure-handler' = 'ignore',
    'dirty.side-output.enable' = 'true',
    'dirty.side-output.line-delimiter' = '\n',
    'dirty.side-output.s3.bucket' = 's3bucket',
    'dirty.side-output.labels' = '[SYSTEM_TIME=${SYSTEM_TIME}][index_es]',
    'dirty.side-output.connector' = 's3',
    'dirty.side-output.s3.key' = 'index_es',
    'inlong.metric.labels' = 'groupId=1&streamId=1&nodeId=2',
    'connector' = 'elasticsearch-7-inlong',
    'hosts' = 'http://localhost:9200',
    'index' = 'index_es',
    'password' = 'password',
    'username' = 'elastic'
);
INSERT INTO `table_output`
    SELECT 
    `a` AS `a`,
    `b` AS `b`,
    `c` AS `c`
    FROM `table_input` ;
```

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Sort

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by yunqingmoswu**
### Prepare a Pull Request
*(Change the title refer to the following example)*

Title Example: [INLONG-7557][Sort] Fix class incompatible error between elasticsearch6 with elasticsearch7

*(The following *XYZ* should be replaced by the actual [GitHub Issue](https://github.com/apache/inlong/issues) number)*

- Fixes #7557 

### Motivation

Fix class incompatible error between elasticsearch6 with elasticsearch7 when dirty data archiving is enabled.

### Modifications

1.Reconstruct elasticsearch-base and remove the dependency on elasticsearch6.
2.Reconstruct dirty data archiving, add a new DirtySinkFailureHandler to implement dirty data archiving.

### Verifying this change

*(Please pick either of the following options)*

- [x] This change is a trivial rework/code cleanup without any test coverage.

- [ ] This change is already covered by existing tests, such as:
  *(please describe tests)*

- [ ] This change added tests and can be verified as follows:

  *(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a follow-up issue for adding the documentation

### CODE REVIEW

File: inlong-sort/sort-connectors/elasticsearch-6/src/main/java/org/apache/inlong/sort/elasticsearch6/Elasticsearch6BulkProcessorIndexer.java [hunk 1]
```diff
@@ -53,32 +49,10 @@ class Elasticsearch6BulkProcessorIndexer implements RequestIndexer {
...
-    @Override
-    public void add(UpdateRequest... updateRequests) {
-        for (UpdateRequest updateRequest : updateRequests) {
-            if (flushOnCheckpoint) {
-                numPendingRequestsRef.getAndIncrement();
-            }
-            this.bulkProcessor.add(updateRequest);
+    public void add(DocWriteRequest<?> request) {
+        if (flushOnCheckpoint) {
+            numPendingRequestsRef.getAndIncrement();
```
Comment (gong) [inline inlong-sort/sort-connectors/elasticsearch-6/src/main/java/org/apache/inlong/sort/elasticsearch6/Elasticsearch6BulkProcessorIndexer.java:54]: Will remove `for` cause other problem?

Comment (yunqingmoswu) [reply inlong-sort/sort-connectors/elasticsearch-6/src/main/java/org/apache/inlong/sort/elasticsearch6/Elasticsearch6BulkProcessorIndexer.java:54]: > 

It is only a optimization for api call will not cause any problem.

File: inlong-sort/sort-connectors/elasticsearch-7/src/main/java/org/apache/inlong/sort/elasticsearch7/utils/DirtySinkFailureHandler.java [hunk 2]
```diff
@@ -0,0 +1,80 @@
...
+            if (request instanceof UpdateRequest) {
+                dirtyData = ((UpdateRequest) request).doc().source().utf8ToString();
+            } else if (request instanceof IndexRequest) {
+                dirtyData = ((IndexRequest) request).source().utf8ToString();
+            } else {
+                dirtyData = request.id();
+            }
+            LOGGER.error("Action request handle error", failure);
+            LOGGER.debug("The dirty data: {}", dirtyData);
+            dirtySinkHelper.invoke(dirtyData, DirtyType.DOCUMENT_PARSE_ERROR, failure);
```
Comment (gong) [inline inlong-sort/sort-connectors/elasticsearch-7/src/main/java/org/apache/inlong/sort/elasticsearch7/utils/DirtySinkFailureHandler.java:64]: Maybe add `dirtySinkHelper != null` judge

File: inlong-sort/sort-connectors/elasticsearch-6/src/main/java/org/apache/inlong/sort/elasticsearch6/utils/DirtySinkFailureHandler.java [hunk 3]
```diff
@@ -0,0 +1,80 @@
...
+            if (request instanceof UpdateRequest) {
+                dirtyData = ((UpdateRequest) request).doc().source().utf8ToString();
+            } else if (request instanceof IndexRequest) {
+                dirtyData = ((IndexRequest) request).source().utf8ToString();
+            } else {
+                dirtyData = request.id();
+            }
+            LOGGER.error("Action request handle error", failure);
+            LOGGER.debug("The dirty data: {}", dirtyData);
+            dirtySinkHelper.invoke(dirtyData, DirtyType.DOCUMENT_PARSE_ERROR, failure);
```
Comment (gong) [inline inlong-sort/sort-connectors/elasticsearch-6/src/main/java/org/apache/inlong/sort/elasticsearch6/utils/DirtySinkFailureHandler.java:64]: Maybe add `dirtySinkHelper != null` judge

File: inlong-sort/sort-connectors/elasticsearch-6/src/main/java/org/apache/inlong/sort/elasticsearch6/table/Elasticsearch6DynamicSinkFactory.java [hunk 4]
```diff
@@ -93,26 +92,27 @@ public class Elasticsearch6DynamicSinkFactory implements DynamicTableSinkFactory
                     INLONG_AUDIT)
```
Comment (EMsnap) [inline inlong-sort/sort-connectors/elasticsearch-6/src/main/java/org/apache/inlong/sort/elasticsearch6/table/Elasticsearch6DynamicSinkFactory.java:92]: add AUDIT_KEYS in  options

File: inlong-sort/sort-connectors/elasticsearch-7/src/main/java/org/apache/inlong/sort/elasticsearch7/table/Elasticsearch7Configuration.java [hunk 5]
```diff
@@ -68,4 +69,38 @@ private static HttpHost validateAndParseHostsString(String host) {
...
+                .map(Elasticsearch7Configuration::validateAndParseHostsString)
+                .collect(Collectors.toList());
+    }
+
+    @SuppressWarnings("unchecked")
+    public ActionRequestFailureHandler<DocWriteRequest<?>> getFailureHandler() {
+        final ActionRequestFailureHandler<DocWriteRequest<?>> failureHandler;
+        String value = config.get(FAILURE_HANDLER_OPTION);
+        switch (value.toUpperCase()) {
+            case "FAIL":
```
Comment (EMsnap) [inline inlong-sort/sort-connectors/elasticsearch-7/src/main/java/org/apache/inlong/sort/elasticsearch7/table/Elasticsearch7Configuration.java:84]: The value name should be Failure handling strategy not Failure handler option  , and the value should be a enum type

File: inlong-sort/sort-connectors/elasticsearch-7/src/main/java/org/apache/inlong/sort/elasticsearch7/table/Elasticsearch7Configuration.java [hunk 6]
```diff
@@ -68,4 +69,38 @@ private static HttpHost validateAndParseHostsString(String host) {
                     e);
         }
     }
+
+    public List<HttpHost> getHosts() {
+        return config.get(HOSTS_OPTION).stream()
```
Comment (EMsnap) [inline inlong-sort/sort-connectors/elasticsearch-7/src/main/java/org/apache/inlong/sort/elasticsearch7/table/Elasticsearch7Configuration.java:74]: npe here

File: inlong-sort/sort-connectors/elasticsearch-7/src/main/java/org/apache/inlong/sort/elasticsearch7/utils/DirtySinkFailureHandler.java (hunk 2 above)
Comment (yunqingmoswu) [reply inlong-sort/sort-connectors/elasticsearch-7/src/main/java/org/apache/inlong/sort/elasticsearch7/utils/DirtySinkFailureHandler.java:64]: It's not necessary because the 'dirtySinkHelper' cannot be null.
image

File: inlong-sort/sort-connectors/elasticsearch-7/src/main/java/org/apache/inlong/sort/elasticsearch7/table/Elasticsearch7Configuration.java (hunk 6 above)
Comment (yunqingmoswu) [reply inlong-sort/sort-connectors/elasticsearch-7/src/main/java/org/apache/inlong/sort/elasticsearch7/table/Elasticsearch7Configuration.java:74]: It will not cause npe, because the 'HOST_OPTION' is a required option and valid before.
image

File: inlong-sort/sort-connectors/elasticsearch-7/src/main/java/org/apache/inlong/sort/elasticsearch7/table/Elasticsearch7Configuration.java (hunk 5 above)
Comment (yunqingmoswu) [reply inlong-sort/sort-connectors/elasticsearch-7/src/main/java/org/apache/inlong/sort/elasticsearch7/table/Elasticsearch7Configuration.java:84]: It is same as the origin handle in flink's elasticsearch connector.

File: inlong-sort/sort-connectors/elasticsearch-6/src/main/java/org/apache/inlong/sort/elasticsearch6/table/Elasticsearch6DynamicSinkFactory.java (hunk 4 above)
Comment (yunqingmoswu) [reply inlong-sort/sort-connectors/elasticsearch-6/src/main/java/org/apache/inlong/sort/elasticsearch6/table/Elasticsearch6DynamicSinkFactory.java]: done

**Review by EMsnap — APPROVED** [review]

**Review by gong — APPROVED** [review]

**Comment by dockerzhang** [comment]
@yunqingmoswu please update the license file and documents if needed.

**Review by healchow — APPROVED** [review]

**Comment by yunqingmoswu** [comment]
> done

**Review by dockerzhang — APPROVED** [review]
