### PR TITLE
[INLONG-6410][Manager] Ensure that the additional parameters of group and stream can be saved

### LINKED ISSUE #6410: [Bug][Manager] The extension parameters of group and stream cannot be saved to ext_params
### What happened

 The extension parameters of group and stream cannot be saved to ext_params

### What you expected to happen

 The extension parameters of group and stream can be saved to ext_ params

### How to reproduce

Add additional parameters and save the group.

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by fuweng11**
### Prepare a Pull Request

- Fixes #6410 

### Motivation

Ensure that the additional parameters of group and stream can be saved
### Modifications
`InlongGroupDTO` extends `BasegInlongGroup`
Ensure that the additional parameters of group and stream can be saved
### Verifying this change

- [X] This change is a trivial rework/code cleanup without any test coverage.

- [ ] This change is already covered by existing tests, such as:
  *(please describe tests)*

- [ ] This change added tests and can be verified as follows:

### Documentation

  - Does this pull request introduce a new feature? (no)

### CODE REVIEW

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupOperator4TubeMQ.java [hunk 1]
```diff
@@ -61,15 +63,25 @@ public InlongTubeMQInfo getFromEntity(InlongGroupEntity entity) {
...
     protected void setTargetEntity(InlongGroupRequest request, InlongGroupEntity targetEntity) {
-        LOGGER.info("do nothing for inlong group with TubeMQ");
+        InlongTubeMQRequest tubeMQRequest = (InlongTubeMQRequest) request;
+        try {
+            InlongTubeMQDTO dto = InlongTubeMQDTO.getFromRequest(tubeMQRequest);
+            targetEntity.setExtParams(objectMapper.writeValueAsString(dto));
+        } catch (Exception e) {
+            throw new BusinessException(ErrorCodeEnum.SOURCE_INFO_INCORRECT.getMessage() + ": " + e.getMessage());
+        }
+        LOGGER.info("success set entity for inlong group with TubeMQ");
```
Comment (healchow) [inline inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupOperator4TubeMQ.java:84]: Not necessary to add this info log, just remove it.

File: inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/consume/BaseInlongConsume.java [hunk 2]
```diff
@@ -0,0 +1,34 @@
...
+ * The base parameter class of InlongGroup, support user extend their own business params.
+ */
+@Data
+@AllArgsConstructor
+@ApiModel("Base info of inlong group")
+public class BaseInlongConsume {
+
+    // you can add extend parameters in this class
+
+}
```
Comment (healchow) [inline inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/consume/BaseInlongConsume.java:34]: Suggest adding one blank line after the end of `}`, then it will not appear this:

image

**Review by healchow — APPROVED** [review]
LGTM

**Review by woofyzhao — APPROVED** [review]

**Review by ciscozhou — APPROVED** [review]

File: inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/consume/BaseInlongConsume.java [hunk 3]
```diff
@@ -0,0 +1,34 @@
...
+
+package org.apache.inlong.manager.pojo.consume;
+
+import io.swagger.annotations.ApiModel;
+import lombok.AllArgsConstructor;
+import lombok.Data;
+
+/**
+ * The base parameter class of InlongGroup, support user extend their own business params.
+ */
```
Comment (gong) [inline inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/consume/BaseInlongConsume.java:26]: Maybe,`The base parameter class of InlongGroup` decription is error, `InlongGroup` should be modified to`InlongConsume`.

**Review by gong — APPROVED** [review]

**Review by dockerzhang — APPROVED** [review]
