### PR TITLE
[INLONG-5052][Manager] The workflow that failed to execute still failed, but returned success

### LINKED ISSUE #5052: [Bug][Manager] The workflow that failed to execute still failed, but returned success
### What happened

image
The workflow that failed to execute still failed, but returned success.
The first execution of the workflow fails, and the page display also fails;
For the second time, even if the execution process still fails, the status of this task has changed successfully - it should not succeed;
The success of step 2 leads to the start of the next process - normally, those who fail cannot continue to execute the following process

### What you expected to happen

The failed task should not show success and proceed to the next process
image

### How to reproduce

After the workflow fails to be executed, click re execute

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by fuweng11**
### Prepare a Pull Request

- Fixes #5052

### Motivation

Ensure that the re executed workflow will no longer behave as successful execution and go to the next step in the case of failure

### Modifications

Add  listeners for workflowtask on the interface where you click execute again

### Verifying this change

*(Please pick either of the following options)*

- [X] This change is a trivial rework/code cleanup without any test coverage.

- [ ] This change is already covered by existing tests, such as:
  *(please describe tests)*

- [ ] This change added tests and can be verified as follows:

### Documentation

  - Does this pull request introduce a new feature? (no)

### CODE REVIEW

**Review by kipshi — APPROVED** [review]

File: inlong-manager/manager-workflow/src/main/java/org/apache/inlong/manager/workflow/core/impl/TaskServiceImpl.java [hunk 1]
```diff
@@ -67,6 +68,8 @@ public WorkflowContext transfer(Integer taskId, String remark, List<String> to,
     public WorkflowContext complete(Integer taskId, String remark, String operator) {
         WorkflowContext context = workflowContextBuilder
                 .buildContextForTask(taskId, WorkflowAction.COMPLETE, remark, operator);
+        ServiceTask serviceTask = (ServiceTask) context.getActionContext().getTask();
```
Comment (healchow) [inline inlong-manager/manager-workflow/src/main/java/org/apache/inlong/manager/workflow/core/impl/TaskServiceImpl.java:71]: Are the results of `context.getActionContext().getTask()` all `ServiceTask`?

Comment (fuweng11) [reply inlong-manager/manager-workflow/src/main/java/org/apache/inlong/manager/workflow/core/impl/TaskServiceImpl.java:71]: no，just one

**Review by dockerzhang — APPROVED** [review]
