### PR TITLE
[INLONG-8080][Manager] Fix the total parameter found on the page is different from the actual value

### LINKED ISSUE #8080: [Bug][Manager] The total parameter found on the page is different from the actual value
### What happened

The total parameter found on the page is different from the actual value.

### What you expected to happen

The total parameter found on the page is different from the actual value.

### How to reproduce

Query data that exceeds the number of pagesize.

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by fuweng11**
### Prepare a Pull Request

- Fixes #8080 

### Motivation

Fix the total parameter found on the page is different from the actual value.

### Modifications

Fix the total parameter found on the page is different from the actual value.

### CODE REVIEW

**Review by dockerzhang — APPROVED** [review]

**Review by dockerzhang — APPROVED** [review]

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/StreamSinkServiceImpl.java [hunk 1]
```diff
@@ -322,9 +323,11 @@ public PageResult<? extends StreamSink> listByCondition(SinkPageRequest request,
         PageHelper.startPage(request.getPageNum(), request.getPageSize());
         OrderFieldEnum.checkOrderField(request);
         OrderTypeEnum.checkOrderType(request);
-        List<StreamSinkEntity> entityPage = sinkMapper.selectByCondition(request);
+        Page<StreamSinkEntity> entityPage = (Page<StreamSinkEntity>) sinkMapper.selectByCondition(request);
```
Comment (vernedeng) [inline inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/StreamSinkServiceImpl.java:326]: Please use pageHelper to do paging

Comment (vernedeng) [inline inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/StreamSinkServiceImpl.java:326]: Please use PageHelper to get the total number of entities.

**Review by vernedeng — CHANGES_REQUESTED** [review]

**Review by healchow — APPROVED** [review]

**Review by vernedeng — APPROVED** [review]
LGTM
