### PR TITLE
[INLONG-8272][SDK] Fix DataProxy's HTTP SDK verification response code error

### LINKED ISSUE #8272: [Bug][SDK] DataProxy's HTTP SDK verification response code error
### What happened

image

When the HTTP SDK return code of DataProxy is 0, it indicates successful interaction. However, in the SDK code, return code 1 indicates successful interaction. In fact, the DataProxy server returns 0 to indicate success. Therefore, in the SDK code, return code 1 indicates successful interaction, which is an error.

### What you expected to happen

When the HTTP SDK return code of DataProxy is 0, it indicates successful interaction.

### How to reproduce

Call the HTTP SDK of DataProxy to send the interface and print the return code.

### Environment

Linux

### InLong version

master

### InLong Component

InLong SDK

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by xuesongxs**
- Fixes #8272

### CODE REVIEW

File: inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/http/InternalHttpSender.java [hunk 1]
```diff
@@ -206,7 +206,7 @@ private SendResult sendByHttp(List<String> bodies, String groupId, String stream
 
                 if (jsonRes.has("code")) {
                     int code = jsonRes.get("code").getAsInt();
-                    if (code == 1) {
```
[the remark this answers is not in the document]
Comment (xuesongxs) [reply inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/http/InternalHttpSender.java:209]: > It is recommended to extract it into static variables to avoid magic numbers.

I have completed the modifications.

**Comment by dockerzhang** [comment]
@xuesongxs please use English to add the commit msg. thanks.

File: inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/config/HostInfo.java [hunk 2]
```diff
@@ -50,9 +52,14 @@ public int compareTo(HostInfo other) {
         return referenceName.compareTo(other.getReferenceName());
     }
 
+    @Override
+    public int hashCode() {
```
Comment (healchow) [inline inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/config/HostInfo.java:56]: The `HostInfo` was used by Map, so it must implement both of `hashCode` and `equals` methods.

File: inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/http/InternalHttpSender.java [hunk 3]
```diff
@@ -165,17 +156,6 @@ public List<HostInfo> getRandomHostInfo() {
 
     /**
      * send request by http
-     *
-     * @param bodies
```
Comment (healchow) [inline inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/http/InternalHttpSender.java:169]: If tags of a Javadoc do not specify description info, their existence is meaningless.

File: inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/http/InternalHttpSender.java [hunk 4]
```diff
@@ -186,39 +166,33 @@ private SendResult sendByHttp(List<String> bodies, String groupId, String stream
...
+            logger.info("begin to post request to {}, encoded content is: {}", url, encodedContents);
             response = httpClient.execute(httpPost);
-            String returnStr = EntityUtils.toString(response.getEntity());
 
-            if (Utils.isNotBlank(returnStr) && response.getStatusLine().getStatusCode() == 200) {
-                logger.debug("Get configure from manager is " + returnStr);
-                JsonObject jsonRes = jsonParser.parse(returnStr).getAsJsonObject();
+            String returnStr = EntityUtils.toString(response.getEntity());
+            int returnCode = response.getStatusLine().getStatusCode();
+            if (Utils.isBlank(returnStr) || HttpStatus.SC_OK != returnCode) {
```
Comment (healchow) [inline inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/http/InternalHttpSender.java:182]: Use guard statements to reduce the cyclomatic complexity of the code and improve readability.

File: inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/http/InternalHttpSender.java [hunk 5]
```diff
@@ -186,39 +166,33 @@ private SendResult sendByHttp(List<String> bodies, String groupId, String stream
...
-                    int code = jsonRes.get("code").getAsInt();
-                    if (code == 1) {
-                        return SendResult.OK;
-                    } else {
-                        logger.debug("get error response {}", returnStr);
-                        return SendResult.INVALID_DATA;
-                    }
+            logger.debug("success to get config from manager, result str: " + returnStr);
+            JsonObject jsonResponse = JsonParser.parseString(returnStr).getAsJsonObject();
+            JsonElement codeElement = jsonResponse.get("code");
```
Comment (gosonzhang) [inline inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/http/InternalHttpSender.java:188]: It would be better to use, not create again, the error code definition of org.apache.commons.lang3.math.NumberUtils.DataProxyErrCode

**Review by healchow — APPROVED** [review]

**Review by healchow — APPROVED** [review]

**Review by gosonzhang — APPROVED** [review]

File: inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/http/InternalHttpSender.java [hunk 6]
```diff
@@ -186,39 +166,33 @@ private SendResult sendByHttp(List<String> bodies, String groupId, String stream
...
+            if (codeElement != null) {
+                if (ConfigConstants.HTTP_RESPONSE_CODE_SUCCESS == codeElement.getAsInt()) {
+                    return SendResult.OK;
+                } else {
+                    return SendResult.INVALID_DATA;
```
Comment (gosonzhang) [inline inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/http/InternalHttpSender.java:193]: There is a problem here. The error information converges to INVALID_DATA. How can the user obtain the specific cause of the error and how to solve this problem?

**Review by dockerzhang — APPROVED** [review]

**Review by dockerzhang — APPROVED** [review]

**Review by dockerzhang — APPROVED** [review]
