### PR TITLE
[INLONG-7976][Agent] The data collected by the agent is incomplete

### LINKED ISSUE #7976: [Bug][Agent] The data collected by the agent is incomplete
### What happened

When the agent collects file data, it will truncate the data content

### What you expected to happen

The data collected by the agent is complete

### How to reproduce

Repair collection logic code

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Agent

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by doleyzi**
### Prepare a Pull Request
*(Change the title refer to the following example)*

- Title Example: [INLONG-7976][Agent]The data collected by the agent is incomplete

*(The following *XYZ* should be replaced by the actual [GitHub Issue](https://github.com/apache/inlong/issues) number)*

- Fixes #7976

### CODE REVIEW

**Review by justinwwhuang — APPROVED** [review]

File: inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/CommonConstants.java [hunk 1]
```diff
@@ -65,7 +65,7 @@ public class CommonConstants {
     public static final String PROXY_SEND_PARTITION_KEY = "proxy.partitionKey";
 
     // max size of single batch in bytes, default is 200KB.
-    public static final int DEFAULT_PROXY_PACKAGE_MAX_SIZE = 200000;
+    public static final int DEFAULT_PROXY_PACKAGE_MAX_SIZE = 800000;
```
Comment (aloyszhang) [inline inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/CommonConstants.java:68]: please keep consistent between comment and code

**Review by dockerzhang — APPROVED** [review]

**Review by pocozh — APPROVED** [review]

**Review by aloyszhang — APPROVED** [review]
