### PR TITLE
[INLONG-4841][Manager] Optimize the service validation method

### LINKED ISSUE #4841: [Improve][Manager] Optimize the service validation method
### Description

Optimize the service validation method

- The current validation method does not use annotations like controller
- If multiple conditions are not met at the same time, only the first exception message will be returned.

image

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by leosanqing**
### Prepare a Pull Request

- Fixes #4841 

### Motivation

- The current validation method does not use annotations like controller
- If multiple conditions are not met at the same time, only the first exception message will be returned.
- 
### Modifications
- Delete unused validation
- Add validation utils for service layer
*Describe the modifications you've done.*

### Verifying this change

*(Please pick either of the following options)*

- [x] This change is already covered by existing tests, such as:
  - GroupServiceTest

### CODE REVIEW

File: inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/group/GroupServiceTest.java [hunk 1]
```diff
@@ -0,0 +1,45 @@
...
+import org.apache.inlong.manager.common.pojo.group.InlongGroupApproveRequest;
+import org.apache.inlong.manager.common.pojo.group.tube.InlongTubeRequest;
+import org.apache.inlong.manager.service.ServiceBaseTest;
+import org.junit.jupiter.api.Assertions;
+import org.junit.jupiter.api.Test;
+
+import javax.annotation.Resource;
+import javax.validation.ConstraintViolationException;
+
+class GroupServiceTest extends ServiceBaseTest {
```
Comment (healchow) [inline inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/group/GroupServiceTest.java:29]: Please add Java doc for class.

File: inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/util/ValidationUtils.java [hunk 2]
```diff
@@ -0,0 +1,42 @@
...
+import javax.validation.Validator;
+import java.util.Set;
+
+/**
+ * With various annotations of javax, it is used to verify object properties, mainly used in the service layer
+ */
+@UtilityClass
+public class ValidationUtils {
+
+    public static void validate(Validator validator, Object object, Class<?>... groups) {
```
Comment (healchow) [inline inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/util/ValidationUtils.java:35]: Please add Java doc for static methods.

File: inlong-dashboard/package-lock.json [hunk 3]
```diff
@@ -11486,7 +11486,7 @@
     "json2mq": {
       "version": "0.2.0",
       "resolved": "https://registry.npmjs.org/json2mq/-/json2mq-0.2.0.tgz",
-      "integrity": "sha512-SzoRg7ux5DWTII9J2qkrZrqV1gt+rTaoufMxEzXbS26Uid0NwaJd123HcoB80TgubEppxxIGdNxCx50fEoEWQA==",
+      "integrity": "sha1-tje9O6nqvhIsg+lyBIOusQ0skEo=",
```
[the remark this answers is not in the document]
Comment (leosanqing) [reply inlong-dashboard/package-lock.json]: I rolled back

**Review by healchow — APPROVED** [review]

**Review by gosonzhang — APPROVED** [review]
