### PR TITLE
[INLONG-5491][Manager] Fix the error of configuring the Pulsar nonpartitioned topic

### LINKED ISSUE #5491: [Bug][Manager] Pulsar failed to configure non partitioned topic
### What happened

Pulsar failed to configure non partitioned topi。

### What you expected to happen

Pulsar successfully configured non partitioned topic.

### How to reproduce

Create inlong_ When group is selected, the pulsar queue type is sequence.

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by fuweng11**
### Prepare a Pull Request

- Fixes #5491 

### Motivation

Fix pulsar failed to configure nonpartitioned topic problem

### Modifications

When creating topic, judge whether to partition

### Verifying this change

*(Please pick either of the following options)*

- [X] This change is a trivial rework/code cleanup without any test coverage.

- [ ] This change is already covered by existing tests, such as:

- [ ] This change added tests and can be verified as follows:

### Documentation

  - Does this pull request introduce a new feature? (no)

### CODE REVIEW

**Comment by dockerzhang** [comment]
@woofyzhao @gong PTAL

**Review by gong — APPROVED** [review]

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/pulsar/PulsarOperator.java [hunk 1]
```diff
@@ -316,19 +321,29 @@ public boolean topicIsExists(PulsarAdmin pulsarAdmin, String tenant, String name
         return topicExists;
     }
 
-    private boolean subscriptionIsExists(PulsarAdmin pulsarAdmin, String topic, String subscription) {
+    private boolean subscriptionIsExists(PulsarAdmin pulsarAdmin, PulsarTopicBean topicBean, String subscription) {
```
Comment (healchow) [inline inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/pulsar/PulsarOperator.java:324]: It is recommended to pass in a field of whether it is a partitioned topic.
Such as `boolean isPartitionedTopic`.

**Review by healchow — CHANGES_REQUESTED** [review]

**Review by healchow — APPROVED** [review]

**Review by woofyzhao — APPROVED** [review]

**Review by dockerzhang — APPROVED** [review]
