### PR TITLE
[INLONG-11772][Dashboard][Manager] Fix login verify fail

### LINKED ISSUE #11772: [Improve][Dashboard] User login verify fail
### What happened

I accidentally encountered a username or password error while logging in.

After inspection, it was found that the frontend mistakenly passed `space symbol`  **ctrl+cv username** when calling the login api, result in an incorrect username or password prompt. This is incorrect.

Image

### What you expected to happen

Log in correctly. Remove `spaces` to verify.

Strictly speaking, `API` also need to be processed by `String.trim()`, not just front-end.

### How to reproduce

Username and password with spaces

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Dashboard

### Are you willing to submit PR?

- [x] Yes, I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Jzow**
Fixes #11772

### Motivation

When users habitually copy and paste their username or password, they may accidentally include leading and trailing spaces. These extra spaces are not removed during the verification process

### Modifications

The modification needs to be done on both the web and api to ensure that the leading and trailing spaces are removed before verifying the username and password.

### Verifying this change

*(Please pick either of the following options)*

- [ ] This change is a trivial rework/code cleanup without any test coverage.

- [x] This change is already covered by existing tests, such as:
  *(please describe tests)*

- [ ] This change added tests and can be verified as follows:

  *(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a follow-up issue for adding the documentation

### CODE REVIEW

**Review by wohainilaodou — DISMISSED** [review]

File: inlong-dashboard/src/ui/pages/Login/index.tsx [hunk 1]
```diff
@@ -55,6 +55,8 @@ const Comp: React.FC = () => {
 
   const login = async () => {
     const data = await form.validateFields();
+    data.username = data.username.trim();
```
Comment (fuweng11) [inline inlong-dashboard/src/ui/pages/Login/index.tsx:58]: Suggest adding space verification on the login page instead of using trim.

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/user/UserServiceImpl.java [hunk 2]
```diff
@@ -318,7 +318,8 @@ public Boolean delete(Integer userId, String currentUser) {
      */
     @Override
     public void login(UserLoginRequest req) {
-        String username = req.getUsername();
+        String username = req.getUsername().trim();
```
Comment (fuweng11) [inline inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/user/UserServiceImpl.java:321]: Please delete this modification as verification logic has been added to the login page.

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/user/UserServiceImpl.java [hunk 3]
```diff
@@ -328,7 +329,7 @@ public void login(UserLoginRequest req) {
         }
 
         Subject subject = SecurityUtils.getSubject();
-        UsernamePasswordToken token = new UsernamePasswordToken(username, req.getPassword());
+        UsernamePasswordToken token = new UsernamePasswordToken(username, password);
```
Comment (fuweng11) [inline inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/user/UserServiceImpl.java:332]: Ditto.

File: inlong-dashboard/src/ui/locales/cn.json [hunk 4]
```diff
@@ -913,9 +913,11 @@
   "pages.ClusterTags.TagPlaceholder": "请输入标签",
   "pages.ClusterTags.TenantPlaceholder": "请选择租户",
   "pages.Login.PleaseEnterUserName": "请输入用户名",
+  "pages.Login.UserNameSpaceNotAllowed": "用户名不能包含空格，请删除空格后重试。",
   "pages.Login.PasswordRules": "只能包含字母、数字、中划线、下划线、@",
   "pages.Login.Login": "登录",
   "pages.Login.PleaseEnterYourPassword": "请输入密码",
+  "pages.Login.UserPasswordSpaceNotAllowed": "密码不能包含空格，请删除空格后重试。",
```
Comment (fuweng11) [inline inlong-dashboard/src/ui/locales/cn.json:920]:
```suggestion
  "pages.Login.UserPasswordSpaceNotAllowed": "密码不能包含空格，请删除空格后重试",
```

File: inlong-dashboard/src/ui/locales/cn.json [hunk 5]
```diff
@@ -913,9 +913,11 @@
   "pages.ClusterTags.TagPlaceholder": "请输入标签",
   "pages.ClusterTags.TenantPlaceholder": "请选择租户",
   "pages.Login.PleaseEnterUserName": "请输入用户名",
+  "pages.Login.UserNameSpaceNotAllowed": "用户名不能包含空格，请删除空格后重试。",
```
Comment (fuweng11) [inline inlong-dashboard/src/ui/locales/cn.json:916]:
```suggestion
  "pages.Login.UserNameSpaceNotAllowed": "用户名不能包含空格，请删除空格后重试",
```

File: inlong-dashboard/src/ui/locales/en.json [hunk 6]
```diff
@@ -907,9 +907,11 @@
   "pages.ClusterTags.TagPlaceholder": "Please enter a tag",
   "pages.ClusterTags.TenantPlaceholder": "Please select a tenant",
   "pages.Login.PleaseEnterUserName": "Please enter user name",
+  "pages.Login.UserNameSpaceNotAllowed": "Username cannot contain spaces. Please remove any spaces and try again.",
```
Comment (fuweng11) [inline inlong-dashboard/src/ui/locales/en.json:910]:
```suggestion
  "pages.Login.UserNameSpaceNotAllowed": "Username cannot contain spaces. Please remove any spaces and try again",
```

File: inlong-dashboard/src/ui/locales/en.json [hunk 7]
```diff
@@ -907,9 +907,11 @@
...
   "pages.Login.PasswordRules": "Only letters, numbers, minus, @, and underscores",
   "pages.Login.Login": "Login",
   "pages.Login.PleaseEnterYourPassword": "Please enter your password",
+  "pages.Login.UserPasswordSpaceNotAllowed": "Password cannot contain spaces. Please remove any spaces and try again.",
```
Comment (fuweng11) [inline inlong-dashboard/src/ui/locales/en.json:914]:
```suggestion
  "pages.Login.UserPasswordSpaceNotAllowed": "Password cannot contain spaces. Please remove any spaces and try again",
```

File: inlong-dashboard/src/ui/locales/en.json [hunk 8]
```diff
@@ -907,9 +907,11 @@
   "pages.ClusterTags.TagPlaceholder": "Please enter a tag",
   "pages.ClusterTags.TenantPlaceholder": "Please select a tenant",
   "pages.Login.PleaseEnterUserName": "Please enter user name",
+  "pages.Login.UserNameSpaceNotAllowed": "Username cannot contain spaces. Please remove any spaces and try again",
   "pages.Login.PasswordRules": "Only letters, numbers, minus, @, and underscores",
   "pages.Login.Login": "Login",
   "pages.Login.PleaseEnterYourPassword": "Please enter your password",
+  "pages.Login.UserPasswordSpaceNotAllowed": "Password cannot contain spaces. Please remove any spaces and try again",
```
Comment (dockerzhang) [inline inlong-dashboard/src/ui/locales/en.json:914]:
```suggestion
  "pages.Login.UserPasswordSpaceNotAllowed": "The username cannot contain spaces, please remove any spaces and try again",
```

**Review by dockerzhang — APPROVED** [review]

**Review by fuweng11 — APPROVED** [review]
