### PR TITLE
[INLONG-11531][Manager] Fix bug in DolphinScheduler engine

### LINKED ISSUE #11531: [Feature][Manager] Fix bug in DolphinScheduler engine
### Description

The `start()` method in DolphinScheduler engine is never used, which cause it didn't correct manage the project in DS

* normaly when DS engine begin, it should create a project in DS, then handle process definition in this project, so `start()` method must be called before `register()`, `unregister()`, `update()` method, or the project code in DS will never be initialize correctly
image

### Use case

_No response_

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by emptyOVO**
Fixes #11531 

### Motivation
* A project in DS engine doesn't need to be created at bean initialize time, so it only needs to be called when a register-related-handle method is called, and this also allows data synchronization at each processing time
* delete operation need to add retry mechanism

### Modifications
* add `start()` method in `handleRegister()`, `handleUnregister()` and `handleUpdate()`, before related operation be called
* because of situation below, deleting operation should add retry mechanism
image

### Verifying this change

*(Please pick either of the following options)*

- [ ] This change is a trivial rework/code cleanup without any test coverage.

- [x] This change is already covered by existing tests, such as:
  *(please describe tests)*

- [ ] This change added tests and can be verified as follows:

  *(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a follow-up issue for adding the documentation

### CODE REVIEW

File: inlong-manager/manager-schedule/src/main/java/org/apache/inlong/manager/schedule/dolphinscheduler/DolphinScheduleUtils.java [hunk 1]
```diff
@@ -489,17 +493,35 @@ public static void delete(String url, String token, long code) {
...
+                }
+
+                if (response.get(DS_CODE).getAsInt() == PROCESS_DEFINITION_IN_USED_ERROR) {
+                    LOGGER.warn("Attempt {} of {}, retrying after {} ms...", attempt, DS_DEFAULT_RETRY_TIMES,
+                            DS_DEFAULT_WAIT_MILLS);
+                    Thread.sleep(DS_DEFAULT_WAIT_MILLS);
+                }
+            }
 
+        } catch (InterruptedException e) {
```
Comment (aloyszhang) [inline inlong-manager/manager-schedule/src/main/java/org/apache/inlong/manager/schedule/dolphinscheduler/DolphinScheduleUtils.java:511]: Where is the place of InterruptedException happening besides when the whole manager service shutdown?

Comment (emptyOVO) [reply inlong-manager/manager-schedule/src/main/java/org/apache/inlong/manager/schedule/dolphinscheduler/DolphinScheduleUtils.java:511]: For now, manager service shutdown may be the only case, the exception is handled here mainly because `Thread.sleep()` needs to clean up resources when the Thread breaks

**Review by aloyszhang — APPROVED** [review]

File: inlong-manager/manager-schedule/src/main/java/org/apache/inlong/manager/schedule/dolphinscheduler/DolphinScheduleUtils.java [hunk 2]
```diff
@@ -489,17 +493,35 @@ public static void delete(String url, String token, long code) {
...
+            Thread.currentThread().interrupt();
+            LOGGER.error("Thread interrupted while retrying delete process or project: ", e);
+            throw new DolphinScheduleException(
+                    DELETION_FAILED,
+                    String.format("Thread interrupted while retrying delete for code: %d at URL: %s", code, url), e);
```
Comment (fuweng11) [inline inlong-manager/manager-schedule/src/main/java/org/apache/inlong/manager/schedule/dolphinscheduler/DolphinScheduleUtils.java:516]:
```suggestion
                    String.format("Thread interrupted while retrying delete for code: %d at URL: %s", code, url));
```

File: inlong-manager/manager-schedule/src/main/java/org/apache/inlong/manager/schedule/dolphinscheduler/DolphinScheduleUtils.java [hunk 3]
```diff
@@ -489,17 +493,35 @@ public static void delete(String url, String token, long code) {
...
         } catch (JsonParseException e) {
             LOGGER.error("JsonParseException during deleting process or project", e);
             throw new DolphinScheduleException(
                     JSON_PARSE_ERROR,
                     String.format("Error deleting process or project with code: %d at URL: %s", code, url), e);
```
Comment (fuweng11) [inline inlong-manager/manager-schedule/src/main/java/org/apache/inlong/manager/schedule/dolphinscheduler/DolphinScheduleUtils.java:521]:
```suggestion
                    String.format("Error deleting process or project with code: %d at URL: %s", code, url));
```

File: inlong-manager/manager-schedule/src/main/java/org/apache/inlong/manager/schedule/dolphinscheduler/DolphinScheduleUtils.java [hunk 4]
```diff
@@ -489,17 +493,35 @@ public static void delete(String url, String token, long code) {
...
 
         } catch (DolphinScheduleException e) {
+            LOGGER.error("Error deleting process or project: ", e);
             throw new DolphinScheduleException(
                     DELETION_FAILED,
                     String.format("Error deleting process or project with code: %d at URL: %s", code, url), e);
```
Comment (fuweng11) [inline inlong-manager/manager-schedule/src/main/java/org/apache/inlong/manager/schedule/dolphinscheduler/DolphinScheduleUtils.java:527]:
```suggestion
                    String.format("Error deleting process or project with code: %d at URL: %s", code, url));
```

File: inlong-manager/manager-schedule/src/main/java/org/apache/inlong/manager/schedule/dolphinscheduler/DolphinScheduleUtils.java [hunk 5]
```diff
@@ -489,17 +493,35 @@ public static void delete(String url, String token, long code) {
             Map<String, String> header = buildHeader(token);
 
             String requestUrl = url + "/" + code;
+            for (int attempt = 1; attempt <= DS_DEFAULT_RETRY_TIMES; attempt++) {
```
Comment (fuweng11) [inline inlong-manager/manager-schedule/src/main/java/org/apache/inlong/manager/schedule/dolphinscheduler/DolphinScheduleUtils.java:496]:
```suggestion
            for (int retryTime = 1; retryTime <= DS_DEFAULT_RETRY_TIMES; retryTime++) {
```

File: inlong-manager/manager-schedule/src/main/java/org/apache/inlong/manager/schedule/dolphinscheduler/DolphinScheduleUtils.java [hunk 6]
```diff
@@ -489,17 +493,35 @@ public static void delete(String url, String token, long code) {
...
+                JsonObject response = executeHttpRequest(requestUrl, DELETE, new HashMap<>(), header);
 
-            JsonObject response = executeHttpRequest(requestUrl, DELETE, new HashMap<>(), header);
-            LOGGER.info("delete process or project success, response data: {}", response);
+                if (response.get(DS_SUCCESS).getAsBoolean()) {
+                    LOGGER.info("Delete process or project success, response data: {}", response);
+                    return;
+                }
+
+                if (response.get(DS_CODE).getAsInt() == PROCESS_DEFINITION_IN_USED_ERROR) {
```
Comment (fuweng11) [inline inlong-manager/manager-schedule/src/main/java/org/apache/inlong/manager/schedule/dolphinscheduler/DolphinScheduleUtils.java:504]: What to do when the maximum number of retries is exceeded？

File: inlong-manager/manager-schedule/src/main/java/org/apache/inlong/manager/schedule/dolphinscheduler/DolphinScheduleUtils.java [hunk 7]
```diff
@@ -489,20 +493,49 @@ public static void delete(String url, String token, long code) {
...
```
Comment (fuweng11) [inline inlong-manager/manager-schedule/src/main/java/org/apache/inlong/manager/schedule/dolphinscheduler/DolphinScheduleUtils.java:504]: What to do when `response.get(DS_CODE).getAsInt() != PROCESS_DEFINITION_IN_USED_ERROR`&& response.get(DS_SUCCESS).getAsBoolean()!= true`?

File: inlong-manager/manager-schedule/src/main/java/org/apache/inlong/manager/schedule/dolphinscheduler/DolphinScheduleUtils.java [hunk 8]
```diff
@@ -489,20 +493,49 @@ public static void delete(String url, String token, long code) {
...
+                    String.format("Thread interrupted while retrying delete for code: %d at URL: %s", code, url));
         } catch (JsonParseException e) {
             LOGGER.error("JsonParseException during deleting process or project", e);
             throw new DolphinScheduleException(
                     JSON_PARSE_ERROR,
-                    String.format("Error deleting process or project with code: %d at URL: %s", code, url), e);
+                    String.format("Error deleting process or project with code: %d at URL: %s", code, url));
 
         } catch (DolphinScheduleException e) {
+            LOGGER.error("Error deleting process or project: ", e);
```
Comment (fuweng11) [inline inlong-manager/manager-schedule/src/main/java/org/apache/inlong/manager/schedule/dolphinscheduler/DolphinScheduleUtils.java:535]:
```suggestion
            LOGGER.error("Error deleting process or project for code={}, url={} ", code, url, e);
```

File: inlong-manager/manager-schedule/src/main/java/org/apache/inlong/manager/schedule/dolphinscheduler/DolphinScheduleUtils.java [hunk 9]
```diff
@@ -489,20 +493,49 @@ public static void delete(String url, String token, long code) {
...
+                                "Maximum retry attempts reached for deleting process or project. URL: {}, Code: {}",
+                                url, code);
+                        throw new DolphinScheduleException(
+                                DELETION_FAILED,
+                                String.format("Failed to delete after %d retries. Code: %d at URL: %s",
+                                        DS_DEFAULT_RETRY_TIMES, code, url));
+                    }
+
+                    LOGGER.warn("Attempt {} of {}, retrying after {} ms...", retryTime, DS_DEFAULT_RETRY_TIMES,
+                            DS_DEFAULT_WAIT_MILLS);
```
Comment (fuweng11) [inline inlong-manager/manager-schedule/src/main/java/org/apache/inlong/manager/schedule/dolphinscheduler/DolphinScheduleUtils.java:517]:
```suggestion
                    LOGGER.warn("Retrying for current retry time ={}, maximum retry count={}, code={}, url={}, after {} ms...", retryTime, DS_DEFAULT_RETRY_TIMES, code, url,  DS_DEFAULT_WAIT_MILLS);
```

**Review by fuweng11 — APPROVED** [review]

**Review by dockerzhang — APPROVED** [review]
