### PR TITLE
[INLONG-10076][Manager] Doris data node supports test connections

### LINKED ISSUE #10076: [Bug][[Manager] Data type 'doris' not support
### What happened

when I add node for doris, I did what offfical step by adding doris connector to flink lib, but I still get node type not support error.
微信截图_20240425194405

### What you expected to happen

add doris node success!

### How to reproduce

1. download latest inlong-1.12 and connectors.
1. add sort-connector-doris-1.11.0.jar to flink lib.
2. start flink
3. start inlong with standalone mode.

### Environment

linux centos 7

### InLong version

1.12.0

### InLong Component

InLong Sort

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by haifxu**
Fixes #10076 

### Motivation

Doris data node supports test connections.

### Modifications

Add test connections for Doris data node.

### Verifying this change

image

### CODE REVIEW

**Review by dockerzhang — APPROVED** [review]

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/doris/DorisDataNodeOperator.java [hunk 1]
```diff
@@ -81,4 +86,21 @@ protected void setTargetEntity(DataNodeRequest request, DataNodeEntity targetEnt
...
 
+    @Override
+    public Boolean testConnection(DataNodeRequest request) {
+        String jdbcUrl = MySQLDataNodeDTO.convertToJdbcurl(request.getUrl());
+        String username = request.getUsername();
+        String password = request.getToken();
+        Preconditions.expectNotBlank(jdbcUrl, ErrorCodeEnum.INVALID_PARAMETER, "connection jdbcUrl cannot be empty");
+        try (Connection ignored = MySQLJdbcUtils.getConnection(jdbcUrl, username, password)) {
+            LOGGER.info("doris connection not null - connection success for jdbcUrl={}, username={}, password={}",
+                    jdbcUrl, username, password);
```
Comment (aloyszhang) [inline inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/doris/DorisDataNodeOperator.java:97]: Is it ok to output the plain text of the password?

Comment (haifxu) [reply inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/doris/DorisDataNodeOperator.java:97]: This is just a test connection to help users confirm whether the wrong password caused the test to fail, so plain text would be better.

**Review by dockerzhang — APPROVED** [review]

**Review by aloyszhang — APPROVED** [review]
