### PR TITLE
[INLONG-6665][Manager] Support to save additional information for Elasticsearch field

### LINKED ISSUE #6665: [Bug][Manager] Unable to save additional information for Elasticsearch field
### What happened

Unable to save additional information for Elasticsearch field.

### What you expected to happen

Additional information of Elasticsearch field saved successfully

### How to reproduce

When saving the Elasticsearch information, add additional information about the field, such as `analyzer`、`searchAnalyzer`、`scalingFactor`.

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by fuweng11**
### Prepare a Pull Request

- Fixes #6665

### Motivation

Support to save additional information for Elasticsearch field

### CODE REVIEW

**Review by vernedeng — APPROVED** [review]

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/es/ElasticsearchSinkOperator.java [hunk 1]
```diff
@@ -101,4 +107,66 @@ public Map<String, String> parse2IdParams(StreamSinkEntity streamSink, List<Stri
...
+    }
+
+    @Override
+    public List<SinkField> getSinkFields(Integer sinkId) {
+        List<StreamSinkFieldEntity> sinkFieldEntities = sinkFieldMapper.selectBySinkId(sinkId);
+        List<SinkField> fieldList = new ArrayList<>();
+        if (CollectionUtils.isEmpty(sinkFieldEntities)) {
+            return fieldList;
+        }
+        sinkFieldEntities.stream().forEach(field -> {
```
Comment (healchow) [inline inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/es/ElasticsearchSinkOperator.java:156]: Maybe `sinkFieldEntities.forEach()` is enough.

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/es/ElasticsearchSinkOperator.java [hunk 2]
```diff
@@ -101,4 +107,66 @@ public Map<String, String> parse2IdParams(StreamSinkEntity streamSink, List<Stri
         return idParams;
     }
 
+    @Override
+    public void saveFieldOpt(SinkRequest request) {
+        List<SinkField> fieldList = request.getSinkFieldList();
+        LOGGER.info("begin to save sink fields={}", fieldList);
```
Comment (healchow) [inline inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/es/ElasticsearchSinkOperator.java:113]: Whether it needs to add "es" to the log?

```
begin to save es sink fields xxx
```

**Review by dockerzhang — APPROVED** [review]

**Review by healchow — APPROVED** [review]
