### PR TITLE
[INLONG-6332][Agent] Fix reboot will reset file position error

### LINKED ISSUE #6332: [Bug][Agent]  Reboot will reset file position
### What happened

Reboot will reset file position, old position is losted.

### What you expected to happen

Do not to reset position.

### How to reproduce

Multiple reboots

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Agent

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by GanfengTan**
Fix reboot will reset file position error when multiple  agent reboots.

- Fixes #6332 

### Motivation

Do not to change position when agent reboots.

### Modifications

Update position by local RocksDB.

### Verifying this change

*(Please pick either of the following options)*

- [x] This change is a trivial rework/code cleanup without any test coverage.

- [ ] This change is already covered by existing tests, such as:
  *(please describe tests)*

- [ ] This change added tests and can be verified as follows:

### CODE REVIEW

File: inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/file/MonitorTextFile.java [hunk 1]
```diff
@@ -53,8 +53,9 @@ private MonitorTextFile() {
     }
 
     /**
-     * Mode of singleton
-     * @return MonitorTextFile instance
+     * mode of singleton
```
Comment (healchow) [inline inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/file/MonitorTextFile.java:56]:
```suggestion
     * Get a singleton instance of MonitorTextFile.
```

**Review by healchow — APPROVED** [review]

**Review by pocozh — APPROVED** [review]

**Review by dockerzhang — APPROVED** [review]
