### PR TITLE
[INLONG-5729][Manager] Fix the failure of suspending or restarting the sources

### LINKED ISSUE #5729: [Bug][Manager] Suspend the agent sources failed as the inlong group cannot be updated
### What happened

Suspend the agent sources failed as the inlong group cannot be updated.

6bab-47ae-9a0d

### What you expected to happen

Can succeed to suspend or restart the sources.

### How to reproduce

Calling the `InlongGroupImpl#suspend()` and `InlongGroupImpl#restart()`.

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by healchow**
### Prepare a Pull Request

- Fixes #5729

### Motivation

Fix the failure of suspending or restarting the sources.

### Verifying this change

- [x] This change is a trivial rework/code cleanup without any test coverage.

### CODE REVIEW

**Review by chestnut-c — APPROVED** [review]

**Review by gong — APPROVED** [review]

File: inlong-manager/manager-web/sql/apache_inlong_manager.sql [hunk 1]
```diff
@@ -759,8 +759,8 @@ CREATE TABLE IF NOT EXISTS `group_heartbeat`
     `component`        varchar(64)  NOT NULL DEFAULT '' COMMENT 'Component name, such as: Agent, Sort...',
     `instance`         varchar(64)  NOT NULL DEFAULT '' COMMENT 'Component instance, can be ip, name...',
     `inlong_group_id`  varchar(256) NOT NULL DEFAULT '' COMMENT 'Owning inlong group id',
-    `status_heartbeat` text         DEFAULT NULL COMMENT 'Status heartbeat info',
-    `metric_heartbeat` text         DEFAULT NULL COMMENT 'Metric heartbeat info',
+    `status_heartbeat` text                  DEFAULT NULL COMMENT 'Status heartbeat info',
```
Comment (leosanqing) [inline inlong-manager/manager-web/sql/apache_inlong_manager.sql:762]: Why is there indentation here, the previous format should be more standardized

Comment (healchow) [reply inlong-manager/manager-web/sql/apache_inlong_manager.sql:762]: 1. It's the IDEA auto-formated.
2. The new format looks better: `DEFAULT` is in the same column.

**Review by LvJiancheng — APPROVED** [review]

**Review by dockerzhang — APPROVED** [review]

**Review by leosanqing — APPROVED** [review]

**Review by yunqingmoswu — APPROVED** [review]
LGTM
