### PR TITLE
[INLONG-10311][Sort] Implement TubeMQ Source report audit information exactly once And fix consuming TubeMQ data twice

### LINKED ISSUE #10311: [Feature][Sort] TubeMQ source support report audit information exactly once
### Description

Currently, audit information reporting only supports at least once. In order to improve the defects of at least once, audit information reporting needs to be upgraded to exactly once.

image

As shown in the figure above, audit information reporting will be repeated

### Use case

Ensure that audit information report is exactly once when an operator encounters an exception or a snapshot fails.

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by XiaoYou201**
### [INLONG-10311][Sort] Implement TubeMQ Source report audit information exactly once

Fixes #10311 

### Motivation

Now，every connectors report audit information only support at least once. So，This pr base it to implements report audit information exactly once. The audit information will not be wrong in much exception situation.

### Modifications
1. Using the checkpoint principle in Flink to modify the process, the modified flow chart is shown in Figure 1 and Figure 2. In Figure 1, the callback method of notifyCompleteCheckpoint is used to upload audit information instead of scheduled upload.

Each Source/Sink will save the checkpointId of the currently ongoing checkpoint, which is nowCheckpointId in the figure. When the audit information is written to the Buffer, nowCheckpointId will be attached, indicating that the audit information
is written during this ongoing checkpoint. The audit information and checkpointId are in a many-to-one relationship.

image
When a snapshot request is received, the current operator's nowCheckpointId is updated to (snapshot) checkpointId + 1. When all operators in a task complete the snapshot, the notifyCompleteCheckpoint method is called back.

At this time, AuditBuffer uploads audit information less than or equal to checkpointId (parameters in the notifyCompleteCheckpoint method).

image

2. The getCurConsumedPartitions method gets the partitions assigned to the client by the tube server, including the partitions where the client has consumed data and t the client has not consumed data. According to the previous logic, the offsets of the partitions that have not been consumed are not recorded. Here, the offsets of the partitions that have not been consumed are added.

### CODE REVIEW

File: inlong-sort/sort-flink/base/src/main/java/org/apache/inlong/sort/base/metric/MetricsCollector.java [hunk 1]
```diff
@@ -31,11 +31,10 @@ public class MetricsCollector<T> implements TimestampedCollector<T> {
 
     private long timestampMillis;
 
-    SourceMetricData metricData;
-
+    SourceMetricsReporter metricsReporter;
```
Comment (vernedeng) [inline inlong-sort/sort-flink/base/src/main/java/org/apache/inlong/sort/base/metric/MetricsCollector.java:34]: private

File: inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/tubemq/src/main/java/org/apache/inlong/sort/tubemq/FlinkTubeMQConsumer.java [hunk 2]
```diff
@@ -257,18 +260,24 @@ public void run(SourceContext<T> ctx) throws Exception {
...
             synchronized (ctx.getCheckpointLock()) {
-
+                lastConsumeInstant = getRecords(lastConsumeInstant, messageList, records);
                 for (T record : records) {
                     ctx.collect(record);
                 }
-                currentOffsets.put(
-                        consumeResult.getPartitionKey(),
-                        consumeResult.getCurrOffset());
+                ConsumerResult confirmResult = confirmOffset(consumeResult);
```
Comment (EMsnap) [inline inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/tubemq/src/main/java/org/apache/inlong/sort/tubemq/FlinkTubeMQConsumer.java:269]: please add description on how this solve the tube message duplicate ( not audit)

File: inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/tubemq/src/main/java/org/apache/inlong/sort/tubemq/table/DynamicTubeMQTableDeserializationSchema.java [hunk 3]
```diff
@@ -110,9 +110,15 @@ public void deserialize(Message message, Collector<RowData> out) throws IOExcept
...
+    public void flushAuditById(long checkpointId) {
         if (sourceMetricData != null) {
-            sourceMetricData.flushAuditData();
+            sourceMetricData.flushAuditById(checkpointId);
+        }
+    }
+    @Override
+    public void setNowCheckpointId(long checkpointId) {
+        if (sourceMetricData != null) {
+            sourceMetricData.setNowCheckpointId(checkpointId + 1);
```
Comment (EMsnap) [inline inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/tubemq/src/main/java/org/apache/inlong/sort/tubemq/table/DynamicTubeMQTableDeserializationSchema.java:121]: method name doesn't match the implementation, added id by 1 but the method name is set

Comment (vernedeng) [inline inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/tubemq/src/main/java/org/apache/inlong/sort/tubemq/table/DynamicTubeMQTableDeserializationSchema.java:121]: why +1 here

File: inlong-sort/sort-flink/base/src/main/java/org/apache/inlong/sort/base/metric/MetricsCollector.java (hunk 1 above)
Comment (XiaoYou201) [reply inlong-sort/sort-flink/base/src/main/java/org/apache/inlong/sort/base/metric/MetricsCollector.java]: fix it, thx~

File: inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/tubemq/src/main/java/org/apache/inlong/sort/tubemq/FlinkTubeMQConsumer.java (hunk 2 above)
Comment (XiaoYou201) [reply inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/tubemq/src/main/java/org/apache/inlong/sort/tubemq/FlinkTubeMQConsumer.java:270]: already add some description and change the title.

File: inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/tubemq/src/main/java/org/apache/inlong/sort/tubemq/table/DynamicTubeMQTableDeserializationSchema.java (hunk 3 above)
Comment (XiaoYou201) [reply inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/tubemq/src/main/java/org/apache/inlong/sort/tubemq/table/DynamicTubeMQTableDeserializationSchema.java]: fix it, thx~

Comment (XiaoYou201) [reply inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/tubemq/src/main/java/org/apache/inlong/sort/tubemq/table/DynamicTubeMQTableDeserializationSchema.java]: already change the implement method, thx~

File: inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/tubemq/src/main/java/org/apache/inlong/sort/tubemq/FlinkTubeMQConsumer.java [hunk 4]
```diff
@@ -311,14 +324,21 @@ private Instant getRecords(Instant lastConsumeInstant, List<Message> messageList
 
     @Override
     public void snapshotState(FunctionSnapshotContext context) throws Exception {
-
+        deserializationSchema.setCurrentCheckpointId(context.getCheckpointId());
+        // Make sure snapshot all tube partitions' offset to avoid inconsistency. See BUG-124774267 for details.
```
Comment (EMsnap) [inline inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/tubemq/src/main/java/org/apache/inlong/sort/tubemq/FlinkTubeMQConsumer.java:328]: what is BUG-124774267 ?

File: inlong-sort/sort-flink/base/src/main/java/org/apache/inlong/sort/base/metric/SourceExactlyMetric.java [hunk 5]
```diff
@@ -0,0 +1,330 @@
...
+import static org.apache.inlong.sort.base.Constants.CURRENT_FETCH_EVENT_TIME_LAG;
+import static org.apache.inlong.sort.base.Constants.NUM_BYTES_IN;
+import static org.apache.inlong.sort.base.Constants.NUM_BYTES_IN_FOR_METER;
+import static org.apache.inlong.sort.base.Constants.NUM_BYTES_IN_PER_SECOND;
+import static org.apache.inlong.sort.base.Constants.NUM_RECORDS_IN;
+import static org.apache.inlong.sort.base.Constants.NUM_RECORDS_IN_FOR_METER;
+import static org.apache.inlong.sort.base.Constants.NUM_RECORDS_IN_PER_SECOND;
+import static org.apache.inlong.sort.base.util.CalculateObjectSizeUtils.getDataSize;
+
+public class SourceExactlyMetric implements MetricData, Serializable, SourceMetricsReporter {
```
Comment (EMsnap) [inline inlong-sort/sort-flink/base/src/main/java/org/apache/inlong/sort/base/metric/SourceExactlyMetric.java:44]: some of the methods are exactly the same as in sourceMetricData, please extract a base class or abstract class

File: inlong-sort/sort-flink/base/src/main/java/org/apache/inlong/sort/base/metric/MetricsCollector.java [hunk 6]
```diff
@@ -31,11 +31,10 @@ public class MetricsCollector<T> implements TimestampedCollector<T> {
 
     private long timestampMillis;
 
-    SourceMetricData metricData;
-
+    private final SourceMetricsReporter metricsReporter;
     public MetricsCollector(Collector<T> collector,
-            SourceMetricData sourceMetricData) {
-        this.metricData = sourceMetricData;
+            SourceMetricsReporter sourceMetricData) {
```
[the remark this answers is not in the document]
Comment (XiaoYou201) [reply inlong-sort/sort-flink/base/src/main/java/org/apache/inlong/sort/base/metric/MetricsCollector.java:36]: fix it， thx～

File: inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/tubemq/src/main/java/org/apache/inlong/sort/tubemq/FlinkTubeMQConsumer.java (hunk 4 above)
Comment (XiaoYou201) [reply inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/tubemq/src/main/java/org/apache/inlong/sort/tubemq/FlinkTubeMQConsumer.java]: fix it， thx～

File: inlong-sort/sort-flink/base/src/main/java/org/apache/inlong/sort/base/metric/SourceExactlyMetric.java (hunk 5 above)
Comment (XiaoYou201) [reply inlong-sort/sort-flink/base/src/main/java/org/apache/inlong/sort/base/metric/SourceExactlyMetric.java:44]: I will make all connectors support report audit information exactly once in the future, so the sourcemetricdata will be deprecated later

**Review by EMsnap — DISMISSED** [review]

File: inlong-sort/sort-flink/base/src/main/java/org/apache/inlong/sort/base/metric/MetricsCollector.java (hunk 6 above)
[the remark this answers is not in the document]
Comment (EMsnap) [reply inlong-sort/sort-flink/base/src/main/java/org/apache/inlong/sort/base/metric/MetricsCollector.java:36]: no change here ?

[the remark this answers is not in the document]
Comment (XiaoYou201) [reply inlong-sort/sort-flink/base/src/main/java/org/apache/inlong/sort/base/metric/MetricsCollector.java:36]: fix it， thx～

**Review by EMsnap — APPROVED** [review]

**Review by aloyszhang — APPROVED** [review]

**Review by dockerzhang — APPROVED** [review]
