### PR TITLE
[INLONG-10748][Common] Fix some null pointer dereference risks in the code.

### LINKED ISSUE #10748: [Bug] Some null pointer dereference risks in the code
### What happened

A code scan found some null pointer dereference risks in the following files:
- `inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/pb/network/TcpChannel.java`: L258
- `inlong-sort/sort-formats/format-common/src/main/java/org/apache/inlong/sort/formats/util/StringUtils.java`: L100
- `inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/StreamSourceServiceImpl.java`: L297
- `inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/PulsarSource.java`: L137
- `inlong-sort/sort-flink/sort-flink-v1.18/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/table/source/PulsarRowDataConverter.java`: L117
- `inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/table/PulsarRowDataConverter.java`: L117
- `inlong-sdk/sdk-common/src/main/java/org/apache/inlong/sdk/commons/protocol/ProxyEvent.java`: L79
- `inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/fetcher/kafka/KafkaSeeker.java`: L99
- `inlong-sort/sort-flink/base/src/main/java/org/apache/inlong/sort/base/format/JsonDynamicSchemaFormat.java`: L106
- `inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/service/AuditMsgConsumerServer.java`: L100
- `inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/file/AbstractSource.java`: L181

### What you expected to happen

The above code files will cause null pointer dereference in some cases, which may produce 'NullPointerException'.

### How to reproduce

When the object referenced in the corresponding code line is null

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Manager, InLong Agent, InLong SDK, InLong Sort, InLong Audit

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by yfsn666**
Fixes #10748

### Motivation

A code scan found some null pointer dereference risks in the code, which will produce `NullPointerException` in some cases.

### Modifications

Add some object non-null judgments or modify the code's processing logic.

### Verifying this change

*(Please pick either of the following options)*

- [x] This change is a trivial rework/code cleanup without any test coverage.

- [ ] This change is already covered by existing tests, such as:
  *(please describe tests)*

- [ ] This change added tests and can be verified as follows:

  *(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Documentation

  - Does this pull request introduce a new feature? no

### CODE REVIEW

File: inlong-sort/sort-formats/format-common/src/main/java/org/apache/inlong/sort/formats/util/StringUtils.java [hunk 1]
```diff
@@ -97,133 +97,135 @@ public static List<Map<String, String>> splitKv(
...
-                        state = STATE_KEY;
-                        break;
-                    case STATE_ESCAPING:
-                        stringBuilder.append(ch);
-                        state = STATE_NORMAL;
-                        break;
-                    case STATE_QUOTING:
-                        stringBuilder.append(ch);
-                        break;
+        if (text != null) {
```
Comment (luchunliang) [inline inlong-sort/sort-formats/format-common/src/main/java/org/apache/inlong/sort/formats/util/StringUtils.java:100]: If text == null, then it is better to return lines directly.

Comment (yfsn666) [reply inlong-sort/sort-formats/format-common/src/main/java/org/apache/inlong/sort/formats/util/StringUtils.java]: fixed.

**Review by aloyszhang — APPROVED** [review]

**Review by justinwwhuang — APPROVED** [review]

**Review by dockerzhang — APPROVED** [review]

**Review by vernedeng — APPROVED** [review]
