### PR TITLE
[INLONG-6968][Sort] Fix the SqlParseException: Encountered "\'"

### LINKED ISSUE #6968: [Bug][Sort] SqlParseException: Encountered "\'"
### What happened

When use sort cli to start flink job,  command like this:
```shell
bin/flink run -c org.apache.inlong.sort.Entrance lib/sort-dist-1.5.0-SNAPSHOT.jar \
--checkpoint.interval 60000 \
--sql.script.file ../sql/group_07.sql
```

occur the following exception:
```java
Caused by: org.apache.calcite.sql.parser.SqlParseException: Encountered "\'" at line 10, column 37.
Was expecting one of:
    <BINARY_STRING_LITERAL> ...
    <QUOTED_STRING> ...
    <PREFIXED_STRING_LITERAL> ...
    <UNICODE_STRING_LITERAL> ...
    <BIG_QUERY_DOUBLE_QUOTED_STRING> ...
    <BIG_QUERY_QUOTED_STRING> ...

	at org.apache.flink.sql.parser.impl.FlinkSqlParserImpl.convertException(FlinkSqlParserImpl.java:452)
	at org.apache.flink.sql.parser.impl.FlinkSqlParserImpl.normalizeException(FlinkSqlParserImpl.java:215)
	at org.apache.calcite.sql.parser.SqlParser.handleException(SqlParser.java:140)
	at org.apache.calcite.sql.parser.SqlParser.parseQuery(SqlParser.java:155)
	at org.apache.calcite.sql.parser.SqlParser.parseStmt(SqlParser.java:180)
	at org.apache.flink.table.planner.parse.CalciteParser.parse(CalciteParser.java:54)
	... 18 more
```

sql like this:
```sql
CREATE TABLE `table_stream_01`(
    `uid` STRING,
    `event_time` STRING)
    WITH (
    'inlong.metric.labels' = 'groupId=group_07&streamId=stream_01&nodeId=stream_01',
    'metrics.audit.proxy.hosts' = 'x.x.x.x:10081',
    'connector' = 'pulsar-inlong',
    'csv.allow-comments' = 'false',
    'csv.disable-quote-character' = 'true',
    'csv.array-element-delimiter' = ';',
    'csv.ignore-parse-errors' = 'true',
    'format' = 'csv',
    'csv.field-delimiter' = ',',
    'admin-url' = 'http://x.x.x.x:8080',
    'generic' = 'true',
    'service-url' = 'pulsar://x.x.x.x:6650',
    'topic' = 'public/group_07/stream_01',
    'scan.startup.mode' = 'earliest'
);
CREATE TABLE `node_sink_01_test_index_1219_v1`(
    PRIMARY KEY (`uid`) NOT ENFORCED,
    `uid` STRING,
    `event_time` STRING)
    WITH (
    'inlong.metric.labels' = 'groupId=group_07&streamId=stream_01&nodeId=sink_01',
    'metrics.audit.proxy.hosts' = 'x.x.x.x:10081',
    'connector' = 'elasticsearch-6-inlong',
    'document-type' = '_doc',
    'hosts' = 'http://x.x.x.x:9200;http://x.x.x.x:9200',
    'index' = 'test_index_1219_v1',
    'password' = 'xxx',
    'username' = 'xxx'
);
INSERT INTO `node_sink_01_test_index_1219_v1`
    SELECT
    `uid` AS `uid`,
    `event_time` AS `event_time`
    FROM `table_stream_01`
```

### What you expected to happen

This option `'csv.array-element-delimiter' = ';'` contains `;`.  And then, `NativeFlinkSqlParser#parse`  split sqls by `;` cause the problem.

### How to reproduce

Use the above SQL can reproduce the problem.

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Sort

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by wangpeix**
### Prepare a Pull Request

- Title: [INLONG-6968][Sort] SqlParseException: Encountered "\\'".

- Fixes #6968 

### Motivation

Fix SqlParseException: Encountered "\\'".

### Modifications
`NativeFlinkSqlParser` splits sql statements by semicolon and newline character.

### CODE REVIEW

**Review by dockerzhang — APPROVED** [review]

File: inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/parser/impl/NativeFlinkSqlParser.java [hunk 1]
```diff
@@ -82,7 +82,7 @@ public ParseResult parse() {
         Preconditions.checkNotNull(tableEnv, "tableEnv is null");
         List<String> createTableSqls = new ArrayList<>();
         List<String> insertSqls = new ArrayList<>();
-        String[] statementSet = statements.split(";");
+        String[] statementSet = statements.split(";(\\r?\\n|\\r)");
```
Comment (yunqingmoswu) [inline inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/parser/impl/NativeFlinkSqlParser.java:85]: Maybe it is better for ';(\\r?\\n|\\r|\\n)'?

Comment (wangpeix) [reply inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/parser/impl/NativeFlinkSqlParser.java:85]: In most case, `;(\\r?\\n|\\r)`  is ok. But If there is a sql statement like this `concat(';\n','b')`, may be problem.

**Review by healchow — APPROVED** [review]

**Review by gong — APPROVED** [review]

**Review by EMsnap — APPROVED** [review]

**Review by yunqingmoswu — APPROVED** [review]
