### PR TITLE
[INLONG-5499][Manager] Fix the status of the data source was wrong

### LINKED ISSUE #5499: [Bug][Manager] The data source is successful, but the status always is issued or added
### What happened

The file or binlog data source is successfully configured, and the status is always [issued and added]

### What you expected to happen

After receiving the command from the agent, the data source will change to normal state

### How to reproduce

View data source status after approval

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by fuweng11**
### Prepare a Pull Request
- Fixes #5499 

### Motivation

Make sure after receiving the command from the agent, the data source will change to normal state

### Modifications
After updating the data source status, return to version correctly

### Verifying this change

*(Please pick either of the following options)*

- [X] This change is a trivial rework/code cleanup without any test coverage.

- [ ] This change is already covered by existing tests, such as:
  *(please describe tests)*

- [ ] This change added tests and can be verified as follows:

### Documentation

  - Does this pull request introduce a new feature? (no)

### CODE REVIEW

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java [hunk 1]
```diff
@@ -192,6 +192,7 @@ private List<DataConfig> fetchNonFileTasks(TaskRequest taskRequest) {
             sourceEntity.setAgentIp(taskRequest.getAgentIp());
             sourceEntity.setUuid(taskRequest.getUuid());
             if (sourceMapper.updateByPrimaryKeySelective(sourceEntity) == 1) {
+                sourceEntity.setVersion(sourceEntity.getVersion() + 1);
```
Comment (healchow) [inline inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java:195]: Suggest changing to `++sourceEntity.getVersion()`.

Comment (fuweng11) [reply inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java:195]: Cannot proceed` ++sourceEntity.getVersion(`

**Review by healchow — APPROVED** [review]

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java (hunk 1 above)
Comment (healchow) [reply inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java:195]: OK👌

**Review by dockerzhang — APPROVED** [review]

**Review by woofyzhao — APPROVED** [review]

**Review by gong — APPROVED** [review]
