### PR TITLE
[INLONG-10547][Agent] Provide a clear prompt after the mq type is incorrect

### LINKED ISSUE #10547: [Improve][Agent] Provide a clear prompt after the mq type is incorrect
### Description

Provide a clear prompt after the mq type is incorrect

### InLong Component

InLong Agent

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by justinwwhuang**
Fixes #10547 

### Motivation

Provide a clear prompt after the mq type is incorrect

### Modifications

Directly prompt for mq type error

### Verifying this change

*(Please pick either of the following options)*

- [x] This change is a trivial rework/code cleanup without any test coverage.

- [ ] This change is already covered by existing tests, such as:
  *(please describe tests)*

- [ ] This change added tests and can be verified as follows:

  *(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Documentation

No doc needed

### CODE REVIEW

File: inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/fetcher/TestManager.java [hunk 1]
```diff
@@ -0,0 +1,65 @@
...
+            List<TaskProfile> taskProfiles = new ArrayList<>();
+            taskResult.getDataConfigs().forEach((config) -> {
+                TaskProfile profile = TaskProfile.convertToTaskProfile(config);
+                taskProfiles.add(profile);
+            });
+            Assert.assertEquals(taskProfiles.size(), taskNum);
+        } catch (Throwable ex) {
+            LOGGER.warn("exception caught", ex);
+            Assert.assertTrue(false);
+        }
```
Comment (aloyszhang) [inline inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/fetcher/TestManager.java:63]: Just throw exception is ok, not need to catch it

**Review by aloyszhang — APPROVED** [review]

**Review by doleyzi — APPROVED** [review]
LGTM
