### PR TITLE
[INLONG-6561][Manager] Fix the InlongGroup cannot be deleted

### LINKED ISSUE #6561: [Bug][Manager] Failed to delete InlongGroup
### What happened

```
2022-11-16 18:39:31.914 -DEBUG [http-nio-8083-exec-9] o.a.i.l.j.BaseJdbcLogger      :137 - <==      Total: 0
2022-11-16 18:39:31.995 -ERROR [http-nio-8083-exec-9] a.i.m.w.e.LogableEventListener:87 - execute listener WorkflowEventLogEntity(id=null, processId=70, processName=DELETE_GROUP_PROCESS, processDisplayName=Delete-Group, inlongGroupId=test_20221111_244, taskId=null, elementName=EndEvent, elementDisplayName=EndEvent, eventType=ProcessEvent, event=COMPLETE, listener=UpdateGroupCompleteListener, startTime=Wed Nov 16 18:39:31 CST 2022, endTime=null, status=-1, async=0, ip=10.160.141.235, remark=null, exception=groupId is invalid) error:
java.lang.IllegalArgumentException: groupId is invalid
```
Failed to delete inlongGroup.

### What you expected to happen

Successfully deleted group.

### How to reproduce

Configure a group, delete stream and source, and then delete the group.

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by fuweng11**
### Prepare a Pull Request
- Fixes #6561 

### Motivation

 Fix the problem that the group cannot be deleted

### Modifications

Delete stream before deleting group.

### CODE REVIEW

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupServiceImpl.java [hunk 1]
```diff
@@ -453,6 +453,10 @@ public Boolean delete(String groupId, String operator) {
         InlongGroupEntity entity = groupMapper.selectByGroupId(groupId);
         Preconditions.checkNotNull(entity, ErrorCodeEnum.GROUP_NOT_FOUND.getMessage());
```
Comment (healchow) [inline inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupServiceImpl.java:455]: Suggest adding a comment: 
```
before deleting an inlong group, delete all inlong streams, sources, sinks, and other info under it
```

**Review by healchow — APPROVED** [review]

**Review by vernedeng — APPROVED** [review]
lgtm

**Review by gong — APPROVED** [review]
