### PR TITLE
[INLONG-7254][Manager] Fix config error when InlongGroupId is in the process of switching

### LINKED ISSUE #7254: [Bug][Manager] Fix config error when InlongGroupId is in the process of switching
### What happened

When a InlongGroupId is in the process of switching, the config of source cluster and target cluster will be mixed up.
Which doubles the data consuming from MQ.

### What you expected to happen

Only consume the clusters under the specify tag, instead of both target tag and backup tag.

### How to reproduce

Switch one InlongGroupId

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by vernedeng**
### Prepare a Pull Request

- Fixes #7254 

### Motivation

When a InlongGroupId is in the process of switching, the config of source cluster and target cluster will be mixed up.
Which doubles the data consuming from MQ.

The solution is to check if the target sort cluster is tagged. If so, fiter the MQs under this tag; otherwise, get all MQs of both source and target MQs.

### Modifications

*Describe the modifications you've done.*

### Verifying this change

*(Please pick either of the following options)*

- [ ] This change added tests and can be verified as follows: Swiching in tagged/untagged cluster.

### Documentation

  - Does this pull request introduce a new feature? yes

### CODE REVIEW

**Review by woofyzhao — APPROVED** [review]

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/SortSourceServiceImpl.java [hunk 1]
```diff
@@ -285,8 +290,12 @@ private void parseAll() {
     }
 
     private Map<String, CacheZone> parseCacheZones(
+            String clusterName,
             List<SortSourceStreamSinkInfo> sinkList) {
 
+        Preconditions.checkNotNull(sortClusters.get(clusterName));
```
Comment (healchow) [inline inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/SortSourceServiceImpl.java:296]: Suggest use the `Preconditions` in manager-common module.

Comment (vernedeng) [reply inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/SortSourceServiceImpl.java]: Fixed, thx

**Review by healchow — APPROVED** [review]
LGTM

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/SortSourceServiceImpl.java [hunk 2]
```diff
@@ -296,14 +305,26 @@ private Map<String, CacheZone> parseCacheZones(
 
         // group them by cluster tag.
         Map<String, List<SortSourceStreamSinkInfo>> tag2SinkInfos = sinkInfoList.stream()
+                .filter(sink -> {
+                    if (StringUtils.isBlank(sortClusterTag)) {
+                        return true;
+                    }
+                    return groupInfos.get(sink.getGroupId()).getClusterTag().equals(sortClusterTag);
```
Comment (fuweng11) [inline inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/SortSourceServiceImpl.java:312]: Maybe there will be NPE?

**Review by gosonzhang — APPROVED** [review]

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/SortSourceServiceImpl.java (hunk 2 above)
Comment (vernedeng) [reply inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/SortSourceServiceImpl.java:312]: The NPE will be thrown when there is a stream sink of a groupId  but this groupId does not exist in inlong_group table. I will add one more filter condition to avoid this case.

**Review by fuweng11 — APPROVED** [review]

**Review by dockerzhang — APPROVED** [review]
