### PR TITLE
[INLONG-6763][Manager] Remove unnecessary validation when saving HiveSinkRequest

### LINKED ISSUE #6763: [Bug][Manager] Remove unnecessary validation when saving HiveSinkRequest
### What happened

You can select data node for the hive flow.
But the current code limits `dataPath` and `jdbcUrl` to null.

### What you expected to happen

We need to release this constraint so that we can select Datanodes without `dataPath` and `jdbcUrl`

### How to reproduce

Save hiveSink without `dataPath` and `jdbcurl`.

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by fuweng11**
### Prepare a Pull Request
- Fixes #6763 

### Motivation

Remove unnecessary validation when saving HiveSinkRequest
### Modifications

Remove unnecessary validation when saving HiveSinkRequest

### CODE REVIEW

**Review by gong — APPROVED** [review]

File: inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/hive/HiveSinkRequest.java [hunk 1]
```diff
@@ -41,7 +41,6 @@
 @JsonTypeDefine(value = SinkType.HIVE)
 public class HiveSinkRequest extends SinkRequest {
 
-    @NotBlank(message = "jdbcUrl cannot be blank")
     @ApiModelProperty("Hive JDBC URL, such as jdbc:hive2://${ip}:${port}")
```
Comment (vernedeng) [inline inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/hive/HiveSinkRequest.java:44]: Maybe need more UT to ensure the blacnk jdbcUrl will not cause some unexcepted failure.

**Review by vernedeng — APPROVED** [review]
lgtm

**Review by dockerzhang — APPROVED** [review]

**Review by healchow — APPROVED** [review]
