### PR TITLE
[INLONG-6771][Manager] Add login failure limit

### LINKED ISSUE #6771: [Improve][Manager] Add login failure limit
### Description

if the user login fails, we should limit the login times to prevent violent retries.

here we can limit it to 3 fails times and wait for 15/30 minutes.

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by leosanqing**
### Prepare a Pull Request
*(Change the title refer to the following example)*

- Title Example: [INLONG-XYZ][Component] Title of the pull request

*(The following *XYZ* should be replaced by the actual [GitHub Issue](https://github.com/apache/inlong/issues) number)*

- Fixes #6771

### Motivation

if the user login fails, we should limit the login times to prevent violent retries.

here we can limit it to 10 fails times and wait for 3 minutes.

### Modifications
loginService

### Verifying this change

- [x] This change is already covered by existing tests, such as:
- AnnoControllerTest

### Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a follow-up issue for adding the documentation

### CODE REVIEW

File: inlong-manager/manager-web/sql/apache_inlong_manager.sql [hunk 1]
```diff
@@ -540,6 +540,10 @@ VALUES ('admin', '1976e096b31cfda81269d0df2775466aac6dd809e3ada1d5ba7831d85e80f1
         '9B5DCE950F284141D5493A2DAFEBD1BFEECE075FC5F426E8B67F33F14876E2D0', 0, 1,
         '2099-12-31 23:59:59', 'inlong_init', 'inlong_init');
 
+VALUES ('test_lock_account', '1976e096b31cfda81269d0df2775466aac6dd809e3ada1d5ba7831d85e80f109',
```
Comment (healchow) [inline inlong-manager/manager-web/sql/apache_inlong_manager.sql:543]: Those changes seem only needed in the test SQL file.

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/user/UserServiceImpl.java [hunk 2]
```diff
@@ -245,4 +262,55 @@ public Boolean delete(Integer userId, String currentUser) {
...
+     * database. The memory method used, the number of multi-node logins is not shared, and a single node is not safe
+     * in high concurrency
+     *
+     * @param req username and pwd
+     */
+    @Override
+    public void login(UserLoginRequest req) {
+        String username = req.getUsername();
+
+        UserLoginLockStatus userLoginLockStatus = loginLockStatusMap.get(username);
```
Comment (healchow) [inline inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/user/UserServiceImpl.java:276]: Maybe change to follow is better,
```
UserLoginLockStatus userLoginLockStatus = loginLockStatusMap.getOrDefault(username, new UserLoginLockStatus());
```

Then there is no need for `if` and `else` to check whether the `userLoginLockStatus` is null or not because you check `lockoutTime != null` at the following.

**Review by healchow — CHANGES_REQUESTED** [review]

**Comment by dockerzhang** [comment]
@fuweng11 PTAL, thanks.

**Review by gosonzhang — APPROVED** [review]

**Review by dockerzhang — APPROVED** [review]
