### PR TITLE
[INLONG-6526][Manager] Fix the manager-client force delete the stream source failed

### LINKED ISSUE #6526: [Bug][Manager] The manager-client force delete the stream source failed
### What happened

The mananger-client calling to forcibly delete the source interface failed.

### What you expected to happen

The mananger-client calling to forcibly delete the source interface successfully.

### How to reproduce

Use the manager client to call the interface to forcibly delete the source.

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by fuweng11**
### Prepare a Pull Request
- Fixes #6526 

### Motivation

 Fix the problem of mananger-client calling to forcibly delete the source interface failed

### Modifications

Modified the parameter name of the interface.

### CODE REVIEW

**Review by gong — APPROVED** [review]

File: inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/StreamSourceController.java [hunk 1]
```diff
@@ -91,11 +91,12 @@ public Response<Boolean> delete(@PathVariable Integer id) {
...
     @ApiOperation(value = "Force delete stream source by groupId and streamId")
     @ApiImplicitParams({
-            @ApiImplicitParam(name = "groupId", dataTypeClass = String.class, required = true),
-            @ApiImplicitParam(name = "streamId", dataTypeClass = String.class, required = true)
+            @ApiImplicitParam(name = "inlongGroupId", dataTypeClass = String.class, required = true),
+            @ApiImplicitParam(name = "inlongStreamId", dataTypeClass = String.class, required = true)
     })
-    public Response<Boolean> forceDelete(@RequestParam String groupId, @RequestParam String streamId) {
-        return Response.success(sourceService.forceDelete(groupId, streamId, LoginUserUtils.getLoginUser().getName()));
+    public Response<Boolean> forceDelete(@RequestParam String inlongGroupId, @RequestParam String inlongStreamId) {
```
Comment (healchow) [inline inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/StreamSourceController.java:97]: Suggest changing in the client module.

**Review by woofyzhao — APPROVED** [review]

**Review by haifxu — APPROVED** [review]

File: inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/StreamSourceController.java (hunk 1 above)
Comment (healchow) [reply inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/StreamSourceController.java:97]: Fine, It can be added to any module.

**Review by healchow — APPROVED** [review]

**Review by vernedeng — APPROVED** [review]
