### PR TITLE
[INLONG-11071][Manager] Fix: failed to handle request on inlong_agent_system by admin

### LINKED ISSUE #11071: [Bug][Manager] Failed to handle request on inlong_agent_system by admin
### What happened

When the manager container is started, the console will continue to output error logs like this:
```
[ ] 2024-09-09 14:26:04.467 -ERROR [http-nio-8083-exec-5] w.c.ControllerExceptionHandler:152 - failed to handle request on path: /inlong/manager/openapi/dataproxy/getIpList/inlong_agent_system by user: admin 
2024-09-09T14:26:04.608632436Z java.lang.NullPointerException: null
2024-09-09T14:26:04.608639991Z 	at org.apache.inlong.manager.service.cluster.InlongClusterServiceImpl.getDataProxyNodes(InlongClusterServiceImpl.java:913) ~[manager-service-1.14.0-SNAPSHOT.jar:1.14.0-SNAPSHOT]
2024-09-09T14:26:04.608655587Z 	at org.apache.inlong.manager.service.cluster.InlongClusterServiceImpl$$FastClassBySpringCGLIB$$5ac56ec1.invoke(<generated>) ~[manager-service-1.14.0-SNAPSHOT.jar:1.14.0-SNAPSHOT]
2024-09-09T14:26:04.608663306Z 	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.34.jar:5.3.34]
2024-09-09T14:26:04.608670472Z 	at org.springframework.aop.framework.CglibAopProxy.invokeMethod(CglibAopProxy.java:386) ~[spring-aop-5.3.27.jar:5.3.27]
2024-09-09T14:26:04.608677344Z 	at org.springframework.aop.framework.CglibAopProxy.access$000(CglibAopProxy.java:85) ~[spring-aop-5.3.27.jar:5.3.27]
2024-09-09T14:26:04.608685223Z 	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:704) ~[spring-aop-5.3.27.jar:5.3.27]
2024-09-09T14:26:04.608692329Z 	at org.apache.inlong.manager.service.cluster.InlongClusterServiceImpl$$EnhancerBySpringCGLIB$$14e2a679.getDataProxyNodes(<generated>) ~[manager-service-1.14.0-SNAPSHOT.jar:1.14.0-SNAPSHOT]
2024-09-09T14:26:04.608700353Z 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_342]
2024-09-09T14:26:04.608709294Z 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_342]
2024-09-09T14:26:04.608719567Z 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_342]
2024-09-09T14:26:04.608729772Z 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_342]
2024-09-09T14:26:04.608738559Z 	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344) ~[spring-aop-5.3.27.jar:5.3.27]
2024-09-09T14:26:04.608748478Z 	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213) ~[spring-aop-5.3.27.jar:5.3.27]
2024-09-09T14:26:04.608759208Z 	at com.sun.proxy.$Proxy210.getDataProxyNodes(Unknown Source) ~[?:?]
2024-09-09T14:26:04.608770692Z 	at org.apache.inlong.manager.web.controller.openapi.DataProxyController.getIpList(DataProxyController.java:59) ~[manager-web.jar:1.14.0-SNAPSHOT]
2024-09-09T14:26:04.608778623Z 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_342]
2024-09-09T14:26:04.608785350Z 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_342]
2024-09-09T14:26:04.608792368Z 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_342]
2024-09-09T14:26:04.608801248Z 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_342]
2024-09-09T14:26:04.608810963Z 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-5.3.34.jar:5.3.34]
2024-09-09T14:26:04.608820145Z 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150) ~[spring-web-5.3.34.jar:5.3.34]
2024-09-09T14:26:04.608830037Z 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) ~[spring-webmvc-5.3.27.jar:5.3.27]
2024-09-09T14:26:04.608845235Z 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[spring-webmvc-5.3.27.jar:5.3.27]
2024-09-09T14:26:04.608855787Z 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) ~[spring-webmvc-5.3.27.jar:5.3.27]
2024-09-09T14:26:04.608863213Z 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.3.27.jar:5.3.27]
2024-09-09T14:26:04.608873760Z 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1072) ~[spring-webmvc-5.3.27.jar:5.3.27]
2024-09-09T14:26:04.608883791Z 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:965) ~[spring-webmvc-5.3.27.jar:5.3.27]
2024-09-09T14:26:04.608893431Z 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.3.27.jar:5.3.27]
2024-09-09T14:26:04.608904619Z 	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) ~[spring-webmvc-5.3.27.jar:5.3.27]
2024-09-09T14:26:04.608933869Z 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:555) ~[tomcat-embed-core-9.0.75.jar:4.0.FR]
2024-09-09T14:26:04.608941297Z 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.3.27.jar:5.3.27]
2024-09-09T14:26:04.608952134Z 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:623) ~[tomcat-embed-core-9.0.75.jar:4.0.FR]
2024-09-09T14:26:04.608961190Z 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209) ~[tomcat-embed-core-9.0.75.jar:9.0.75]
2024-09-09T14:26:04.608972108Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.75.jar:9.0.75]
2024-09-09T14:26:04.608983375Z 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51) ~[tomcat-embed-websocket-9.0.75.jar:9.0.75]
2024-09-09T14:26:04.608994369Z 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[tomcat-embed-core-9.0.75.jar:9.0.75]
2024-09-09T14:26:04.609002187Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.75.jar:9.0.75]
2024-09-09T14:26:04.609013319Z 	at org.apache.inlong.manager.web.filter.TenantInsertionFilter.doFilter(TenantInsertionFilter.java:71) ~[manager-web.jar:1.14.0-SNAPSHOT]
2024-09-09T14:26:04.609025138Z 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[tomcat-embed-core-9.0.75.jar:9.0.75]
2024-09-09T14:26:04.609034891Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.75.jar:9.0.75]
2024-09-09T14:26:04.609044656Z 	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61) ~[shiro-web-1.13.0.jar:1.13.0]
2024-09-09T14:26:04.609061636Z 	at org.apache.inlong.manager.web.auth.tenant.TenantAuthenticatingFilter.doFilter(TenantAuthenticatingFilter.java:81) ~[manager-web.jar:1.14.0-SNAPSHOT]
2024-09-09T14:26:04.609073668Z 	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66) ~[shiro-web-1.13.0.jar:1.13.0]
2024-09-09T14:26:04.609084912Z 	at org.apache.inlong.manager.web.auth.openapi.OpenAPIFilter.doFilter(OpenAPIFilter.java:84) ~[manager-web.jar:1.14.0-SNAPSHOT]
2024-09-09T14:26:04.609092854Z 	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66) ~[shiro-web-1.13.0.jar:1.13.0]
2024-09-09T14:26:04.609103899Z 	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108) ~[shiro-web-1.13.0.jar:1.13.0]
2024-09-09T14:26:04.609113752Z 	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137) ~[shiro-web-1.13.0.jar:1.13.0]
2024-09-09T14:26:04.609123085Z 	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:154) ~[shiro-web-1.13.0.jar:1.13.0]
2024-09-09T14:26:04.609133078Z 	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66) ~[shiro-web-1.13.0.jar:1.13.0]
2024-09-09T14:26:04.609144322Z 	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:458) ~[shiro-web-1.13.0.jar:1.13.0]
2024-09-09T14:26:04.609155333Z 	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:373) ~[shiro-web-1.13.0.jar:1.13.0]
2024-09-09T14:26:04.609166062Z 	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90) ~[shiro-core-1.13.0.jar:1.13.0]
2024-09-09T14:26:04.609173127Z 	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83) ~[shiro-core-1.13.0.jar:1.13.0]
2024-09-09T14:26:04.609180250Z 	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:387) ~[shiro-core-1.13.0.jar:1.13.0]
2024-09-09T14:26:04.609187949Z 	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:370) ~[shiro-web-1.13.0.jar:1.13.0]
2024-09-09T14:26:04.609194800Z 	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:154) ~[shiro-web-1.13.0.jar:1.13.0]
2024-09-09T14:26:04.609202128Z 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[tomcat-embed-core-9.0.75.jar:9.0.75]
2024-09-09T14:26:04.609209264Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.75.jar:9.0.75]
2024-09-09T14:26:04.609216750Z 	at org.apache.inlong.manager.web.trace.TraceFilter.doFilter(TraceFilter.java:80) ~[manager-web.jar:1.14.0-SNAPSHOT]
2024-09-09T14:26:04.609224161Z 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[tomcat-embed-core-9.0.75.jar:9.0.75]
2024-09-09T14:26:04.609232155Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.75.jar:9.0.75]
2024-09-09T14:26:04.609240086Z 	at org.apache.inlong.manager.web.filter.EmptyTenantFilter.doFilter(EmptyTenantFilter.java:50) ~[manager-web.jar:1.14.0-SNAPSHOT]
2024-09-09T14:26:04.609251686Z 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[tomcat-embed-core-9.0.75.jar:9.0.75]
2024-09-09T14:26:04.609258979Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.75.jar:9.0.75]
2024-09-09T14:26:04.609266805Z 	at org.apache.inlong.manager.web.filter.HttpServletRequestFilter.doFilter(HttpServletRequestFilter.java:45) ~[manager-web.jar:1.14.0-SNAPSHOT]
2024-09-09T14:26:04.609274056Z 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[tomcat-embed-core-9.0.75.jar:9.0.75]
2024-09-09T14:26:04.609281400Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.75.jar:9.0.75]
2024-09-09T14:26:04.609288308Z 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.3.34.jar:5.3.34]
2024-09-09T14:26:04.609295387Z 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.34.jar:5.3.34]
2024-09-09T14:26:04.609302311Z 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[tomcat-embed-core-9.0.75.jar:9.0.75]
2024-09-09T14:26:04.609309513Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.75.jar:9.0.75]
2024-09-09T14:26:04.609316513Z 	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.3.34.jar:5.3.34]
2024-09-09T14:26:04.609324447Z 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.34.jar:5.3.34]
2024-09-09T14:26:04.609331374Z 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[tomcat-embed-core-9.0.75.jar:9.0.75]
2024-09-09T14:26:04.609338907Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.75.jar:9.0.75]
2024-09-09T14:26:04.609345653Z 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.3.34.jar:5.3.34]
2024-09-09T14:26:04.609352971Z 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.34.jar:5.3.34]
2024-09-09T14:26:04.609360482Z 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[tomcat-embed-core-9.0.75.jar:9.0.75]
2024-09-09T14:26:04.609367438Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.75.jar:9.0.75]
2024-09-09T14:26:04.609374372Z 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167) ~[tomcat-embed-core-9.0.75.jar:9.0.75]
2024-09-09T14:26:04.609381449Z 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90) ~[tomcat-embed-core-9.0.75.jar:9.0.75]
2024-09-09T14:26:04.609392974Z 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481) ~[tomcat-embed-core-9.0.75.jar:9.0.75]
2024-09-09T14:26:04.609400303Z 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130) ~[tomcat-embed-core-9.0.75.jar:9.0.75]
2024-09-09T14:26:04.609407647Z 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) ~[tomcat-embed-core-9.0.75.jar:9.0.75]
2024-09-09T14:26:04.609415412Z 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[tomcat-embed-core-9.0.75.jar:9.0.75]
2024-09-09T14:26:04.609422443Z 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) ~[tomcat-embed-core-9.0.75.jar:9.0.75]
2024-09-09T14:26:04.609429845Z 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390) ~[tomcat-embed-core-9.0.75.jar:9.0.75]
2024-09-09T14:26:04.609436792Z 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) ~[tomcat-embed-core-9.0.75.jar:9.0.75]
2024-09-09T14:26:04.609443663Z 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:926) ~[tomcat-embed-core-9.0.75.jar:9.0.75]
2024-09-09T14:26:04.609450450Z 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791) ~[tomcat-embed-core-9.0.75.jar:9.0.75]
2024-09-09T14:26:04.609457377Z 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[tomcat-embed-core-9.0.75.jar:9.0.75]
2024-09-09T14:26:04.609464474Z 	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-9.0.75.jar:9.0.75]
2024-09-09T14:26:04.609472193Z 	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-9.0.75.jar:9.0.75]
2024-09-09T14:26:04.609480361Z 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.75.jar:9.0.75]
2024-09-09T14:26:04.609487457Z 	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_342]
```

### What you expected to happen

Resolving errors

### How to reproduce

Run the manager module through docker-compose， you can find the error logs at the console

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [x] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by qy-liuhuo**
Fixes #11071 

### Motivation

When the dataproxy module requests the `/dataproxy/getIpList/inlong_agent_system` interface, an error occurs because there is no record in the `inlong_group` table where the `inlong_group_id` is equals to `inlong_agent_system`. This results in the manager console continuously outputting exceptions

### Modifications

- Changed getDataProxyNodes function in the `org/apache/inlong/manager/service/cluster/InlongClusterServiceImpl.java` file to throw an exception when there is no record in the `inlong_group` table where the `inlong_group_id` is equals to `inlong_agent_system`

- Changed getIpList function in the `org/apache/inlong/manager/web/controller/openapi/DataProxyController.java` file to return fail response when an exception occurs in the `getDataProxyNodes` function. 

### Verifying this change

Previous error message：

```
[ ] 2024-09-09 14:26:04.467 -ERROR [http-nio-8083-exec-5] w.c.ControllerExceptionHandler:152 - failed to handle request on path: /inlong/manager/openapi/dataproxy/getIpList/inlong_agent_system by user: admin 
2024-09-09T14:26:04.608632436Z java.lang.NullPointerException: null
2024-09-09T14:26:04.608639991Z 	at org.apache.inlong.manager.service.cluster.InlongClusterServiceImpl.getDataProxyNodes(InlongClusterServiceImpl.java:913) ~[manager-service-1.14.0-SNAPSHOT.jar:1.14.0-SNAPSHOT]
2024-09-09T14:26:04.608655587Z 	at org.apache.inlong.manager.service.cluster.InlongClusterServiceImpl$$FastClassBySpringCGLIB$$5ac56ec1.invoke(<generated>) ~[manager-service-1.14.0-SNAPSHOT.jar:1.14.0-SNAPSHOT]
...
...
```
Current error log：

```
2024-09-13T11:43:02.098668598Z [ ] 2024-09-13 11:43:01.248 -ERROR [http-nio-8083-exec-3] m.s.c.InlongClusterServiceImpl:915 - group not found by groupId=inlong_agent_system 
```

### CODE REVIEW

**Review by aloyszhang — DISMISSED** [review]

File: inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/DataProxyController.java [hunk 1]
```diff
@@ -56,7 +56,11 @@ public class DataProxyController {
     @ApiOperation(value = "Get data proxy IP list by InlongGroupId")
     public Response<DataProxyNodeResponse> getIpList(@PathVariable String inlongGroupId,
             @RequestParam(required = false) String protocolType) {
-        return Response.success(clusterService.getDataProxyNodes(inlongGroupId, protocolType));
+        try {
```
Comment (fuweng11) [inline inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/DataProxyController.java:59]: There is no need to catch exceptions here, BusinessException will be handled in the ControlExceptionHandler.

Comment (qy-liuhuo) [reply inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/DataProxyController.java]: Thank you，I have removed it

**Review by fuweng11 — APPROVED** [review]

**Review by dockerzhang — APPROVED** [review]
