### PR TITLE
[INLONG-12065][Sort] Sort Format supports outputting complete row information when field parsing errors occur.

### LINKED ISSUE #12065: [Improve][Sort] Sort Format supports outputting complete row information when errors occur in field parsing.
### Description

Sort Format supports outputting complete row information when errors occur in field parsing.eg:
It only prints the field information when parsing fails. 
```
try {
            return ((BasicFormatInfo<?>) fieldFormatInfo).deserialize(fieldText);
        } catch (Exception e) {
            if (failureHandler != null) {
                failureHandler.onConvertingFieldFailure(fieldName, fieldText, fieldFormatInfo, e);
            } else {
                LOG.warn("Could not properly deserialize the" + "text: {},for field:{}",
                        fieldText, fieldName, e);
            }
        }
```
It is expected to output the complete row information when an error occurs. such as
```
try {
            return ((BasicFormatInfo<?>) fieldFormatInfo).deserialize(fieldText);
        } catch (Exception e) {
            if (failureHandler != null) {
                failureHandler.onConvertingFieldFailure(fieldName, fieldText, fieldFormatInfo,
                        head, inLongMsgBody, originBody, e);
            } else {
                LOG.warn("Could not properly deserialize the" + "text: {},for field:{}"
                        + ". predefinedFields = {},fields = {}, attr={}, originBody={}",
                        fieldText, fieldName,
                        head == null ? "" : head.getPredefinedFields(),
                        inLongMsgBody == null ? "" : inLongMsgBody.getFields(),
                        head == null ? "" : head.getAttributes(),
                        originBody == null ? (inLongMsgBody == null ? "" : new String(inLongMsgBody.getDataBytes()))
                                : originBody,
                        e);
            }
        }
```

### InLong Component

InLong Sort

### Are you willing to submit PR?

- [x] Yes, I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by baomingyu**
Fixes #12065 
### Modifications
modifications like this
>
```
try {

            return ((BasicFormatInfo<?>) fieldFormatInfo).deserialize(fieldText);
        } catch (Exception e) {
            if (failureHandler != null) {
                failureHandler.onConvertingFieldFailure(fieldName, fieldText, fieldFormatInfo,
                        head, inLongMsgBody, originBody, e);
            } else {
                LOG.warn("Could not properly deserialize the" + "text: {},for field:{}"
                        + ". predefinedFields = {},fields = {}, attr={}, originBody={}",
                        fieldText, fieldName,
                        head == null ? "" : head.getPredefinedFields(),
                        inLongMsgBody == null ? "" : inLongMsgBody.getFields(),
                        head == null ? "" : head.getAttributes(),
                        originBody == null ? (inLongMsgBody == null ? "" : new String(inLongMsgBody.getDataBytes()))
                                : originBody,
                        e);
            }
        }
```

When defining the failureHandler, the output shall be generated through onConvertingFieldFailure if it is implemented; otherwise, the output shall be written to the log.

### CODE REVIEW

File: inlong-sort/sort-formats/format-common/src/main/java/org/apache/inlong/sort/formats/inlongmsg/InLongMsgBody.java [hunk 1]
```diff
@@ -25,14 +28,20 @@
...
+@Data
 public class InLongMsgBody implements Serializable {
 
     private static final long serialVersionUID = 1L;
 
     /**
      * The body of the record.
      */
-    private final byte[] data;
+    private final byte[] dataBytes;
```
Comment (vernedeng) [inline inlong-sort/sort-formats/format-common/src/main/java/org/apache/inlong/sort/formats/inlongmsg/InLongMsgBody.java]: seems to be a compatibility issue

**Review by luchunliang — APPROVED** [review]

**Review by vernedeng — APPROVED** [review]
