### PR TITLE
[INLONG-6026][Audit] Fix the executed error of ClickHouse audit SQL file

### LINKED ISSUE #6026: [Bug][Audit] SQL file executed error for ClickHouse in Audit
### What happened

Execute the `apache_inlong_audit_clickhouse.sql` error:

```sql
5b142b25d12d :) SET NAMES utf8mb4;

Syntax error: failed at position 11 ('utf8mb4'):

SET NAMES utf8mb4;

Expected one of: token, Dot, Equals
```

```sql
5b142b25d12d :) SET FOREIGN_KEY_CHECKS = 0;

SET FOREIGN_KEY_CHECKS = 0

Query id: a79b41c4-f65e-44cf-a76d-bd49de02c293

0 rows in set. Elapsed: 0.001 sec. 

Received exception from server (version 22.1.3):
Code: 115. DB::Exception: Received from localhost:9000. DB::Exception: Unknown setting FOREIGN_KEY_CHECKS. (UNKNOWN_SETTING)
```

```sql
5b142b25d12d :) SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";

Syntax error: failed at position 16 ('"NO_AUTO_VALUE_ON_ZERO"'):

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";

Expected one of: TRUE, FALSE, literal, NULL, number, Bool, true, false, string literal
```

```sql
5b142b25d12d :) SET time_zone = "+00:00";

Syntax error: failed at position 17 ('"+00:00"'):

SET time_zone = "+00:00";

Expected one of: TRUE, FALSE, literal, NULL, number, Bool, true, false, string literal
```

### What you expected to happen

Can execute successfully.

### How to reproduce

Just execute the `apache_inlong_audit_clickhouse.sql`.

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Audit

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by ciscozhou**
### Prepare a Pull Request

- Title: [INLONG-6026][Audit] Fix the executed error of ClickHouse audit SQL file

- Fixes #6026

### Motivation

ClickHouse not support those operations, remove them.

```
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";
```

### Verifying this change

- [x] This change is a trivial rework/code cleanup without any test coverage.

### CODE REVIEW

File: inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/service/ElasticsearchService.java [hunk 1]
```diff
@@ -60,19 +59,29 @@
 public class ElasticsearchService implements InsertData, AutoCloseable {
 
     private static final Logger LOG = LoggerFactory.getLogger(ElasticsearchService.class);
+    private static final Gson GSON;
```
Comment (healchow) [inline inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/service/ElasticsearchService.java:62]: The issue associated with this PR describes an issue with the ClickHouse SQL files, and it is not recommended to submit other unrelated codes in this PR.

**Review by healchow — CHANGES_REQUESTED** [review]

File: inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/service/ElasticsearchService.java (hunk 1 above)
Comment (ciscozhou) [reply inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/service/ElasticsearchService.java:62]: OK, I will remove them.

**Review by dockerzhang — APPROVED** [review]

**Review by luchunliang — APPROVED** [review]
LGTM

**Review by baomingyu — APPROVED** [review]
+1
