### PR TITLE
[INLONG-5246][Manager] Return all cluster nodes under the same tag and type

### LINKED ISSUE #5246: [Bug][Manager] Agent gets dataproxy list and always returns empty
### What happened

企业微信截图_16589111871490

Agent gets dataproxy list and always returns empty

### What you expected to happen

All dataproxy cluster nodes can be obtained from the manager.

### How to reproduce

Using agent to obtain dataproxy node information

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by fuweng11**
### Prepare a Pull Request

- Fixes #5246 

### Motivation

Ensure that the agent can get the dataproxy node.

### Modifications

 Return all cluster nodes under the same cluster tag and type to the agent instead of return first.

### Verifying this change

- [X] This change is a trivial rework/code cleanup without any test coverage.

- [ ] This change is already covered by existing tests, such as:
  *(please describe tests)*

- [ ] This change added tests and can be verified as follows:

  *(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Documentation

  - Does this pull request introduce a new feature? (no)

### CODE REVIEW

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/InlongClusterServiceImpl.java [hunk 1]
```diff
@@ -635,19 +635,20 @@ public DataProxyNodeResponse getDataProxyNodes(String inlongGroupId) {
...
+                nodeInfo.setId(nodeEntity.getId());
+                nodeInfo.setIp(nodeEntity.getIp());
+                nodeInfo.setPort(nodeEntity.getPort());
+                nodeInfos.add(nodeInfo);
+            }
         }
 
         DataProxyNodeResponse response = new DataProxyNodeResponse();
-        response.setClusterId(clusterId);
+        response.setClusterId(clusterEntity.getId());
```
Comment (healchow) [inline inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/InlongClusterServiceImpl.java:651]: Just change to `response.setClusterId(clusterList.get(0).getId());`.

**Review by healchow — APPROVED** [review]

**Review by yunqingmoswu — APPROVED** [review]
LGTM

**Review by haifxu — APPROVED** [review]

**Review by woofyzhao — APPROVED** [review]

**Review by dockerzhang — APPROVED** [review]
