### PR TITLE
[INLONG-6316][DataProxy] Fix  heartbeat information is null

### LINKED ISSUE #6316: [Bug][DataProxy] Heartbeat information is null
### What happened

Heartbeat information is null when dataproxy start.

### What you expected to happen

Heartbeat information is not null when dataproxy start.

### How to reproduce

No

### Environment

_No response_

### InLong version

master

### InLong Component

InLong DataProxy

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by GanfengTan**
### Prepare a Pull Request
Fix  heartbeat information is null. 
- Fixes #6316 

### Motivation

Ip and port are null.

### Modifications

*Describe the modifications you've done.*

### Verifying this change

*(Please pick either of the following options)*

- [x] This change is a trivial rework/code cleanup without any test coverage.

- [ ] This change is already covered by existing tests, such as:
  *(please describe tests)*

- [ ] This change added tests and can be verified as follows:

### CODE REVIEW

**Review by woofyzhao — APPROVED** [review]

**Review by gosonzhang — APPROVED** [review]

File: inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/heartbeat/HeartbeatManager.java [hunk 1]
```diff
@@ -168,4 +174,11 @@ private HeartbeatMsg buildHeartbeat() {
         heartbeatMsg.setStreamHeartbeats(streamHeartbeats);
         return heartbeatMsg;
     }
+
+    private boolean validReportInfo(SourceReportInfo reportInfo) {
+        if (StringUtils.isBlank(reportInfo.getIp()) || StringUtils.isBlank(reportInfo.getPort())) {
```
Comment (healchow) [inline inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/heartbeat/HeartbeatManager.java:179]: Can simply to `return StringUtils.isNotBlank(reportInfo.getIp()) && StringUtils.isNotBlank(reportInfo.getPort());`.

Comment (GanfengTan) [reply inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/heartbeat/HeartbeatManager.java]: done

**Review by dockerzhang — APPROVED** [review]

**Review by healchow — APPROVED** [review]

**Review by dockerzhang — APPROVED** [review]
