### PR TITLE
[INLONG-6978][Sort] Get primary keys for PostgreSQL

### LINKED ISSUE #6978: [Bug][Sort] Get primary keys for PostgreSQL
### What happened

get primary key from exception can't meet all conditions.

### What you expected to happen

get primary key from exception meet all conditions.

### How to reproduce

get PG primary keys from connection query db instead of exception

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Sort

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by kuansix**
### Prepare a Pull Request
- [INLONG-6978][Sort] get PG primary keys from connection query db
- Fixes #6978 

### Motivation

Get primary key from exception can't meet all conditions, change to query db.

### Modifications
1.  AbstractJdbcDialect add getPkNamesFromDb function: get getPkNames from query db.tb.
2. JdbcMultiBatchingOutputFormat query getPkNamesFromDb when getOrCreateStatementExecutor.

### Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a follow-up issue for adding the documentation

### CODE REVIEW

File: inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/dialect/PostgresDialect.java [hunk 1]
```diff
@@ -137,4 +146,71 @@ public List<LogicalTypeRoot> unsupportedTypes() {
...
+                return null;
+            }
+        } catch (Exception e) {
+            LOG.error("TableIdentifier:{} getAndSetPkNamesFromDb get err:", tableIdentifier, e);
+            checkAndClose(st);
+        }
+        return null;
+    }
+
+    public void checkAndClose(PreparedStatement st) {
```
Comment (healchow) [inline inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/dialect/PostgresDialect.java:207]: It seems `private` is enough.

File: inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/dialect/PostgresDialect.java [hunk 2]
```diff
@@ -137,4 +146,71 @@ public List<LogicalTypeRoot> unsupportedTypes() {
...
+                            .setDialect(jdbcOptions.getDialect())
+                            .setParallelism(jdbcOptions.getParallelism())
+                            .setConnectionCheckTimeoutSeconds(jdbcOptions.getConnectionCheckTimeoutSeconds())
+                            .setDriverName(jdbcOptions.getDriverName())
+                            .setUsername(jdbcOptions.getUsername().orElse(""))
+                            .setPassword(jdbcOptions.getPassword().orElse(""))
+                            .build();
+            SimpleJdbcConnectionProvider tableConnectionProvider = new SimpleJdbcConnectionProvider(jdbcExecOptions);
+            Connection conn = tableConnectionProvider.getOrEstablishConnection();
+            String query = "SELECT\n" +
```
Comment (healchow) [inline inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/dialect/PostgresDialect.java:168]: Suggest extract to a global string.

File: inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/dialect/PostgresDialect.java [hunk 3]
```diff
@@ -137,4 +146,71 @@ public List<LogicalTypeRoot> unsupportedTypes() {
...
+                            .setTableName(JdbcMultiBatchingComm.getTbNameFromIdentifier(tableIdentifier))
+                            .setDialect(jdbcOptions.getDialect())
+                            .setParallelism(jdbcOptions.getParallelism())
+                            .setConnectionCheckTimeoutSeconds(jdbcOptions.getConnectionCheckTimeoutSeconds())
+                            .setDriverName(jdbcOptions.getDriverName())
+                            .setUsername(jdbcOptions.getUsername().orElse(""))
+                            .setPassword(jdbcOptions.getPassword().orElse(""))
+                            .build();
+            SimpleJdbcConnectionProvider tableConnectionProvider = new SimpleJdbcConnectionProvider(jdbcExecOptions);
+            Connection conn = tableConnectionProvider.getOrEstablishConnection();
```
Comment (healchow) [inline inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/dialect/PostgresDialect.java:167]: Does this connection need to close?

File: inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/dialect/PostgresDialect.java [hunk 4]
```diff
@@ -137,4 +146,71 @@ public List<LogicalTypeRoot> unsupportedTypes() {
                 LogicalTypeRoot.SYMBOL,
                 LogicalTypeRoot.UNRESOLVED);
     }
+
+    @Override
+    public List<String> getAndSetPkNamesFromDb(String tableIdentifier, JdbcOptions jdbcOptions) {
```
Comment (healchow) [inline inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/dialect/PostgresDialect.java:151]: Why is it called Get and Set? I just see a Get operation in the implementation logic.

File: inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/dialect/PostgresDialect.java (hunk 3 above)
Comment (kuansix) [reply inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/dialect/PostgresDialect.java:167]: close when task exit,  implement in JdbcMultiBatchingOutputFormat.close

File: inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/table/AbstractJdbcDialect.java [hunk 5]
```diff
@@ -98,4 +99,12 @@ public void validate(TableSchema schema) throws ValidationException {
      * @return a list of logical type roots.
      */
     public abstract List<LogicalTypeRoot> unsupportedTypes();
+
+    /**
+     * get getPkNames from query db.tb
+     *
+     * @return a list of PkNames.
+     */
+    public abstract List<String> getPkNamesFromDb(String tableIdentifier,
```
Comment (yunqingmoswu) [inline inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/table/AbstractJdbcDialect.java:108]: maybe it is better to remove abstract, subclass can override it if needed.

File: inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/internal/JdbcMultiBatchingComm.java [hunk 6]
```diff
@@ -173,4 +173,26 @@ private static RowData getPrimaryKey(RowData row, RowData.FieldGetter[] fieldGet
...
+        if (2 == fileArray.length) {
+            return fileArray[1];
+        }
+        if (3 == fileArray.length) {
+            return fileArray[1] + "." + fileArray[2];
+        }
+        return null;
+    }
+
+    public static String getTDbNameFromIdentifier(String tableIdentifier) {
```
Comment (gong) [inline inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/internal/JdbcMultiBatchingComm.java:209]: method name is similar, I suggest use  full name.

File: inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/internal/JdbcMultiBatchingComm.java [hunk 7]
```diff
@@ -173,4 +174,47 @@ private static RowData getPrimaryKey(RowData row, RowData.FieldGetter[] fieldGet
...
+    }
+
+    /**
+     * Get table name From tableIdentifier
+     * tableIdentifier maybe: ${dbName}.${tbName} or ${dbName}.${schemaName}.${tbName}
+     *
+     * @param tableIdentifier The table identifier for which to get table name.
+     */
+    public static String getTableNameFromIdentifier(String tableIdentifier) {
+        String[] fileArray = tableIdentifier.split("\\.");
```
Comment (EMsnap) [inline inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/internal/JdbcMultiBatchingComm.java:199]: please use a name that has the right meaning

Comment (EMsnap) [reply inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/internal/JdbcMultiBatchingComm.java:199]: Maybe IdentifierArray?

File: inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/dialect/PostgresDialect.java [hunk 8]
```diff
@@ -169,7 +169,7 @@ public List<LogicalTypeRoot> unsupportedTypes() {
     public PreparedStatement setQuerySql(Connection conn,
             String tableIdentifier) throws SQLException {
```
Comment (gong) [inline inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/dialect/PostgresDialect.java:170]: The method name is too generic. It can't express specific meaning.

File: inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/internal/JdbcMultiBatchingComm.java (hunk 7 above)
Comment (kuansix) [reply inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/internal/JdbcMultiBatchingComm.java]: fieldArray done

File: inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/dialect/PostgresDialect.java (hunk 8 above)
Comment (kuansix) [reply inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/dialect/PostgresDialect.java]: done

**Review by dockerzhang — APPROVED** [review]

**Review by yunqingmoswu — APPROVED** [review]

**Review by healchow — APPROVED** [review]
LGTM
