### PR TITLE
[INLONG-10059][Agent] Fix the exception of installation package comparison

### LINKED ISSUE #10059: [Improve][Agent] Exception of installation package comparison if md5 is null
### Description

There are an bug in the comparison  of installation package md5, an exception will occur when md5 is null

### InLong Component

InLong Agent

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by justinwwhuang**
Fixes #10059

### Motivation
There are an bug in the comparison of installation package md5, an exception will occur when md5 is null
### Modifications

Use Objects.equals instead of equals to handle null md5

### Verifying this change

*(Please pick either of the following options)*

- [x] This change is a trivial rework/code cleanup without any test coverage.

- [ ] This change is already covered by existing tests, such as:
  *(please describe tests)*

- [ ] This change added tests and can be verified as follows:

  *(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Documentation
No doc needed

### CODE REVIEW

File: inlong-agent/agent-installer/src/main/java/org/apache/inlong/agent/installer/ModuleManager.java [hunk 1]
```diff
@@ -461,7 +462,7 @@ private boolean downloadModule(ModuleConfig module) {
     private boolean isPackageDownloaded(ModuleConfig module) {
         String path = module.getPackageConfig().getStoragePath() + "/" + module.getPackageConfig().getFileName();
         String fileMd5 = calcFileMd5(path);
-        if (fileMd5.equals(module.getPackageConfig().getMd5())) {
+        if (Objects.equals(fileMd5, module.getPackageConfig().getMd5())) {
```
Comment (aloyszhang) [inline inlong-agent/agent-installer/src/main/java/org/apache/inlong/agent/installer/ModuleManager.java:465]: what if  both`fileMd5` and `module.getPackageConfig().getMd5()` are null.

Comment (justinwwhuang) [reply inlong-agent/agent-installer/src/main/java/org/apache/inlong/agent/installer/ModuleManager.java:465]: After obtaining the module configuration, it is necessary to add a check, md5 cannot be null

Comment (justinwwhuang) [reply inlong-agent/agent-installer/src/main/java/org/apache/inlong/agent/installer/ModuleManager.java:465]: If this situation occurs currently, there will be repeated pulling of installation packages

**Review by dockerzhang — APPROVED** [review]

**Review by aloyszhang — APPROVED** [review]
