### PR TITLE
[INLONG-5637][Sort] Fix kafka load node npe error

### LINKED ISSUE #5637: [Bug][Sort] Fix kafka  load node npe error
### What happened

It cause a npe error if the value of `inlong.metric` is not set.
企业微信截图_4e9ad185-9b19-492d-b527-3d93b7e45735

### What you expected to happen

It is all right even if the value of `inlong.metric` is not set.

### How to reproduce

Build a kafka load node without the value of `inlong.metric` and run it.

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Sort

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by yunqingmoswu**
### Prepare a Pull Request
*(Change the title refer to the following example)*

Title: [INLONG-5637][Sort] Fix kafka load node npe error

*(The following *XYZ* should be replaced by the actual [GitHub Issue](https://github.com/apache/inlong/issues) number)*

Fixes #5637

### Motivation

Fix the npe error of kafka load node

### Modifications

Update the logic  of sendOutMetrics and sendDirtyMetrics in FlinkKafkaProducer.

### Verifying this change

*(Please pick either of the following options)*

- [ ] This change is a trivial rework/code cleanup without any test coverage.

- [x] This change is already covered by existing tests, such as:
  *(please describe tests)*

- [ ] This change added tests and can be verified as follows:

  *(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a follow-up issue for adding the documentation

### CODE REVIEW

File: inlong-sort/sort-connectors/kafka/src/main/java/org/apache/inlong/sort/kafka/FlinkKafkaProducer.java [hunk 1]
```diff
@@ -928,19 +928,15 @@ public void onCompletion(RecordMetadata metadata, Exception exception) {
...
             metricData.getNumRecordsOut().inc(rowSize);
-        }
-        if (metricData.getNumBytesOut() != null) {
             metricData.getNumBytesOut().inc(dataSize);
         }
     }
 
     private void sendDirtyMetrics(Long rowSize, Long dataSize) {
         if (metricData.getDirtyRecords() != null) {
             metricData.getDirtyRecords().inc(rowSize);
```
Comment (thesumery) [inline inlong-sort/sort-connectors/kafka/src/main/java/org/apache/inlong/sort/kafka/FlinkKafkaProducer.java:939]: use SinkMetricData#invoke instead ?

File: inlong-sort/sort-connectors/kafka/src/main/java/org/apache/inlong/sort/kafka/FlinkKafkaProducer.java [hunk 2]
```diff
@@ -928,19 +928,15 @@ public void onCompletion(RecordMetadata metadata, Exception exception) {
...
+        if (metricData != null) {
             metricData.getNumRecordsOut().inc(rowSize);
-        }
-        if (metricData.getNumBytesOut() != null) {
             metricData.getNumBytesOut().inc(dataSize);
         }
     }
 
     private void sendDirtyMetrics(Long rowSize, Long dataSize) {
         if (metricData.getDirtyRecords() != null) {
```
Comment (gong) [inline inlong-sort/sort-connectors/kafka/src/main/java/org/apache/inlong/sort/kafka/FlinkKafkaProducer.java:938]: same NPE problem

File: inlong-sort/sort-connectors/kafka/src/main/java/org/apache/inlong/sort/kafka/FlinkKafkaProducer.java (hunk 1 above)
Comment (gong) [inline inlong-sort/sort-connectors/kafka/src/main/java/org/apache/inlong/sort/kafka/FlinkKafkaProducer.java:939]: same NPE problem

Comment (yunqingmoswu) [reply inlong-sort/sort-connectors/kafka/src/main/java/org/apache/inlong/sort/kafka/FlinkKafkaProducer.java]: > same NPE problem
Yes, i will do it.

Comment (yunqingmoswu) [reply inlong-sort/sort-connectors/kafka/src/main/java/org/apache/inlong/sort/kafka/FlinkKafkaProducer.java:939]: Yes, i will do it.

**Review by healchow — APPROVED** [review]

**Review by gong — APPROVED** [review]

**Review by thesumery — APPROVED** [review]

**Review by dockerzhang — APPROVED** [review]

**Review by EMsnap — APPROVED** [review]
