### PR TITLE
[INLONG-10464][SDK] InlongSDK support retry sending when failed

### LINKED ISSUE #10464: [Feature][SDK] InlongSDK support retry sending when failed
### Description

When InlongSDK fails to send data to DataProxy, it returns the failure to the user directly. Add the capability to retry sending.

image

Location:
inlong-sdk/dataproxy-sdk/

Requirements:
1. Choose another dataproxy node to resend data when the send fails.
2. Able to configure max retry times.
3. Check failures and only retry those retriable, discard those not.

**This issue is a dedicated issue for the 2024 Tencent Rhino-bird Open Source Talent Training event and is only available for college students to claim**
【Claim the issue】Sign up for the corresponding issue in columns M~R of the [Research and Study Base](https://docs.qq.com/sheet/DTk9YV3pXSklZZ29D) "issue Camp" to be considered as **successfully claimed**.
【Complete the issue】For students who have claimed the issue, please also reply "Successfully claimed this issue" in the comment section of this issue; if there is no progress submitted within 7 days, including but not limited to comments, commits, or Pull Requests, it will be considered as voluntarily giving up the issue and the committee will release the issue to the next person in line.

### Use case

_No response_

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by emptyOVO**
Fixes #10464 

### Motivation
When InlongSDK fails to send data to DataProxy, it returns the failure to the user directly. Add the capability to retry sending.
* Support choose another MessageSender to resend data when the send fails
* Able to configure max retry times
* Check failures and only retry those retriable, discard those not.

### Modifications
1. add `sendSuccess` variable marks sending status last time
2. add methods `retryWhenSendMessageFail` `retryWhenSendMessageIndexFail` to send message, send message by itself first, if fail ,choose another node to retry, and ensure the node is retriable, discard those not
3. add `getRandomSuccessSender` to choose retriable MessageSender in `CACHE_SENDER` 

### Verifying this change

*(Please pick either of the following options)*

- [x] This change is a trivial rework/code cleanup without any test coverage.

- [ ] This change is already covered by existing tests, such as:
  *(please describe tests)*

- [ ] This change added tests and can be verified as follows:

  *(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a follow-up issue for adding the documentation

### CODE REVIEW

File: inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/DefaultMessageSender.java [hunk 1]
```diff
@@ -191,11 +195,93 @@ public String getSDKVersion() {
...
+    private DefaultMessageSender getRandomSuccessSender() {
+        List<Integer> keys = new ArrayList<>(CACHE_SENDER.keySet());
+        if (keys.isEmpty()) {
+            return null;
+        }
+        int attempts = 0;
+        int maxAttempts = keys.size();
+        // choose sending success MessageSender randomly
+        while (attempts < maxAttempts) {
+            int randomIndex = ThreadLocalRandom.current().nextInt(keys.size());
```
Comment (gosonzhang) [inline inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/DefaultMessageSender.java:265]: The senders are saved according to different clusterIds and cannot be obtained randomly.

File: inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/ConfigConstants.java [hunk 2]
```diff
@@ -74,4 +74,6 @@ public class ConfigConstants {
     public static String HTTP = "http://";
     public static String HTTPS = "https://";
 
+    public static int SENDER_MAX_RETRY = 3;
```
Comment (gosonzhang) [inline inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/ConfigConstants.java:77]: The number of retries should be configurable

File: inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/DefaultMessageSender.java [hunk 3]
```diff
@@ -191,11 +195,80 @@ public String getSDKVersion() {
...
+                break;
+            }
+            attempts++;
+        }
+
+        return sendIndexResult;
+    }
+
+    private DefaultMessageSender getAnotherSuccessSender(DefaultMessageSender currentSender) {
+        for (DefaultMessageSender sender : CACHE_SENDER.values()) {
```
Comment (gosonzhang) [inline inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/DefaultMessageSender.java:257]: The sender object is bound to the clusterId. You cannot select a random sender.

Comment (emptyOVO) [reply inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/DefaultMessageSender.java]: done

File: inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/DefaultMessageSender.java [hunk 4]
```diff
@@ -191,11 +194,39 @@ public String getSDKVersion() {
         return ConfigConstants.PROXY_SDK_VERSION;
     }
 
+    private SendResult retryWhenSendMessageFail(Function<Sender, SendResult> sendOperation) {
+        int attempts = 0;
+        SendResult sendResult = null;
+        while (attempts < this.senderMaxRetry + 1) {
```
Comment (gosonzhang) [inline inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/DefaultMessageSender.java:200]: No need to increase by 1, senderMaxRetry has defined the maximum number of retries. If you increase by 1 during comparison, it will send one more time than the set value.

File: inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/ConfigConstants.java [hunk 5]
```diff
@@ -74,4 +74,6 @@ public class ConfigConstants {
     public static String HTTP = "http://";
     public static String HTTPS = "https://";
 
+    public static int DEFAULT_SENDER_MAX_RETRY = 3;
```
Comment (gosonzhang) [inline inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/ConfigConstants.java:77]: The default value setting should remain consistent with the behavior before modification

File: inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/DefaultMessageSender.java (hunk 4 above)
Comment (emptyOVO) [reply inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/DefaultMessageSender.java:200]: I think the retryTime here should be the number of retries rather than the total number of executions, and by default it should be executed once like the original code, so I add 1 here

File: inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/ConfigConstants.java (hunk 5 above)
Comment (emptyOVO) [reply inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/ConfigConstants.java]: done

File: inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/DefaultMessageSender.java (hunk 4 above)
Comment (emptyOVO) [reply inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/DefaultMessageSender.java]: done

File: inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/ProxyClientConfig.java [hunk 6]
```diff
@@ -100,11 +100,12 @@ public class ProxyClientConfig {
     private LoadBalance loadBalance;
 
     private int maxRetry;
+    private int senderMaxRetry;
 
     /* pay attention to the last url parameter ip */
     public ProxyClientConfig(String localHost, boolean requestByHttp, String managerIp,
             int managerPort, String inlongGroupId, String authSecretId, String authSecretKey,
-            LoadBalance loadBalance, int virtualNode, int maxRetry) throws ProxysdkException {
+            LoadBalance loadBalance, int virtualNode, int maxRetry, int senderMaxRetry) throws ProxysdkException {
```
[the remark this answers is not in the document]
Comment (emptyOVO) [reply inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/ProxyClientConfig.java]: done

**Review by gosonzhang — APPROVED** [review]

**Review by aloyszhang — APPROVED** [review]
