### PR TITLE
[INLONG-6005][DataProxy] Fix resend read values

### LINKED ISSUE #6005: [Bug][DataProxy] Bug with metics values
### What happened

Bug with metics values

### What you expected to happen

No bug with metics values

### How to reproduce

Normally run

### Environment

_No response_

### InLong version

master

### InLong Component

InLong DataProxy

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by lucaspeng12138**
### Prepare a Pull Request
[INLONG-6005][Dataproxy] Fix resend read values
- Fixes #6005 

### Motivation

Fix resend read values

### Modifications

Fix resend read values

### Verifying this change

Fix resend read values

### CODE REVIEW

**Review by gosonzhang — APPROVED** [review]

File: inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/sink/DorisSinkServiceTest.java [hunk 1]
```diff
@@ -0,0 +1,100 @@
...
+import org.apache.inlong.manager.service.ServiceBaseTest;
+import org.apache.inlong.manager.service.core.impl.InlongStreamServiceTest;
+import org.junit.jupiter.api.Assertions;
+import org.junit.jupiter.api.Test;
+import org.springframework.beans.factory.annotation.Autowired;
+
+/**
+ * ClickHouse sink service test
+ */
+public class DorisSinkServiceTest extends ServiceBaseTest {
```
Comment (healchow) [inline inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/sink/DorisSinkServiceTest.java:35]: This class does not belong to the issue, suggest committing it to another PR.

**Review by healchow — CHANGES_REQUESTED** [review]

**Review by healchow — APPROVED** [review]
