### PR TITLE
[INLONG-10449][Dashboard] The field template for selecting a new data

### LINKED ISSUE #10449: [Bug][Dashboard] The field template for selecting a new data flow does not take effect
### What happened

The field template for selecting a new data flow does not take effect

### What you expected to happen

The field template for selecting a new data flow takes effect

### How to reproduce

After clicking Add Data Source and selecting a metadata field template, the element data field will not be populated

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Dashboard

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by wohainilaodou**
Fixes #10449 

### Motivation

Let the metadata template take effect
### Modifications
Let the metadata template take effect

### Verifying this change
before
Metadata fields are not populated after a template is selected
image
after

image
image

before 
exits template version 
after 
remove the template version
image
before
image
after
image

### CODE REVIEW

**Review by fuweng11 — APPROVED** [review]

File: inlong-dashboard/src/ui/components/EditableTable/index.tsx [hunk 1]
```diff
@@ -202,7 +206,16 @@ const EditableTable = ({
       triggerChange(newData);
     }
   };
-
+  const onClearAppend = (fields: RowType[]) => {
+    console.log(fields);
```
Comment (haifxu) [inline inlong-dashboard/src/ui/components/EditableTable/index.tsx:210]: Unnecessary output.

Comment (wohainilaodou) [reply inlong-dashboard/src/ui/components/EditableTable/index.tsx:210]: done

**Review by dockerzhang — APPROVED** [review]

**Review by fuweng11 — APPROVED** [review]

**Review by haifxu — APPROVED** [review]
