### PR TITLE
[INLONG-9253][Agent] Fix bug: get byte postion of file by line count offset failed

### LINKED ISSUE #9253: [Bug][Agent] Get byte position of file by line count offset failed
### What happened

Get byte postion of file by line count offset failed

### What you expected to happen

Get byte postion of file by line count offset 

### How to reproduce

fix the bug

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Agent

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by justinwwhuang**
[INLONG-9253][Agent] Fix bug: get byte postion of file by line count offset failed
- Fixes #9253 

### Motivation
Fix bug: get byte postion of file by line count offset failed
### Modifications

Fix bug: get byte postion of file by line count offset failed
### Verifying this change

*(Please pick either of the following options)*

- [ ] This change is a trivial rework/code cleanup without any test coverage.

- [ ] This change is already covered by existing tests, such as:
  *(please describe tests)*

- [ ] This change added tests and can be verified as follows:

  *(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a follow-up issue for adding the documentation

### CODE REVIEW

**Review by doleyzi — APPROVED** [review]

File: inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/LogFileSource.java [hunk 1]
```diff
@@ -247,7 +248,7 @@ private long getBytePositionByLine(long linePosition) throws IOException {
                 }
             }
         } catch (Exception e) {
-            LOGGER.error("getBytePositionByLine error {}", e.getMessage());
+            LOGGER.error("getBytePositionByLine error {}", e.getStackTrace());
```
Comment (fuweng11) [inline inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/LogFileSource.java:251]: Please use ` LOGGER.error("getBytePositionByLine error :", e);`

Comment (justinwwhuang) [reply inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/LogFileSource.java:251]: ok, fix it next issue

**Review by fuweng11 — APPROVED** [review]

**Review by dockerzhang — APPROVED** [review]
