### PR TITLE
[INLONG-10754][Manager] Add start and ent time check for schedule info

### LINKED ISSUE #10754: [Bug][Manager] Offline data sync may create too many scheduling instances at the start point
### What happened

When configuring an offline data sync with crontab scheduling, there may be too many scheduling instances (Flink batch job), including instances before the current time.

### What you expected to happen

The schedule instances before the current time should not be generated.

### How to reproduce

1. add an inlong group for offline sync with crontab expression in which the `start time` is  before the current time in the schedule info by open API
2. submit the group and approve it
3. the scheduling instances before the current time are also generated

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by aloyszhang**
Fixes #10754 

### Motivation

Fix the problems for crontab expression offline sync job may generate too many schedule instances before the current time

### Modifications

1. check start time and end time, make sure not null
2. make sure the start time is not before the current time
3. make sure the end time is not before the start time

### Verifying this change

*(Please pick either of the following options)*

- [x] This change is a trivial rework/code cleanup without any test coverage.

### Documentation

  - Does this pull request introduce a new feature? (no)

### CODE REVIEW

**Review by dockerzhang — APPROVED** [review]

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupServiceImpl.java [hunk 1]
```diff
@@ -221,6 +222,20 @@ public String save(InlongGroupRequest request, String operator) {
 
         // save schedule info for offline group
         if (DATASYNC_OFFLINE_MODE.equals(request.getInlongGroupMode())) {
+            Timestamp startTime = request.getStartTime();
+            Timestamp endTime = request.getEndTime();
+            if (startTime == null || endTime == null) {
+                LOGGER.error("start time or end time cannot be empty for groupId={}", groupId);
+                throw new BusinessException("start time or end time cannot be empty");
+            }
```
Comment (fuweng11) [inline inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupServiceImpl.java:230]:
```suggestion
            Preconditions.expectTrue(startTime != null && endTime != null, "start time or end time cannot be empty");
```

Comment (aloyszhang) [reply inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupServiceImpl.java]: fixed, PTAL

**Review by fuweng11 — DISMISSED** [review]

**Comment by aloyszhang** [comment]
I found that the update interface also needs this logic, and I will complete it soon.

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupServiceImpl.java [hunk 2]
```diff
@@ -498,6 +523,7 @@ public String update(InlongGroupRequest request, String operator) {
 
         // save schedule info for offline group
         if (DATASYNC_OFFLINE_MODE.equals(request.getInlongGroupMode())) {
+            constrainStartAndEndTime(request);
```
Comment (fuweng11) [inline inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupServiceImpl.java:526]: checkStartAndEndTime

Comment (aloyszhang) [reply inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupServiceImpl.java:526]: I think constrain is better here since we do check and re-set both

**Review by fuweng11 — APPROVED** [review]

**Review by dockerzhang — APPROVED** [review]
