### PR TITLE
[INLONG-11153][Manager] Fix the problem of HTTP sink does not automatically allocate sort cluster

### LINKED ISSUE #11153: [Bug][Manager] HTTP sink does not automatically allocate sort cluster
### What happened

HTTP sink does not automatically allocate sort cluster.

### What you expected to happen

HTTP sink automatically allocates sort cluster.

### How to reproduce

Configure HTTP Sink.

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by fuweng11**
Fixes #11153

### Motivation

Fix the problem of HTTP sink does not automatically allocate sort cluster.

### Modifications

Fix the problem of HTTP sink does not automatically allocate sort cluster.

### CODE REVIEW

**Review by dockerzhang — APPROVED** [review]

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sink/http/HttpResourceOperator.java [hunk 1]
```diff
@@ -0,0 +1,57 @@
...
+        return SinkType.HTTP.equals(sinkType);
+    }
+
+    @Override
+    public void createSinkResource(SinkInfo sinkInfo) {
+        LOG.info("begin to create sink resources sinkId={}", sinkInfo.getId());
+        if (SinkStatus.CONFIG_SUCCESSFUL.getCode().equals(sinkInfo.getStatus())) {
+            LOG.warn("sink resource [" + sinkInfo.getId() + "] already success, skip to create");
+            return;
+        } else if (InlongConstants.DISABLE_CREATE_RESOURCE.equals(sinkInfo.getEnableCreateResource())) {
```
Comment (aloyszhang) [inline inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sink/http/HttpResourceOperator.java:49]: move the disable check to the first place of this method

Comment (fuweng11) [reply inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sink/http/HttpResourceOperator.java]: Fixed.

**Review by vernedeng — APPROVED** [review]

**Review by aloyszhang — APPROVED** [review]
