### PR TITLE
[INLONG-5844][Manager] Sub sources should be filtered when querying task status

### LINKED ISSUE #5844: [Bug][Manager] Sub sources should be filtered when querying task status
### What happened

Sub sources are not filtered when querying task status.

### What you expected to happen

Sub sources should be filtered when querying task status.

### How to reproduce

query group status info

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by woofyzhao**
- Fixes #5844

### CODE REVIEW

File: inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/InlongGroupContext.java [hunk 1]
```diff
@@ -90,7 +91,10 @@ private List<StreamSource> getGroupSources() {
             if (MapUtils.isNotEmpty(sources)) {
                 for (Map.Entry<String, StreamSource> entry : sources.entrySet()) {
                     StreamSource source = entry.getValue();
-                    if (source != null) {
+                    // when template id is null it is considered as normal source other than template source
+                    // sub sources are filtered because they are already collected in template source's sub source list
+                    System.out.println("get source = " + source);
```
Comment (GanfengTan) [inline inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/InlongGroupContext.java:96]: Please, delete the expression.

**Review by GanfengTan — APPROVED** [review]

**Review by healchow — APPROVED** [review]

**Review by ciscozhou — APPROVED** [review]

**Review by healchow — APPROVED** [review]

**Review by dockerzhang — APPROVED** [review]
