### PR TITLE
[INLONG-7292][Sort] Accurately detect and archive dirty data for Doris/StarRocks/JDBC

### LINKED ISSUE #7292: [Bug][Sort] The invokeMultiple method cannot accurately detect and archive dirty data
### What happened

the method could not accurately detect and archive dirty data

### What you expected to happen

it should archive data properly

### How to reproduce

do a dirty data archive with those connectors

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Sort

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Yizhou-Yang**
### Prepare a Pull Request

- Fixes #7292

### Motivation
There are two different bugs that should be fixed by this.
1) when archiving, the patternreplaceutils and JsonDymanicSchema competes for ${} symbol, and it will throw exceptions.
2) Sometimes, when invoking dirty data, there is no JsonNode. In this case, the dirty data still needs to be archived.

### Modification

This fix does two things:
1) created a regexreplace method which does the regex replacement process all at once, while not interfering (editing) the common process layer.
2) for those cases where jsonnode is not available, manually pass in identifier so that at least the data can be processed in all cases

### CODE REVIEW

File: inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/dirty/DirtySinkHelper.java [hunk 1]
```diff
@@ -110,22 +118,56 @@ public void invokeMultiple(T dirtyData, DirtyType dirtyType, Throwable e,
             }
             throw ex;
         }
-        if (dirtySink != null) {
-            JsonNode rootNode;
-            DirtyData.Builder<T> builder = DirtyData.builder();
-            try {
+
+        JsonDynamicSchemaFormat jsonDynamicSchemaFormat =
```
Comment (EMsnap) [inline inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/dirty/DirtySinkHelper.java:122]: too long for one method

File: inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/internal/JdbcMultiBatchingOutputFormat.java [hunk 2]
```diff
@@ -566,7 +566,8 @@ protected void attemptFlush() throws IOException {
                         outputMetrics(tableIdentifier, Long.valueOf(tableIdRecordList.size()),
                                 1L, true);
                         if (!schemaUpdateExceptionPolicy.equals(SchemaUpdateExceptionPolicy.THROW_WITH_STOP)) {
-                            dirtySinkHelper.invokeMultiple(record, DirtyType.RETRY_LOAD_ERROR, tableException,
+                            dirtySinkHelper.invokeMultiple(tableIdentifier + "%#%#%#" + record.toString(),
```
Comment (EMsnap) [inline inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/internal/JdbcMultiBatchingOutputFormat.java:569]: "%#%#%#" make constant with meaningful name

File: inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/dirty/DirtySinkHelper.java [hunk 3]
```diff
@@ -136,6 +185,51 @@ public void invokeMultiple(T dirtyData, DirtyType dirtyType, Throwable e,
...
     }
 
+    private String regexReplace(String pattern, DirtyType dirtyType,
+            String dirtyMessage, List<String> actualIdentifier) throws IOException {
+
+        if (pattern == null) {
+            return null;
+        }
+
+        final Pattern REGEX_PATTERN = Pattern.compile("\\$\\{\\s*([\\w.-]+)\\s*}", Pattern.CASE_INSENSITIVE);
```
Comment (healchow) [inline inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/dirty/DirtySinkHelper.java:195]: Suggest changing this regex pattern to a final static variable, or changing the `regexReplace` method to static, which can improve the performance.

**Review by healchow — CHANGES_REQUESTED** [review]

**Comment by healchow** [comment]
Please add more info for the PR, such as the Motivation, Modifications and Verifying…

File: inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/Constants.java [hunk 4]
```diff
@@ -135,6 +135,8 @@ public final class Constants {
 
     public static final String AUTO_DESERIALIZE_FALSE = "autoDeserialize=false";
 
+    public static final String SEPARATOR = "%#%#%#";
```
Comment (healchow) [inline inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/Constants.java:138]: The name of `SEPARATOR` was unclearly.

File: inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/Constants.java [hunk 5]
```diff
@@ -135,6 +135,8 @@ public final class Constants {
 
     public static final String AUTO_DESERIALIZE_FALSE = "autoDeserialize=false";
 
+    public static final String DIRTY_IDENTIFIER_SEPARATOR = "%#%#%#";
```
Comment (yunqingmoswu) [inline inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/Constants.java:138]: Make sure it is right?

Comment (Yizhou-Yang) [reply inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/Constants.java:138]: it is entirely made up to pass in identifier before the actual dirty data, so it can be anything as long as it wont be user's db/table name

File: inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/dirty/DirtySinkHelper.java [hunk 6]
```diff
@@ -136,6 +178,51 @@ public void invokeMultiple(T dirtyData, DirtyType dirtyType, Throwable e,
...
```
Comment (gong) [inline inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/dirty/DirtySinkHelper.java]: Add some UT for this REGEX_PATTERN or regexReplace method

**Review by yunqingmoswu — APPROVED** [review]

File: inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/dirty/DirtySinkHelper.java (hunk 6 above)
Comment (Yizhou-Yang) [reply inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/dirty/DirtySinkHelper.java]: added

**Review by gong — APPROVED** [review]

**Comment by Yizhou-Yang** [comment]
TODO : the pr is still being performance-tested and need to remove logs and add comments before the final merge

**Review by healchow — APPROVED** [review]
LGTM

**Review by EMsnap — APPROVED** [review]
