### PR TITLE
[INLONG-6276][Manager] Fix the problem of parsing the ASCII code when submitting the Sort task

### LINKED ISSUE #6276: [Bug][Manager] The data separator is a number when submitting the Sort task
### What happened

When submitting sort, the data separator is a number.
```
2022-10-25 14:23:03 ~ 2022-10-25 14:23:06 [StartupSortListener] event: [COMPLETE], executed [failed],
 remark: [null], exception: [startup failed: Start job null failed in backend exception[java.lang.Exception:
 submit job failed: The main method caused an error: Unable to create a source for reading table 'default_catalog.default_database.table_b_test_wkstream_1025'.
 Table options are: 'admin-url'='http://xxxx:8080' 'connector'='pulsar-inlong' 'format'='inlong-msg' 'generic'='true' 'inlong-msg.csv.allow-comments'='false'
 'inlong-msg.csv.array-element-delimiter'=';' 'inlong-msg.csv.disable-quote-character'='true' 'inlong-msg.csv.field-delimiter'='124'
 'inlong-msg.csv.ignore-parse-errors'='true' 'inlong-msg.ignore-parse-errors'='false' 'inlong-msg.inner.format'='csv'
```

### What you expected to happen

When submitting a sort, the data separator transmits characters.

### How to reproduce

After the group and stream related information is configured, it is approved and configured, and a sort failure log appears.

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by fuweng11**
### Prepare a Pull Request

- Fixes #6276 

### Motivation

When submitting sort, the data separator is a number.

### Modifications

Before submitting the sort task, the separator is judged. If it is a number, it will be converted into characters

### Verifying this change

- [X] This change is a trivial rework/code cleanup without any test coverage.

- [ ] This change is already covered by existing tests, such as:
  *(please describe tests)*

- [ ] This change added tests and can be verified as follows:

### Documentation

  - Does this pull request introduce a new feature? (no)

### CODE REVIEW

File: inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/util/ExtractNodeUtils.java [hunk 1]
```diff
@@ -247,7 +247,12 @@ public static PulsarExtractNode createExtractNode(PulsarSource pulsarSource) {
         DataTypeEnum dataType = DataTypeEnum.forName(pulsarSource.getSerializationType());
         switch (dataType) {
             case CSV:
-                format = new CsvFormat(pulsarSource.getDataSeparator());
+                String dataSeparatorStr = pulsarSource.getDataSeparator();
+                if (StringUtils.isNumeric(dataSeparatorStr)) {
+                    char dataSeparator = (char) Integer.parseInt(pulsarSource.getDataSeparator());
+                    dataSeparatorStr = Character.toString(dataSeparator);
+                }
+                format = new CsvFormat(dataSeparatorStr);
```
Comment (healchow) [inline inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/util/ExtractNodeUtils.java:255]:
```suggestion
                String separatorStr = pulsarSource.getDataSeparator();
                if (StringUtils.isNumeric(separatorStr)) {
                    char separator = (char) Integer.parseInt(separatorStr);
                    separatorStr = Character.toString(separator);
                }
                format = new CsvFormat(separatorStr);
```

**Review by luchunliang — APPROVED** [review]
LGTM

**Review by vernedeng — APPROVED** [review]
lgtm

**Review by healchow — APPROVED** [review]

**Review by gong — APPROVED** [review]

**Review by dockerzhang — APPROVED** [review]
