### PR TITLE
[INLONG-6602][DataProxy] Fix the IP config was invalid

### LINKED ISSUE #6602: [Bug][DataProxy] ip config not valid
### What happened

ip config not valid.
It may be a regular expression validation problem

### What you expected to happen

image

### How to reproduce

Fill in the actual IP of the server in dataproxy-pulsar.conf

### Environment

_No response_

### InLong version

1.4.0

### InLong Component

InLong DataProxy

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by gosonzhang**
- Fixes #6602

### CODE REVIEW

File: inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/BaseSource.java [hunk 1]
```diff
@@ -41,6 +41,7 @@
 import org.apache.inlong.common.monitor.MonitorIndex;
 import org.apache.inlong.common.monitor.MonitorIndexExt;
 import org.apache.inlong.dataproxy.metrics.DataProxyMetricItemSet;
+import org.apache.inlong.dataproxy.utils.ConfStringUtils;
```
Comment (aloyszhang) [inline inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/BaseSource.java:44]: un-used import

**Review by dockerzhang — APPROVED** [review]

File: inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/BaseSource.java (hunk 1 above)
Comment (gosonzhang) [reply inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/BaseSource.java:44]: It's used on line 226,227

**Review by healchow — APPROVED** [review]
