### PR TITLE
[INLONG-11556][Agent] Resolve exceptions when saving installation packages

### LINKED ISSUE #11556: [Improve][Agent] Resolve exceptions when saving installation packages
### Description

1. Create a non-existent folder
2. Identify the home directory

### InLong Component

InLong Agent

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by justinwwhuang**
Fixes #11556 

### Motivation

Resolve exceptions when saving installation packages

### Modifications

1. Create a non-existent folder
2. Identify the home directory

### Verifying this change

*(Please pick either of the following options)*

- [x] This change is a trivial rework/code cleanup without any test coverage.

- [ ] This change is already covered by existing tests, such as:
  *(please describe tests)*

- [ ] This change added tests and can be verified as follows:

  *(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Documentation

No doc needed

### CODE REVIEW

**Review by aloyszhang — APPROVED** [review]

File: inlong-agent/agent-installer/src/main/java/org/apache/inlong/agent/installer/ModuleManager.java [hunk 1]
```diff
@@ -589,6 +599,11 @@ private boolean isPackageDownloaded(ModuleConfig module) {
         }
     }
 
+    private String getRealPath(String originPath) {
+        String homeDir = System.getProperty("user.home");
```
Comment (doleyzi) [inline inlong-agent/agent-installer/src/main/java/org/apache/inlong/agent/installer/ModuleManager.java:603]: It is recommended to add a null judgment protection

**Review by doleyzi — APPROVED** [review]

**Review by aloyszhang — APPROVED** [review]
