### PR TITLE
[INLONG-9023][Manager] Fix the problem of failed to stop job task

### LINKED ISSUE #9023: [Bug][Manager] Failed to stop job task
### What happened

Failed to stop job task.

### What you expected to happen

Success to stop job task.

### How to reproduce

Stop job task.

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by fuweng11**
### Prepare a Pull Request

- Fixes #9023 

### Motivation

Fix the problem of failed to stop job task.

### Modifications

Fix the problem of failed to stop job task.

### CODE REVIEW

File: inlong-manager/manager-plugins/base/src/main/java/org/apache/inlong/manager/plugin/flink/FlinkOperation.java [hunk 1]
```diff
@@ -351,20 +350,21 @@ public void pollJobStatus(FlinkInfo flinkInfo) throws Exception {
...
+                    log.info("job status is {} for {}", jobStatus, jobId);
                     break;
                 }
-                log.info("job was not Running for {}", jobId);
-                TimeUnit.SECONDS.sleep(5);
+                log.info("job status is {} for {}", jobStatus, jobId);
             } catch (Exception e) {
                 log.error("poll job status error for {}, exception: ", flinkInfo, e);
             }
+            TimeUnit.SECONDS.sleep(5);
```
Comment (vernedeng) [inline inlong-manager/manager-plugins/base/src/main/java/org/apache/inlong/manager/plugin/flink/FlinkOperation.java:366]: why sleep 5 ms

Comment (fuweng11) [reply inlong-manager/manager-plugins/base/src/main/java/org/apache/inlong/manager/plugin/flink/FlinkOperation.java:366]: Because it is necessary to continuously loop to determine whether the job status is expected.

**Review by healchow — APPROVED** [review]
LGTM

**Review by dockerzhang — APPROVED** [review]

**Review by vernedeng — APPROVED** [review]
