### PR TITLE
[INLONG-8953][Sort] Fix Iceberg source defaults the StartSnapshot to the latest

### LINKED ISSUE #8953: [Bug][Sort] Iceberg source default the StartSnapshot to the latest
### What happened

Iceberg source force defaults the StartSnapshot to the latest and cannot be reset.

### What you expected to happen

Offer the option to allow the user to assign the start snapshot strategy from the earliest.

### How to reproduce

Create an iceberg source.

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Sort

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by vernedeng**
### Prepare a Pull Request
*(Change the title refer to the following example)*

- Title Example: [INLONG-XYZ][Component] Title of the pull request

*(The following *XYZ* should be replaced by the actual [GitHub Issue](https://github.com/apache/inlong/issues) number)*

- Fixes #8953 

### Motivation

Iceberg source force defaults the StartSnapshot to the latest and cannot be reset.

### Modifications

Offer the option to allow the user to assign the start snapshot strategy from the earliest.

### Verifying this change

*(Please pick either of the following options)*

- [ ] This change is a trivial rework/code cleanup without any test coverage.

- [ ] This change is already covered by existing tests, such as:
  *(please describe tests)*

- [ ] This change added tests and can be verified as follows:

  *(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a follow-up issue for adding the documentation

### CODE REVIEW

File: inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/extract/IcebergExtractNode.java [hunk 1]
```diff
@@ -110,7 +110,10 @@ public Map<String, String> tableOptions() {
         options.put(IcebergConstant.TABLE_KEY, tableName);
         options.put(IcebergConstant.CATALOG_TYPE_KEY, catalogType.name());
         options.put(IcebergConstant.CATALOG_NAME_KEY, catalogName);
+        // support streaming only
         options.put(IcebergConstant.STREAMING, "true");
+        options.put(IcebergConstant.STARTING_STRATEGY_KEY,
```
Comment (EMsnap) [inline inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/extract/IcebergExtractNode.java:115]: Guess we need this parameter to be configurable, use FROM_LATEST by default and stili we support changing it

**Review by EMsnap — COMMENTED** [review]
what if we set start_from_latest and restart job from checkpoint ?  Will it start from checkpoint or from latest snapshot ?

**Review by EMsnap — APPROVED** [review]

**Review by dockerzhang — APPROVED** [review]
