### PR TITLE
[INLONG-6001][Manager] Ensure that the newly created sink under the successful stream can be configured normally

### LINKED ISSUE #6001: [Improve][Manager] Workflow cannot be triggered when a new sink is created under a successful stream
### What happened

The configuration process cannot be triggered when a new sink is created under a successfully configured group.

### What you expected to happen

Create a new sink under the successfully configured group. 
The sink can successfully trigger the configuration process

### How to reproduce

Create a new group and configure it successfully and create a new data store under the current group.

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by fuweng11**
### Prepare a Pull Request
- Fixes #6001 

### Motivation
Ensure that the newly created sink under the successfully configured stream can be configured normally

### Modifications

Judge the stream status when saving. If the configuration is successful, the sink configuration process will be triggered

### Verifying this change

- [X] This change is a trivial rework/code cleanup without any test coverage.

- [ ] This change is already covered by existing tests, such as:
  *(please describe tests)*

- [ ] This change added tests and can be verified as follows:

### Documentation

  - Does this pull request introduce a new feature? (no)

### CODE REVIEW

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/listener/sort/StreamSortConfigListener.java [hunk 1]
```diff
@@ -62,18 +60,15 @@ public TaskEvent event() {
     @Override
     public boolean accept(WorkflowContext context) {
         ProcessForm processForm = context.getProcessForm();
+        String className = processForm.getClass().getSimpleName();
         String groupId = processForm.getInlongGroupId();
-        if (!(processForm instanceof GroupResourceProcessForm)) {
-            LOGGER.warn("zookeeper enabled was [false] for groupId [{}]", groupId);
+        if (processForm instanceof GroupResourceProcessForm || processForm instanceof StreamResourceProcessForm) {
```
Comment (healchow) [inline inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/listener/sort/StreamSortConfigListener.java:65]: Only need to check `StreamResourceProcessForm`, because the following `listen` method casts `ProcessForm` to `StreamResourceProcessForm`.

**Review by healchow — CHANGES_REQUESTED** [review]

**Review by healchow — APPROVED** [review]

**Review by woofyzhao — APPROVED** [review]

**Review by dockerzhang — APPROVED** [review]

**Review by gosonzhang — APPROVED** [review]
