### PR TITLE
[INLONG-7172][Sort] Fix new table write into iceberg failed

### LINKED ISSUE #7172: [Bug]Fix new tables doesn't have restored flink job id
### What happened

When a new table is added in the Flink job, the following error will be reported when the job is restarted with status.
image

### What you expected to happen

The new table can be successfully written to iceberg.

### How to reproduce

Add a new table to the flink job, and then restart the job with status.

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Sort

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by e-mhui**
### Prepare a Pull Request

[INLONG-7172][Sort] Fix new table write into iceberg failed

- Fixes #7172 

### Motivation

When a new table is added in the Flink job,  and then restart the job with status. The new table can be successfully written to iceberg.

### Modifications

The new table has no state after the job is restarted, so we need to ignore the subsequent operations when the state is restored.

```java
       if (context.isRestored()) {
            // New table doesn't have restored flink job id.
            if (!jobIdState.get().iterator().hasNext()) {
                return;
            }
            /**
             * ...
             */
        }
```

### CODE REVIEW

**Review by thesumery — APPROVED** [review]

File: inlong-sort/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/multiple/IcebergSingleFileCommiter.java [hunk 1]
```diff
@@ -161,6 +161,10 @@ public void initializeState(FunctionInitializationContext context) throws Except
         this.checkpointsState = context.getOperatorStateStore().getListState(stateDescriptor);
         this.jobIdState = context.getOperatorStateStore().getListState(jobIdDescriptor);
         if (context.isRestored()) {
+            // New table doesn't have restored flink job id.
+            if (!jobIdState.get().iterator().hasNext()) {
```
Comment (EMsnap) [inline inlong-sort/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/multiple/IcebergSingleFileCommiter.java:165]: if (context.isRestored() && jobIdState.get().iterator().hasNext())

**Review by EMsnap — APPROVED** [review]

File: inlong-sort/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/multiple/IcebergSingleFileCommiter.java [hunk 2]
```diff
@@ -160,7 +160,7 @@ public void initializeState(FunctionInitializationContext context) throws Except
 
         this.checkpointsState = context.getOperatorStateStore().getListState(stateDescriptor);
         this.jobIdState = context.getOperatorStateStore().getListState(jobIdDescriptor);
-        if (context.isRestored()) {
+        if (context.isRestored() && jobIdState.get().iterator().hasNext()) {
```
Comment (EMsnap) [inline inlong-sort/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/multiple/IcebergSingleFileCommiter.java:163]: keep the comment you submit before pls

Comment (e-mhui) [reply inlong-sort/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/multiple/IcebergSingleFileCommiter.java:164]: done.

**Review by yunqingmoswu — APPROVED** [review]

**Review by gong — APPROVED** [review]
