### PR TITLE
[INLONG-5705][Manager] Fix the deprecated dependency of PageInfo

### LINKED ISSUE #5705: [Bug][Manager] The PageInfo was deprecated in the pagination query
### What happened

企业微信截图_16614209014801
### What you expected to happen

replace the dependency with a new one

### How to reproduce

compile the streamline

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Yizhou-Yang**
Fixes #5705

### CODE REVIEW

**Review by dockerzhang — APPROVED** [review]

**Review by aloyszhang — APPROVED** [review]

File: inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/LogCommand.java [hunk 1]
```diff
@@ -73,8 +73,8 @@ void run() {
                 InlongGroupClient groupClient = ClientUtils.clientFactory.getGroupClient();
                 InlongGroupPageRequest pageRequest = new InlongGroupPageRequest();
                 pageRequest.setKeyword(inputs[1]);
-                PageInfo<InlongGroupBriefInfo> pageInfo = groupClient.listGroups(pageRequest);
-                if (pageInfo.getSize() > MAX_LOG_SIZE) {
+                PageResult<InlongGroupBriefInfo> pageInfo = groupClient.listGroups(pageRequest);
```
Comment (healchow) [inline inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/LogCommand.java:76]: Change the `pageInfo` to `pageResult`.

File: inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/LogCommand.java [hunk 2]
```diff
@@ -73,8 +73,8 @@ void run() {
                 InlongGroupClient groupClient = ClientUtils.clientFactory.getGroupClient();
                 InlongGroupPageRequest pageRequest = new InlongGroupPageRequest();
                 pageRequest.setKeyword(inputs[1]);
-                PageInfo<InlongGroupBriefInfo> pageInfo = groupClient.listGroups(pageRequest);
-                if (pageInfo.getSize() > MAX_LOG_SIZE) {
+                PageResult<InlongGroupBriefInfo> groupPageResults = groupClient.listGroups(pageRequest);
```
Comment (healchow) [inline inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/LogCommand.java:76]: Why `results`, not `result`?

**Review by healchow — APPROVED** [review]
