### PR TITLE
[INLONG-11298][Agent] Fix bug for pulsar source with empty data process and specified time consumption

### LINKED ISSUE #11298: [Improve][Agent] Pulsar source needs to do some exception handling
### Description

1 When reading data but return null
2 Select to read from specified time

### InLong Component

InLong Agent

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by justinwwhuang**
Fixes #11298 

### Motivation

Fix bug for pulsar source

### Modifications

1 Do not obtain offset when no data is read

2 When reading data at a specified time, the subscription site defaults to Lastest.

### Verifying this change

*(Please pick either of the following options)*

- [x] This change is a trivial rework/code cleanup without any test coverage.

- [ ] This change is already covered by existing tests, such as:
  *(please describe tests)*

- [ ] This change added tests and can be verified as follows:

  *(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Documentation

No doc needed

### CODE REVIEW

**Review by dockerzhang — APPROVED** [review]

File: inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/PulsarSource.java [hunk 1]
```diff
@@ -68,8 +69,12 @@ protected void initSource(InstanceProfile profile) {
             topic = profile.getInstanceId();
             serviceUrl = profile.get(TASK_PULSAR_SERVICE_URL);
             subscription = profile.get(TASK_PULSAR_SUBSCRIPTION, PULSAR_SUBSCRIPTION_PREFIX + inlongStreamId);
-            subscriptionPosition = profile.get(TASK_PULSAR_SUBSCRIPTION_POSITION,
-                    SubscriptionInitialPosition.Latest.name());
+            String position = profile.get(TASK_PULSAR_SUBSCRIPTION_POSITION, SubscriptionInitialPosition.Latest.name());
+            if (position.equals(SUBSCRIPTION_CUSTOM)) {
```
Comment (aloyszhang) [inline inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/PulsarSource.java:73]: what does `SUBSCRIPTION_CUSTOM` mean?

**Review by doleyzi — DISMISSED** [review]

**Review by aloyszhang — APPROVED** [review]

**Review by doleyzi — APPROVED** [review]
