### PR TITLE
[INLONG-5803][Agent] Fix NPE when collect file data

### LINKED ISSUE #5803: [Bug][Agent] NPE when collect file data
### What happened

Incremental data collection

### What you expected to happen

Collect file data.

### How to reproduce

1. Create task for file data
2. Create file

### Environment

_No response_

### InLong version

1.3.0

### InLong Component

InLong Agent

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by GanfengTan**
Fix NPE
- Fixes #5803 

### Motivation

No message.

### Modifications

No message.

### Verifying this change

*(Please pick either of the following options)*

- [x] This change is a trivial rework/code cleanup without any test coverage.

- [ ] This change is already covered by existing tests, such as:
  *(please describe tests)*

- [ ] This change added tests and can be verified as follows:

### CODE REVIEW

File: inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/file/MonitorTextFile.java [hunk 1]
```diff
@@ -111,17 +114,23 @@ public void run() {
...
+                LOGGER.error("monitor {} error:", this.fileReaderOperator.file.getName(), e);
             }
         }
 
         private void listen() throws IOException {
             BasicFileAttributes attributesAfter = Files
                     .readAttributes(this.fileReaderOperator.file.toPath(), BasicFileAttributes.class);
-            if (attributesBefore.lastModifiedTime().compareTo(attributesAfter.lastModifiedTime()) < 0
-                    && !this.fileReaderOperator.iterator.hasNext()) {
+            if (attributesBefore.lastModifiedTime().compareTo(attributesAfter.lastModifiedTime()) < 0) {
```
Comment (healchow) [inline inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/file/MonitorTextFile.java:126]: Suggested adding a comment for the reason for return.

**Review by healchow — APPROVED** [review]

File: inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/file/MonitorTextFile.java [hunk 2]
```diff
@@ -76,6 +77,7 @@ public void monitor(FileReaderOperator fileReaderOperator, TextFileReader textFi
      */
     private class MonitorEventRunnable implements Runnable {
 
+        private static final int WAIT_TIME = 30;
```
Comment (EMsnap) [inline inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/file/MonitorTextFile.java:80]: add a configuration for the wait time pls

Comment (GanfengTan) [reply inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/file/MonitorTextFile.java:80]: Internal startup logical, don`t have to add configuration.

**Review by dockerzhang — APPROVED** [review]
