### PR TITLE
[INLONG-5424][Manager] Fix JSON serialization error for Authentication when getting inlongGroupInfo

### LINKED ISSUE #5424: [Bug][Manager] JSON serialization error for Authentication when getting inlongGroupInfo
### What happened

com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `org.apache.inlong.manager.common.auth.Authentication` (no Creators, like default constructor, exist): abstract types either need to be mapped to concrete types, have custom deserializer, or contain additional type information
 at [Source: (String)"{"id":1,"inlongGroupId":"rf84249bb-e02d-44c2-ba1f-1ab009ddfaa3","name":"rf84249bb-e02d-44c2-ba1f-1ab009ddfaa3","description":"The group rf84249bb-e02d-44c2-ba1f-1ab009ddfaa3 is auto created xxx ","middlewareType":null,"mqType":"NONE","mqResource":"rf84249bb-e02d-44c2-ba1f-1ab009ddfaa3","enableZookeeper":0,"enableCreateResource":0,"lightweight":1,"inlongClusterTag":"xxx,"dailyRecords":10000000,"dailyStorage":null,"peakRecords":100000,"maxLength":10000,"inCharges"[truncated 5090 chars]; line: 1, column: 3420] (through reference chain: org.apache.inlong.manager.pojo.group.none.InlongNoneMqInfo["sortConf"]->org.apache.inlong.manager.pojo.sort.FlinkSortConf["authentication"])
        at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67)
at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1615)
        at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:400)
        at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1077)
        at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserialize(AbstractDeserializer.java:265)
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:293)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:194)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:166)
        at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:132)
        at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:99)
        at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:254)
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:138)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:293)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:194)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:166)
        at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:132)
        at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:99)
        at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:254)
        at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:68)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4526)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3468)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3436)
        at org.apache.inlong.manager.common.util.JsonUtils.parseObject(JsonUtils.java:82)
        at org.apache.inlong.manager.client.api.inner.client.InlongGroupClient.getGroupInfo

### What you expected to happen

no exception

### How to reproduce

just use inlong manager client to create group

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by gong**
### Prepare a Pull Request

- [INLONG-5424][Manager] Fix json serialization for Authentication when get inlongGroupInfo

- Fixes #5424 

### Motivation

Fix json serialization for Authentication when get inlongGroupInfo

### Modifications

* modify UT for inlong-manager/manager-client/src/test/java/org/apache/inlong/manager/client/api/inner/ClientFactoryTest.java, you can reproduce problem if you modify this UT
* Add annation for Authentication

### CODE REVIEW

File: inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/auth/Authentication.java [hunk 1]
```diff
@@ -17,11 +17,20 @@
...
+import com.fasterxml.jackson.annotation.JsonSubTypes;
+import com.fasterxml.jackson.annotation.JsonTypeInfo;
 import com.fasterxml.jackson.databind.ObjectMapper;
 
 import java.util.Locale;
 import java.util.Map;
 
+@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, visible = true, property = "type")
+@JsonSubTypes({
+        @JsonSubTypes.Type(value = DefaultAuthentication.class, name = DefaultAuthentication.DEFAULT),
```
Comment (healchow) [inline inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/auth/Authentication.java:29]: It is recommended to specify its specific type through `@JsonTypeDefine` on the subclass, without adding all subclasses on the parent class - refer to the advice of the open-closed principle.

**Review by healchow — CHANGES_REQUESTED** [review]

File: inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/auth/Authentication.java (hunk 1 above)
Comment (gong) [reply inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/auth/Authentication.java]: modify JosonUtils

**Review by healchow — APPROVED** [review]

**Review by dockerzhang — APPROVED** [review]

**Review by gosonzhang — APPROVED** [review]

**Review by haibo-duan — APPROVED** [review]
