### PR TITLE
[INLONG-5703][Manager] Add separator-related fields for some sources

### LINKED ISSUE #5703: [Feature][Manager] Add separator-related fields for File, Kafka, and Pulsar sources
### What happened

Get separator from enum 'DataSeparator' 

### What you expected to happen

Get separator from enum 'DataSeparator' 

### How to reproduce

none

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by e-mhui**
### Prepare a Pull Request

[INLONG-5703][Manager] Get separator from enum 'DataSeparator' and remove fieldDelimiter from properties of PulsarSource

- Fixes #5703 

### Motivation

- DataSeparator is an ascii code, so we should get separator from enum `DataSeparator `
- if not remove fieldDelimiter, it will be parse into sql option. for example:

```
"properties": {
  "properties.auth-params": "token:xxxx",
  "properties.auth-plugin-classname": "org.apache.pulsar.client.impl.auth.AuthenticationToken",
  "fieldDelimiter": "|"
}
```

### CODE REVIEW

File: inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/pulsar/PulsarSource.java [hunk 1]
```diff
@@ -62,6 +64,15 @@ public class PulsarSource extends StreamSource {
     @ApiModelProperty("Primary key, needed when serialization type is csv, json, avro")
     private String primaryKey;
 
+    @ApiModelProperty(value = "Data encoding format: UTF-8, GBK")
+    private String dataEncoding = StandardCharsets.UTF_8.toString();
+
+    @ApiModelProperty(value = "Data separator, stored as ASCII code")
+    private String dataSeparator = DataSeparator.VERTICAL_BAR.getAsciiCode().toString();
```
Comment (healchow) [inline inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/pulsar/PulsarSource.java:71]: Just set the default value in the `PulsarSourceRequest`, other classes do not need it.

Comment (e-mhui) [reply inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/pulsar/PulsarSource.java]: done

**Review by healchow — APPROVED** [review]

**Review by dockerzhang — APPROVED** [review]
