### PR TITLE
[INLONG-7513][DataProxy] Delete duplicate definitions

### LINKED ISSUE #7513: [Improve][DataProxy] Delete duplicate definitions
### What happened

image

Duplicate definition

### What you expected to happen

Delete duplicate definitions

### How to reproduce

Delete duplicate definitions

### Environment

_No response_

### InLong version

master

### InLong Component

InLong DataProxy

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by lby1119**
- Fixes #7513

### Motivation

There are duplicate definitions here, so delete the duplicate part.

### Modifications

Delete the duplicate definition part.

### Verifying this change

*(Please pick either of the following options)*

- [ ] This change is a trivial rework/code cleanup without any test coverage.

### CODE REVIEW

**Comment by healchow** [comment]
Thanks for your contribution 🎉

File: inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/pulsar/PulsarHandler.java [hunk 1]
```diff
@@ -282,8 +282,6 @@ private CompressionType getPulsarCompressionType() {
         switch (type) {
             case "LZ4":
                 return CompressionType.LZ4;
-            case "NONE":
```
Comment (healchow) [inline inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/pulsar/PulsarHandler.java:285]: I guess it's better to move the `case "NONE" line above the `default` line.

Comment (dockerzhang) [reply inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/pulsar/PulsarHandler.java:285]: replicated for the default definition, you could check the issue.

**Review by dockerzhang — APPROVED** [review]

File: inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/pulsar/PulsarHandler.java (hunk 1 above)
Comment (healchow) [reply inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/pulsar/PulsarHandler.java:285]: I mean change it to this:

```java
            case "NONE":
            default:
                return CompressionType.NONE;
```

The advantage is that it can be clearly pointed out that we also support the `"NONE"` configuration item.

**Review by healchow — APPROVED** [review]
LGTM

File: inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/pulsar/PulsarHandler.java [hunk 2]
```diff
@@ -282,15 +282,14 @@ private CompressionType getPulsarCompressionType() {
...
-                return CompressionType.NONE;
             case "ZLIB":
                 return CompressionType.ZLIB;
             case "ZSTD":
                 return CompressionType.ZSTD;
             case "SNAPPY":
                 return CompressionType.SNAPPY;
-            default:
+            case "NONE":
+                default:
```
Comment (healchow) [inline inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/pulsar/PulsarHandler.java:292]:
```suggestion
            default:
```

**Review by healchow — APPROVED** [review]
LGTM
