### PR TITLE
[INLONG-6594][Sort] Fix ClickHouse connector throw exception when source is change log stream

### LINKED ISSUE #6594: [Bug][Sort] Clickhouse connector throw exception when source is change log stream
### What happened

* clickhouse throw exception "Can't UPDATE key column `id`" when update source data. It means that `alter table update ... where` can't update primaryKey. [refer to](https://stackoverflow.com/questions/55976700/is-it-possible-to-update-primary-key-in-clickhouse-using-mergetree-engine) .

* clickhouse throw exception "Table default.test_user doesn't exist". But jdbc-url have database name. [Refer to](https://github.com/ClickHouse/ClickHouse/issues/19278). Maybe we should specify database.

### What you expected to happen

just work well

### How to reproduce

just sync mysql data to clickhouse

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Sort

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by gong**
### Prepare a Pull Request

- [INLONG-6594][Sort] Fix ClickHouse sort connector throw exception when source is change log stream

- Fixes #6594 

### Motivation

 Fix ClickHouse sort connector throw exception when source is change log stream
* ClickHouse throw exception "Can't UPDATE key column id" when update source data. It means that alter table update ... where can't update primaryKey. [refer to](https://stackoverflow.com/questions/55976700/is-it-possible-to-update-primary-key-in-clickhouse-using-mergetree-engine) .

* ClickHouse throw exception "Table default.test_user doesn't exist". But jdbc-url have database name. https://github.com/ClickHouse/ClickHouse/issues/19278. Maybe we should specify database.

### Modifications

* Modify clickhouse Dialect
* Modify clickhouse load node UT, tableName should include 'database.table'

### CODE REVIEW

File: inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/dialect/ClickHouseDialect.java [hunk 1]
```diff
@@ -154,6 +178,67 @@ public String getDeleteStatement(String tableName, String[] conditionFields) {
                 Arrays.stream(conditionFields)
                         .map(f -> format("%s = :%s", quoteIdentifier(f), f))
                         .collect(Collectors.joining(" AND "));
-        return "ALTER TABLE " + quoteIdentifier(tableName) + " DELETE WHERE " + conditionClause;
+        Pair<String, String> pair = getDatabaseAndTableName(tableName);
```
Comment (EMsnap) [inline inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/dialect/ClickHouseDialect.java:181]: use a name that illustrate the actual data, since "pair" can be infered from its class type

Comment (gong) [reply inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/dialect/ClickHouseDialect.java]: ok

File: inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/dialect/ClickHouseDialect.java [hunk 2]
```diff
@@ -129,22 +135,40 @@ public List<LogicalTypeRoot> unsupportedTypes() {
...
                         .collect(Collectors.joining(", "));
+
         String conditionClause =
                 Arrays.stream(conditionFields)
                         .map(f -> format("%s = :%s", quoteIdentifier(f), f))
                         .collect(Collectors.joining(" AND "));
+        Pair<String, String> databaseAndTableName = getDatabaseAndTableName(tableName);
         return "ALTER TABLE "
-                + quoteIdentifier(tableName)
+                + quoteIdentifier(databaseAndTableName.getLeft())
```
Comment (thesumery) [inline inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/dialect/ClickHouseDialect.java:151]: if here has bug, maybe delete statement have the same problem?

File: inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/dialect/ClickHouseDialect.java [hunk 3]
```diff
@@ -129,22 +135,40 @@ public List<LogicalTypeRoot> unsupportedTypes() {
...
+                + POINT
+                + quoteIdentifier(databaseAndTableName.getRight())
                 + " UPDATE "
                 + setClause
                 + " WHERE "
                 + conditionClause;
     }
 
+    private Pair<String, String> getDatabaseAndTableName(String tableName) {
```
Comment (thesumery) [inline inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/dialect/ClickHouseDialect.java:160]: add some coment to describe this issue?

File: inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/dialect/ClickHouseDialect.java (hunk 2 above)
Comment (gong) [reply inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/dialect/ClickHouseDialect.java:151]: I test delete op, not to found it. But I can add it.

File: inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/dialect/ClickHouseDialect.java (hunk 3 above)
Comment (gong) [reply inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/dialect/ClickHouseDialect.java:160]: ok

File: inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/dialect/ClickHouseDialect.java (hunk 2 above)
Comment (gong) [reply inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/dialect/ClickHouseDialect.java:151]: > if here has bug, maybe delete statement have the same problem?

@thesumery I test delete is ok. I hava add it for delete.

**Review by healchow — APPROVED** [review]

**Review by EMsnap — APPROVED** [review]
