### PR TITLE
[INLONG-5611][Manager] Set the sink status after updating the sink info

### LINKED ISSUE #5611: [Bug][Manager] Wrong sink status after updating the sink info when the inlong group was not submitted
### What happened

Wrong sink status after updating the sink info when the inlong group was not submitted.

### What you expected to happen

Should keep waiting for be approved status for the sink.

### How to reproduce

Just update one sink when the inlong group status was waiting for approval.

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by ciscozhou**
### Prepare a Pull Request

- Fixes #5611

### Motivation

Set the sink status after updating the sink info.

### Modifications

After updating the stream sink info, if the status of inlong stream was CONFIG_SUCCESSFUL or CONFIG_FAILED, change the sink status to CONFIG_ING, otherwise not change the sink status.

1. If the stream status was CONFIG_SUCCESSFUL, no matter what status of the sink, all changing to CONFIG_ING, and start the CREATE_STREAM_PROCESS, after the process will change the sink status to CONFIG_SUCCESSFUL or CONFIG_FAILED.

2. If the stream status was CONFIG_FAILED, it means there are some errors occurred, the user must fix it first, and in this situation, sink status also need to be CONFIG_ING, it tells the user that the sink info was updated success, and begin to configuring. Only after the stream error was fixed, the sink status will change to CONFIG_SUCCESSFUL or CONFIG_FAILED.

### Verifying this change

- [x] This change is a trivial rework/code cleanup without any test coverage.

### CODE REVIEW

**Review by healchow — APPROVED** [review]

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/StreamSinkServiceImpl.java [hunk 1]
```diff
@@ -224,23 +231,27 @@ public Boolean update(SinkRequest request, String operator) {
             }
         }
         List<SinkField> fields = request.getSinkFieldList();
-        // Remove id in sinkField when save
+        // Remove id in sinkField before saving or updating
         if (CollectionUtils.isNotEmpty(fields)) {
             fields.forEach(sinkField -> sinkField.setId(null));
```
Comment (woofyzhao) [inline inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/StreamSinkServiceImpl.java:236]: Can we just remove the id field to be inserted in the sql stmt ?

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/StreamSinkServiceImpl.java [hunk 2]
```diff
@@ -224,23 +231,27 @@ public Boolean update(SinkRequest request, String operator) {
...
+            nextStatus = SinkStatus.CONFIG_ING;
+        }
         StreamSinkOperator sinkOperator = operatorFactory.getInstance(request.getSinkType());
-        sinkOperator.updateOpt(request, operator);
+        sinkOperator.updateOpt(request, nextStatus, operator);
 
-        // The inlong group status is [Configuration successful], then asynchronously initiate
-        // the [Single inlong stream resource creation] workflow
-        if (GroupStatus.CONFIG_SUCCESSFUL.getCode().equals(groupEntity.getStatus())) {
+        // If the stream is [CONFIG_SUCCESSFUL], then asynchronously start the [CREATE_STREAM_RESOURCE] process
```
Comment (woofyzhao) [inline inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/StreamSinkServiceImpl.java:247]: In the comment it still says asynchronously

**Review by woofyzhao — APPROVED** [review]

**Review by dockerzhang — APPROVED** [review]
