### PR TITLE
[INLONG-5767][Sort] Fix IOUtils interface is incompatible in JDK 17

### LINKED ISSUE #5767: [Improve][Sort] IOUtils interface is incompatible in jdk17
### Description

image

### InLong Component

InLong Sort

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by xuesongxs**
Fixes #5767

### CODE REVIEW

**Review by yunqingmoswu — APPROVED** [review]
LGTM

**Review by gong — APPROVED** [review]

File: inlong-sort/sort-end-to-end-tests/src/test/java/org/apache/inlong/sort/tests/utils/FlinkContainerTestEnv.java [hunk 1]
```diff
@@ -293,8 +294,11 @@ private String constructDistJar(Path... jars) throws IOException {
             for (Path jar : jars) {
                 try (InputStream is = new FileInputStream(jar.toFile())) {
                     jos.putNextEntry(new JarEntry("lib/" + jar.getFileName().toString()));
-                    jos.write(IOUtils.readNBytes(is, is.available()));
+                    jos.write(IOUtils.toByteArray(is));
+                    is.close();
```
Comment (thesumery) [inline inlong-sort/sort-end-to-end-tests/src/test/java/org/apache/inlong/sort/tests/utils/FlinkContainerTestEnv.java:298]: is.close() is useless , try with resource will auto close it.

**Review by healchow — APPROVED** [review]

**Review by dockerzhang — APPROVED** [review]

**Review by thesumery — APPROVED** [review]
