### PR TITLE
[INLONG-6250][Sort] Return ZonedTimestamp when mysql data schema is timestamp or dataTime

### LINKED ISSUE #6250: [Bug][Sort] MySQL -> Iceberg exception when data is timestamp
### What you expected to happen

mysql -> iceberg exception when data schema is data time 

### How to reproduce

企业微信截图_eed0bcd2-5aae-4576-8f6a-cacacb5c5a1e

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Sort

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by EMsnap**
- Fixes #6250 

### Motivation

[INLONG-6250][Sort] Return ZonedTimestamp when mysql data schema is timestamp or dataTime

### Modifications

[INLONG-6250][Sort] Return ZonedTimestamp when mysql data schema is timestamp or dataTime

### Verifying this change

run AllmigrateTest

### CODE REVIEW

File: inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/debezium/table/RowDataDebeziumDeserializeSchema.java [hunk 1]
```diff
@@ -635,14 +634,10 @@ private Object getTimeValue(Object fieldValue, String schemaName) {
...
-                ZonedDateTime zonedDateTime = ZonedDateTime.parse((CharSequence) fieldValue);
-                fieldValue = timestampFormatter.format(zonedDateTime
-                        .withZoneSameInstant(serverTimeZone).toLocalDateTime());
+                // by default the field value is zoned timestamp, no need to convert
                 break;
             case Timestamp.SCHEMA_NAME:
-                Instant instantTime = Instant.ofEpochMilli((Long) fieldValue);
-                fieldValue = timestampFormatter.format(LocalDateTime.ofInstant(instantTime,
-                        serverTimeZone));
+                fieldValue = Instant.ofEpochMilli((Long) fieldValue).toString();
```
Comment (thesumery) [inline inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/debezium/table/RowDataDebeziumDeserializeSchema.java:640]: think about timezone problem.

Comment (thesumery) [reply inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/debezium/table/RowDataDebeziumDeserializeSchema.java:640]: Instance.ofEpochMilli default think about UTC time zone, so it is useless for parameter `serverTimeZone`;

**Review by gong — APPROVED** [review]

**Review by thesumery — APPROVED** [review]

**Review by yunqingmoswu — APPROVED** [review]

**Review by healchow — APPROVED** [review]

**Review by dockerzhang — APPROVED** [review]
