### PR TITLE
[INLONG-6745][Manager] Support StarRocks load node management

### LINKED ISSUE #6745: [Feature][Manager]Support StarRocks load node management
### Description

Inspired by doris-cdc-inlong, starrocks-cdc-inlong can also support transferring all tables in one database on time.

StarRocks FE api has changed, been different from Doris FE api. If you use doris-cdc-inlong to handle StarRocks tables writing, it will give a error: `http://x.x.x.x:xxxx/api/backends?is_alive=true failed. java.io.IOException: Failed to get response from Doris.` That is why we need a sarrocks-cdc-inlong connector.

This PR provides StarRocks load node management is InLong Manager.

### Use case

_No response_

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by liaorui**
### Prepare a Pull Request

- [INLONG-6745][Manager] Support StarRocks load node management

- Fixes #6745

### Motivation

Inspired by doris-inlong, starrocks-inlong can also support transferring all tables in one database on time.

StarRocks FE api has changed, been different from Doris FE api. If you use doris-cdc-inlong to handle StarRocks tables writing, it will give a error: http://x.x.x.x:xxxx/api/backends?is_alive=true failed. java.io.IOException: Failed to get response from Doris. That is why we need a sarrocks-inlong connector.

This PR provides StarRocks load node management is InLong Manager.

### Modifications

1. SinkType has new STARROCKS type.

2. manager-pojo has new StarRocksSink, StarRocksSinkDTO and StarRocksSinkRequest classes.

3. LoadNodeUtils has new createLoadNode method for creating StarRocksLoadNode object.

4. manager-service has new StarRocksSinkOperator class.

### Verifying this change

*(Please pick either of the following options)*

- [ ] This change is a trivial rework/code cleanup without any test coverage.

- [ ] This change is already covered by existing tests, such as:
  *(please describe tests)*

- [ ] This change added tests and can be verified as follows:

  *(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a follow-up issue for adding the documentation

### CODE REVIEW

File: inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/starrocks/StarRocksSink.java [hunk 1]
```diff
@@ -0,0 +1,87 @@
...
+/**
+ * StarRocks sink info
+ */
+@Data
+@SuperBuilder
+@AllArgsConstructor
+@ToString(callSuper = true)
+@EqualsAndHashCode(callSuper = true)
+@ApiModel(value = "StarRocks sink info")
+@JsonTypeDefine(value = SinkType.DORIS)
```
Comment (healchow) [inline inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/starrocks/StarRocksSink.java:42]: `DORIS`?

**Review by healchow — APPROVED** [review]
LGTM

**Review by fuweng11 — APPROVED** [review]

**Review by dockerzhang — APPROVED** [review]
