### PR TITLE
[INLONG-10265][Manager] Fix the problem of correct wrong starrocks create table statement

### LINKED ISSUE #10265: [Bug][Manager] Correct wrong starrocks create table statement
### What happened

There are some problem in create table statement.
image

### What you expected to happen

Successfuly execute create table statement

### How to reproduce

Correct the wrong create table statement

### Environment

docker

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by fuweng11**
- Fixes #10265

### Motivation

Fix the problem of correct wrong starrocks create table statement.

### Modifications

Fix the problem of correct wrong starrocks create table statement.

### CODE REVIEW

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sink/starrocks/StarRocksSqlBuilder.java [hunk 1]
```diff
@@ -161,6 +156,11 @@ private static String getColumnsAndComments(StarRocksTableInfo tableInfo) {
             columnList.add(columnStr.toString());
         }
         StringBuilder result = new StringBuilder().append(" (").append(StringUtils.join(columnList, ",")).append(") ");
+        if (!StringUtils.isEmpty(tableInfo.getPrimaryKey())) {
```
Comment (vernedeng) [inline inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sink/starrocks/StarRocksSqlBuilder.java:159]: StringUtils.isNotEmpty

Comment (fuweng11) [reply inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sink/starrocks/StarRocksSqlBuilder.java]: Fixed.

**Review by vernedeng — APPROVED** [review]

**Review by dockerzhang — APPROVED** [review]
