### PR TITLE
[INLONG-11410][DataProxy] Fixed the bug of excessive packet length when Go SDK receives DataProxy response

### LINKED ISSUE #11410: [Bug][DataProxy] Fixed the bug of excessive packet length when Go SDK receives DataProxy response
### What happened

When using go SDK to report data, the error "exceed max frame length" always appears:

image

### What you expected to happen

Receiving without error

### How to reproduce

Use Go SDK report data

### Environment

linux

### InLong version

master

### InLong Component

InLong DataProxy

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by gosonzhang**
Fixes #11410

Fill in the length of the corresponding package attribute according to the actual setting value

### CODE REVIEW

File: inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/ServerMessageHandler.java [hunk 1]
```diff
@@ -558,11 +558,14 @@ private void procBinHeartbeatMsg(BaseSource source, Channel channel,
...
-        int binTotalLen = 1 + 4 + 2 + 2;
+        int attrsLen = 0;
+        byte[] byTeAttrs = null;
         if (null != attrs) {
-            binTotalLen += attrs.length();
+            byTeAttrs = attrs.getBytes(StandardCharsets.UTF_8);
+            attrsLen = byTeAttrs.length;
         }
+        // binTotalLen = mstType + uniq + attrsLen + attrs + magic
+        int binTotalLen = 1 + 4 + 2 + 2 + attrsLen;
```
Comment (aloyszhang) [inline inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/ServerMessageHandler.java:568]: please describe the length of every element in the correct order

File: inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/ServerMessageHandler.java [hunk 2]
```diff
@@ -656,15 +664,16 @@ private ByteBuf buildTxtMsgRspPackage(MsgType msgType, String attrs, AbsV0MsgCod
...
         if (null != attrData) {
-            binTotalLen += attrData.length;
+            attrsLen = attrData.length;
         }
         // check load value
         if (loadValue == 0 || loadValue == (-1)) {
             loadValue = 0xffff;
         }
+        // binTotalLen = mstType + dataTime + version + bodyLen + body + attrsLen + attrs + magic
+        int binTotalLen = 1 + 4 + 1 + 4 + 2 + 2 + 2 + attrsLen;
```
Comment (aloyszhang) [inline inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/ServerMessageHandler.java:676]: ditto

**Review by aloyszhang — APPROVED** [review]

**Review by dockerzhang — APPROVED** [review]

**Review by fuweng11 — APPROVED** [review]
