### PR TITLE
[INLONG-6016][Sort] Serialization failed when submit load DLC sort job

### LINKED ISSUE #6016: [Bug][Sort] Serialization failed when submit load DLC sort job
### What happened

企业微信截图_1664009567927

### What you expected to happen

start a load DLC job success.

### How to reproduce

submit a load DLC sort job.

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Sort

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by thesumery**
### Prepare a Pull Request
*[INLONG-6016][Sort] Serialization failed when submit load DLC sort job*

- Fixes #6016 

### Motivation

*Fix serialization failed when submit load DLC sort job*

### Modifications

*Add `Serializable` interface for `MetricOption`*

### CODE REVIEW

File: inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/metric/MetricOption.java [hunk 1]
```diff
@@ -33,7 +34,7 @@
 import static org.apache.inlong.sort.base.Constants.GROUP_ID;
 import static org.apache.inlong.sort.base.Constants.STREAM_ID;
 
-public class MetricOption {
+public class MetricOption implements Serializable {
```
Comment (gong) [inline inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/metric/MetricOption.java:37]: declares its serialVersionUID

**Review by gong — APPROVED** [review]

**Review by EMsnap — APPROVED** [review]

**Review by healchow — APPROVED** [review]

**Review by dockerzhang — APPROVED** [review]
